begin;
create table if not exists public.board_posts(id uuid primary key default gen_random_uuid(),category text not null default 'STRATEGY_CHAT',title text not null default '',content text not null,author_id uuid references public.users(id),author_name text not null,author_avatar text,author_character_id text,replies_count integer default 0,created_at timestamptz default now(),updated_at timestamptz default now(),user_id uuid references public.users(id),author_avatar_url text,target_type text not null default 'GLOBAL',target_id uuid,is_system boolean not null default false,reply_to_message_id uuid references public.board_posts(id),raid_rescue_id uuid);
create table if not exists public.direct_messages(id uuid primary key default gen_random_uuid(),sender_id uuid not null references public.users(id),recipient_id uuid not null references public.users(id),message text not null,created_at timestamptz default now(),is_read boolean not null default false);
create table if not exists public.chat_read_states(user_id uuid not null references public.users(id),target_type text not null,target_id uuid not null,last_read_at timestamptz not null default now(),primary key(user_id,target_type,target_id));
create table if not exists public.news(id bigint generated by default as identity primary key,category text not null,title text not null,content text not null,link_url text,start_at timestamptz not null,end_at timestamptz,created_at timestamptz not null default now(),is_published boolean not null default false,release_key text);
alter table public.board_posts enable row level security;
alter table public.direct_messages enable row level security;
alter table public.chat_read_states enable row level security;
alter table public.news enable row level security;
revoke all on public.board_posts,public.direct_messages,public.chat_read_states,public.news from public,anon,authenticated;
grant all on public.board_posts,public.direct_messages,public.chat_read_states,public.news to service_role;
grant usage,select on sequence public.news_id_seq to service_role;
grant select on public.board_posts,public.direct_messages,public.news to authenticated;
create policy community_channel_read on public.board_posts for select to authenticated using(target_type='GLOBAL' or (target_type='GUILD' and target_id in(select guild_id from public.guild_members where user_id=auth.uid())));
create policy direct_message_owner_read on public.direct_messages for select to authenticated using(auth.uid() in(sender_id,recipient_id));
create policy published_news_read on public.news for select to authenticated using(is_published and start_at<=now() and (end_at is null or end_at>now()));
create index board_posts_channel_time on public.board_posts(target_type,target_id,created_at desc);
create index direct_messages_recipient_time on public.direct_messages(recipient_id,created_at desc);
create or replace function public.get_public_profiles(p_user_ids uuid[]) returns jsonb language plpgsql stable security definer set search_path='' as $$
begin
 if auth.uid() is null or p_user_ids is null or cardinality(p_user_ids) not between 1 and 100 then raise exception 'invalid public profile request' using errcode='42501';end if;
 return coalesce((select jsonb_agg(jsonb_build_object('id',u.id,'user_id',u.id,'username',u.username,'avatar_url',u.avatar_url,'bio',u.bio,'favorite_character_id',coalesce(s.state->>'homeCharacterId',u.favorite_character_id),'level',u.level,'xp',u.xp,'guild_id',m.guild_id,'guild_name',g.name)) from public.users u left join public.game04_player_state s on s.user_id=u.id left join public.guild_members m on m.user_id=u.id left join public.guilds g on g.id=m.guild_id where u.id=any(p_user_ids)),'[]'::jsonb);
end $$;
revoke all on function public.get_public_profiles(uuid[]) from public,anon;
grant execute on function public.get_public_profiles(uuid[]) to authenticated;
commit;
