SET check_function_bodies = false;
SET search_path = public, extensions, pg_catalog;
GRANT EXECUTE ON FUNCTION "public"."canonical_equipment_lb_multiplier"(p_plus_val integer) TO "anon";
GRANT EXECUTE ON FUNCTION "public"."canonical_equipment_lb_multiplier"(p_plus_val integer) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."canonical_equipment_lb_multiplier"(p_plus_val integer) TO "service_role";
REVOKE ALL ON FUNCTION "public"."canonical_equipment_lb_options"(p_category text, p_plus_val integer) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."canonical_equipment_lb_options"(p_category text, p_plus_val integer) TO PUBLIC;
GRANT EXECUTE ON FUNCTION "public"."canonical_equipment_lb_options"(p_category text, p_plus_val integer) TO "anon";
GRANT EXECUTE ON FUNCTION "public"."canonical_equipment_lb_options"(p_category text, p_plus_val integer) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."canonical_equipment_lb_options"(p_category text, p_plus_val integer) TO "service_role";
REVOKE ALL ON FUNCTION "public"."canonical_equipment_runtime_projection"(p_user_id uuid, p_user_character_id uuid) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."canonical_equipment_runtime_projection"(p_user_id uuid, p_user_character_id uuid) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."canonical_equipment_runtime_projection"(p_user_id uuid, p_user_character_id uuid) TO "service_role";
REVOKE ALL ON FUNCTION "public"."canonical_equipment_runtime_projection_00170"(p_user_id uuid, p_user_character_id uuid) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."canonical_equipment_runtime_projection_00170"(p_user_id uuid, p_user_character_id uuid) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."canonical_equipment_runtime_projection_00170"(p_user_id uuid, p_user_character_id uuid) TO "service_role";
REVOKE ALL ON FUNCTION "public"."canonical_quest_enemy_snapshot"(p_quest_id text) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."canonical_quest_enemy_snapshot"(p_quest_id text) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."canonical_quest_enemy_snapshot"(p_quest_id text) TO "service_role";
REVOKE ALL ON FUNCTION "public"."canonical_quest_is_unlocked"(p_user_id uuid, p_quest_id text) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."canonical_quest_is_unlocked"(p_user_id uuid, p_quest_id text) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."canonical_quest_is_unlocked"(p_user_id uuid, p_quest_id text) TO "service_role";
REVOKE ALL ON FUNCTION "public"."canonical_raid_rotation_pair"(p_date date) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."canonical_raid_rotation_pair"(p_date date) TO PUBLIC;
GRANT EXECUTE ON FUNCTION "public"."canonical_raid_rotation_pair"(p_date date) TO "anon";
GRANT EXECUTE ON FUNCTION "public"."canonical_raid_rotation_pair"(p_date date) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."canonical_raid_rotation_pair"(p_date date) TO "service_role";
REVOKE ALL ON FUNCTION "public"."canonical_ranking_reward_payload"() FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."canonical_ranking_reward_payload"() TO "service_role";
REVOKE ALL ON FUNCTION "public"."canonical_skill_slot_count"(p_awakening integer) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."canonical_skill_slot_count"(p_awakening integer) TO PUBLIC;
GRANT EXECUTE ON FUNCTION "public"."canonical_skill_slot_count"(p_awakening integer) TO "anon";
GRANT EXECUTE ON FUNCTION "public"."canonical_skill_slot_count"(p_awakening integer) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."canonical_skill_slot_count"(p_awakening integer) TO "service_role";
REVOKE ALL ON FUNCTION "public"."capture_current_lifetime_onboarding_grant"(p_user_id uuid) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."capture_current_lifetime_onboarding_grant"(p_user_id uuid) TO "service_role";
REVOKE ALL ON FUNCTION "public"."capture_daily_ranking_guild_membership"() FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."capture_daily_ranking_guild_membership"() TO "service_role";
REVOKE ALL ON FUNCTION "public"."capture_daily_ranking_participation"() FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."capture_daily_ranking_participation"() TO "service_role";
REVOKE ALL ON FUNCTION "public"."capture_gvg_guild_result"() FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."capture_gvg_guild_result"() TO "service_role";
REVOKE ALL ON FUNCTION "public"."capture_gvg_individual_damage"() FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."capture_gvg_individual_damage"() TO "service_role";
REVOKE ALL ON FUNCTION "public"."capture_pvp_daily_win"() FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."capture_pvp_daily_win"() TO "service_role";
REVOKE ALL ON FUNCTION "public"."character_awaken"(p_user_id uuid, p_character_id text, p_cash_cost integer) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."character_awaken"(p_user_id uuid, p_character_id text, p_cash_cost integer) TO "service_role";
REVOKE ALL ON FUNCTION "public"."character_level_up"(p_user_id uuid, p_character_id text, p_exp_item_id text, p_count integer, p_cash_cost integer) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."character_level_up"(p_user_id uuid, p_character_id text, p_exp_item_id text, p_count integer, p_cash_cost integer) TO "service_role";
REVOKE ALL ON FUNCTION "public"."check_current_gameplay_reset_eligibility"() FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."check_current_gameplay_reset_eligibility"() TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."check_current_gameplay_reset_eligibility"() TO "service_role";
REVOKE ALL ON FUNCTION "public"."claim_all_mission_rewards"(p_mission_ids text[]) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."claim_all_mission_rewards"(p_mission_ids text[]) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."claim_all_mission_rewards"(p_mission_ids text[]) TO "service_role";
REVOKE ALL ON FUNCTION "public"."claim_all_mission_rewards"(p_user_id uuid, p_mission_ids text[]) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."claim_all_mission_rewards"(p_user_id uuid, p_mission_ids text[]) TO "service_role";
REVOKE ALL ON FUNCTION "public"."claim_all_presents"() FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."claim_all_presents"() TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."claim_all_presents"() TO "service_role";
REVOKE ALL ON FUNCTION "public"."claim_all_presents"(p_user_id uuid) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."claim_all_presents"(p_user_id uuid) TO "service_role";
REVOKE ALL ON FUNCTION "public"."claim_battle_rewards"(p_user_id uuid, p_cash_amount integer, p_exp_amount integer, p_item_rewards jsonb) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."claim_battle_rewards"(p_user_id uuid, p_cash_amount integer, p_exp_amount integer, p_item_rewards jsonb) TO "service_role";
REVOKE ALL ON FUNCTION "public"."claim_daily_pass_reward"(p_user_id uuid) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."claim_daily_pass_reward"(p_user_id uuid) TO "service_role";
GRANT EXECUTE ON FUNCTION "public"."claim_daily_pass_reward"(p_user_id uuid) TO "authenticated";
REVOKE ALL ON FUNCTION "public"."claim_daily_pass_reward_core_20260823"(p_user_id uuid) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."claim_daily_pass_reward_core_20260823"(p_user_id uuid) TO "service_role";
REVOKE ALL ON FUNCTION "public"."claim_gvg_base"(p_guild_id uuid, p_base_id text) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."claim_gvg_base"(p_guild_id uuid, p_base_id text) TO "service_role";
REVOKE ALL ON FUNCTION "public"."claim_mission_reward"(p_mission_id text) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."claim_mission_reward"(p_mission_id text) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."claim_mission_reward"(p_mission_id text) TO "service_role";
REVOKE ALL ON FUNCTION "public"."claim_mission_reward"(p_user_id uuid, p_mission_id text) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."claim_mission_reward"(p_user_id uuid, p_mission_id text) TO "service_role";
REVOKE ALL ON FUNCTION "public"."claim_present"(p_present_id uuid) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."claim_present"(p_present_id uuid) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."claim_present"(p_present_id uuid) TO "service_role";
REVOKE ALL ON FUNCTION "public"."claim_present"(p_user_id uuid, p_present_id uuid) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."claim_present"(p_user_id uuid, p_present_id uuid) TO "service_role";
REVOKE ALL ON FUNCTION "public"."cleanup_expired_anonymous_onboarding"() FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."cleanup_expired_anonymous_onboarding"() TO "service_role";
REVOKE ALL ON FUNCTION "public"."complete_gvg_match_on_timeout"(p_match_session_id uuid) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."complete_gvg_match_on_timeout"(p_match_session_id uuid) TO "anon";
GRANT EXECUTE ON FUNCTION "public"."complete_gvg_match_on_timeout"(p_match_session_id uuid) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."complete_gvg_match_on_timeout"(p_match_session_id uuid) TO "service_role";
REVOKE ALL ON FUNCTION "public"."billing_validate_special_payment"() FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."billing_validate_special_payment"() TO "service_role";
REVOKE ALL ON FUNCTION "public"."capture_quest_raid_encounter_v1"() FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON FUNCTION "public"."complete_patrol_instant"(p_user_id uuid, p_patrol_id uuid, p_diamond_cost integer) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."complete_patrol_instant"(p_user_id uuid, p_patrol_id uuid, p_diamond_cost integer) TO "service_role";
REVOKE ALL ON FUNCTION "public"."complete_patrol_instantly"(p_user_id uuid, p_patrol_id uuid, p_use_currency text) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."complete_patrol_instantly"(p_user_id uuid, p_patrol_id uuid, p_use_currency text) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."complete_patrol_instantly"(p_user_id uuid, p_patrol_id uuid, p_use_currency text) TO "service_role";
REVOKE ALL ON FUNCTION "public"."complete_patrol_preopen"(p_patrol_id uuid) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."complete_patrol_preopen"(p_patrol_id uuid) TO "service_role";
REVOKE ALL ON FUNCTION "public"."complete_patrol_v2"(p_user_id uuid, p_patrol_id uuid, p_cash bigint, p_xp integer, p_course_name text, p_reward_item_id text, p_reward_qty integer, p_gear_dropped boolean, p_is_victory boolean, p_battle_reward_item_id text, p_battle_reward_qty integer) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."complete_patrol_v2"(p_user_id uuid, p_patrol_id uuid, p_cash bigint, p_xp integer, p_course_name text, p_reward_item_id text, p_reward_qty integer, p_gear_dropped boolean, p_is_victory boolean, p_battle_reward_item_id text, p_battle_reward_qty integer) TO "service_role";
REVOKE ALL ON FUNCTION "public"."complete_tutorial_authentication"(p_auth_method text) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."complete_tutorial_authentication"(p_auth_method text) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."complete_tutorial_authentication"(p_auth_method text) TO "service_role";
REVOKE ALL ON FUNCTION "public"."consume_pvp_point"(p_user_id uuid) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."consume_pvp_point"(p_user_id uuid) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."consume_pvp_point"(p_user_id uuid) TO "service_role";
REVOKE ALL ON FUNCTION "public"."consume_raid_attempt"(p_user_id uuid, p_cost_type text, p_cost_amount integer) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."consume_raid_attempt"(p_user_id uuid, p_cost_type text, p_cost_amount integer) TO "service_role";
REVOKE ALL ON FUNCTION "public"."consume_tutorial_character_daily_free_gacha"() FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."consume_tutorial_character_daily_free_gacha"() TO "service_role";
REVOKE ALL ON FUNCTION "public"."consume_vitality_for_gvg"(p_user_id uuid, p_cost integer) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."consume_vitality_for_gvg"(p_user_id uuid, p_cost integer) TO "service_role";
REVOKE ALL ON FUNCTION "public"."converge_ranking_lifecycle_safety"(p_at timestamp with time zone) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."converge_ranking_lifecycle_safety"(p_at timestamp with time zone) TO "service_role";
REVOKE ALL ON FUNCTION "public"."create_battle_replay_pending"(p_battle_mode text, p_tactic_id text, p_random_seed bigint, p_player_snapshot jsonb, p_enemy_snapshot jsonb, p_source_reference_id uuid) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."create_battle_replay_pending"(p_battle_mode text, p_tactic_id text, p_random_seed bigint, p_player_snapshot jsonb, p_enemy_snapshot jsonb, p_source_reference_id uuid) TO "anon";
GRANT EXECUTE ON FUNCTION "public"."create_battle_replay_pending"(p_battle_mode text, p_tactic_id text, p_random_seed bigint, p_player_snapshot jsonb, p_enemy_snapshot jsonb, p_source_reference_id uuid) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."create_battle_replay_pending"(p_battle_mode text, p_tactic_id text, p_random_seed bigint, p_player_snapshot jsonb, p_enemy_snapshot jsonb, p_source_reference_id uuid) TO "service_role";
REVOKE ALL ON FUNCTION "public"."create_bbs_post"(p_thread_id uuid, p_content text) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."create_bbs_post"(p_thread_id uuid, p_content text) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."create_bbs_post"(p_thread_id uuid, p_content text) TO "service_role";
REVOKE ALL ON FUNCTION "public"."current_ranking_season_id"(p_type text, p_at timestamp with time zone) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."current_ranking_season_id"(p_type text, p_at timestamp with time zone) TO "service_role";
REVOKE ALL ON FUNCTION "public"."_exchange_pity_reward_before_special_release"(p_user_id uuid, p_reward_type text, p_reward_id text) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."_exchange_pity_reward_before_special_release"(p_user_id uuid, p_reward_type text, p_reward_id text) TO "service_role";
REVOKE ALL ON FUNCTION "public"."get_quest_raid_encounters_v1"() FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."get_quest_raid_encounters_v1"() TO "authenticated";
REVOKE ALL ON FUNCTION "public"."acknowledge_quest_raid_encounter_v1"(p_patrol_id uuid) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."acknowledge_quest_raid_encounter_v1"(p_patrol_id uuid) TO "authenticated";
REVOKE ALL ON FUNCTION "public"."_special_gacha_is_exclusive"(p_type text, p_id text) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."_special_gacha_is_exclusive"(p_type text, p_id text) TO "service_role";
REVOKE ALL ON FUNCTION "public"."draw_gacha_item"(p_gacha_id text, p_rarity text) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."draw_gacha_item"(p_gacha_id text, p_rarity text) TO "service_role";
REVOKE ALL ON FUNCTION "public"."exchange_special_gacha_reward"(p_reward_type text, p_reward_id text, p_request_id uuid) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."exchange_special_gacha_reward"(p_reward_type text, p_reward_id text, p_request_id uuid) TO "service_role";
GRANT EXECUTE ON FUNCTION "public"."exchange_special_gacha_reward"(p_reward_type text, p_reward_id text, p_request_id uuid) TO "authenticated";
REVOKE ALL ON FUNCTION "public"."get_special_gacha_catalog"() FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."get_special_gacha_catalog"() TO "service_role";
GRANT EXECUTE ON FUNCTION "public"."get_special_gacha_catalog"() TO "authenticated";
REVOKE ALL ON FUNCTION "public"."create_bbs_thread"(p_category text, p_title text, p_content text) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."create_bbs_thread"(p_category text, p_title text, p_content text) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."create_bbs_thread"(p_category text, p_title text, p_content text) TO "service_role";
REVOKE ALL ON FUNCTION "public"."create_guild"(p_user_id uuid, p_guild_name text, p_guild_description text, p_guild_logo text, p_guild_color text, p_creation_cost integer) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."create_guild"(p_user_id uuid, p_guild_name text, p_guild_description text, p_guild_logo text, p_guild_color text, p_creation_cost integer) TO "service_role";
REVOKE ALL ON FUNCTION "public"."create_guild_v2"(p_user_id uuid, p_guild_name text, p_creation_cost integer) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."create_guild_v2"(p_user_id uuid, p_guild_name text, p_creation_cost integer) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."create_guild_v2"(p_user_id uuid, p_guild_name text, p_creation_cost integer) TO "service_role";
REVOKE ALL ON FUNCTION "public"."create_gvg_match_session"(p_session_key text, p_scheduled_start_at timestamp with time zone, p_scheduled_end_at timestamp with time zone, p_guild_a_id uuid, p_guild_b_id uuid, p_guild_a_phase_hp bigint, p_guild_b_phase_hp bigint, p_npc_guild_name text) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."create_gvg_match_session"(p_session_key text, p_scheduled_start_at timestamp with time zone, p_scheduled_end_at timestamp with time zone, p_guild_a_id uuid, p_guild_b_id uuid, p_guild_a_phase_hp bigint, p_guild_b_phase_hp bigint, p_npc_guild_name text) TO "anon";
GRANT EXECUTE ON FUNCTION "public"."create_gvg_match_session"(p_session_key text, p_scheduled_start_at timestamp with time zone, p_scheduled_end_at timestamp with time zone, p_guild_a_id uuid, p_guild_b_id uuid, p_guild_a_phase_hp bigint, p_guild_b_phase_hp bigint, p_npc_guild_name text) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."create_gvg_match_session"(p_session_key text, p_scheduled_start_at timestamp with time zone, p_scheduled_end_at timestamp with time zone, p_guild_a_id uuid, p_guild_b_id uuid, p_guild_a_phase_hp bigint, p_guild_b_phase_hp bigint, p_npc_guild_name text) TO "service_role";
REVOKE ALL ON FUNCTION "public"."current_gameplay_reset_eligibility"(p_user_id uuid) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."current_gameplay_reset_eligibility"(p_user_id uuid) TO "service_role";
REVOKE ALL ON FUNCTION "public"."defer_tutorial_authentication"() FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."defer_tutorial_authentication"() TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."defer_tutorial_authentication"() TO "service_role";
REVOKE ALL ON FUNCTION "public"."discard_current_anonymous_account_for_switch"() FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."discard_current_anonymous_account_for_switch"() TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."discard_current_anonymous_account_for_switch"() TO "service_role";
REVOKE ALL ON FUNCTION "public"."dispatch_completed_free_normal_gacha_mission"() FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."dispatch_completed_free_normal_gacha_mission"() TO "service_role";
REVOKE ALL ON FUNCTION "public"."dispatch_guild_chat_mission"() FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."dispatch_guild_chat_mission"() TO "service_role";
REVOKE ALL ON FUNCTION "public"."distribute_ranking_rewards"() FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."distribute_ranking_rewards"() TO "service_role";
REVOKE ALL ON FUNCTION "public"."donate_to_guild"(p_user_id uuid, p_guild_id uuid, p_amount integer) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."donate_to_guild"(p_user_id uuid, p_guild_id uuid, p_amount integer) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."donate_to_guild"(p_user_id uuid, p_guild_id uuid, p_amount integer) TO "service_role";
REVOKE ALL ON FUNCTION "public"."enforce_guild_member_cap"() FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."enforce_guild_member_cap"() TO PUBLIC;
GRANT EXECUTE ON FUNCTION "public"."enforce_guild_member_cap"() TO "anon";
GRANT EXECUTE ON FUNCTION "public"."enforce_guild_member_cap"() TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."enforce_guild_member_cap"() TO "service_role";
REVOKE ALL ON FUNCTION "public"."equip_guild_cosmetic"(p_guild_id uuid, p_slot text, p_cosmetic_id text) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."equip_guild_cosmetic"(p_guild_id uuid, p_slot text, p_cosmetic_id text) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."equip_guild_cosmetic"(p_guild_id uuid, p_slot text, p_cosmetic_id text) TO "service_role";
REVOKE ALL ON FUNCTION "public"."process_gvg_battle_result_v2"(p_user_id uuid, p_guild_id uuid, p_base_id text, p_is_practice boolean, p_is_win boolean) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."process_gvg_battle_result_v2"(p_user_id uuid, p_guild_id uuid, p_base_id text, p_is_practice boolean, p_is_win boolean) TO "service_role";
REVOKE ALL ON FUNCTION "public"."resolve_quest_raid_encounter_v1"(p_patrol_id uuid) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."resolve_quest_raid_encounter_v1"(p_patrol_id uuid) TO "authenticated";
REVOKE ALL ON FUNCTION "public"."list_guild_emblems"(p_guild_id uuid) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."list_guild_emblems"(p_guild_id uuid) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."list_guild_emblems"(p_guild_id uuid) TO "service_role";
REVOKE ALL ON FUNCTION "public"."get_guild_emblems"(p_guild_ids uuid[]) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."get_guild_emblems"(p_guild_ids uuid[]) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."get_guild_emblems"(p_guild_ids uuid[]) TO "service_role";
REVOKE ALL ON FUNCTION "public"."set_guild_emblem"(p_guild_id uuid, p_emblem_id text) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."set_guild_emblem"(p_guild_id uuid, p_emblem_id text) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."set_guild_emblem"(p_guild_id uuid, p_emblem_id text) TO "service_role";
REVOKE ALL ON FUNCTION "public"."initialize_guild_emblem"() FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."initialize_guild_emblem"() TO "service_role";
REVOKE ALL ON FUNCTION "public"."set_profile_leader_v1"(p_character_id text) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."set_profile_leader_v1"(p_character_id text) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."set_profile_leader_v1"(p_character_id text) TO "service_role";
REVOKE ALL ON FUNCTION "public"."create_patrol_battle_replay"(p_patrol_id uuid, p_tactic_id text) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."create_patrol_battle_replay"(p_patrol_id uuid, p_tactic_id text) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."create_patrol_battle_replay"(p_patrol_id uuid, p_tactic_id text) TO "service_role";
REVOKE ALL ON FUNCTION "public"."_draw_gacha_item_before_special_release"(p_gacha_id text, p_rarity text) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."_draw_gacha_item_before_special_release"(p_gacha_id text, p_rarity text) TO "service_role";
REVOKE ALL ON FUNCTION "public"."draw_gacha_rarity"(p_gacha_id text) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."draw_gacha_rarity"(p_gacha_id text) TO "service_role";
REVOKE ALL ON FUNCTION "public"."enforce_canonical_guild_join_level"() FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."enforce_canonical_guild_join_level"() TO "service_role";
REVOKE ALL ON FUNCTION "public"."enforce_mission_claim_prerequisite"() FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."enforce_mission_claim_prerequisite"() TO "service_role";
REVOKE ALL ON FUNCTION "public"."ensure_active_special_missions"(p_user_id uuid) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."ensure_active_special_missions"(p_user_id uuid) TO "service_role";
REVOKE ALL ON FUNCTION "public"."ensure_current_player_profile"() FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."ensure_current_player_profile"() TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."ensure_current_player_profile"() TO "service_role";
REVOKE ALL ON FUNCTION "public"."equip_character_cosmetic"(p_user_character_id uuid, p_slot text, p_cosmetic_id text) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."equip_character_cosmetic"(p_user_character_id uuid, p_slot text, p_cosmetic_id text) TO "anon";
GRANT EXECUTE ON FUNCTION "public"."equip_character_cosmetic"(p_user_character_id uuid, p_slot text, p_cosmetic_id text) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."equip_character_cosmetic"(p_user_character_id uuid, p_slot text, p_cosmetic_id text) TO "service_role";
REVOKE ALL ON FUNCTION "public"."equip_gear_bulk"(p_character_id text, p_user_id uuid, p_gear_ids jsonb) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."equip_gear_bulk"(p_character_id text, p_user_id uuid, p_gear_ids jsonb) TO "service_role";
REVOKE ALL ON FUNCTION "public"."equip_guild_decoration"(p_guild_id uuid, p_type text, p_item_id text) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."equip_guild_decoration"(p_guild_id uuid, p_type text, p_item_id text) TO "anon";
GRANT EXECUTE ON FUNCTION "public"."equip_guild_decoration"(p_guild_id uuid, p_type text, p_item_id text) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."equip_guild_decoration"(p_guild_id uuid, p_type text, p_item_id text) TO "service_role";
REVOKE ALL ON FUNCTION "public"."equip_owned_title"(p_title_id text) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."equip_owned_title"(p_title_id text) TO "anon";
GRANT EXECUTE ON FUNCTION "public"."equip_owned_title"(p_title_id text) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."equip_owned_title"(p_title_id text) TO "service_role";
REVOKE ALL ON FUNCTION "public"."equip_skill_bulk"(p_character_id text, p_user_id uuid, p_skill_ids jsonb) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."equip_skill_bulk"(p_character_id text, p_user_id uuid, p_skill_ids jsonb) TO "service_role";
REVOKE ALL ON FUNCTION "public"."equip_user_cosmetic"(p_slot text, p_cosmetic_id text) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."equip_user_cosmetic"(p_slot text, p_cosmetic_id text) TO "anon";
GRANT EXECUTE ON FUNCTION "public"."equip_user_cosmetic"(p_slot text, p_cosmetic_id text) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."equip_user_cosmetic"(p_slot text, p_cosmetic_id text) TO "service_role";
REVOKE ALL ON FUNCTION "public"."equipment_level_battle_scale"(p_level integer) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."equipment_level_battle_scale"(p_level integer) TO "service_role";
REVOKE ALL ON FUNCTION "public"."execute_character_gacha"(p_user_id uuid, p_gacha_id text, p_pull_count integer, p_currency_type text, p_request_id uuid) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."execute_character_gacha"(p_user_id uuid, p_gacha_id text, p_pull_count integer, p_currency_type text, p_request_id uuid) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."execute_character_gacha"(p_user_id uuid, p_gacha_id text, p_pull_count integer, p_currency_type text, p_request_id uuid) TO "service_role";
REVOKE ALL ON FUNCTION "public"."finalize_daily_ranking_rewards"(p_ranking_day_key date) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."finalize_daily_ranking_rewards"(p_ranking_day_key date) TO "service_role";
REVOKE ALL ON FUNCTION "public"."get_raid_room_rescue_reward_v1"(p_room_id uuid) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."get_raid_room_rescue_reward_v1"(p_room_id uuid) TO "authenticated";
REVOKE ALL ON FUNCTION "public"."_grant_gameplay_reward_v1"(p_user uuid, p_source text, p_key text, p_item text, p_quantity integer) FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON FUNCTION "public"."finalize_preopen_guild_power_season_v2"(p_cosmetic_id text) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."finalize_preopen_guild_power_season_v2"(p_cosmetic_id text) TO "service_role";
REVOKE ALL ON FUNCTION "public"."close_gvg_preparation_missions_v1"(p_progress_end timestamp with time zone, p_claim_anchor timestamp with time zone) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."close_gvg_preparation_missions_v1"(p_progress_end timestamp with time zone, p_claim_anchor timestamp with time zone) TO "service_role";
REVOKE ALL ON FUNCTION "public"."evaluate_mission_progress"(p_user_id uuid, p_trigger_type text, p_progress_increment integer) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."evaluate_mission_progress"(p_user_id uuid, p_trigger_type text, p_progress_increment integer) TO "service_role";
REVOKE ALL ON FUNCTION "public"."execute_asset_gacha"(p_user_id uuid, p_gacha_id text, p_pull_count integer, p_currency_type text) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."execute_asset_gacha"(p_user_id uuid, p_gacha_id text, p_pull_count integer, p_currency_type text) TO "service_role";
REVOKE ALL ON FUNCTION "public"."execute_asset_gacha"(p_user_id uuid, p_gacha_id text, p_pull_count integer, p_currency_type text, p_request_id uuid) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."execute_asset_gacha"(p_user_id uuid, p_gacha_id text, p_pull_count integer, p_currency_type text, p_request_id uuid) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."execute_asset_gacha"(p_user_id uuid, p_gacha_id text, p_pull_count integer, p_currency_type text, p_request_id uuid) TO "service_role";
REVOKE ALL ON FUNCTION "public"."execute_character_gacha"(p_user_id uuid, p_gacha_id text, p_pull_count integer, p_currency_type text) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."execute_character_gacha"(p_user_id uuid, p_gacha_id text, p_pull_count integer, p_currency_type text) TO "service_role";
REVOKE ALL ON FUNCTION "public"."execute_character_gacha_core_20260812"(p_user_id uuid, p_gacha_id text, p_pull_count integer, p_currency_type text) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."execute_character_gacha_core_20260812"(p_user_id uuid, p_gacha_id text, p_pull_count integer, p_currency_type text) TO "service_role";
REVOKE ALL ON FUNCTION "public"."execute_gacha"(p_user_id uuid, p_currency_type text, p_currency_cost integer, p_results jsonb) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."execute_gacha"(p_user_id uuid, p_currency_type text, p_currency_cost integer, p_results jsonb) TO "service_role";
REVOKE ALL ON FUNCTION "public"."execute_gacha"(p_user_id uuid, p_scout_type text, p_scout_count integer, p_use_currency text) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."execute_gacha"(p_user_id uuid, p_scout_type text, p_scout_count integer, p_use_currency text) TO "service_role";
REVOKE ALL ON FUNCTION "public"."execute_tutorial_character_gacha"(p_request_id uuid) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."execute_tutorial_character_gacha"(p_request_id uuid) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."execute_tutorial_character_gacha"(p_request_id uuid) TO "service_role";
REVOKE ALL ON FUNCTION "public"."finalize_preopen_guild_power_season"() FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."finalize_preopen_guild_power_season"() TO "service_role";
REVOKE ALL ON FUNCTION "public"."finalize_pvp_battle"(p_replay_id uuid, p_result jsonb) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."finalize_pvp_battle"(p_replay_id uuid, p_result jsonb) TO "service_role";
REVOKE ALL ON FUNCTION "public"."finalize_pvp_season_rewards"(p_season_id uuid) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."finalize_pvp_season_rewards"(p_season_id uuid) TO "service_role";
REVOKE ALL ON FUNCTION "public"."finalize_raid_battle"(p_replay_id uuid, p_result jsonb) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."finalize_raid_battle"(p_replay_id uuid, p_result jsonb) TO "service_role";
REVOKE ALL ON FUNCTION "public"."get_public_ranking_reward_master"() FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."get_public_ranking_reward_master"() TO "service_role";
GRANT EXECUTE ON FUNCTION "public"."get_public_ranking_reward_master"() TO "authenticated";
REVOKE ALL ON FUNCTION "public"."record_current_guild_login"() FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."record_current_guild_login"() TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."record_current_guild_login"() TO "service_role";
REVOKE ALL ON FUNCTION "public"."get_growth_exp_master"() FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."get_growth_exp_master"() TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."get_growth_exp_master"() TO "service_role";
REVOKE ALL ON FUNCTION "public"."quote_growth_exp"(p_kind text, p_owned_id uuid, p_materials jsonb) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."quote_growth_exp"(p_kind text, p_owned_id uuid, p_materials jsonb) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."quote_growth_exp"(p_kind text, p_owned_id uuid, p_materials jsonb) TO "service_role";
REVOKE ALL ON FUNCTION "public"."execute_growth_exp"(p_kind text, p_owned_id uuid, p_materials jsonb, p_request_id uuid) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."execute_growth_exp"(p_kind text, p_owned_id uuid, p_materials jsonb, p_request_id uuid) TO "service_role";
REVOKE ALL ON FUNCTION "public"."level_up_character_exp"(p_character_id uuid, p_materials jsonb, p_request_id uuid) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."level_up_character_exp"(p_character_id uuid, p_materials jsonb, p_request_id uuid) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."level_up_character_exp"(p_character_id uuid, p_materials jsonb, p_request_id uuid) TO "service_role";
REVOKE ALL ON FUNCTION "public"."level_up_equipment_exp"(p_equipment_id uuid, p_materials jsonb, p_request_id uuid) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."level_up_equipment_exp"(p_equipment_id uuid, p_materials jsonb, p_request_id uuid) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."level_up_equipment_exp"(p_equipment_id uuid, p_materials jsonb, p_request_id uuid) TO "service_role";
REVOKE ALL ON FUNCTION "public"."monthly_power_continuous_jst_days"(p_joined timestamp with time zone, p_start timestamp with time zone, p_end timestamp with time zone) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."monthly_power_continuous_jst_days"(p_joined timestamp with time zone, p_start timestamp with time zone, p_end timestamp with time zone) TO "service_role";
REVOKE ALL ON FUNCTION "public"."finalize_raid_season_rewards"(p_season_id uuid) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."finalize_raid_season_rewards"(p_season_id uuid) TO "service_role";
REVOKE ALL ON FUNCTION "public"."find_gvg_match_opponent"(p_session_key text, p_guild_id uuid) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."find_gvg_match_opponent"(p_session_key text, p_guild_id uuid) TO "anon";
GRANT EXECUTE ON FUNCTION "public"."find_gvg_match_opponent"(p_session_key text, p_guild_id uuid) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."find_gvg_match_opponent"(p_session_key text, p_guild_id uuid) TO "service_role";
REVOKE ALL ON FUNCTION "public"."funnel_mission_trigger_type"(p_milestone text) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."funnel_mission_trigger_type"(p_milestone text) TO "service_role";
REVOKE ALL ON FUNCTION "public"."generate_canonical_quest_encounter_snapshot"(p_user_id uuid, p_quest_id text, p_allow_repeat_reroll boolean) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."generate_canonical_quest_encounter_snapshot"(p_user_id uuid, p_quest_id text, p_allow_repeat_reroll boolean) TO PUBLIC;
GRANT EXECUTE ON FUNCTION "public"."generate_canonical_quest_encounter_snapshot"(p_user_id uuid, p_quest_id text, p_allow_repeat_reroll boolean) TO "anon";
GRANT EXECUTE ON FUNCTION "public"."generate_canonical_quest_encounter_snapshot"(p_user_id uuid, p_quest_id text, p_allow_repeat_reroll boolean) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."generate_canonical_quest_encounter_snapshot"(p_user_id uuid, p_quest_id text, p_allow_repeat_reroll boolean) TO "service_role";
REVOKE ALL ON FUNCTION "public"."generate_current_user_invite_code"() FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."generate_current_user_invite_code"() TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."generate_current_user_invite_code"() TO "service_role";
REVOKE ALL ON FUNCTION "public"."generate_user_gift_code"(p_user_id uuid) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."generate_user_gift_code"(p_user_id uuid) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."generate_user_gift_code"(p_user_id uuid) TO "service_role";
REVOKE ALL ON FUNCTION "public"."get_active_mission_events"() FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."get_active_mission_events"() TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."get_active_mission_events"() TO "service_role";
REVOKE ALL ON FUNCTION "public"."get_active_ranking_seasons"() FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."get_active_ranking_seasons"() TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."get_active_ranking_seasons"() TO "service_role";
REVOKE ALL ON FUNCTION "public"."get_bbs_unread_counts"() FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."get_bbs_unread_counts"() TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."get_bbs_unread_counts"() TO "service_role";
REVOKE ALL ON FUNCTION "public"."get_canonical_quest_progression"() FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."get_canonical_quest_progression"() TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."get_canonical_quest_progression"() TO "service_role";
REVOKE ALL ON FUNCTION "public"."get_chat_unread_counts"() FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."get_chat_unread_counts"() TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."get_chat_unread_counts"() TO "service_role";
REVOKE ALL ON FUNCTION "public"."get_current_main_formation"() FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."get_current_main_formation"() TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."get_current_main_formation"() TO "service_role";
REVOKE ALL ON FUNCTION "public"."get_current_onboarding_state"() FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."get_current_onboarding_state"() TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."get_current_onboarding_state"() TO "service_role";
REVOKE ALL ON FUNCTION "public"."get_my_power_snapshot"() FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."get_my_power_snapshot"() TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."get_my_power_snapshot"() TO "service_role";
REVOKE ALL ON FUNCTION "public"."monthly_power_live_rankings_v1"(p_type text) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."monthly_power_live_rankings_v1"(p_type text) TO "service_role";
REVOKE ALL ON FUNCTION "public"."reject_monthly_power_snapshot_mutation"() FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."reject_monthly_power_snapshot_mutation"() TO "service_role";
REVOKE ALL ON FUNCTION "public"."snapshot_monthly_power_season_v1"(p_season_id uuid) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."snapshot_monthly_power_season_v1"(p_season_id uuid) TO "service_role";
REVOKE ALL ON FUNCTION "public"."guard_monthly_power_season_cutoff"() FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."guard_monthly_power_season_cutoff"() TO "service_role";
REVOKE ALL ON FUNCTION "public"."grant_monthly_power_items_v1"(p_season_id uuid) FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON FUNCTION "public"."finalize_monthly_power_season_rewards_v1"(p_season_id uuid) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."finalize_monthly_power_season_rewards_v1"(p_season_id uuid) TO "service_role";
REVOKE ALL ON FUNCTION "public"."get_current_raid_attempt_state"() FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."get_current_raid_attempt_state"() TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."get_current_raid_attempt_state"() TO "service_role";
REVOKE ALL ON FUNCTION "public"."get_current_raid_battle_rewards"(p_replay_id uuid) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."get_current_raid_battle_rewards"(p_replay_id uuid) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."get_current_raid_battle_rewards"(p_replay_id uuid) TO "service_role";
REVOKE ALL ON FUNCTION "public"."get_current_skill_display"(p_skill_ids text[]) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."get_current_skill_display"(p_skill_ids text[]) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."get_current_skill_display"(p_skill_ids text[]) TO "service_role";
REVOKE ALL ON FUNCTION "public"."get_direct_message_unread_counts"() FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."get_direct_message_unread_counts"() TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."get_direct_message_unread_counts"() TO "service_role";
REVOKE ALL ON FUNCTION "public"."get_friend_helper_loadout"(p_friend_user_id uuid) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."get_friend_helper_loadout"(p_friend_user_id uuid) TO "service_role";
GRANT EXECUTE ON FUNCTION "public"."get_friend_helper_loadout"(p_friend_user_id uuid) TO "authenticated";
REVOKE ALL ON FUNCTION "public"."get_friend_helper_loadout_core_20260823"(p_friend_user_id uuid) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."get_friend_helper_loadout_core_20260823"(p_friend_user_id uuid) TO "service_role";
REVOKE ALL ON FUNCTION "public"."get_my_pending_ranking_reward_notification"() FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."get_my_pending_ranking_reward_notification"() TO "service_role";
GRANT EXECUTE ON FUNCTION "public"."get_my_pending_ranking_reward_notification"() TO "authenticated";
REVOKE ALL ON FUNCTION "public"."get_patrol_battle_enemy"(p_patrol_id uuid) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."get_patrol_battle_enemy"(p_patrol_id uuid) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."get_patrol_battle_enemy"(p_patrol_id uuid) TO "service_role";
REVOKE ALL ON FUNCTION "public"."get_pending_mission_event_dialog"() FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."get_pending_mission_event_dialog"() TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."get_pending_mission_event_dialog"() TO "service_role";
REVOKE ALL ON FUNCTION "public"."get_public_battle_loadout"(p_target_user_id uuid) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."get_public_battle_loadout"(p_target_user_id uuid) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."get_public_battle_loadout"(p_target_user_id uuid) TO "service_role";
REVOKE ALL ON FUNCTION "public"."get_public_battle_roster"(p_target_user_id uuid) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."get_public_battle_roster"(p_target_user_id uuid) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."get_public_battle_roster"(p_target_user_id uuid) TO "service_role";
REVOKE ALL ON FUNCTION "public"."gvg_season_reset"() FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."gvg_season_reset"() TO "service_role";
REVOKE ALL ON FUNCTION "public"."_issue_raid_room_rescue_rewards_v1"(p_room_id uuid) FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON FUNCTION "public"."_issue_raid_room_clear_rewards_v1"(p_room_id uuid) FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON FUNCTION "public"."issue_quest_raid_encounter_bonus_v1"() FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON FUNCTION "public"."get_monthly_power_season_rewards_v1"(p_ranking_type text) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."get_monthly_power_season_rewards_v1"(p_ranking_type text) TO "service_role";
GRANT EXECUTE ON FUNCTION "public"."get_monthly_power_season_rewards_v1"(p_ranking_type text) TO "authenticated";
REVOKE ALL ON FUNCTION "public"."start_formal_open_seasons_v1"(p_open_at timestamp with time zone) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."start_formal_open_seasons_v1"(p_open_at timestamp with time zone) TO "service_role";
REVOKE ALL ON FUNCTION "public"."finalize_due_monthly_power_seasons_v1"() FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."finalize_due_monthly_power_seasons_v1"() TO "service_role";
REVOKE ALL ON FUNCTION "public"."get_equipped_season_honors"(p_owner_scope text, p_owner_id uuid) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."get_equipped_season_honors"(p_owner_scope text, p_owner_id uuid) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."get_equipped_season_honors"(p_owner_scope text, p_owner_id uuid) TO "service_role";
REVOKE ALL ON FUNCTION "public"."_issue_raid_daily_clear_bonus_v2"(p_room_id uuid, p_user_id uuid) FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON FUNCTION "public"."claim_patrol_rewards"(p_patrol_id uuid) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."claim_patrol_rewards"(p_patrol_id uuid) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."claim_patrol_rewards"(p_patrol_id uuid) TO "service_role";
REVOKE ALL ON FUNCTION "public"."get_public_battle_roster_by_character_ids"(p_character_ids uuid[]) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."get_public_battle_roster_by_character_ids"(p_character_ids uuid[]) TO "anon";
GRANT EXECUTE ON FUNCTION "public"."get_public_battle_roster_by_character_ids"(p_character_ids uuid[]) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."get_public_battle_roster_by_character_ids"(p_character_ids uuid[]) TO "service_role";
REVOKE ALL ON FUNCTION "public"."get_public_guild_base_controls"() FROM PUBLIC, anon, authenticated, service_role;
