import fs from 'node:fs';import crypto from 'node:crypto';import assert from 'node:assert/strict';
const root=process.env.GAME04_RAID_QA_DIR;if(!root)throw Error('GAME04_RAID_QA_DIR required (private session directory)');
const cfg=JSON.parse(fs.readFileSync(new URL('../../config/game04-preview-public.json',import.meta.url)));
assert.equal(cfg.supabaseUrl,'https://lrgyllgzcdcphlbmkknc.supabase.co');
const phase=process.argv[2];
async function session(label){let s;const p=`${root}/${label}.json`;if(fs.existsSync(p))s=JSON.parse(fs.readFileSync(p));else {if(phase!=='bootstrap')throw Error('Bootstrap QA sessions first');const r=await fetch(cfg.supabaseUrl+'/auth/v1/signup',{method:'POST',headers:{apikey:cfg.supabaseAnonKey,'Content-Type':'application/json'},body:JSON.stringify({data:{qa:true,purpose:'game04-m5-06-shared-level-20260919'}})});s=await r.json();if(!r.ok)throw Error(`signup:${r.status}`);fs.writeFileSync(p,JSON.stringify(s),{mode:0o600});}if(s.expires_at*1000<Date.now()+60000){const r=await fetch(cfg.supabaseUrl+'/auth/v1/token?grant_type=refresh_token',{method:'POST',headers:{apikey:cfg.supabaseAnonKey,'Content-Type':'application/json'},body:JSON.stringify({refresh_token:s.refresh_token})});s=await r.json();assert.ok(r.ok);fs.writeFileSync(p,JSON.stringify(s),{mode:0o600});}return s;}
const a=await session('a'),b=await session('b');
async function call(s,path,body){const r=await fetch(cfg.supabaseUrl+path,{method:'POST',headers:{apikey:cfg.supabaseAnonKey,Authorization:`Bearer ${s.access_token}`,'Content-Type':'application/json'},body:JSON.stringify(body)});const d=await r.json();if(!r.ok)throw Error(JSON.stringify({status:r.status,error:d.error||d.message,path}));return d;}
async function api(s,action,payload={},requestId=crypto.randomUUID()){return call(s,'/functions/v1/game04-redesign-api',{action,payload,requestId});}
if(phase==='bootstrap'){for(const [s,n]of [[a,'QA共有Lv主催'],[b,'QA共有Lv参加']]){await call(s,'/rest/v1/rpc/initialize_current_player',{p_username:n,p_invite_code:null});const result=await api(s,'get_state');fs.writeFileSync(`${root}/${s===a?'a':'b'}-state.json`,JSON.stringify(result.state));}fs.writeFileSync(`${root}/ids.json`,JSON.stringify({owner:a.user.id,late:b.user.id,room:crypto.randomUUID()},null,2));console.log(fs.readFileSync(`${root}/ids.json`,'utf8'));process.exit();}
const ids=JSON.parse(fs.readFileSync(`${root}/ids.json`));const roomOf=d=>d.rooms.find(r=>r.id===ids.room);const mine=d=>roomOf(d).participants.find(p=>p.userId===b.user.id);
if(phase==='join-win'){await api(b,'raid_join',{roomId:ids.room});const pre=await api(b,'get_state');assert.equal(roomOf(pre).level,14);const id=crypto.randomUUID();const r=await api(b,'raid_battle',{roomId:ids.room},id);assert.equal(r.battle.outcome,'win');assert.equal(r.battle.frames[0].enemies[0].maxHp,19175);const retry=await api(b,'raid_battle',{roomId:ids.room},id);assert.equal(mine(retry).wins,1);assert.equal(r.state.energy,retry.state.energy);fs.writeFileSync(`${root}/win.json`,JSON.stringify(r));console.log(JSON.stringify({phase,id,outcome:r.battle.outcome,enemyHp:r.battle.frames[0].enemies[0].maxHp,wins:mine(r).wins,energy:r.state.energy}));}
if(phase==='win2'){const r=await api(b,'raid_battle',{roomId:ids.room});assert.equal(r.battle.outcome,'win');assert.equal(mine(r).wins,2);console.log(JSON.stringify({phase,outcome:r.battle.outcome,wins:mine(r).wins}));}
if(phase==='lose'){const r=await api(b,'raid_battle',{roomId:ids.room});assert.equal(r.battle.outcome,'lose');assert.equal(mine(r).wins,1);fs.writeFileSync(`${root}/lose.json`,JSON.stringify(r));console.log(JSON.stringify({phase,outcome:r.battle.outcome,wins:mine(r).wins}));}
if(phase==='resume'){const f=JSON.parse(fs.readFileSync(`${root}/resume-ids.json`));const pre=await api(b,'get_state');const r=await api(b,'raid_battle',{roomId:ids.room},f.lateBattle);assert.equal(r.battle.outcome,'win');assert.equal(roomOf(r).level,15);assert.equal(roomOf(r).hp,roomOf(pre).hp);assert.equal(mine(r).wins,3);assert.equal(roomOf(r).rewardGrants.some(g=>g.userId===b.user.id&&g.id.startsWith('defeat:14:')),false);fs.writeFileSync(`${root}/resume.json`,JSON.stringify(r));console.log(JSON.stringify({phase,sharedLevel:roomOf(r).level,hp:roomOf(r).hp,wins:mine(r).wins,oldEnemyHp:r.battle.frames[0].enemies[0].maxHp}));}
if(phase==='owner-defeat'){const f=JSON.parse(fs.readFileSync(`${root}/resume-ids.json`));const r=await api(a,'raid_battle',{roomId:ids.room},f.ownerBattle);assert.equal(roomOf(r).level,15);console.log(JSON.stringify({phase,level:roomOf(r).level,hp:roomOf(r).hp}));}
if(phase==='new-defeat-claim'){const r=await api(b,'raid_battle',{roomId:ids.room});assert.equal(r.battle.outcome,'win');assert.equal(roomOf(r).level,16);assert.ok(r.battle.frames[0].enemies[0].maxHp>19175);const grant=roomOf(r).rewardGrants.find(g=>g.id===`defeat:15:${b.user.id}`);assert.ok(grant);const [r1,r2]=await Promise.all([api(b,'raid_claim',{roomId:ids.room}),api(b,'raid_claim',{roomId:ids.room})].map(p=>p.catch(e=>({error:e.message}))));const final=await api(b,'raid_claim',{roomId:ids.room});assert.ok(roomOf(final).rewardGrants.filter(g=>g.userId===b.user.id).every(g=>g.claimed));const again=await api(b,'raid_claim',{roomId:ids.room});assert.deepEqual(final.state.materials,again.state.materials);const expected={...r.state.materials};for(const g of roomOf(r).rewardGrants.filter(g=>g.userId===b.user.id&&!g.claimed))for(const rw of g.rewards){if(rw.kind==='skill_material')expected.skill+=rw.amount;if(rw.kind==='equipment_material')expected.equipment+=rw.amount;}assert.deepEqual(final.state.materials,expected);fs.writeFileSync(`${root}/final.json`,JSON.stringify(final));console.log(JSON.stringify({phase,nextEnemyHp:r.battle.frames[0].enemies[0].maxHp,grantId:grant.id,parallelClaimResponses:[r1.error?'conflict':'ok',r2.error?'conflict':'ok'],materials:final.state.materials}));}

if(phase==='concurrent'){const f=JSON.parse(fs.readFileSync(`${root}/resume-ids.json`));const before=await api(b,'get_state');const previous=roomOf(before);const results=await Promise.all([api(a,'raid_battle',{roomId:ids.room},f.ownerBattle),api(b,'raid_battle',{roomId:ids.room},f.lateBattle)]);const final=await api(b,'get_state');const current=roomOf(final);const damage=results.reduce((sum,r)=>sum+Math.floor(r.battle.totalDamage*(r.battle.outcome==='win'?1.5:1)),0);assert.equal(current.hp,previous.hp-damage);assert.equal(current.participants.reduce((sum,p)=>sum+p.attempts,0),previous.participants.reduce((sum,p)=>sum+p.attempts,0)+2);assert.ok(current.settledBattleIds.includes(f.ownerBattle)&&current.settledBattleIds.includes(f.lateBattle));fs.writeFileSync(`${root}/concurrent.json`,JSON.stringify(final));console.log(JSON.stringify({phase,level:current.level,combinedDamage:damage,sharedHp:current.hp,bothSettled:true}));}
