// Version-specific adapter. Network and Deno server registration are disabled.
// Do not apply this symbol map to a different bundle; hash mismatch MUST stop.
const fs=require('fs'),vm=require('vm'),crypto=require('crypto');
const {clean,keyed}=require('./runtime.cjs');
function collect(file){const source=fs.readFileSync(file,'utf8');const hash=crypto.createHash('sha256').update(source).digest('hex');if(hash!=='59e497ae9278ba1108ed3a31f510bd4d266eac6535c815bc5f26692f29eac215')throw Error('Unknown API bundle: '+hash);
 const c={structuredClone,crypto:globalThis.crypto,URL,Response,Request,TextEncoder,TextDecoder,Deno:{env:{get:()=>''},serve:()=>{}},fetch:()=>{throw Error('audit network disabled')}};vm.createContext(c);vm.runInContext(source,c,{timeout:10000});
 return clean({characters:keyed(c.De.map(x=>({...x,stats:undefined,levels:Object.fromEntries(Array.from({length:100},(_,i)=>[i+1,c.Ka(x,i+1,0)])),passives:Object.fromEntries(Array.from({length:6},(_,i)=>[i,c.Le(x,i)??null]))}))),skills:keyed(c.Cu.flatMap(id=>Array.from({length:11},(_,lb)=>({lb,...c.Ju(id,lb)}))),r=>r.id+':'+r.lb),equipment:keyed(c.ge.map(x=>({...x,levels:Object.fromEntries(Array.from({length:100},(_,i)=>[i+1,c.wa(x,i+1,0)]))}))),quests:keyed(c.Ru),encounters:keyed(c.H0),invasions:keyed(c.Nu.flatMap(x=>[0,.5,.999999].map(draw=>({draw,...c.Zt(x.id,()=>draw)}))),r=>r.id+':'+r.draw),missions:keyed(c.yt.missions),initial:c.Pa('AUDIT_NEW_USER'),battleRules:c.Ze,acquisition:c.o0,formalGacha:c.tu,growth:{version:c.ke,expValues:c.i0,soulUnlock:c.Da,awakening:c.fa,lbSteps:c.s0,skillLbFactors:c.Ca,equipmentLbFactors:c.ga,duplicates:c.r0,totals:c.n0,rows:['character','equipment'].flatMap(kind=>['N','R','SR','SSR'].flatMap(rarity=>Array.from({length:100},(_,i)=>({kind,rarity,level:i+1,exp:c.He(kind,rarity,i+1),cash:c.l0(kind,rarity,i+1)})))),playerExp:Array.from({length:100},(_,i)=>c.d0(i+1))}});
}
module.exports={collect};if(require.main===module)fs.writeFileSync(process.argv[3],JSON.stringify(collect(process.argv[2]),null,2)+'\n');
