begin;
do $$
declare uid uuid:='e6e9a324-0dfb-4042-b490-6e0a1ebc056c'; v1 uuid:=gen_random_uuid(); v2 uuid:=gen_random_uuid(); v3 uuid:=gen_random_uuid(); r jsonb; gift uuid; before_balance bigint; today text:=to_char(statement_timestamp() at time zone 'Asia/Tokyo','YYYY-MM-DD');
begin
 if not exists(select 1 from public.users where id=uid and username='UI検証A') then raise exception 'Dedicated QA guard';end if;
 perform set_config('request.jwt.claim.sub',uid::text,true);
 delete from public.game04_home_promotion_visits where user_id=uid;
 delete from public.game04_home_promotion_state where user_id=uid;
 update public.game04_player_state set state=jsonb_set(jsonb_set(jsonb_set(state,'{tutorial}','{"step":16}'),'{earlyProgress}','{"completedAreas":[]}'),'{clearedStages}','[]') - 'dailyNormalGachaDate' where user_id=uid;
 r:=public.game04_home_promotion(v1,'enter');if r?'kind' then raise exception 'tutorial promotion';end if;
 if exists(select 1 from public.game04_home_promotion_state where user_id=uid) then raise exception 'tutorial counted';end if;
 update public.game04_player_state set state=jsonb_set(state,'{tutorial}','{"step":17}') where user_id=uid;
 r:=public.game04_home_promotion(v1,'enter');if r?'kind' then raise exception 'first entry promotion';end if;
 r:=public.game04_home_promotion(v1,'enter');if (select visits from public.game04_home_promotion_state where user_id=uid)<>1 then raise exception 'retry counted';end if;
 r:=public.game04_home_promotion(v2,'enter');if r->>'kind'<>'daily-free' then raise exception 'second missing';end if;
 r:=public.game04_home_promotion(v2,'reserve');
 if (select free_shown_day from public.game04_home_promotion_state where user_id=uid) is not null then raise exception 'reserved counted as shown';end if;
 perform public.game04_home_promotion(v3,'enter');r:=public.game04_home_promotion(v3,'reserve');if r?'kind' then raise exception 'cross-device reservation';end if;
 r:=public.game04_home_promotion(v2,'shown');if r->>'recorded'<>'true' then raise exception 'display not saved';end if;
 r:=public.game04_home_promotion(v3,'reserve');if r?'kind' then raise exception 'daily repeat';end if;
 update public.game04_home_promotion_state set free_shown_day='2000-01-01' where user_id=uid;
 update public.game04_player_state set state=jsonb_set(state,'{dailyNormalGachaDate}',to_jsonb(today)) where user_id=uid;
 r:=public.game04_home_promotion(v3,'reserve');if r?'kind' then raise exception 'already used shown';end if;
 update public.game04_player_state set state=state-'dailyNormalGachaDate' where user_id=uid;
 r:=public.game04_home_promotion(v3,'reserve');if r->>'kind'<>'daily-free' then raise exception 'next JST day missing';end if;
 perform public.game04_home_promotion(v3,'release');
 update public.game04_player_state set state=jsonb_set(state,'{earlyProgress,completedAreas}','["mikawa"]') where user_id=uid;
 insert into public.user_shop_purchases(user_id,product_id,purchase_count) values(uid,'beginner_pack_01',1) on conflict(user_id,product_id) do update set purchase_count=1;
 r:=public.game04_home_promotion(v3,'reserve');if r->>'kind'='starter' then raise exception 'purchased starter promoted';end if;
 perform public.game04_home_promotion(v3,'release');
 delete from public.user_shop_purchases where user_id=uid and product_id='beginner_pack_01';
 r:=public.game04_home_promotion(v3,'reserve');if r->>'kind'<>'starter' then raise exception 'starter priority';end if;
 perform public.game04_home_promotion(v3,'shown');
 r:=public.game04_home_promotion(v3,'reserve');if r?'kind' then raise exception 'stacked promotion';end if;
 if (select starter_shown_at from public.game04_home_promotion_state where user_id=uid) is null then raise exception 'starter not saved';end if;
 -- No real campaign enabled outside this transaction; all QA grants roll back.
 if public.game04_ensure_release_present() is not null then raise exception 'disabled campaign granted';end if;
 update public.game04_release_campaigns set enabled=true,claim_policy_approved=true,starts_at=statement_timestamp()+interval '1 day' where id='game04-release-2026';
 if public.game04_ensure_release_present() is not null then raise exception 'before start granted';end if;
 update public.game04_release_campaigns set starts_at=statement_timestamp()-interval '1 day',ends_at=statement_timestamp() where id='game04-release-2026';
 if public.game04_ensure_release_present() is not null then raise exception 'exclusive end granted';end if;
 update public.game04_release_campaigns set ends_at='2026-12-31 15:00+00' where id='game04-release-2026';
 gift:=public.game04_ensure_release_present();if gift is null then raise exception 'eligible no gift';end if;
 if public.game04_ensure_release_present()<>gift then raise exception 'duplicate gift';end if;
 if not exists(select 1 from public.presents where id=gift and quantity=300 and item_id='DIAMOND' and expire_at=statement_timestamp()+interval '90 days') then raise exception 'invalid gift';end if;
 if exists(select 1 from public.billing_asset_lots where present_id=gift) then raise exception 'free became paid';end if;
 select neon_diamonds into before_balance from public.users where id=uid;
 perform public.claim_present(gift);
 if (select neon_diamonds from public.users where id=uid)<>before_balance+300 then raise exception 'incorrect claim balance';end if;
 begin perform public.claim_present(gift);raise exception 'duplicate claim accepted';exception when others then if sqlerrm='duplicate claim accepted' then raise;end if;end;
 if (select neon_diamonds from public.users where id=uid)<>before_balance+300 then raise exception 'duplicate credit';end if;
end $$;
rollback;
select 'PASS: tutorial/first/second/idempotent entry/reservation/actual shown/daily/free used/starter priority/no stacking/campaign disabled/start/end/dedup/free claim. All QA changes rolled back.' result;
