SET check_function_bodies = false;
SET search_path = public, extensions, pg_catalog;
ALTER TABLE "public"."battle_replay_events" ADD CONSTRAINT "battle_replay_events_battle_replay_session_id_fkey" FOREIGN KEY (battle_replay_session_id) REFERENCES battle_replay_sessions(id) ON DELETE CASCADE;
ALTER TABLE "public"."battle_replay_sessions" ADD CONSTRAINT "battle_replay_sessions_requester_user_id_fkey" FOREIGN KEY (requester_user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE "public"."bbs_posts" ADD CONSTRAINT "bbs_posts_thread_id_fkey" FOREIGN KEY (thread_id) REFERENCES bbs_threads(id) ON DELETE CASCADE;
ALTER TABLE "public"."bbs_posts" ADD CONSTRAINT "bbs_posts_user_id_fkey" FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE "public"."bbs_read_states" ADD CONSTRAINT "bbs_read_states_thread_id_fkey" FOREIGN KEY (thread_id) REFERENCES bbs_threads(id) ON DELETE CASCADE;
ALTER TABLE "public"."bbs_read_states" ADD CONSTRAINT "bbs_read_states_user_id_fkey" FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE "public"."bbs_threads" ADD CONSTRAINT "bbs_threads_user_id_fkey" FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE "public"."billing_asset_lots" ADD CONSTRAINT "billing_asset_lots_order_id_fkey" FOREIGN KEY (order_id) REFERENCES billing_orders(id);
ALTER TABLE "public"."billing_asset_lots" ADD CONSTRAINT "billing_asset_lots_present_id_fkey" FOREIGN KEY (present_id) REFERENCES presents(id);
ALTER TABLE "public"."billing_asset_lots" ADD CONSTRAINT "billing_asset_lots_source_lot_id_fkey" FOREIGN KEY (source_lot_id) REFERENCES billing_asset_lots(id);
ALTER TABLE "public"."billing_asset_lots" ADD CONSTRAINT "billing_asset_lots_user_id_fkey" FOREIGN KEY (user_id) REFERENCES users(id);
ALTER TABLE "public"."billing_grants" ADD CONSTRAINT "billing_grants_order_id_fkey" FOREIGN KEY (order_id) REFERENCES billing_orders(id);
ALTER TABLE "public"."billing_grants" ADD CONSTRAINT "billing_grants_user_id_fkey" FOREIGN KEY (user_id) REFERENCES users(id);
ALTER TABLE "public"."billing_orders" ADD CONSTRAINT "billing_orders_product_id_fkey" FOREIGN KEY (product_id) REFERENCES billing_products(id);
ALTER TABLE "public"."billing_orders" ADD CONSTRAINT "billing_orders_user_id_fkey" FOREIGN KEY (user_id) REFERENCES users(id);
ALTER TABLE "public"."billing_shop_receipts" ADD CONSTRAINT "billing_shop_receipts_product_id_fkey" FOREIGN KEY (product_id) REFERENCES billing_products(id);
ALTER TABLE "public"."billing_shop_receipts" ADD CONSTRAINT "billing_shop_receipts_user_id_fkey" FOREIGN KEY (user_id) REFERENCES users(id);
ALTER TABLE "public"."board_posts" ADD CONSTRAINT "board_posts_author_id_fkey" FOREIGN KEY (author_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE "public"."board_posts" ADD CONSTRAINT "board_posts_raid_rescue_id_fkey" FOREIGN KEY (raid_rescue_id) REFERENCES raid_room_rescue_publications(id);
ALTER TABLE "public"."board_posts" ADD CONSTRAINT "board_posts_reply_to_message_id_fkey" FOREIGN KEY (reply_to_message_id) REFERENCES board_posts(id) ON DELETE SET NULL;
ALTER TABLE "public"."board_posts" ADD CONSTRAINT "board_posts_user_id_fkey" FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE "public"."canonical_character_growth_assignments" ADD CONSTRAINT "canonical_character_growth_assignment_version_character_id_fkey" FOREIGN KEY (version, character_id) REFERENCES canonical_character_master(version, character_id);
ALTER TABLE "public"."canonical_character_growth_assignments" ADD CONSTRAINT "canonical_character_growth_assignments_growth_pattern_id_fkey" FOREIGN KEY (growth_pattern_id) REFERENCES canonical_character_growth_exponents(growth_pattern_id);
ALTER TABLE "public"."canonical_character_master" ADD CONSTRAINT "canonical_character_master_version_fkey" FOREIGN KEY (version) REFERENCES canonical_gameplay_master_versions(version);
ALTER TABLE "public"."canonical_daily_activity_claims" ADD CONSTRAINT "canonical_daily_activity_claims_user_id_fkey" FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE "public"."canonical_equipment_lb_slot_options" ADD CONSTRAINT "canonical_equipment_lb_slot_options_version_fkey" FOREIGN KEY (version) REFERENCES canonical_gameplay_master_versions(version);
ALTER TABLE "public"."canonical_equipment_lb_steps" ADD CONSTRAINT "canonical_equipment_lb_steps_version_fkey" FOREIGN KEY (version) REFERENCES canonical_gameplay_master_versions(version);
ALTER TABLE "public"."canonical_equipment_master" ADD CONSTRAINT "canonical_equipment_master_version_fkey" FOREIGN KEY (version) REFERENCES canonical_gameplay_master_versions(version);
ALTER TABLE "public"."canonical_skill_master" ADD CONSTRAINT "canonical_skill_master_version_fkey" FOREIGN KEY (version) REFERENCES canonical_gameplay_master_versions(version);
ALTER TABLE "public"."character_battle_master" ADD CONSTRAINT "character_battle_master_growth_pattern_id_fkey" FOREIGN KEY (growth_pattern_id) REFERENCES character_growth_patterns(pattern_id);
ALTER TABLE "public"."character_cosmetics" ADD CONSTRAINT "character_cosmetics_cosmetic_id_fkey" FOREIGN KEY (cosmetic_id) REFERENCES cosmetic_master(id) ON DELETE CASCADE;
ALTER TABLE "public"."character_cosmetics" ADD CONSTRAINT "character_cosmetics_user_character_id_fkey" FOREIGN KEY (user_character_id) REFERENCES user_characters(id) ON DELETE CASCADE;
ALTER TABLE "public"."character_release_master" ADD CONSTRAINT "character_release_master_growth_pattern_id_fkey" FOREIGN KEY (growth_pattern_id) REFERENCES character_growth_patterns(pattern_id);
ALTER TABLE "public"."chat_read_states" ADD CONSTRAINT "chat_read_states_user_id_fkey" FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE "public"."client_funnel_events" ADD CONSTRAINT "client_funnel_events_user_id_fkey" FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE "public"."direct_messages" ADD CONSTRAINT "direct_messages_recipient_id_fkey" FOREIGN KEY (recipient_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE "public"."direct_messages" ADD CONSTRAINT "direct_messages_sender_id_fkey" FOREIGN KEY (sender_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE "public"."equipped_cosmetics" ADD CONSTRAINT "equipped_cosmetics_cosmetic_id_fkey" FOREIGN KEY (cosmetic_id) REFERENCES cosmetic_master(id) ON DELETE CASCADE;
ALTER TABLE "public"."equipped_cosmetics" ADD CONSTRAINT "equipped_cosmetics_user_id_fkey" FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE "public"."friend_requests" ADD CONSTRAINT "friend_requests_receiver_id_fkey" FOREIGN KEY (receiver_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE "public"."friend_requests" ADD CONSTRAINT "friend_requests_sender_id_fkey" FOREIGN KEY (sender_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE "public"."gacha_execution_history" ADD CONSTRAINT "gacha_execution_history_gacha_id_fkey" FOREIGN KEY (gacha_id) REFERENCES gacha_masters(id);
ALTER TABLE "public"."gacha_execution_history" ADD CONSTRAINT "gacha_execution_history_user_id_fkey" FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE "public"."gacha_items_master" ADD CONSTRAINT "gacha_items_master_gacha_id_fkey" FOREIGN KEY (gacha_id) REFERENCES gacha_masters(id) ON DELETE CASCADE;
ALTER TABLE "public"."gacha_rarity_rates" ADD CONSTRAINT "gacha_rarity_rates_gacha_id_fkey" FOREIGN KEY (gacha_id) REFERENCES gacha_masters(id) ON DELETE CASCADE;
ALTER TABLE "public"."gameplay_reset_requests" ADD CONSTRAINT "gameplay_reset_requests_user_id_fkey" FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE "public"."gameplay_reward_delivery_ledger" ADD CONSTRAINT "gameplay_reward_delivery_ledger_user_id_fkey" FOREIGN KEY (user_id) REFERENCES users(id);
ALTER TABLE "public"."growth_exp_execution_history" ADD CONSTRAINT "growth_exp_execution_history_user_id_fkey" FOREIGN KEY (user_id) REFERENCES users(id);
ALTER TABLE "public"."guild_activity_grants" ADD CONSTRAINT "guild_activity_grants_guild_id_fkey" FOREIGN KEY (guild_id) REFERENCES guilds(id) ON DELETE CASCADE;
ALTER TABLE "public"."guild_activity_grants" ADD CONSTRAINT "guild_activity_grants_user_id_fkey" FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE "public"."guild_base_controls" ADD CONSTRAINT "guild_base_controls_guild_id_fkey" FOREIGN KEY (guild_id) REFERENCES guilds(id) ON DELETE SET NULL;
ALTER TABLE "public"."guild_cosmetics" ADD CONSTRAINT "guild_cosmetics_cosmetic_id_fkey" FOREIGN KEY (cosmetic_id) REFERENCES cosmetic_master(id) ON DELETE CASCADE;
ALTER TABLE "public"."guild_cosmetics" ADD CONSTRAINT "guild_cosmetics_guild_id_fkey" FOREIGN KEY (guild_id) REFERENCES guilds(id) ON DELETE CASCADE;
ALTER TABLE "public"."guild_decorations" ADD CONSTRAINT "guild_decorations_guild_id_fkey" FOREIGN KEY (guild_id) REFERENCES guilds(id) ON DELETE CASCADE;
ALTER TABLE "public"."guild_equipped_cosmetics" ADD CONSTRAINT "guild_equipped_cosmetics_cosmetic_id_fkey" FOREIGN KEY (cosmetic_id) REFERENCES cosmetic_master(id) ON DELETE CASCADE;
ALTER TABLE "public"."guild_equipped_cosmetics" ADD CONSTRAINT "guild_equipped_cosmetics_guild_id_fkey" FOREIGN KEY (guild_id) REFERENCES guilds(id) ON DELETE CASCADE;
ALTER TABLE "public"."guild_exp_daily_ledger" ADD CONSTRAINT "guild_exp_daily_ledger_guild_id_fkey" FOREIGN KEY (guild_id) REFERENCES guilds(id);
ALTER TABLE "public"."guild_exp_daily_ledger" ADD CONSTRAINT "guild_exp_daily_ledger_source_fkey" FOREIGN KEY (source) REFERENCES canonical_guild_exp_source_master(source);
ALTER TABLE "public"."guild_exp_daily_ledger" ADD CONSTRAINT "guild_exp_daily_ledger_user_id_fkey" FOREIGN KEY (user_id) REFERENCES users(id);
ALTER TABLE "public"."guild_exp_daily_progress" ADD CONSTRAINT "guild_exp_daily_progress_guild_id_fkey" FOREIGN KEY (guild_id) REFERENCES guilds(id);
ALTER TABLE "public"."guild_exp_daily_progress" ADD CONSTRAINT "guild_exp_daily_progress_user_id_fkey" FOREIGN KEY (user_id) REFERENCES users(id);
ALTER TABLE "public"."guild_human_response_metrics" ADD CONSTRAINT "guild_human_response_metrics_first_human_response_message__fkey" FOREIGN KEY (first_human_response_message_id) REFERENCES board_posts(id) ON DELETE SET NULL;
ALTER TABLE "public"."guild_human_response_metrics" ADD CONSTRAINT "guild_human_response_metrics_guild_id_fkey" FOREIGN KEY (guild_id) REFERENCES guilds(id) ON DELETE CASCADE;
ALTER TABLE "public"."guild_human_response_metrics" ADD CONSTRAINT "guild_human_response_metrics_join_request_id_fkey" FOREIGN KEY (join_request_id) REFERENCES guild_join_requests(id) ON DELETE CASCADE;
ALTER TABLE "public"."guild_human_response_metrics" ADD CONSTRAINT "guild_human_response_metrics_joined_user_id_fkey" FOREIGN KEY (joined_user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE "public"."guild_join_requests" ADD CONSTRAINT "guild_join_requests_guild_id_fkey" FOREIGN KEY (guild_id) REFERENCES guilds(id) ON DELETE CASCADE;
ALTER TABLE "public"."guild_join_requests" ADD CONSTRAINT "guild_join_requests_reviewed_by_fkey" FOREIGN KEY (reviewed_by) REFERENCES users(id) ON DELETE SET NULL;
ALTER TABLE "public"."guild_join_requests" ADD CONSTRAINT "guild_join_requests_user_id_fkey" FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE "public"."guild_members" ADD CONSTRAINT "guild_members_guild_id_fkey" FOREIGN KEY (guild_id) REFERENCES guilds(id) ON DELETE CASCADE;
ALTER TABLE "public"."guild_members" ADD CONSTRAINT "guild_members_user_id_fkey" FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE "public"."guilds" ADD CONSTRAINT "guilds_leader_id_fkey" FOREIGN KEY (leader_id) REFERENCES users(id) ON DELETE SET NULL;
ALTER TABLE "public"."gvg_attack_logs" ADD CONSTRAINT "gvg_attack_logs_attacker_guild_id_fkey" FOREIGN KEY (attacker_guild_id) REFERENCES guilds(id) ON DELETE RESTRICT;
ALTER TABLE "public"."gvg_attack_logs" ADD CONSTRAINT "gvg_attack_logs_attacker_user_id_fkey" FOREIGN KEY (attacker_user_id) REFERENCES users(id) ON DELETE RESTRICT;
ALTER TABLE "public"."gvg_attack_logs" ADD CONSTRAINT "gvg_attack_logs_battle_replay_session_id_fkey" FOREIGN KEY (battle_replay_session_id) REFERENCES battle_replay_sessions(id) ON DELETE SET NULL;
ALTER TABLE "public"."gvg_attack_logs" ADD CONSTRAINT "gvg_attack_logs_defender_snapshot_id_fkey" FOREIGN KEY (defender_snapshot_id) REFERENCES gvg_match_member_snapshots(id) ON DELETE SET NULL;
ALTER TABLE "public"."gvg_attack_logs" ADD CONSTRAINT "gvg_attack_logs_match_session_id_fkey" FOREIGN KEY (match_session_id) REFERENCES gvg_match_sessions(id) ON DELETE CASCADE;
ALTER TABLE "public"."gvg_defense_decks" ADD CONSTRAINT "gvg_defense_decks_guild_id_fkey" FOREIGN KEY (guild_id) REFERENCES guilds(id) ON DELETE CASCADE;
ALTER TABLE "public"."gvg_defense_decks" ADD CONSTRAINT "gvg_defense_decks_user_id_fkey" FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE "public"."gvg_guild_ratings" ADD CONSTRAINT "gvg_guild_ratings_guild_id_fkey" FOREIGN KEY (guild_id) REFERENCES guilds(id) ON DELETE CASCADE;
ALTER TABLE "public"."gvg_guild_season_rankings" ADD CONSTRAINT "gvg_guild_season_rankings_guild_id_fkey" FOREIGN KEY (guild_id) REFERENCES guilds(id) ON DELETE CASCADE;
ALTER TABLE "public"."gvg_guild_season_rankings" ADD CONSTRAINT "gvg_guild_season_rankings_season_id_fkey" FOREIGN KEY (season_id) REFERENCES ranking_seasons(id) ON DELETE CASCADE;
ALTER TABLE "public"."gvg_individual_season_rankings" ADD CONSTRAINT "gvg_individual_season_rankings_guild_id_fkey" FOREIGN KEY (guild_id) REFERENCES guilds(id) ON DELETE SET NULL;
ALTER TABLE "public"."gvg_individual_season_rankings" ADD CONSTRAINT "gvg_individual_season_rankings_season_id_fkey" FOREIGN KEY (season_id) REFERENCES ranking_seasons(id) ON DELETE CASCADE;
ALTER TABLE "public"."gvg_individual_season_rankings" ADD CONSTRAINT "gvg_individual_season_rankings_user_id_fkey" FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE "public"."gvg_match_member_snapshots" ADD CONSTRAINT "gvg_match_member_snapshots_guild_id_fkey" FOREIGN KEY (guild_id) REFERENCES guilds(id) ON DELETE CASCADE;
ALTER TABLE "public"."gvg_match_member_snapshots" ADD CONSTRAINT "gvg_match_member_snapshots_match_session_id_fkey" FOREIGN KEY (match_session_id) REFERENCES gvg_match_sessions(id) ON DELETE CASCADE;
ALTER TABLE "public"."gvg_match_member_snapshots" ADD CONSTRAINT "gvg_match_member_snapshots_user_id_fkey" FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE "public"."gvg_match_sessions" ADD CONSTRAINT "gvg_match_sessions_guild_a_id_fkey" FOREIGN KEY (guild_a_id) REFERENCES guilds(id) ON DELETE RESTRICT;
ALTER TABLE "public"."gvg_match_sessions" ADD CONSTRAINT "gvg_match_sessions_guild_b_id_fkey" FOREIGN KEY (guild_b_id) REFERENCES guilds(id) ON DELETE RESTRICT;
ALTER TABLE "public"."gvg_match_sessions" ADD CONSTRAINT "gvg_match_sessions_winner_guild_id_fkey" FOREIGN KEY (winner_guild_id) REFERENCES guilds(id) ON DELETE SET NULL;
ALTER TABLE "public"."gvg_matches" ADD CONSTRAINT "gvg_matches_guild_a_id_fkey" FOREIGN KEY (guild_a_id) REFERENCES guilds(id) ON DELETE SET NULL;
ALTER TABLE "public"."gvg_matches" ADD CONSTRAINT "gvg_matches_guild_b_id_fkey" FOREIGN KEY (guild_b_id) REFERENCES guilds(id) ON DELETE SET NULL;
ALTER TABLE "public"."gvg_matches" ADD CONSTRAINT "gvg_matches_winner_guild_id_fkey" FOREIGN KEY (winner_guild_id) REFERENCES guilds(id) ON DELETE SET NULL;
ALTER TABLE "private"."initial_equipment_receipts" ADD CONSTRAINT "initial_equipment_receipts_user_id_fkey" FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE "public"."kpi_account_classification_periods" ADD CONSTRAINT "kpi_account_classification_periods_subject_id_fkey" FOREIGN KEY (subject_id) REFERENCES kpi_subjects(subject_id) ON DELETE RESTRICT;
ALTER TABLE "public"."kpi_acquisition_journey_facts" ADD CONSTRAINT "kpi_acquisition_journey_facts_journey_id_fkey" FOREIGN KEY (journey_id) REFERENCES kpi_acquisition_journeys(journey_id) ON DELETE RESTRICT;
ALTER TABLE "public"."kpi_acquisition_subject_bindings" ADD CONSTRAINT "kpi_acquisition_subject_bindings_journey_id_fkey" FOREIGN KEY (journey_id) REFERENCES kpi_acquisition_journeys(journey_id) ON DELETE RESTRICT;
ALTER TABLE "public"."kpi_acquisition_subject_bindings" ADD CONSTRAINT "kpi_acquisition_subject_bindings_subject_id_fkey" FOREIGN KEY (subject_id) REFERENCES kpi_subjects(subject_id) ON DELETE RESTRICT;
ALTER TABLE "public"."kpi_daily_user_activity" ADD CONSTRAINT "kpi_daily_user_activity_subject_id_fkey" FOREIGN KEY (subject_id) REFERENCES kpi_subjects(subject_id) ON DELETE RESTRICT;
ALTER TABLE "public"."kpi_gacha_execution_facts" ADD CONSTRAINT "kpi_gacha_execution_facts_subject_id_fkey" FOREIGN KEY (subject_id) REFERENCES kpi_subjects(subject_id) ON DELETE RESTRICT;
ALTER TABLE "public"."kpi_guild_chat_activation_facts" ADD CONSTRAINT "kpi_guild_chat_activation_facts_first_message_fact_id_fkey" FOREIGN KEY (first_message_fact_id) REFERENCES kpi_guild_chat_message_facts(id) ON DELETE RESTRICT;
ALTER TABLE "public"."kpi_guild_chat_activation_facts" ADD CONSTRAINT "kpi_guild_chat_activation_facts_membership_period_id_fkey" FOREIGN KEY (membership_period_id) REFERENCES kpi_guild_membership_periods(id) ON DELETE RESTRICT;
ALTER TABLE "public"."kpi_guild_chat_activation_facts" ADD CONSTRAINT "kpi_guild_chat_activation_facts_subject_id_fkey" FOREIGN KEY (subject_id) REFERENCES kpi_subjects(subject_id) ON DELETE RESTRICT;
ALTER TABLE "public"."kpi_guild_chat_message_facts" ADD CONSTRAINT "kpi_guild_chat_message_facts_membership_period_id_fkey" FOREIGN KEY (membership_period_id) REFERENCES kpi_guild_membership_periods(id) ON DELETE RESTRICT;
ALTER TABLE "public"."kpi_guild_chat_message_facts" ADD CONSTRAINT "kpi_guild_chat_message_facts_subject_id_fkey" FOREIGN KEY (subject_id) REFERENCES kpi_subjects(subject_id) ON DELETE RESTRICT;
ALTER TABLE "public"."kpi_guild_conversion_facts" ADD CONSTRAINT "kpi_guild_conversion_facts_membership_period_id_fkey" FOREIGN KEY (membership_period_id) REFERENCES kpi_guild_membership_periods(id) ON DELETE RESTRICT;
ALTER TABLE "public"."kpi_guild_conversion_facts" ADD CONSTRAINT "kpi_guild_conversion_facts_subject_id_fkey" FOREIGN KEY (subject_id) REFERENCES kpi_subjects(subject_id) ON DELETE RESTRICT;
ALTER TABLE "public"."kpi_guild_membership_periods" ADD CONSTRAINT "kpi_guild_membership_periods_subject_id_fkey" FOREIGN KEY (subject_id) REFERENCES kpi_subjects(subject_id) ON DELETE RESTRICT;
ALTER TABLE "public"."kpi_marketing_daily_fact_revisions" ADD CONSTRAINT "kpi_marketing_daily_fact_revi_scope_id_platform_report_dat_fkey" FOREIGN KEY (scope_id, platform, report_date_jst, account_key, currency, reporting_grain) REFERENCES kpi_marketing_reporting_scopes(id, platform, report_date_jst, account_key, currency, reporting_grain) ON DELETE RESTRICT;
ALTER TABLE "public"."kpi_marketing_daily_fact_revisions" ADD CONSTRAINT "kpi_marketing_daily_fact_revisions_batch_id_fkey" FOREIGN KEY (batch_id) REFERENCES kpi_marketing_import_batches(id) ON DELETE RESTRICT;
ALTER TABLE "public"."kpi_metric_snapshots" ADD CONSTRAINT "kpi_metric_snapshots_run_id_fkey" FOREIGN KEY (run_id) REFERENCES kpi_aggregation_runs(run_id) ON DELETE CASCADE;
ALTER TABLE "public"."kpi_subject_identity_transition_facts" ADD CONSTRAINT "kpi_subject_identity_transition_facts_from_subject_id_fkey" FOREIGN KEY (from_subject_id) REFERENCES kpi_subjects(subject_id) ON DELETE RESTRICT;
ALTER TABLE "public"."kpi_subject_identity_transition_facts" ADD CONSTRAINT "kpi_subject_identity_transition_facts_to_subject_id_fkey" FOREIGN KEY (to_subject_id) REFERENCES kpi_subjects(subject_id) ON DELETE RESTRICT;
ALTER TABLE "public"."kpi_tutorial_completion_facts" ADD CONSTRAINT "kpi_tutorial_completion_facts_subject_id_fkey" FOREIGN KEY (subject_id) REFERENCES kpi_subjects(subject_id) ON DELETE RESTRICT;
ALTER TABLE "public"."kpi_tutorial_journey_facts" ADD CONSTRAINT "kpi_tutorial_journey_facts_subject_id_fkey" FOREIGN KEY (subject_id) REFERENCES kpi_subjects(subject_id) ON DELETE RESTRICT;
ALTER TABLE "public"."kpi_tutorial_mypage_ready_contexts" ADD CONSTRAINT "kpi_tutorial_mypage_ready_contexts_subject_id_fkey" FOREIGN KEY (subject_id) REFERENCES kpi_subjects(subject_id) ON DELETE RESTRICT;
ALTER TABLE "public"."mission_event_dialog_views" ADD CONSTRAINT "mission_event_dialog_views_event_id_fkey" FOREIGN KEY (event_id) REFERENCES mission_events(id) ON DELETE CASCADE;
ALTER TABLE "public"."mission_event_dialog_views" ADD CONSTRAINT "mission_event_dialog_views_user_id_fkey" FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE "public"."mission_event_telemetry" ADD CONSTRAINT "mission_event_telemetry_event_id_fkey" FOREIGN KEY (event_id) REFERENCES mission_events(id) ON DELETE CASCADE;
ALTER TABLE "public"."mission_event_telemetry" ADD CONSTRAINT "mission_event_telemetry_mission_id_fkey" FOREIGN KEY (mission_id) REFERENCES missions(id);
ALTER TABLE "public"."mission_event_telemetry" ADD CONSTRAINT "mission_event_telemetry_user_id_fkey" FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE "public"."mission_reward_components" ADD CONSTRAINT "mission_reward_components_mission_id_fkey" FOREIGN KEY (mission_id) REFERENCES missions(id) ON DELETE CASCADE;
ALTER TABLE "public"."mission_reward_delivery_items" ADD CONSTRAINT "mission_reward_delivery_items_delivery_ledger_id_fkey" FOREIGN KEY (delivery_ledger_id) REFERENCES mission_reward_delivery_ledger(id) ON DELETE CASCADE;
ALTER TABLE "public"."mission_reward_delivery_ledger" ADD CONSTRAINT "mission_reward_delivery_ledger_mission_id_fkey" FOREIGN KEY (mission_id) REFERENCES missions(id);
ALTER TABLE "public"."mission_reward_delivery_ledger" ADD CONSTRAINT "mission_reward_delivery_ledger_user_id_fkey" FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE "public"."mission_reward_delivery_ledger" ADD CONSTRAINT "mission_reward_delivery_ledger_user_mission_id_fkey" FOREIGN KEY (user_mission_id) REFERENCES user_missions(id) ON DELETE CASCADE;
ALTER TABLE "public"."missions" ADD CONSTRAINT "missions_event_id_fkey" FOREIGN KEY (event_id) REFERENCES mission_events(id);
ALTER TABLE "public"."monthly_power_entity_snapshots" ADD CONSTRAINT "monthly_power_entity_snapshots_season_id_fkey" FOREIGN KEY (season_id) REFERENCES monthly_power_season_runs(season_id);
ALTER TABLE "public"."monthly_power_honor_bindings" ADD CONSTRAINT "monthly_power_honor_bindings_cosmetic_id_fkey" FOREIGN KEY (cosmetic_id) REFERENCES cosmetic_master(id);
ALTER TABLE "public"."monthly_power_honor_bindings" ADD CONSTRAINT "monthly_power_honor_bindings_reward_version_ranking_type_r_fkey" FOREIGN KEY (reward_version, ranking_type, rank_min) REFERENCES monthly_power_reward_master(reward_version, ranking_type, rank_min);
ALTER TABLE "public"."monthly_power_honor_grants" ADD CONSTRAINT "monthly_power_honor_grants_cosmetic_id_fkey" FOREIGN KEY (cosmetic_id) REFERENCES cosmetic_master(id);
ALTER TABLE "public"."monthly_power_honor_grants" ADD CONSTRAINT "monthly_power_honor_grants_season_id_fkey" FOREIGN KEY (season_id) REFERENCES monthly_power_season_runs(season_id);
ALTER TABLE "public"."monthly_power_honor_recipients" ADD CONSTRAINT "monthly_power_honor_recipient_season_id_entity_id_cosmetic_fkey" FOREIGN KEY (season_id, entity_id, cosmetic_id) REFERENCES monthly_power_honor_grants(season_id, entity_id, cosmetic_id);
ALTER TABLE "public"."monthly_power_honor_recipients" ADD CONSTRAINT "monthly_power_honor_recipients_recipient_user_id_fkey" FOREIGN KEY (recipient_user_id) REFERENCES users(id);
ALTER TABLE "public"."monthly_power_honor_requirements" ADD CONSTRAINT "monthly_power_honor_requirements_season_id_fkey" FOREIGN KEY (season_id) REFERENCES monthly_power_season_runs(season_id);
ALTER TABLE "public"."monthly_power_member_snapshots" ADD CONSTRAINT "monthly_power_member_snapshots_season_id_fkey" FOREIGN KEY (season_id) REFERENCES monthly_power_season_runs(season_id);
ALTER TABLE "public"."monthly_power_season_runs" ADD CONSTRAINT "monthly_power_season_runs_season_id_fkey" FOREIGN KEY (season_id) REFERENCES ranking_seasons(id);
ALTER TABLE "public"."operations_maintenance_testers" ADD CONSTRAINT "operations_maintenance_testers_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE "public"."patrol_npcs" ADD CONSTRAINT "patrol_npcs_quest_id_fkey" FOREIGN KEY (quest_id) REFERENCES quests(id) ON DELETE CASCADE;
ALTER TABLE "public"."payment_transactions" ADD CONSTRAINT "payment_transactions_user_id_fkey" FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE "public"."presents" ADD CONSTRAINT "presents_user_id_fkey" FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE "public"."pvp_daily_wins" ADD CONSTRAINT "pvp_daily_wins_user_id_fkey" FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE "public"."pvp_defense_decks" ADD CONSTRAINT "pvp_defense_decks_user_id_fkey" FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE "public"."pvp_defense_logs" ADD CONSTRAINT "pvp_defense_logs_user_id_fkey" FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE "public"."pvp_ranking_reward_grants" ADD CONSTRAINT "pvp_ranking_reward_grants_season_id_fkey" FOREIGN KEY (season_id) REFERENCES ranking_seasons(id);
ALTER TABLE "public"."pvp_ranking_reward_grants" ADD CONSTRAINT "pvp_ranking_reward_grants_user_id_fkey" FOREIGN KEY (user_id) REFERENCES users(id);
ALTER TABLE "public"."pvp_ranks" ADD CONSTRAINT "pvp_ranks_user_id_fkey" FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE "public"."quest_raid_encounter_bonus_grants" ADD CONSTRAINT "quest_raid_encounter_bonus_grants_room_id_fkey" FOREIGN KEY (room_id) REFERENCES raid_rooms(id);
ALTER TABLE "public"."quest_raid_encounter_bonus_grants" ADD CONSTRAINT "quest_raid_encounter_bonus_grants_user_id_fkey" FOREIGN KEY (user_id) REFERENCES users(id);
ALTER TABLE "public"."quest_raid_encounter_progress" ADD CONSTRAINT "quest_raid_encounter_progress_user_id_fkey" FOREIGN KEY (user_id) REFERENCES users(id);
ALTER TABLE "public"."quest_raid_encounters" ADD CONSTRAINT "quest_raid_encounters_patrol_id_fkey" FOREIGN KEY (patrol_id) REFERENCES user_patrols(id);
ALTER TABLE "public"."quest_raid_encounters" ADD CONSTRAINT "quest_raid_encounters_room_id_fkey" FOREIGN KEY (room_id) REFERENCES raid_rooms(id);
ALTER TABLE "public"."quest_raid_encounters" ADD CONSTRAINT "quest_raid_encounters_user_id_fkey" FOREIGN KEY (user_id) REFERENCES users(id);
ALTER TABLE "public"."quests" ADD CONSTRAINT "quests_town_id_fkey" FOREIGN KEY (town_id) REFERENCES quest_towns(id) ON DELETE SET NULL;
ALTER TABLE "public"."raid_bosses" ADD CONSTRAINT "raid_bosses_boss_master_id_fkey" FOREIGN KEY (boss_master_id) REFERENCES raid_boss_master(id);
ALTER TABLE "public"."raid_bosses" ADD CONSTRAINT "raid_bosses_raid_variant_id_fkey" FOREIGN KEY (raid_variant_id) REFERENCES canonical_raid_variants(raid_variant_id);
ALTER TABLE "public"."raid_clear_reward_claims" ADD CONSTRAINT "raid_clear_reward_claims_source_instance_id_fkey" FOREIGN KEY (source_instance_id) REFERENCES raid_bosses(id);
ALTER TABLE "public"."raid_clear_reward_claims" ADD CONSTRAINT "raid_clear_reward_claims_user_id_fkey" FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE "public"."raid_clear_reward_deliveries" ADD CONSTRAINT "raid_clear_reward_deliveries_raid_day_key_user_id_reward_t_fkey" FOREIGN KEY (raid_day_key, user_id, reward_type) REFERENCES raid_clear_reward_claims(raid_day_key, user_id, reward_type);
ALTER TABLE "public"."raid_completion_xp_grants" ADD CONSTRAINT "raid_completion_xp_grants_user_id_fkey" FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE "public"."raid_daily_clear_bonus_ledger" ADD CONSTRAINT "raid_daily_clear_bonus_ledger_difficulty_fkey" FOREIGN KEY (difficulty) REFERENCES raid_daily_clear_bonus_rules(difficulty);
ALTER TABLE "public"."raid_daily_clear_bonus_ledger" ADD CONSTRAINT "raid_daily_clear_bonus_ledger_source_instance_id_fkey" FOREIGN KEY (source_instance_id) REFERENCES raid_bosses(id);
ALTER TABLE "public"."raid_daily_clear_bonus_ledger" ADD CONSTRAINT "raid_daily_clear_bonus_ledger_source_room_id_fkey" FOREIGN KEY (source_room_id) REFERENCES raid_rooms(id);
ALTER TABLE "public"."raid_daily_clear_bonus_ledger" ADD CONSTRAINT "raid_daily_clear_bonus_ledger_user_id_fkey" FOREIGN KEY (user_id) REFERENCES users(id);
ALTER TABLE "public"."raid_daily_clear_bonus_rules" ADD CONSTRAINT "raid_daily_clear_bonus_rules_difficulty_fkey" FOREIGN KEY (difficulty) REFERENCES raid_room_clear_reward_rules(difficulty);
ALTER TABLE "private"."raid_daily_targets" ADD CONSTRAINT "raid_daily_targets_first_variant_id_fkey" FOREIGN KEY (first_variant_id) REFERENCES canonical_raid_variants(raid_variant_id);
ALTER TABLE "private"."raid_daily_targets" ADD CONSTRAINT "raid_daily_targets_second_variant_id_fkey" FOREIGN KEY (second_variant_id) REFERENCES canonical_raid_variants(raid_variant_id);
ALTER TABLE "public"."raid_damage_logs" ADD CONSTRAINT "raid_damage_logs_battle_replay_session_id_fkey" FOREIGN KEY (battle_replay_session_id) REFERENCES battle_replay_sessions(id) ON DELETE RESTRICT;
ALTER TABLE "public"."raid_damage_logs" ADD CONSTRAINT "raid_damage_logs_guild_id_fkey" FOREIGN KEY (guild_id) REFERENCES guilds(id) ON DELETE SET NULL;
ALTER TABLE "public"."raid_damage_logs" ADD CONSTRAINT "raid_damage_logs_raid_boss_instance_id_fkey" FOREIGN KEY (raid_boss_instance_id) REFERENCES raid_bosses(id) ON DELETE CASCADE;
ALTER TABLE "public"."raid_damage_logs" ADD CONSTRAINT "raid_damage_logs_user_id_fkey" FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE "public"."raid_instance_user_progress" ADD CONSTRAINT "raid_instance_user_progress_raid_boss_instance_id_fkey" FOREIGN KEY (raid_boss_instance_id) REFERENCES raid_bosses(id);
ALTER TABLE "public"."raid_instance_user_progress" ADD CONSTRAINT "raid_instance_user_progress_user_id_fkey" FOREIGN KEY (user_id) REFERENCES users(id);
ALTER TABLE "public"."raid_production_reward_grants" ADD CONSTRAINT "raid_production_reward_grants_raid_boss_instance_id_fkey" FOREIGN KEY (raid_boss_instance_id) REFERENCES raid_bosses(id);
ALTER TABLE "public"."raid_production_reward_grants" ADD CONSTRAINT "raid_production_reward_grants_user_id_fkey" FOREIGN KEY (user_id) REFERENCES users(id);
ALTER TABLE "public"."raid_reward_grants" ADD CONSTRAINT "raid_reward_grants_raid_boss_instance_id_fkey" FOREIGN KEY (raid_boss_instance_id) REFERENCES raid_bosses(id) ON DELETE CASCADE;
ALTER TABLE "public"."raid_reward_grants" ADD CONSTRAINT "raid_reward_grants_reward_id_fkey" FOREIGN KEY (reward_id) REFERENCES raid_rewards_master(id) ON DELETE RESTRICT;
ALTER TABLE "public"."raid_reward_grants" ADD CONSTRAINT "raid_reward_grants_user_id_fkey" FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE "public"."raid_room_battle_request_cancellations" ADD CONSTRAINT "raid_room_battle_request_cancellations_user_id_fkey" FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE "public"."raid_room_battle_start_requests" ADD CONSTRAINT "raid_room_battle_start_requests_replay_session_id_fkey" FOREIGN KEY (replay_session_id) REFERENCES battle_replay_sessions(id);
ALTER TABLE "public"."raid_room_battle_start_requests" ADD CONSTRAINT "raid_room_battle_start_requests_room_id_fkey" FOREIGN KEY (room_id) REFERENCES raid_rooms(id);
ALTER TABLE "public"."raid_room_battle_start_requests" ADD CONSTRAINT "raid_room_battle_start_requests_user_id_fkey" FOREIGN KEY (user_id) REFERENCES users(id);
ALTER TABLE "public"."raid_room_clear_reward_grants" ADD CONSTRAINT "raid_room_clear_reward_grants_direct_delivery_id_fkey" FOREIGN KEY (direct_delivery_id) REFERENCES gameplay_reward_delivery_ledger(id);
ALTER TABLE "public"."raid_room_clear_reward_grants" ADD CONSTRAINT "raid_room_clear_reward_grants_present_id_fkey" FOREIGN KEY (present_id) REFERENCES presents(id);
ALTER TABLE "public"."raid_room_clear_reward_grants" ADD CONSTRAINT "raid_room_clear_reward_grants_room_id_user_id_fkey" FOREIGN KEY (room_id, user_id) REFERENCES raid_room_clear_rewards(room_id, user_id);
ALTER TABLE "public"."raid_room_clear_reward_items" ADD CONSTRAINT "raid_room_clear_reward_items_difficulty_fkey" FOREIGN KEY (difficulty) REFERENCES raid_room_clear_reward_rules(difficulty);
ALTER TABLE "public"."raid_room_clear_reward_rules" ADD CONSTRAINT "raid_room_clear_reward_rules_difficulty_fkey" FOREIGN KEY (difficulty) REFERENCES raid_room_difficulty_rules(difficulty);
ALTER TABLE "public"."raid_room_clear_rewards" ADD CONSTRAINT "raid_room_clear_rewards_room_id_user_id_fkey" FOREIGN KEY (room_id, user_id) REFERENCES raid_room_members(room_id, user_id);
ALTER TABLE "public"."raid_room_combat_profiles" ADD CONSTRAINT "raid_room_combat_profiles_raid_variant_id_fkey" FOREIGN KEY (raid_variant_id) REFERENCES canonical_raid_variants(raid_variant_id);
ALTER TABLE "public"."raid_room_combat_snapshots" ADD CONSTRAINT "raid_room_combat_snapshots_room_id_fkey" FOREIGN KEY (room_id) REFERENCES raid_rooms(id);
ALTER TABLE "public"."raid_room_creation_requests" ADD CONSTRAINT "raid_room_creation_requests_room_id_fkey" FOREIGN KEY (room_id) REFERENCES raid_rooms(id);
ALTER TABLE "public"."raid_room_creation_requests" ADD CONSTRAINT "raid_room_creation_requests_user_id_fkey" FOREIGN KEY (user_id) REFERENCES users(id);
ALTER TABLE "public"."raid_room_members" ADD CONSTRAINT "raid_room_members_room_id_fkey" FOREIGN KEY (room_id) REFERENCES raid_rooms(id);
ALTER TABLE "public"."raid_room_members" ADD CONSTRAINT "raid_room_members_user_id_fkey" FOREIGN KEY (user_id) REFERENCES users(id);
ALTER TABLE "public"."raid_room_rescue_members" ADD CONSTRAINT "raid_room_rescue_members_rescue_id_fkey" FOREIGN KEY (rescue_id) REFERENCES raid_room_rescue_publications(id);
ALTER TABLE "public"."raid_room_rescue_members" ADD CONSTRAINT "raid_room_rescue_members_room_id_user_id_fkey" FOREIGN KEY (room_id, user_id) REFERENCES raid_room_members(room_id, user_id);
ALTER TABLE "public"."raid_room_rescue_publications" ADD CONSTRAINT "raid_room_rescue_publications_guild_id_fkey" FOREIGN KEY (guild_id) REFERENCES guilds(id);
ALTER TABLE "public"."raid_room_rescue_publications" ADD CONSTRAINT "raid_room_rescue_publications_requester_user_id_fkey" FOREIGN KEY (requester_user_id) REFERENCES users(id);
ALTER TABLE "public"."raid_room_rescue_publications" ADD CONSTRAINT "raid_room_rescue_publications_room_id_fkey" FOREIGN KEY (room_id) REFERENCES raid_rooms(id);
ALTER TABLE "public"."raid_room_rescue_requests" ADD CONSTRAINT "raid_room_rescue_requests_room_id_fkey" FOREIGN KEY (room_id) REFERENCES raid_rooms(id);
ALTER TABLE "public"."raid_room_rescue_requests" ADD CONSTRAINT "raid_room_rescue_requests_user_id_fkey" FOREIGN KEY (user_id) REFERENCES users(id);
ALTER TABLE "public"."raid_room_rescue_reward_grants" ADD CONSTRAINT "raid_room_rescue_reward_grants_direct_delivery_id_fkey" FOREIGN KEY (direct_delivery_id) REFERENCES gameplay_reward_delivery_ledger(id);
ALTER TABLE "public"."raid_room_rescue_reward_grants" ADD CONSTRAINT "raid_room_rescue_reward_grants_present_id_fkey" FOREIGN KEY (present_id) REFERENCES presents(id);
ALTER TABLE "public"."raid_room_rescue_reward_grants" ADD CONSTRAINT "raid_room_rescue_reward_grants_room_id_user_id_fkey" FOREIGN KEY (room_id, user_id) REFERENCES raid_room_rescue_rewards(room_id, user_id);
ALTER TABLE "public"."raid_room_rescue_reward_items" ADD CONSTRAINT "raid_room_rescue_reward_items_difficulty_fkey" FOREIGN KEY (difficulty) REFERENCES raid_room_rescue_reward_rules(difficulty);
ALTER TABLE "public"."raid_room_rescue_reward_rules" ADD CONSTRAINT "raid_room_rescue_reward_rules_difficulty_fkey" FOREIGN KEY (difficulty) REFERENCES raid_room_difficulty_rules(difficulty);
ALTER TABLE "public"."raid_room_rescue_rewards" ADD CONSTRAINT "raid_room_rescue_rewards_room_id_user_id_fkey" FOREIGN KEY (room_id, user_id) REFERENCES raid_room_rescue_members(room_id, user_id);
ALTER TABLE "public"."raid_rooms" ADD CONSTRAINT "raid_rooms_owner_user_id_fkey" FOREIGN KEY (owner_user_id) REFERENCES users(id);
ALTER TABLE "public"."raid_rooms" ADD CONSTRAINT "raid_rooms_raid_boss_instance_id_fkey" FOREIGN KEY (raid_boss_instance_id) REFERENCES raid_bosses(id);
ALTER TABLE "public"."ranking_daily_activity_snapshots" ADD CONSTRAINT "ranking_daily_activity_snapshots_user_id_fkey" FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE "public"."ranking_daily_participation" ADD CONSTRAINT "ranking_daily_participation_user_id_fkey" FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE "public"."ranking_daily_recipient_snapshots" ADD CONSTRAINT "ranking_daily_recipient_snaps_ranking_day_key_ranking_type_fkey" FOREIGN KEY (ranking_day_key, ranking_type, ranked_entity_id) REFERENCES ranking_daily_entity_snapshots(ranking_day_key, ranking_type, ranked_entity_id);
ALTER TABLE "public"."ranking_daily_recipient_snapshots" ADD CONSTRAINT "ranking_daily_recipient_snapshots_recipient_user_id_fkey" FOREIGN KEY (recipient_user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE "public"."ranking_daily_reward_awards" ADD CONSTRAINT "ranking_daily_reward_awards_recipient_user_id_fkey" FOREIGN KEY (recipient_user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE "public"."ranking_daily_reward_item_grants" ADD CONSTRAINT "ranking_daily_reward_item_grants_award_id_fkey" FOREIGN KEY (award_id) REFERENCES ranking_daily_reward_awards(id) ON DELETE CASCADE;
ALTER TABLE "public"."ranking_guild_exclusions" ADD CONSTRAINT "ranking_guild_exclusions_guild_id_fkey" FOREIGN KEY (guild_id) REFERENCES guilds(id) ON DELETE CASCADE;
ALTER TABLE "public"."ranking_guild_power_finalization_audits" ADD CONSTRAINT "ranking_guild_power_finalization_audits_season_id_fkey" FOREIGN KEY (season_id) REFERENCES ranking_seasons(id);
ALTER TABLE "public"."ranking_guild_power_reward_grants" ADD CONSTRAINT "ranking_guild_power_reward_grants_cosmetic_id_fkey" FOREIGN KEY (cosmetic_id) REFERENCES cosmetic_master(id);
ALTER TABLE "public"."ranking_guild_power_reward_grants" ADD CONSTRAINT "ranking_guild_power_reward_grants_guild_id_fkey" FOREIGN KEY (guild_id) REFERENCES guilds(id) ON DELETE CASCADE;
ALTER TABLE "public"."ranking_guild_power_reward_grants" ADD CONSTRAINT "ranking_guild_power_reward_grants_season_id_fkey" FOREIGN KEY (season_id) REFERENCES ranking_seasons(id);
ALTER TABLE "public"."ranking_guild_power_reward_recipients" ADD CONSTRAINT "ranking_guild_power_reward_recipients_guild_id_fkey" FOREIGN KEY (guild_id) REFERENCES guilds(id) ON DELETE CASCADE;
ALTER TABLE "public"."ranking_guild_power_reward_recipients" ADD CONSTRAINT "ranking_guild_power_reward_recipients_recipient_user_id_fkey" FOREIGN KEY (recipient_user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE "public"."ranking_guild_power_reward_recipients" ADD CONSTRAINT "ranking_guild_power_reward_recipients_season_id_fkey" FOREIGN KEY (season_id) REFERENCES ranking_seasons(id);
ALTER TABLE "public"."ranking_guild_power_season_master" ADD CONSTRAINT "ranking_guild_power_season_master_season_id_fkey" FOREIGN KEY (season_id) REFERENCES ranking_seasons(id);
ALTER TABLE "public"."ranking_guild_power_season_snapshots" ADD CONSTRAINT "ranking_guild_power_season_snapshots_season_id_fkey" FOREIGN KEY (season_id) REFERENCES ranking_seasons(id);
ALTER TABLE "public"."ranking_pvp_season_snapshots" ADD CONSTRAINT "ranking_pvp_season_snapshots_season_id_fkey" FOREIGN KEY (season_id) REFERENCES ranking_seasons(id);
ALTER TABLE "public"."ranking_pvp_season_snapshots" ADD CONSTRAINT "ranking_pvp_season_snapshots_user_id_fkey" FOREIGN KEY (user_id) REFERENCES users(id);
ALTER TABLE "public"."ranking_raid_guild_season_snapshots" ADD CONSTRAINT "ranking_raid_guild_season_snapshots_guild_id_fkey" FOREIGN KEY (guild_id) REFERENCES guilds(id);
ALTER TABLE "public"."ranking_raid_guild_season_snapshots" ADD CONSTRAINT "ranking_raid_guild_season_snapshots_season_id_fkey" FOREIGN KEY (season_id) REFERENCES ranking_seasons(id);
ALTER TABLE "public"."ranking_raid_personal_season_snapshots" ADD CONSTRAINT "ranking_raid_personal_season_snapshots_season_id_fkey" FOREIGN KEY (season_id) REFERENCES ranking_seasons(id);
ALTER TABLE "public"."ranking_raid_personal_season_snapshots" ADD CONSTRAINT "ranking_raid_personal_season_snapshots_user_id_fkey" FOREIGN KEY (user_id) REFERENCES users(id);
ALTER TABLE "public"."ranking_reward_notifications" ADD CONSTRAINT "ranking_reward_notifications_recipient_user_id_fkey" FOREIGN KEY (recipient_user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE "public"."ranking_season_reward_grants" ADD CONSTRAINT "ranking_season_reward_grants_present_id_fkey" FOREIGN KEY (present_id) REFERENCES presents(id);
ALTER TABLE "public"."ranking_season_reward_grants" ADD CONSTRAINT "ranking_season_reward_grants_recipient_user_id_fkey" FOREIGN KEY (recipient_user_id) REFERENCES users(id);
ALTER TABLE "public"."ranking_season_reward_grants" ADD CONSTRAINT "ranking_season_reward_grants_season_id_fkey" FOREIGN KEY (season_id) REFERENCES ranking_seasons(id);
ALTER TABLE "public"."ranking_season_transition_audits" ADD CONSTRAINT "ranking_season_transition_audits_season_id_fkey" FOREIGN KEY (season_id) REFERENCES ranking_seasons(id);
ALTER TABLE "public"."social_activity_feed" ADD CONSTRAINT "social_activity_feed_actor_user_id_fkey" FOREIGN KEY (actor_user_id) REFERENCES users(id) ON DELETE SET NULL;
ALTER TABLE "public"."social_activity_feed" ADD CONSTRAINT "social_activity_feed_guild_id_fkey" FOREIGN KEY (guild_id) REFERENCES guilds(id) ON DELETE SET NULL;
ALTER TABLE "public"."social_activity_projection_state" ADD CONSTRAINT "social_activity_projection_state_subject_user_id_fkey" FOREIGN KEY (subject_user_id) REFERENCES users(id) ON DELETE SET NULL;
ALTER TABLE "public"."special_gacha_exchange_receipts" ADD CONSTRAINT "special_gacha_exchange_receipts_gacha_id_fkey" FOREIGN KEY (gacha_id) REFERENCES gacha_masters(id);
ALTER TABLE "public"."special_gacha_exchange_receipts" ADD CONSTRAINT "special_gacha_exchange_receipts_user_id_fkey" FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE "public"."special_gacha_pool_groups" ADD CONSTRAINT "special_gacha_pool_groups_gacha_id_fkey" FOREIGN KEY (gacha_id) REFERENCES gacha_masters(id);
ALTER TABLE "public"."story_sessions" ADD CONSTRAINT "story_sessions_user_id_fkey" FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE "public"."tutorial_progress" ADD CONSTRAINT "tutorial_progress_user_id_fkey" FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE "public"."user_account_auth_methods" ADD CONSTRAINT "user_account_auth_methods_user_id_fkey" FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE "public"."user_avatar_parts" ADD CONSTRAINT "user_avatar_parts_user_id_fkey" FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE "public"."user_avatars" ADD CONSTRAINT "user_avatars_user_id_fkey" FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE "public"."user_characters" ADD CONSTRAINT "user_characters_user_id_fkey" FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE "public"."user_chats" ADD CONSTRAINT "user_chats_guild_id_fkey" FOREIGN KEY (guild_id) REFERENCES guilds(id) ON DELETE CASCADE;
ALTER TABLE "public"."user_chats" ADD CONSTRAINT "user_chats_sender_id_fkey" FOREIGN KEY (sender_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE "public"."user_cosmetics" ADD CONSTRAINT "user_cosmetics_cosmetic_id_fkey" FOREIGN KEY (cosmetic_id) REFERENCES cosmetic_master(id) ON DELETE CASCADE;
ALTER TABLE "public"."user_cosmetics" ADD CONSTRAINT "user_cosmetics_user_id_fkey" FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE "public"."user_daily_gacha_claims" ADD CONSTRAINT "user_daily_gacha_claims_user_id_fkey" FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE "public"."user_equipments" ADD CONSTRAINT "user_equipments_user_id_fkey" FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE "public"."user_friends" ADD CONSTRAINT "user_friends_friend_id_fkey" FOREIGN KEY (friend_id) REFERENCES users(id);
ALTER TABLE "public"."user_friends" ADD CONSTRAINT "user_friends_user_id_fkey" FOREIGN KEY (user_id) REFERENCES users(id);
ALTER TABLE "public"."user_funnel_milestones" ADD CONSTRAINT "user_funnel_milestones_user_id_fkey" FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE "public"."user_gacha_pity_points" ADD CONSTRAINT "user_gacha_pity_points_user_id_fkey" FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE "public"."user_gvg_ranks" ADD CONSTRAINT "user_gvg_ranks_user_id_fkey" FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE "public"."user_invitations" ADD CONSTRAINT "user_invitations_invitee_user_id_fkey" FOREIGN KEY (invitee_user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE "public"."user_invitations" ADD CONSTRAINT "user_invitations_inviter_user_id_fkey" FOREIGN KEY (inviter_user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE "public"."user_items" ADD CONSTRAINT "user_items_user_id_fkey" FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE "public"."user_lifetime_onboarding_grants" ADD CONSTRAINT "user_lifetime_onboarding_grants_user_id_fkey" FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE "public"."user_login_bonuses" ADD CONSTRAINT "user_login_bonuses_user_id_fkey" FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE "public"."user_main_formations" ADD CONSTRAINT "user_main_formations_user_character_id_fkey" FOREIGN KEY (user_character_id) REFERENCES user_characters(id) ON DELETE CASCADE;
ALTER TABLE "public"."user_main_formations" ADD CONSTRAINT "user_main_formations_user_id_fkey" FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE "public"."user_missions" ADD CONSTRAINT "user_missions_mission_id_fkey" FOREIGN KEY (mission_id) REFERENCES missions(id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE "public"."user_missions" ADD CONSTRAINT "user_missions_user_id_fkey" FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE "public"."user_monthly_passes" ADD CONSTRAINT "user_monthly_passes_user_id_fkey" FOREIGN KEY (user_id) REFERENCES users(id);
ALTER TABLE "public"."user_patrols" ADD CONSTRAINT "user_patrols_user_id_fkey" FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE "public"."user_power_rankings" ADD CONSTRAINT "user_power_rankings_user_id_fkey" FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE "public"."user_profile_decorations" ADD CONSTRAINT "user_profile_decorations_user_id_fkey" FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE "public"."user_quest_first_clears" ADD CONSTRAINT "user_quest_first_clears_quest_id_fkey" FOREIGN KEY (quest_id) REFERENCES quests(id);
ALTER TABLE "public"."user_quest_first_clears" ADD CONSTRAINT "user_quest_first_clears_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE "public"."user_raid_daily_attempts" ADD CONSTRAINT "user_raid_daily_attempts_user_id_fkey" FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE "public"."user_shop_purchases" ADD CONSTRAINT "user_shop_purchases_user_id_fkey" FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE "public"."user_skills" ADD CONSTRAINT "user_skills_user_id_fkey" FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE "public"."user_titles" ADD CONSTRAINT "user_titles_title_id_fkey" FOREIGN KEY (title_id) REFERENCES title_master(id) ON DELETE RESTRICT;
ALTER TABLE "public"."user_titles" ADD CONSTRAINT "user_titles_user_id_fkey" FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE "public"."users" ADD CONSTRAINT "users_guild_id_fkey" FOREIGN KEY (guild_id) REFERENCES guilds(id) ON DELETE SET NULL;
