SET check_function_bodies = false;
SET search_path = public, extensions, pg_catalog;
REVOKE ALL ON TABLE "public"."canonical_raid_reward_master" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE "public"."canonical_raid_variants" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE "public"."canonical_reward_supply_sources" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE "public"."canonical_user_level_master" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE "public"."character_awakening_master" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE "public"."character_battle_master" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE "public"."character_cosmetics" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE "public"."character_growth_patterns" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE "public"."character_release_master" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE "public"."chat_read_states" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE "public"."client_funnel_events" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE "public"."cosmetic_master" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE "public"."direct_messages" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE "public"."enemies" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE "public"."equipment_battle_master" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE "public"."equipment_level_up_master" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE "public"."equipment_limit_break_master" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE "public"."equipped_cosmetics" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE "public"."feature_operating_states" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE "public"."friend_requests" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE "public"."gacha_execution_history" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE "public"."gacha_items_master" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE "public"."gacha_masters" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE "public"."gacha_rarity_rates" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE "public"."gameplay_reset_requests" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE "public"."guild_activity_grants" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE "public"."guild_base_controls" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE "public"."guild_cosmetics" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE "public"."guild_equipped_cosmetics" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE "public"."guild_exp_daily_ledger" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE "public"."guild_exp_daily_progress" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE "public"."guild_human_response_metrics" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE "public"."guild_join_requests" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE "public"."guild_level_master" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE "public"."guild_members" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE "public"."guild_recommendation_weights" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE "public"."guild_xp_action_master" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE "public"."guilds" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE "public"."gvg_attack_logs" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE "public"."gvg_defense_decks" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE "public"."gvg_guild_ratings" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE "public"."gvg_guild_season_rankings" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE "public"."gvg_individual_season_rankings" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE "public"."gvg_match_member_snapshots" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE "public"."gvg_match_sessions" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE "public"."gvg_matches" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE "public"."gvg_rewards_master" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE "public"."gvg_season_status" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE "public"."home_banner_master" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE "public"."login_bonus_master" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE "public"."mission_event_dialog_views" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE "public"."mission_event_telemetry" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE "public"."mission_events" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE "public"."mission_reward_components" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE "public"."mission_reward_delivery_items" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE "public"."mission_reward_delivery_ledger" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE "public"."missions" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE "public"."operations_feature_state_audit" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE "public"."patrol_npcs" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE "public"."payment_transactions" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE "public"."presents" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE "public"."pvp_daily_wins" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE "public"."pvp_defense_decks" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE "public"."pvp_defense_logs" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE "public"."pvp_ranks" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE "public"."pvp_rewards_master" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE "public"."quest_towns" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE "public"."quests" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE "public"."raid_attempt_cost_master" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE "public"."raid_boss_master" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE "public"."raid_bosses" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE "public"."raid_clear_reward_claims" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE "public"."raid_clear_reward_deliveries" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE "public"."raid_completion_xp_grants" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE "public"."raid_damage_logs" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE "public"."raid_reward_grants" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE "public"."raid_rewards_master" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE "public"."ranking_daily_entity_snapshots" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE "public"."ranking_daily_finalization_audits" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE "public"."ranking_daily_participation" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE "public"."ranking_daily_recipient_snapshots" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE "public"."ranking_daily_reward_awards" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE "public"."ranking_daily_reward_item_grants" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE "public"."ranking_guild_exclusions" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE "public"."ranking_guild_power_finalization_audits" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE "public"."ranking_guild_power_reward_grants" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE "public"."ranking_guild_power_reward_recipients" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE "public"."ranking_guild_power_season_master" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE "public"."ranking_guild_power_season_snapshots" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE "public"."ranking_pvp_season_snapshots" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE "public"."ranking_raid_guild_season_snapshots" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE "public"."ranking_raid_personal_season_snapshots" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE "public"."ranking_reward_notifications" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE "public"."ranking_season_transition_audits" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE "public"."ranking_seasons" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE "public"."skill_battle_master" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE "public"."skill_limit_break_master" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE "public"."social_activity_projection_state" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE "public"."story_sessions" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE "public"."title_master" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE "public"."tutorial_progress" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE "public"."user_account_auth_methods" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE "public"."user_avatar_parts" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE "public"."user_avatars" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE "public"."user_chats" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE "public"."user_cosmetics" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE "public"."user_daily_gacha_claims" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE "public"."user_friends" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE "public"."user_funnel_milestones" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE "public"."user_gacha_pity_points" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE "public"."user_gvg_ranks" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE "public"."user_invitations" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE "public"."user_items" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE "public"."user_level_master" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE "public"."user_lifetime_onboarding_grants" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE "public"."user_login_bonuses" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE "public"."user_main_formations" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE "public"."user_missions" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE "public"."user_monthly_passes" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE "public"."user_power_rankings" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE "public"."user_profile_decorations" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE "public"."user_quest_first_clears" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE "public"."user_raid_daily_attempts" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE "public"."user_shop_purchases" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE "public"."user_skills" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE "public"."user_titles" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE "public"."users" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE "public"."user_patrols" FROM PUBLIC, anon, authenticated, service_role;
GRANT INSERT ON TABLE "public"."ranking_daily_activity_snapshots" TO "service_role";
GRANT SELECT ON TABLE "public"."ranking_daily_activity_snapshots" TO "service_role";
GRANT UPDATE ON TABLE "public"."ranking_daily_activity_snapshots" TO "service_role";
GRANT DELETE ON TABLE "public"."ranking_daily_activity_snapshots" TO "service_role";
GRANT TRUNCATE ON TABLE "public"."ranking_daily_activity_snapshots" TO "service_role";
GRANT REFERENCES ON TABLE "public"."ranking_daily_activity_snapshots" TO "service_role";
GRANT TRIGGER ON TABLE "public"."ranking_daily_activity_snapshots" TO "service_role";
GRANT MAINTAIN ON TABLE "public"."ranking_daily_activity_snapshots" TO "service_role";
GRANT INSERT ON TABLE "public"."kpi_subjects" TO "service_role";
GRANT SELECT ON TABLE "public"."kpi_subjects" TO "service_role";
GRANT UPDATE ON TABLE "public"."kpi_subjects" TO "service_role";
GRANT DELETE ON TABLE "public"."kpi_subjects" TO "service_role";
GRANT TRUNCATE ON TABLE "public"."kpi_subjects" TO "service_role";
GRANT REFERENCES ON TABLE "public"."kpi_subjects" TO "service_role";
GRANT TRIGGER ON TABLE "public"."kpi_subjects" TO "service_role";
GRANT MAINTAIN ON TABLE "public"."kpi_subjects" TO "service_role";
GRANT INSERT ON TABLE "public"."kpi_daily_user_activity" TO "service_role";
GRANT SELECT ON TABLE "public"."kpi_daily_user_activity" TO "service_role";
GRANT UPDATE ON TABLE "public"."kpi_daily_user_activity" TO "service_role";
GRANT DELETE ON TABLE "public"."kpi_daily_user_activity" TO "service_role";
GRANT TRUNCATE ON TABLE "public"."kpi_daily_user_activity" TO "service_role";
GRANT REFERENCES ON TABLE "public"."kpi_daily_user_activity" TO "service_role";
GRANT TRIGGER ON TABLE "public"."kpi_daily_user_activity" TO "service_role";
GRANT MAINTAIN ON TABLE "public"."kpi_daily_user_activity" TO "service_role";
GRANT INSERT ON TABLE "public"."kpi_account_classification_periods" TO "service_role";
GRANT SELECT ON TABLE "public"."kpi_account_classification_periods" TO "service_role";
GRANT UPDATE ON TABLE "public"."kpi_account_classification_periods" TO "service_role";
GRANT DELETE ON TABLE "public"."kpi_account_classification_periods" TO "service_role";
GRANT TRUNCATE ON TABLE "public"."kpi_account_classification_periods" TO "service_role";
GRANT REFERENCES ON TABLE "public"."kpi_account_classification_periods" TO "service_role";
GRANT TRIGGER ON TABLE "public"."kpi_account_classification_periods" TO "service_role";
GRANT MAINTAIN ON TABLE "public"."kpi_account_classification_periods" TO "service_role";
GRANT INSERT ON TABLE "public"."kpi_guild_membership_periods" TO "service_role";
GRANT SELECT ON TABLE "public"."kpi_guild_membership_periods" TO "service_role";
GRANT UPDATE ON TABLE "public"."kpi_guild_membership_periods" TO "service_role";
GRANT DELETE ON TABLE "public"."kpi_guild_membership_periods" TO "service_role";
GRANT TRUNCATE ON TABLE "public"."kpi_guild_membership_periods" TO "service_role";
GRANT REFERENCES ON TABLE "public"."kpi_guild_membership_periods" TO "service_role";
GRANT TRIGGER ON TABLE "public"."kpi_guild_membership_periods" TO "service_role";
GRANT MAINTAIN ON TABLE "public"."kpi_guild_membership_periods" TO "service_role";
GRANT INSERT ON TABLE "public"."kpi_tutorial_completion_facts" TO "service_role";
GRANT SELECT ON TABLE "public"."kpi_tutorial_completion_facts" TO "service_role";
GRANT UPDATE ON TABLE "public"."kpi_tutorial_completion_facts" TO "service_role";
GRANT DELETE ON TABLE "public"."kpi_tutorial_completion_facts" TO "service_role";
GRANT TRUNCATE ON TABLE "public"."kpi_tutorial_completion_facts" TO "service_role";
GRANT REFERENCES ON TABLE "public"."kpi_tutorial_completion_facts" TO "service_role";
GRANT TRIGGER ON TABLE "public"."kpi_tutorial_completion_facts" TO "service_role";
GRANT MAINTAIN ON TABLE "public"."kpi_tutorial_completion_facts" TO "service_role";
GRANT INSERT ON TABLE "public"."kpi_gacha_execution_facts" TO "service_role";
GRANT SELECT ON TABLE "public"."kpi_gacha_execution_facts" TO "service_role";
GRANT UPDATE ON TABLE "public"."kpi_gacha_execution_facts" TO "service_role";
GRANT DELETE ON TABLE "public"."kpi_gacha_execution_facts" TO "service_role";
GRANT TRUNCATE ON TABLE "public"."kpi_gacha_execution_facts" TO "service_role";
GRANT REFERENCES ON TABLE "public"."kpi_gacha_execution_facts" TO "service_role";
GRANT TRIGGER ON TABLE "public"."kpi_gacha_execution_facts" TO "service_role";
GRANT MAINTAIN ON TABLE "public"."kpi_gacha_execution_facts" TO "service_role";
GRANT SELECT ON SEQUENCE "public"."kpi_account_classification_periods_id_seq" TO "anon";
GRANT UPDATE ON SEQUENCE "public"."kpi_account_classification_periods_id_seq" TO "anon";
GRANT USAGE ON SEQUENCE "public"."kpi_account_classification_periods_id_seq" TO "anon";
GRANT SELECT ON SEQUENCE "public"."kpi_account_classification_periods_id_seq" TO "authenticated";
GRANT UPDATE ON SEQUENCE "public"."kpi_account_classification_periods_id_seq" TO "authenticated";
GRANT USAGE ON SEQUENCE "public"."kpi_account_classification_periods_id_seq" TO "authenticated";
GRANT SELECT ON SEQUENCE "public"."kpi_account_classification_periods_id_seq" TO "service_role";
GRANT UPDATE ON SEQUENCE "public"."kpi_account_classification_periods_id_seq" TO "service_role";
GRANT USAGE ON SEQUENCE "public"."kpi_account_classification_periods_id_seq" TO "service_role";
GRANT SELECT ON SEQUENCE "public"."kpi_guild_membership_periods_id_seq" TO "anon";
GRANT UPDATE ON SEQUENCE "public"."kpi_guild_membership_periods_id_seq" TO "anon";
GRANT USAGE ON SEQUENCE "public"."kpi_guild_membership_periods_id_seq" TO "anon";
GRANT SELECT ON SEQUENCE "public"."kpi_guild_membership_periods_id_seq" TO "authenticated";
GRANT UPDATE ON SEQUENCE "public"."kpi_guild_membership_periods_id_seq" TO "authenticated";
GRANT USAGE ON SEQUENCE "public"."kpi_guild_membership_periods_id_seq" TO "authenticated";
GRANT SELECT ON SEQUENCE "public"."kpi_guild_membership_periods_id_seq" TO "service_role";
GRANT UPDATE ON SEQUENCE "public"."kpi_guild_membership_periods_id_seq" TO "service_role";
GRANT USAGE ON SEQUENCE "public"."kpi_guild_membership_periods_id_seq" TO "service_role";
GRANT INSERT ON TABLE "public"."kpi_aggregation_runs" TO "service_role";
GRANT SELECT ON TABLE "public"."kpi_aggregation_runs" TO "service_role";
GRANT UPDATE ON TABLE "public"."kpi_aggregation_runs" TO "service_role";
GRANT DELETE ON TABLE "public"."kpi_aggregation_runs" TO "service_role";
GRANT TRUNCATE ON TABLE "public"."kpi_aggregation_runs" TO "service_role";
GRANT REFERENCES ON TABLE "public"."kpi_aggregation_runs" TO "service_role";
GRANT TRIGGER ON TABLE "public"."kpi_aggregation_runs" TO "service_role";
GRANT MAINTAIN ON TABLE "public"."kpi_aggregation_runs" TO "service_role";
GRANT INSERT ON TABLE "public"."kpi_metric_snapshots" TO "service_role";
GRANT SELECT ON TABLE "public"."kpi_metric_snapshots" TO "service_role";
GRANT UPDATE ON TABLE "public"."kpi_metric_snapshots" TO "service_role";
GRANT DELETE ON TABLE "public"."kpi_metric_snapshots" TO "service_role";
GRANT TRUNCATE ON TABLE "public"."kpi_metric_snapshots" TO "service_role";
GRANT REFERENCES ON TABLE "public"."kpi_metric_snapshots" TO "service_role";
GRANT TRIGGER ON TABLE "public"."kpi_metric_snapshots" TO "service_role";
GRANT MAINTAIN ON TABLE "public"."kpi_metric_snapshots" TO "service_role";
GRANT SELECT ON SEQUENCE "public"."kpi_metric_snapshots_id_seq" TO "anon";
GRANT UPDATE ON SEQUENCE "public"."kpi_metric_snapshots_id_seq" TO "anon";
GRANT USAGE ON SEQUENCE "public"."kpi_metric_snapshots_id_seq" TO "anon";
GRANT SELECT ON SEQUENCE "public"."kpi_metric_snapshots_id_seq" TO "authenticated";
GRANT UPDATE ON SEQUENCE "public"."kpi_metric_snapshots_id_seq" TO "authenticated";
GRANT USAGE ON SEQUENCE "public"."kpi_metric_snapshots_id_seq" TO "authenticated";
GRANT SELECT ON SEQUENCE "public"."kpi_metric_snapshots_id_seq" TO "service_role";
GRANT UPDATE ON SEQUENCE "public"."kpi_metric_snapshots_id_seq" TO "service_role";
GRANT USAGE ON SEQUENCE "public"."kpi_metric_snapshots_id_seq" TO "service_role";
GRANT INSERT ON TABLE "public"."special_gacha_pool_groups" TO "service_role";
GRANT SELECT ON TABLE "public"."special_gacha_pool_groups" TO "service_role";
GRANT UPDATE ON TABLE "public"."special_gacha_pool_groups" TO "service_role";
GRANT DELETE ON TABLE "public"."special_gacha_pool_groups" TO "service_role";
GRANT TRUNCATE ON TABLE "public"."special_gacha_pool_groups" TO "service_role";
GRANT REFERENCES ON TABLE "public"."special_gacha_pool_groups" TO "service_role";
GRANT TRIGGER ON TABLE "public"."special_gacha_pool_groups" TO "service_role";
GRANT MAINTAIN ON TABLE "public"."special_gacha_pool_groups" TO "service_role";
GRANT SELECT ON TABLE "public"."special_gacha_pool_groups" TO "authenticated";
GRANT INSERT ON TABLE "public"."gameplay_reward_delivery_ledger" TO "service_role";
GRANT SELECT ON TABLE "public"."gameplay_reward_delivery_ledger" TO "service_role";
GRANT UPDATE ON TABLE "public"."gameplay_reward_delivery_ledger" TO "service_role";
GRANT DELETE ON TABLE "public"."gameplay_reward_delivery_ledger" TO "service_role";
GRANT TRUNCATE ON TABLE "public"."gameplay_reward_delivery_ledger" TO "service_role";
GRANT REFERENCES ON TABLE "public"."gameplay_reward_delivery_ledger" TO "service_role";
GRANT TRIGGER ON TABLE "public"."gameplay_reward_delivery_ledger" TO "service_role";
GRANT MAINTAIN ON TABLE "public"."gameplay_reward_delivery_ledger" TO "service_role";
GRANT INSERT ON TABLE "public"."user_characters" TO "anon";
GRANT SELECT ON TABLE "public"."user_characters" TO "anon";
GRANT UPDATE ON TABLE "public"."user_characters" TO "anon";
GRANT DELETE ON TABLE "public"."user_characters" TO "anon";
GRANT TRUNCATE ON TABLE "public"."user_characters" TO "anon";
GRANT REFERENCES ON TABLE "public"."user_characters" TO "anon";
GRANT TRIGGER ON TABLE "public"."user_characters" TO "anon";
GRANT MAINTAIN ON TABLE "public"."user_characters" TO "anon";
GRANT SELECT ON TABLE "public"."user_characters" TO "authenticated";
GRANT TRUNCATE ON TABLE "public"."user_characters" TO "authenticated";
GRANT REFERENCES ON TABLE "public"."user_characters" TO "authenticated";
GRANT TRIGGER ON TABLE "public"."user_characters" TO "authenticated";
GRANT MAINTAIN ON TABLE "public"."user_characters" TO "authenticated";
GRANT INSERT ON TABLE "public"."user_characters" TO "service_role";
GRANT SELECT ON TABLE "public"."user_characters" TO "service_role";
GRANT UPDATE ON TABLE "public"."user_characters" TO "service_role";
GRANT DELETE ON TABLE "public"."user_characters" TO "service_role";
GRANT TRUNCATE ON TABLE "public"."user_characters" TO "service_role";
GRANT REFERENCES ON TABLE "public"."user_characters" TO "service_role";
GRANT TRIGGER ON TABLE "public"."user_characters" TO "service_role";
GRANT MAINTAIN ON TABLE "public"."user_characters" TO "service_role";
GRANT INSERT ON TABLE "public"."user_equipments" TO "anon";
GRANT SELECT ON TABLE "public"."user_equipments" TO "anon";
GRANT UPDATE ON TABLE "public"."user_equipments" TO "anon";
GRANT DELETE ON TABLE "public"."user_equipments" TO "anon";
GRANT TRUNCATE ON TABLE "public"."user_equipments" TO "anon";
GRANT REFERENCES ON TABLE "public"."user_equipments" TO "anon";
GRANT TRIGGER ON TABLE "public"."user_equipments" TO "anon";
GRANT MAINTAIN ON TABLE "public"."user_equipments" TO "anon";
GRANT SELECT ON TABLE "public"."user_equipments" TO "authenticated";
GRANT TRUNCATE ON TABLE "public"."user_equipments" TO "authenticated";
GRANT REFERENCES ON TABLE "public"."user_equipments" TO "authenticated";
GRANT TRIGGER ON TABLE "public"."user_equipments" TO "authenticated";
GRANT MAINTAIN ON TABLE "public"."user_equipments" TO "authenticated";
GRANT INSERT ON TABLE "public"."user_equipments" TO "service_role";
GRANT SELECT ON TABLE "public"."user_equipments" TO "service_role";
GRANT UPDATE ON TABLE "public"."user_equipments" TO "service_role";
GRANT DELETE ON TABLE "public"."user_equipments" TO "service_role";
GRANT TRUNCATE ON TABLE "public"."user_equipments" TO "service_role";
GRANT REFERENCES ON TABLE "public"."user_equipments" TO "service_role";
GRANT TRIGGER ON TABLE "public"."user_equipments" TO "service_role";
GRANT MAINTAIN ON TABLE "public"."user_equipments" TO "service_role";
GRANT INSERT ON TABLE "public"."character_level_up_master" TO "authenticated";
GRANT SELECT ON TABLE "public"."character_level_up_master" TO "authenticated";
GRANT UPDATE ON TABLE "public"."character_level_up_master" TO "authenticated";
GRANT DELETE ON TABLE "public"."character_level_up_master" TO "authenticated";
GRANT TRUNCATE ON TABLE "public"."character_level_up_master" TO "authenticated";
GRANT REFERENCES ON TABLE "public"."character_level_up_master" TO "authenticated";
GRANT TRIGGER ON TABLE "public"."character_level_up_master" TO "authenticated";
GRANT MAINTAIN ON TABLE "public"."character_level_up_master" TO "authenticated";
GRANT INSERT ON TABLE "public"."character_level_up_master" TO "service_role";
GRANT SELECT ON TABLE "public"."character_level_up_master" TO "service_role";
GRANT UPDATE ON TABLE "public"."character_level_up_master" TO "service_role";
GRANT DELETE ON TABLE "public"."character_level_up_master" TO "service_role";
GRANT TRUNCATE ON TABLE "public"."character_level_up_master" TO "service_role";
GRANT REFERENCES ON TABLE "public"."character_level_up_master" TO "service_role";
GRANT TRIGGER ON TABLE "public"."character_level_up_master" TO "service_role";
GRANT MAINTAIN ON TABLE "public"."character_level_up_master" TO "service_role";
GRANT INSERT ON TABLE "public"."growth_exp_execution_history" TO "service_role";
GRANT SELECT ON TABLE "public"."growth_exp_execution_history" TO "service_role";
GRANT UPDATE ON TABLE "public"."growth_exp_execution_history" TO "service_role";
GRANT DELETE ON TABLE "public"."growth_exp_execution_history" TO "service_role";
GRANT TRUNCATE ON TABLE "public"."growth_exp_execution_history" TO "service_role";
GRANT REFERENCES ON TABLE "public"."growth_exp_execution_history" TO "service_role";
GRANT TRIGGER ON TABLE "public"."growth_exp_execution_history" TO "service_role";
GRANT MAINTAIN ON TABLE "public"."growth_exp_execution_history" TO "service_role";
GRANT SELECT ON TABLE "public"."growth_exp_execution_history" TO "authenticated";
GRANT SELECT ON TABLE "public"."kpi_tutorial_journey_facts" TO "service_role";
GRANT SELECT ON TABLE "public"."kpi_acquisition_journeys" TO "service_role";
GRANT SELECT ON TABLE "public"."kpi_tutorial_mypage_ready_contexts" TO "service_role";
GRANT SELECT ON TABLE "public"."kpi_subject_identity_transition_facts" TO "service_role";
GRANT SELECT ON TABLE "public"."kpi_acquisition_journey_facts" TO "service_role";
GRANT SELECT ON TABLE "public"."kpi_guild_conversion_facts" TO "service_role";
GRANT INSERT ON TABLE "public"."canonical_character_growth_exponents" TO "service_role";
GRANT SELECT ON TABLE "public"."canonical_character_growth_exponents" TO "service_role";
GRANT UPDATE ON TABLE "public"."canonical_character_growth_exponents" TO "service_role";
GRANT DELETE ON TABLE "public"."canonical_character_growth_exponents" TO "service_role";
GRANT TRUNCATE ON TABLE "public"."canonical_character_growth_exponents" TO "service_role";
GRANT REFERENCES ON TABLE "public"."canonical_character_growth_exponents" TO "service_role";
GRANT TRIGGER ON TABLE "public"."canonical_character_growth_exponents" TO "service_role";
GRANT MAINTAIN ON TABLE "public"."canonical_character_growth_exponents" TO "service_role";
GRANT SELECT ON TABLE "public"."canonical_character_growth_exponents" TO "anon";
GRANT SELECT ON TABLE "public"."canonical_character_growth_exponents" TO "authenticated";
GRANT SELECT ON TABLE "public"."kpi_guild_chat_message_facts" TO "service_role";
GRANT INSERT ON TABLE "public"."canonical_character_growth_assignments" TO "service_role";
GRANT SELECT ON TABLE "public"."canonical_character_growth_assignments" TO "service_role";
GRANT UPDATE ON TABLE "public"."canonical_character_growth_assignments" TO "service_role";
GRANT DELETE ON TABLE "public"."canonical_character_growth_assignments" TO "service_role";
GRANT TRUNCATE ON TABLE "public"."canonical_character_growth_assignments" TO "service_role";
GRANT REFERENCES ON TABLE "public"."canonical_character_growth_assignments" TO "service_role";
GRANT TRIGGER ON TABLE "public"."canonical_character_growth_assignments" TO "service_role";
GRANT MAINTAIN ON TABLE "public"."canonical_character_growth_assignments" TO "service_role";
GRANT SELECT ON TABLE "public"."canonical_character_growth_assignments" TO "anon";
GRANT SELECT ON TABLE "public"."canonical_character_growth_assignments" TO "authenticated";
GRANT SELECT ON TABLE "public"."kpi_guild_chat_activation_facts" TO "service_role";
GRANT SELECT ON TABLE "public"."kpi_marketing_import_batches" TO "service_role";
GRANT SELECT ON TABLE "public"."kpi_acquisition_subject_bindings" TO "service_role";
GRANT SELECT ON TABLE "public"."kpi_marketing_reporting_scopes" TO "service_role";
GRANT SELECT ON TABLE "public"."kpi_marketing_daily_fact_revisions" TO "service_role";
GRANT SELECT ON TABLE "public"."kpi_canonical_tutorial_completions_v1" TO "service_role";
GRANT SELECT ON TABLE "public"."kpi_guild_daily_chat_activity_v1" TO "service_role";
GRANT SELECT ON TABLE "public"."kpi_effective_active_guild_daily_v1" TO "service_role";
GRANT SELECT ON TABLE "public"."kpi_marketing_latest_revisions_v1" TO "service_role";
GRANT INSERT ON TABLE "public"."operations_maintenance_testers" TO "service_role";
GRANT SELECT ON TABLE "public"."operations_maintenance_testers" TO "service_role";
GRANT UPDATE ON TABLE "public"."operations_maintenance_testers" TO "service_role";
GRANT DELETE ON TABLE "public"."operations_maintenance_testers" TO "service_role";
GRANT TRUNCATE ON TABLE "public"."operations_maintenance_testers" TO "service_role";
GRANT REFERENCES ON TABLE "public"."operations_maintenance_testers" TO "service_role";
GRANT TRIGGER ON TABLE "public"."operations_maintenance_testers" TO "service_role";
GRANT MAINTAIN ON TABLE "public"."operations_maintenance_testers" TO "service_role";
GRANT SELECT ON TABLE "public"."operations_maintenance_testers" TO "authenticated";
GRANT INSERT ON TABLE "public"."ranking_season_reward_grants" TO "service_role";
GRANT SELECT ON TABLE "public"."ranking_season_reward_grants" TO "service_role";
GRANT UPDATE ON TABLE "public"."ranking_season_reward_grants" TO "service_role";
GRANT DELETE ON TABLE "public"."ranking_season_reward_grants" TO "service_role";
GRANT TRUNCATE ON TABLE "public"."ranking_season_reward_grants" TO "service_role";
GRANT REFERENCES ON TABLE "public"."ranking_season_reward_grants" TO "service_role";
GRANT TRIGGER ON TABLE "public"."ranking_season_reward_grants" TO "service_role";
GRANT MAINTAIN ON TABLE "public"."ranking_season_reward_grants" TO "service_role";
GRANT INSERT ON TABLE "public"."monthly_power_season_runs" TO "service_role";
GRANT SELECT ON TABLE "public"."monthly_power_season_runs" TO "service_role";
GRANT UPDATE ON TABLE "public"."monthly_power_season_runs" TO "service_role";
GRANT DELETE ON TABLE "public"."monthly_power_season_runs" TO "service_role";
GRANT TRUNCATE ON TABLE "public"."monthly_power_season_runs" TO "service_role";
GRANT REFERENCES ON TABLE "public"."monthly_power_season_runs" TO "service_role";
GRANT TRIGGER ON TABLE "public"."monthly_power_season_runs" TO "service_role";
GRANT MAINTAIN ON TABLE "public"."monthly_power_season_runs" TO "service_role";
GRANT INSERT ON TABLE "public"."monthly_power_entity_snapshots" TO "service_role";
GRANT SELECT ON TABLE "public"."monthly_power_entity_snapshots" TO "service_role";
GRANT UPDATE ON TABLE "public"."monthly_power_entity_snapshots" TO "service_role";
GRANT DELETE ON TABLE "public"."monthly_power_entity_snapshots" TO "service_role";
GRANT TRUNCATE ON TABLE "public"."monthly_power_entity_snapshots" TO "service_role";
GRANT REFERENCES ON TABLE "public"."monthly_power_entity_snapshots" TO "service_role";
GRANT TRIGGER ON TABLE "public"."monthly_power_entity_snapshots" TO "service_role";
GRANT MAINTAIN ON TABLE "public"."monthly_power_entity_snapshots" TO "service_role";
GRANT INSERT ON TABLE "public"."monthly_power_member_snapshots" TO "service_role";
GRANT SELECT ON TABLE "public"."monthly_power_member_snapshots" TO "service_role";
GRANT UPDATE ON TABLE "public"."monthly_power_member_snapshots" TO "service_role";
GRANT DELETE ON TABLE "public"."monthly_power_member_snapshots" TO "service_role";
GRANT TRUNCATE ON TABLE "public"."monthly_power_member_snapshots" TO "service_role";
GRANT REFERENCES ON TABLE "public"."monthly_power_member_snapshots" TO "service_role";
GRANT TRIGGER ON TABLE "public"."monthly_power_member_snapshots" TO "service_role";
GRANT MAINTAIN ON TABLE "public"."monthly_power_member_snapshots" TO "service_role";
GRANT INSERT ON TABLE "public"."monthly_power_honor_requirements" TO "service_role";
GRANT SELECT ON TABLE "public"."monthly_power_honor_requirements" TO "service_role";
GRANT UPDATE ON TABLE "public"."monthly_power_honor_requirements" TO "service_role";
GRANT DELETE ON TABLE "public"."monthly_power_honor_requirements" TO "service_role";
GRANT TRUNCATE ON TABLE "public"."monthly_power_honor_requirements" TO "service_role";
GRANT REFERENCES ON TABLE "public"."monthly_power_honor_requirements" TO "service_role";
GRANT TRIGGER ON TABLE "public"."monthly_power_honor_requirements" TO "service_role";
GRANT MAINTAIN ON TABLE "public"."monthly_power_honor_requirements" TO "service_role";
GRANT INSERT ON TABLE "public"."monthly_power_reward_master" TO "service_role";
GRANT SELECT ON TABLE "public"."monthly_power_reward_master" TO "service_role";
GRANT UPDATE ON TABLE "public"."monthly_power_reward_master" TO "service_role";
GRANT DELETE ON TABLE "public"."monthly_power_reward_master" TO "service_role";
