SET check_function_bodies = false;
SET search_path = public, extensions, pg_catalog;
GRANT EXECUTE ON FUNCTION "public"."get_public_guild_base_controls"() TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."get_public_guild_base_controls"() TO "service_role";
REVOKE ALL ON FUNCTION "public"."get_public_guild_detail"(p_guild_id uuid) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."get_public_guild_detail"(p_guild_id uuid) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."get_public_guild_detail"(p_guild_id uuid) TO "service_role";
REVOKE ALL ON FUNCTION "public"."get_public_guild_power_rankings"(p_daily boolean, p_limit integer, p_offset integer) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."get_public_guild_power_rankings"(p_daily boolean, p_limit integer, p_offset integer) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."get_public_guild_power_rankings"(p_daily boolean, p_limit integer, p_offset integer) TO "service_role";
REVOKE ALL ON FUNCTION "public"."get_public_gvg_rankings"(p_limit integer, p_offset integer) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."get_public_gvg_rankings"(p_limit integer, p_offset integer) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."get_public_gvg_rankings"(p_limit integer, p_offset integer) TO "service_role";
REVOKE ALL ON FUNCTION "public"."get_public_leader_characters"(p_user_ids uuid[]) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."get_public_leader_characters"(p_user_ids uuid[]) TO "anon";
GRANT EXECUTE ON FUNCTION "public"."get_public_leader_characters"(p_user_ids uuid[]) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."get_public_leader_characters"(p_user_ids uuid[]) TO "service_role";
REVOKE ALL ON FUNCTION "public"."get_public_player_detail"(p_user_id uuid) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."get_public_player_detail"(p_user_id uuid) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."get_public_player_detail"(p_user_id uuid) TO "service_role";
REVOKE ALL ON FUNCTION "public"."get_public_power_rankings"() FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."get_public_power_rankings"() TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."get_public_power_rankings"() TO "service_role";
REVOKE ALL ON FUNCTION "public"."get_public_power_rankings"(p_daily boolean, p_limit integer, p_offset integer) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."get_public_power_rankings"(p_daily boolean, p_limit integer, p_offset integer) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."get_public_power_rankings"(p_daily boolean, p_limit integer, p_offset integer) TO "service_role";
REVOKE ALL ON FUNCTION "public"."get_public_profiles"(p_user_ids uuid[]) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."get_public_profiles"(p_user_ids uuid[]) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."get_public_profiles"(p_user_ids uuid[]) TO "service_role";
REVOKE ALL ON FUNCTION "public"."_raid_room_clear_reward_progress_v1"(p_room_id uuid, p_user_id uuid) FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON FUNCTION "public"."quest_raid_encounter_projection_v1"(p_patrol_id uuid) FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON FUNCTION "public"."get_quest_raid_bonus_v1"(p_room_id uuid) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."get_quest_raid_bonus_v1"(p_room_id uuid) TO "authenticated";
REVOKE ALL ON FUNCTION "public"."get_raid_reward_policy_v2"() FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."get_raid_reward_policy_v2"() TO "authenticated";
REVOKE ALL ON FUNCTION "public"."_quest_raid_cash_xp_v2"(p_patrol uuid) FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON FUNCTION "public"."on_quest_base_cash_snapshot"() FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."on_quest_base_cash_snapshot"() TO "service_role";
REVOKE ALL ON FUNCTION "public"."advance_monthly_power_seasons_v1"() FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."advance_monthly_power_seasons_v1"() TO "service_role";
REVOKE ALL ON FUNCTION "private"."apply_recommended_main_skills_v1"(p_user_id uuid) FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON FUNCTION "public"."_exchange_pity_reward_per_banner"(p_user_id uuid, p_reward_type text, p_reward_id text, p_gacha_id text) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."_exchange_pity_reward_per_banner"(p_user_id uuid, p_reward_type text, p_reward_id text, p_gacha_id text) TO "service_role";
REVOKE ALL ON FUNCTION "public"."get_public_pvp_rankings"(p_daily boolean, p_limit integer, p_offset integer) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."get_public_pvp_rankings"(p_daily boolean, p_limit integer, p_offset integer) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."get_public_pvp_rankings"(p_daily boolean, p_limit integer, p_offset integer) TO "service_role";
REVOKE ALL ON FUNCTION "public"."get_pvp_opponents"(p_user_id uuid, p_my_points integer) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."get_pvp_opponents"(p_user_id uuid, p_my_points integer) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."get_pvp_opponents"(p_user_id uuid, p_my_points integer) TO "service_role";
REVOKE ALL ON FUNCTION "public"."get_pvp_opponents_page"(p_user_id uuid, p_my_points integer, p_offset integer) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."get_pvp_opponents_page"(p_user_id uuid, p_my_points integer, p_offset integer) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."get_pvp_opponents_page"(p_user_id uuid, p_my_points integer, p_offset integer) TO "service_role";
REVOKE ALL ON FUNCTION "public"."get_pvp_rankings_page"(p_limit integer, p_offset integer) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."get_pvp_rankings_page"(p_limit integer, p_offset integer) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."get_pvp_rankings_page"(p_limit integer, p_offset integer) TO "service_role";
REVOKE ALL ON FUNCTION "public"."get_raid_rankings"(p_instance_id uuid) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."get_raid_rankings"(p_instance_id uuid) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."get_raid_rankings"(p_instance_id uuid) TO "service_role";
REVOKE ALL ON FUNCTION "public"."get_raid_rankings"(p_instance_id uuid, p_limit integer, p_offset integer) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."get_raid_rankings"(p_instance_id uuid, p_limit integer, p_offset integer) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."get_raid_rankings"(p_instance_id uuid, p_limit integer, p_offset integer) TO "service_role";
REVOKE ALL ON FUNCTION "public"."get_raid_season_rankings"(p_limit integer, p_offset integer) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."get_raid_season_rankings"(p_limit integer, p_offset integer) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."get_raid_season_rankings"(p_limit integer, p_offset integer) TO "service_role";
REVOKE ALL ON FUNCTION "public"."get_recommended_guilds"(p_limit integer) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."get_recommended_guilds"(p_limit integer) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."get_recommended_guilds"(p_limit integer) TO "service_role";
REVOKE ALL ON FUNCTION "public"."get_user_setup_status"() FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."get_user_setup_status"() TO "anon";
GRANT EXECUTE ON FUNCTION "public"."get_user_setup_status"() TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."get_user_setup_status"() TO "service_role";
REVOKE ALL ON FUNCTION "public"."grant_canonical_daily_ranking_reward"(p_ranking_day_key date, p_ranking_type text, p_recipient_user_id uuid, p_ranked_entity_id uuid, p_rank_position integer, p_score bigint) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."grant_canonical_daily_ranking_reward"(p_ranking_day_key date, p_ranking_type text, p_recipient_user_id uuid, p_ranked_entity_id uuid, p_rank_position integer, p_score bigint) TO "service_role";
REVOKE ALL ON FUNCTION "public"."grant_canonical_guild_daily_exp"(p_user_id uuid, p_source text, p_source_reference_id uuid) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."grant_canonical_guild_daily_exp"(p_user_id uuid, p_source text, p_source_reference_id uuid) TO "service_role";
REVOKE ALL ON FUNCTION "public"."grant_mission_reward_bundle"(p_delivery_ledger_id uuid, p_user_id uuid, p_mission_id text) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."grant_mission_reward_bundle"(p_delivery_ledger_id uuid, p_user_id uuid, p_mission_id text) TO "service_role";
REVOKE ALL ON FUNCTION "public"."grant_present_payload"(p_user_id uuid, p_item_id text, p_quantity integer) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."grant_present_payload"(p_user_id uuid, p_item_id text, p_quantity integer) TO "service_role";
REVOKE ALL ON FUNCTION "public"."guard_equipped_title_ownership"() FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."guard_equipped_title_ownership"() TO PUBLIC;
GRANT EXECUTE ON FUNCTION "public"."guard_equipped_title_ownership"() TO "anon";
GRANT EXECUTE ON FUNCTION "public"."guard_equipped_title_ownership"() TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."guard_equipped_title_ownership"() TO "service_role";
REVOKE ALL ON FUNCTION "public"."guard_gvg_defense_deck_lock"() FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."guard_gvg_defense_deck_lock"() TO PUBLIC;
GRANT EXECUTE ON FUNCTION "public"."guard_gvg_defense_deck_lock"() TO "anon";
GRANT EXECUTE ON FUNCTION "public"."guard_gvg_defense_deck_lock"() TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."guard_gvg_defense_deck_lock"() TO "service_role";
REVOKE ALL ON FUNCTION "public"."reject_friend_request"(p_request_id uuid) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."reject_friend_request"(p_request_id uuid) TO "service_role";
GRANT EXECUTE ON FUNCTION "public"."reject_friend_request"(p_request_id uuid) TO "authenticated";
REVOKE ALL ON FUNCTION "public"."exchange_special_gacha_reward"(p_gacha_id text, p_reward_type text, p_reward_id text, p_request_id uuid) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."exchange_special_gacha_reward"(p_gacha_id text, p_reward_type text, p_reward_id text, p_request_id uuid) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."exchange_special_gacha_reward"(p_gacha_id text, p_reward_type text, p_reward_id text, p_request_id uuid) TO "service_role";
REVOKE ALL ON FUNCTION "public"."get_special_gacha_catalog_v2"() FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."get_special_gacha_catalog_v2"() TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."get_special_gacha_catalog_v2"() TO "service_role";
REVOKE ALL ON FUNCTION "public"."activate_formal_open_next_day_seasons_v1"() FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."activate_formal_open_next_day_seasons_v1"() TO "service_role";
REVOKE ALL ON FUNCTION "public"."get_upcoming_ranking_seasons_v1"() FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."get_upcoming_ranking_seasons_v1"() TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."get_upcoming_ranking_seasons_v1"() TO "service_role";
REVOKE ALL ON FUNCTION "public"."grant_raid_completion_xp"(p_boss_id text) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."grant_raid_completion_xp"(p_boss_id text) TO "anon";
GRANT EXECUTE ON FUNCTION "public"."grant_raid_completion_xp"(p_boss_id text) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."grant_raid_completion_xp"(p_boss_id text) TO "service_role";
REVOKE ALL ON FUNCTION "public"."guard_daily_profile_changes"() FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."guard_daily_profile_changes"() TO PUBLIC;
GRANT EXECUTE ON FUNCTION "public"."guard_daily_profile_changes"() TO "anon";
GRANT EXECUTE ON FUNCTION "public"."guard_daily_profile_changes"() TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."guard_daily_profile_changes"() TO "service_role";
REVOKE ALL ON FUNCTION "public"."guard_gvg_membership_lock"() FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."guard_gvg_membership_lock"() TO PUBLIC;
GRANT EXECUTE ON FUNCTION "public"."guard_gvg_membership_lock"() TO "anon";
GRANT EXECUTE ON FUNCTION "public"."guard_gvg_membership_lock"() TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."guard_gvg_membership_lock"() TO "service_role";
REVOKE ALL ON FUNCTION "public"."guard_preopen_guild_power_cutoff"() FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."guard_preopen_guild_power_cutoff"() TO "service_role";
REVOKE ALL ON FUNCTION "public"."guild_jst_date"(p_at timestamp with time zone) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."guild_jst_date"(p_at timestamp with time zone) TO "service_role";
REVOKE ALL ON FUNCTION "public"."initialize_current_player"(p_username text, p_invite_code text) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."initialize_current_player"(p_username text, p_invite_code text) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."initialize_current_player"(p_username text, p_invite_code text) TO "service_role";
REVOKE ALL ON FUNCTION "public"."initialize_new_user"(p_user_id uuid, p_name text) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."initialize_new_user"(p_user_id uuid, p_name text) TO "service_role";
REVOKE ALL ON FUNCTION "public"."initialize_new_user"(p_user_id uuid, p_username text, p_character_id text, p_area_id text, p_gift_code text, p_gender text, p_hair_id text, p_face_id text) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."initialize_new_user"(p_user_id uuid, p_username text, p_character_id text, p_area_id text, p_gift_code text, p_gender text, p_hair_id text, p_face_id text) TO "anon";
GRANT EXECUTE ON FUNCTION "public"."initialize_new_user"(p_user_id uuid, p_username text, p_character_id text, p_area_id text, p_gift_code text, p_gender text, p_hair_id text, p_face_id text) TO "service_role";
REVOKE ALL ON FUNCTION "public"."is_current_guild_master"(p_guild_id uuid) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."is_current_guild_master"(p_guild_id uuid) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."is_current_guild_master"(p_guild_id uuid) TO "service_role";
REVOKE ALL ON FUNCTION "public"."is_current_guild_member"(p_guild_id uuid) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."is_current_guild_member"(p_guild_id uuid) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."is_current_guild_member"(p_guild_id uuid) TO "service_role";
REVOKE ALL ON FUNCTION "public"."join_guild"(p_guild_id uuid) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."join_guild"(p_guild_id uuid) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."join_guild"(p_guild_id uuid) TO "service_role";
REVOKE ALL ON FUNCTION "public"."kick_guild_member"(p_guild_id uuid, p_user_id uuid) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."kick_guild_member"(p_guild_id uuid, p_user_id uuid) TO "service_role";
GRANT EXECUTE ON FUNCTION "public"."kick_guild_member"(p_guild_id uuid, p_user_id uuid) TO "authenticated";
REVOKE ALL ON FUNCTION "public"."leave_guild"(p_user_id uuid, p_guild_id uuid, p_is_master boolean, p_has_others boolean) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."leave_guild"(p_user_id uuid, p_guild_id uuid, p_is_master boolean, p_has_others boolean) TO "service_role";
GRANT EXECUTE ON FUNCTION "public"."leave_guild"(p_user_id uuid, p_guild_id uuid, p_is_master boolean, p_has_others boolean) TO "authenticated";
REVOKE ALL ON FUNCTION "public"."level_up_character"(p_character_id uuid, p_exp_item_id text, p_count integer) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."level_up_character"(p_character_id uuid, p_exp_item_id text, p_count integer) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."level_up_character"(p_character_id uuid, p_exp_item_id text, p_count integer) TO "service_role";
REVOKE ALL ON FUNCTION "public"."level_up_equipment"(p_equipment_id uuid, p_exp_item_id text, p_count integer) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."level_up_equipment"(p_equipment_id uuid, p_exp_item_id text, p_count integer) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."level_up_equipment"(p_equipment_id uuid, p_exp_item_id text, p_count integer) TO "service_role";
REVOKE ALL ON FUNCTION "public"."limit_break_equipment"(p_equipment_id uuid, p_use_wildcard boolean, p_dupe_id uuid) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."limit_break_equipment"(p_equipment_id uuid, p_use_wildcard boolean, p_dupe_id uuid) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."limit_break_equipment"(p_equipment_id uuid, p_use_wildcard boolean, p_dupe_id uuid) TO "service_role";
REVOKE ALL ON FUNCTION "public"."limit_break_gear"(p_user_id uuid, p_equipment_id uuid, p_cash_cost integer, p_hammer_cost integer) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."limit_break_gear"(p_user_id uuid, p_equipment_id uuid, p_cash_cost integer, p_hammer_cost integer) TO "service_role";
REVOKE ALL ON FUNCTION "public"."mark_bbs_thread_read"(p_thread_id uuid) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."mark_bbs_thread_read"(p_thread_id uuid) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."mark_bbs_thread_read"(p_thread_id uuid) TO "service_role";
REVOKE ALL ON FUNCTION "public"."on_m9x_join_approved_metric"() FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."on_m9x_join_approved_metric"() TO PUBLIC;
GRANT EXECUTE ON FUNCTION "public"."on_m9x_join_approved_metric"() TO "anon";
GRANT EXECUTE ON FUNCTION "public"."on_m9x_join_approved_metric"() TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."on_m9x_join_approved_metric"() TO "service_role";
REVOKE ALL ON FUNCTION "public"."sync_user_guild_membership"() FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."sync_user_guild_membership"() TO PUBLIC;
GRANT EXECUTE ON FUNCTION "public"."sync_user_guild_membership"() TO "anon";
GRANT EXECUTE ON FUNCTION "public"."sync_user_guild_membership"() TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."sync_user_guild_membership"() TO "service_role";
REVOKE ALL ON FUNCTION "public"."limit_break_gear_v2"(p_user_id uuid, p_equipment_id uuid, p_cash_cost integer, p_use_wildcard boolean, p_dupe_id uuid, p_new_options jsonb) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."limit_break_gear_v2"(p_user_id uuid, p_equipment_id uuid, p_cash_cost integer, p_use_wildcard boolean, p_dupe_id uuid, p_new_options jsonb) TO "service_role";
REVOKE ALL ON FUNCTION "public"."limit_break_skill"(p_skill_id uuid, p_use_wildcard boolean, p_dupe_id uuid) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."limit_break_skill"(p_skill_id uuid, p_use_wildcard boolean, p_dupe_id uuid) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."limit_break_skill"(p_skill_id uuid, p_use_wildcard boolean, p_dupe_id uuid) TO "service_role";
REVOKE ALL ON FUNCTION "public"."limit_break_skill"(p_user_id uuid, p_skill_id uuid, p_cash_cost integer, p_book_cost integer) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."limit_break_skill"(p_user_id uuid, p_skill_id uuid, p_cash_cost integer, p_book_cost integer) TO "service_role";
REVOKE ALL ON FUNCTION "public"."limit_break_skill_v2"(p_user_id uuid, p_skill_id uuid, p_cash_cost integer, p_use_wildcard boolean, p_dupe_id uuid, p_wildcard_item_id text) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."limit_break_skill_v2"(p_user_id uuid, p_skill_id uuid, p_cash_cost integer, p_use_wildcard boolean, p_dupe_id uuid, p_wildcard_item_id text) TO "service_role";
REVOKE ALL ON FUNCTION "public"."mark_chat_channel_read"(p_target_type text) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."mark_chat_channel_read"(p_target_type text) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."mark_chat_channel_read"(p_target_type text) TO "service_role";
REVOKE ALL ON FUNCTION "public"."mark_direct_message_read"(p_message_id uuid) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."mark_direct_message_read"(p_message_id uuid) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."mark_direct_message_read"(p_message_id uuid) TO "service_role";
REVOKE ALL ON FUNCTION "public"."mark_mission_event_dialog_viewed"(p_event_id text, p_jst_date date) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."mark_mission_event_dialog_viewed"(p_event_id text, p_jst_date date) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."mark_mission_event_dialog_viewed"(p_event_id text, p_jst_date date) TO "service_role";
REVOKE ALL ON FUNCTION "public"."move_current_user_base"(p_base_id text) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."move_current_user_base"(p_base_id text) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."move_current_user_base"(p_base_id text) TO "service_role";
REVOKE ALL ON FUNCTION "public"."normalize_user_mission_progress"() FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."normalize_user_mission_progress"() TO "service_role";
REVOKE ALL ON FUNCTION "public"."on_canonical_daily_activity_finalized"() FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."on_canonical_daily_activity_finalized"() TO PUBLIC;
GRANT EXECUTE ON FUNCTION "public"."on_canonical_daily_activity_finalized"() TO "anon";
GRANT EXECUTE ON FUNCTION "public"."on_canonical_daily_activity_finalized"() TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."on_canonical_daily_activity_finalized"() TO "service_role";
REVOKE ALL ON FUNCTION "public"."on_canonical_guild_chat_exp"() FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."on_canonical_guild_chat_exp"() TO PUBLIC;
GRANT EXECUTE ON FUNCTION "public"."on_canonical_guild_chat_exp"() TO "anon";
GRANT EXECUTE ON FUNCTION "public"."on_canonical_guild_chat_exp"() TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."on_canonical_guild_chat_exp"() TO "service_role";
REVOKE ALL ON FUNCTION "public"."on_canonical_guild_official_battle_exp"() FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."on_canonical_guild_official_battle_exp"() TO PUBLIC;
GRANT EXECUTE ON FUNCTION "public"."on_canonical_guild_official_battle_exp"() TO "anon";
GRANT EXECUTE ON FUNCTION "public"."on_canonical_guild_official_battle_exp"() TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."on_canonical_guild_official_battle_exp"() TO "service_role";
REVOKE ALL ON FUNCTION "public"."on_canonical_guild_quest_exp"() FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."on_canonical_guild_quest_exp"() TO PUBLIC;
GRANT EXECUTE ON FUNCTION "public"."on_canonical_guild_quest_exp"() TO "anon";
GRANT EXECUTE ON FUNCTION "public"."on_canonical_guild_quest_exp"() TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."on_canonical_guild_quest_exp"() TO "service_role";
REVOKE ALL ON FUNCTION "public"."on_canonical_hard_quest_complete"() FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."on_canonical_hard_quest_complete"() TO PUBLIC;
GRANT EXECUTE ON FUNCTION "public"."on_canonical_hard_quest_complete"() TO "anon";
GRANT EXECUTE ON FUNCTION "public"."on_canonical_hard_quest_complete"() TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."on_canonical_hard_quest_complete"() TO "service_role";
REVOKE ALL ON FUNCTION "public"."on_canonical_patrol_snapshot"() FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."on_canonical_patrol_snapshot"() TO PUBLIC;
GRANT EXECUTE ON FUNCTION "public"."on_canonical_patrol_snapshot"() TO "anon";
GRANT EXECUTE ON FUNCTION "public"."on_canonical_patrol_snapshot"() TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."on_canonical_patrol_snapshot"() TO "service_role";
REVOKE ALL ON FUNCTION "public"."on_daily_mission_authority_change"() FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."on_daily_mission_authority_change"() TO "service_role";
REVOKE ALL ON FUNCTION "public"."on_first_official_battle_funnel"() FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."on_first_official_battle_funnel"() TO "service_role";
REVOKE ALL ON FUNCTION "public"."on_funnel_mission_progress"() FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."on_funnel_mission_progress"() TO "service_role";
REVOKE ALL ON FUNCTION "public"."on_login_bonus_mission_progress"() FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."on_login_bonus_mission_progress"() TO PUBLIC;
GRANT EXECUTE ON FUNCTION "public"."on_login_bonus_mission_progress"() TO "anon";
GRANT EXECUTE ON FUNCTION "public"."on_login_bonus_mission_progress"() TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."on_login_bonus_mission_progress"() TO "service_role";
REVOKE ALL ON FUNCTION "public"."power_projection_owned_row_changed"() FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."power_projection_owned_row_changed"() TO "service_role";
REVOKE ALL ON FUNCTION "public"."on_guild_chat_activation"() FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."on_guild_chat_activation"() TO "service_role";
REVOKE ALL ON FUNCTION "public"."on_guild_funnel"() FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."on_guild_funnel"() TO "service_role";
REVOKE ALL ON FUNCTION "public"."on_m9x_first_human_response"() FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."on_m9x_first_human_response"() TO PUBLIC;
GRANT EXECUTE ON FUNCTION "public"."on_m9x_first_human_response"() TO "anon";
GRANT EXECUTE ON FUNCTION "public"."on_m9x_first_human_response"() TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."on_m9x_first_human_response"() TO "service_role";
REVOKE ALL ON FUNCTION "public"."on_m9x_gacha_activity"() FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON FUNCTION "public"."on_m9x_guild_created_activity"() FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."on_m9x_guild_created_activity"() TO PUBLIC;
GRANT EXECUTE ON FUNCTION "public"."on_m9x_guild_created_activity"() TO "anon";
GRANT EXECUTE ON FUNCTION "public"."on_m9x_guild_created_activity"() TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."on_m9x_guild_created_activity"() TO "service_role";
REVOKE ALL ON FUNCTION "public"."on_m9x_power_leader_activity"() FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."on_m9x_power_leader_activity"() TO PUBLIC;
GRANT EXECUTE ON FUNCTION "public"."on_m9x_power_leader_activity"() TO "anon";
GRANT EXECUTE ON FUNCTION "public"."on_m9x_power_leader_activity"() TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."on_m9x_power_leader_activity"() TO "service_role";
REVOKE ALL ON FUNCTION "public"."on_main_formation_special_mission_change"() FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."on_main_formation_special_mission_change"() TO "service_role";
REVOKE ALL ON FUNCTION "public"."on_mission_claim_unlock"() FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."on_mission_claim_unlock"() TO "service_role";
REVOKE ALL ON FUNCTION "public"."on_official_battle_funnel"() FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."on_official_battle_funnel"() TO "service_role";
REVOKE ALL ON FUNCTION "public"."on_post_tutorial_free_asset_gacha"() FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."on_post_tutorial_free_asset_gacha"() TO "service_role";
REVOKE ALL ON FUNCTION "public"."on_progression_growth_funnel"() FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."on_progression_growth_funnel"() TO "service_role";
REVOKE ALL ON FUNCTION "public"."on_ranking_successful_view_special_mission"() FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."on_ranking_successful_view_special_mission"() TO "service_role";
REVOKE ALL ON FUNCTION "public"."on_special_mission_status_change"() FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."on_special_mission_status_change"() TO "service_role";
REVOKE ALL ON FUNCTION "public"."on_tutorial_complete_funnel"() FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."on_tutorial_complete_funnel"() TO "service_role";
REVOKE ALL ON FUNCTION "public"."operations_feature_state"(p_feature_key text) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."operations_feature_state"(p_feature_key text) TO PUBLIC;
GRANT EXECUTE ON FUNCTION "public"."operations_feature_state"(p_feature_key text) TO "anon";
GRANT EXECUTE ON FUNCTION "public"."operations_feature_state"(p_feature_key text) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."operations_feature_state"(p_feature_key text) TO "service_role";
REVOKE ALL ON FUNCTION "public"."power_projection_master_changed"() FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."power_projection_master_changed"() TO "service_role";
REVOKE ALL ON FUNCTION "public"."prepare_current_tutorial_growth"() FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."prepare_current_tutorial_growth"() TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."prepare_current_tutorial_growth"() TO "service_role";
REVOKE ALL ON FUNCTION "public"."process_daily_reset"(p_user_id uuid) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."process_daily_reset"(p_user_id uuid) TO "service_role";
REVOKE ALL ON FUNCTION "public"."process_gvg_battle_result"(p_user_id uuid, p_guild_id uuid, p_base_id text, p_is_practice boolean, p_is_win boolean) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."process_gvg_battle_result"(p_user_id uuid, p_guild_id uuid, p_base_id text, p_is_practice boolean, p_is_win boolean) TO "service_role";
REVOKE ALL ON FUNCTION "public"."process_gvg_battle_result_v2"(p_guild_id uuid, p_battle_id text, p_points integer, p_is_guild_a boolean) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."process_gvg_battle_result_v2"(p_guild_id uuid, p_battle_id text, p_points integer, p_is_guild_a boolean) TO PUBLIC;
GRANT EXECUTE ON FUNCTION "public"."process_gvg_battle_result_v2"(p_guild_id uuid, p_battle_id text, p_points integer, p_is_guild_a boolean) TO "anon";
GRANT EXECUTE ON FUNCTION "public"."process_gvg_battle_result_v2"(p_guild_id uuid, p_battle_id text, p_points integer, p_is_guild_a boolean) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."process_gvg_battle_result_v2"(p_guild_id uuid, p_battle_id text, p_points integer, p_is_guild_a boolean) TO "service_role";
REVOKE ALL ON FUNCTION "public"."process_login_bonus"() FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."process_login_bonus"() TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."process_login_bonus"() TO "service_role";
REVOKE ALL ON FUNCTION "public"."process_pvp_match_result"(p_user_id uuid, p_target_user_id uuid, p_is_win boolean, p_point_diff integer, p_cash_reward integer) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."process_pvp_match_result"(p_user_id uuid, p_target_user_id uuid, p_is_win boolean, p_point_diff integer, p_cash_reward integer) TO "service_role";
REVOKE ALL ON FUNCTION "public"."process_pvp_match_result_v2"(p_user_id uuid, p_is_win boolean, p_point_diff integer, p_cash_reward integer) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."process_pvp_match_result_v2"(p_user_id uuid, p_is_win boolean, p_point_diff integer, p_cash_reward integer) TO "service_role";
REVOKE ALL ON FUNCTION "public"."process_stripe_shop_purchase"(p_user_id uuid, p_product_id text) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."process_stripe_shop_purchase"(p_user_id uuid, p_product_id text) TO "service_role";
REVOKE ALL ON FUNCTION "public"."process_stripe_shop_purchase"(p_user_id uuid, p_product_id text, p_stripe_session_id text) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."process_stripe_shop_purchase"(p_user_id uuid, p_product_id text, p_stripe_session_id text) TO "service_role";
REVOKE ALL ON FUNCTION "public"."process_stripe_shop_purchase"(p_user_id uuid, p_stripe_session_id text, p_product_id text, p_amount_jpy integer, p_items jsonb, p_product_title text, p_is_beginner boolean, p_purchase_limit integer) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."process_stripe_shop_purchase"(p_user_id uuid, p_stripe_session_id text, p_product_id text, p_amount_jpy integer, p_items jsonb, p_product_title text, p_is_beginner boolean, p_purchase_limit integer) TO "service_role";
REVOKE ALL ON FUNCTION "public"."purchase_monthly_pass"(p_user_id uuid) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."purchase_monthly_pass"(p_user_id uuid) TO "service_role";
GRANT EXECUTE ON FUNCTION "public"."purchase_monthly_pass"(p_user_id uuid) TO "authenticated";
REVOKE ALL ON FUNCTION "public"."purchase_monthly_pass_core_20260823"(p_user_id uuid) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."purchase_monthly_pass_core_20260823"(p_user_id uuid) TO "service_role";
REVOKE ALL ON FUNCTION "public"."pvp_season_reset"(p_user_id uuid, p_current_rate integer) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."pvp_season_reset"(p_user_id uuid, p_current_rate integer) TO "service_role";
REVOKE ALL ON FUNCTION "public"."raid_boss_defeat"() FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."raid_boss_defeat"() TO "service_role";
REVOKE ALL ON FUNCTION "public"."raid_season_reset"() FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."raid_season_reset"() TO "service_role";
REVOKE ALL ON FUNCTION "public"."ranking_period_bounds"(p_type text, p_at timestamp with time zone) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."ranking_period_bounds"(p_type text, p_at timestamp with time zone) TO "service_role";
REVOKE ALL ON FUNCTION "public"."reconcile_pvp_after_season_boundary"(p_season_id uuid, p_transition_at timestamp with time zone) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."reconcile_pvp_after_season_boundary"(p_season_id uuid, p_transition_at timestamp with time zone) TO "service_role";
REVOKE ALL ON FUNCTION "public"."record_client_funnel_event"(p_event_name text, p_source_screen text, p_source_cta text, p_object_id text, p_metadata jsonb) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."record_client_funnel_event"(p_event_name text, p_source_screen text, p_source_cta text, p_object_id text, p_metadata jsonb) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."record_client_funnel_event"(p_event_name text, p_source_screen text, p_source_cta text, p_object_id text, p_metadata jsonb) TO "service_role";
REVOKE ALL ON FUNCTION "public"."record_funnel_milestone"(p_user_id uuid, p_milestone text, p_metadata jsonb) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."record_funnel_milestone"(p_user_id uuid, p_milestone text, p_metadata jsonb) TO "service_role";
REVOKE ALL ON FUNCTION "public"."record_guild_activity"(p_action_type text, p_source_id uuid) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."record_guild_activity"(p_action_type text, p_source_id uuid) TO "service_role";
REVOKE ALL ON FUNCTION "public"."record_mission_event_telemetry"(p_event_id text, p_event_name text, p_source text, p_mission_id text, p_metadata jsonb) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."record_mission_event_telemetry"(p_event_id text, p_event_name text, p_source text, p_mission_id text, p_metadata jsonb) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."record_mission_event_telemetry"(p_event_id text, p_event_name text, p_source text, p_mission_id text, p_metadata jsonb) TO "service_role";
REVOKE ALL ON FUNCTION "public"."record_post_tutorial_guide_milestone"(p_user_id uuid, p_milestone text, p_metadata jsonb) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."record_post_tutorial_guide_milestone"(p_user_id uuid, p_milestone text, p_metadata jsonb) TO "service_role";
REVOKE ALL ON FUNCTION "public"."record_raid_boss_damage"(p_user_id uuid, p_boss_id text, p_damage integer) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."record_raid_boss_damage"(p_user_id uuid, p_boss_id text, p_damage integer) TO "service_role";
REVOKE ALL ON FUNCTION "public"."reject_friend_request_core_20260823"(p_request_id uuid) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."reject_friend_request_core_20260823"(p_request_id uuid) TO "service_role";
REVOKE ALL ON FUNCTION "public"."record_raid_boss_damage_v2"(p_user_id uuid, p_boss_id text, p_damage integer) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."record_raid_boss_damage_v2"(p_user_id uuid, p_boss_id text, p_damage integer) TO "service_role";
REVOKE ALL ON FUNCTION "public"."refresh_all_user_power_projections"() FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."refresh_all_user_power_projections"() TO "service_role";
REVOKE ALL ON FUNCTION "public"."refresh_daily_mission_completion_aggregates"(p_user_id uuid, p_cycle_date date) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."refresh_daily_mission_completion_aggregates"(p_user_id uuid, p_cycle_date date) TO "service_role";
REVOKE ALL ON FUNCTION "public"."refresh_special_event_completion"(p_user_id uuid, p_event_id text) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."refresh_special_event_completion"(p_user_id uuid, p_event_id text) TO "service_role";
REVOKE ALL ON FUNCTION "public"."refresh_user_power_projection"(p_user_id uuid) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."refresh_user_power_projection"(p_user_id uuid) TO "service_role";
REVOKE ALL ON FUNCTION "public"."reject_guild_power_snapshot_mutation"() FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."reject_guild_power_snapshot_mutation"() TO "service_role";
REVOKE ALL ON FUNCTION "public"."reject_mutation_during_maintenance"() FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."reject_mutation_during_maintenance"() TO PUBLIC;
GRANT EXECUTE ON FUNCTION "public"."reject_mutation_during_maintenance"() TO "anon";
GRANT EXECUTE ON FUNCTION "public"."reject_mutation_during_maintenance"() TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."reject_mutation_during_maintenance"() TO "service_role";
REVOKE ALL ON FUNCTION "public"."remove_friend"(p_friend_id uuid) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."remove_friend"(p_friend_id uuid) TO "service_role";
GRANT EXECUTE ON FUNCTION "public"."remove_friend"(p_friend_id uuid) TO "authenticated";
REVOKE ALL ON FUNCTION "public"."remove_friend"(p_user_id uuid, p_friend_id uuid) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."remove_friend"(p_user_id uuid, p_friend_id uuid) TO "service_role";
REVOKE ALL ON FUNCTION "public"."remove_friend_core_20260823"(p_friend_id uuid) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."remove_friend_core_20260823"(p_friend_id uuid) TO "service_role";
REVOKE ALL ON FUNCTION "public"."remove_legacy_pvp_cash_before_finalize"() FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."remove_legacy_pvp_cash_before_finalize"() TO PUBLIC;
GRANT EXECUTE ON FUNCTION "public"."remove_legacy_pvp_cash_before_finalize"() TO "anon";
GRANT EXECUTE ON FUNCTION "public"."remove_legacy_pvp_cash_before_finalize"() TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."remove_legacy_pvp_cash_before_finalize"() TO "service_role";
REVOKE ALL ON FUNCTION "public"."request_guild_join"(p_guild_id uuid) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."request_guild_join"(p_guild_id uuid) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."request_guild_join"(p_guild_id uuid) TO "service_role";
REVOKE ALL ON FUNCTION "public"."reset_current_gameplay"(p_request_id uuid, p_acknowledged boolean) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."reset_current_gameplay"(p_request_id uuid, p_acknowledged boolean) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."reset_current_gameplay"(p_request_id uuid, p_acknowledged boolean) TO "service_role";
REVOKE ALL ON FUNCTION "public"."reset_daily_power_rankings"() FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."reset_daily_power_rankings"() TO "service_role";
REVOKE ALL ON FUNCTION "public"."reset_seasonal_power_rankings"() FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."reset_seasonal_power_rankings"() TO "service_role";
REVOKE ALL ON FUNCTION "public"."resolve_canonical_reward_item"(p_reward_id text) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."resolve_canonical_reward_item"(p_reward_id text) TO "service_role";
REVOKE ALL ON FUNCTION "public"."resolve_gvg_attack"(p_attack_id uuid, p_battle_replay_session_id uuid, p_is_victory boolean, p_raw_damage bigint) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."resolve_gvg_attack"(p_attack_id uuid, p_battle_replay_session_id uuid, p_is_victory boolean, p_raw_damage bigint) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."resolve_gvg_attack"(p_attack_id uuid, p_battle_replay_session_id uuid, p_is_victory boolean, p_raw_damage bigint) TO "service_role";
REVOKE ALL ON FUNCTION "public"."resolve_gvg_attack_core_20260817"(p_attack_id uuid, p_battle_replay_session_id uuid, p_is_victory boolean, p_raw_damage bigint) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."resolve_gvg_attack_core_20260817"(p_attack_id uuid, p_battle_replay_session_id uuid, p_is_victory boolean, p_raw_damage bigint) TO "service_role";
REVOKE ALL ON FUNCTION "public"."resolve_gvg_attack_legacy"(p_attack_id uuid, p_battle_replay_session_id uuid, p_is_victory boolean, p_raw_damage bigint) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."resolve_gvg_attack_legacy"(p_attack_id uuid, p_battle_replay_session_id uuid, p_is_victory boolean, p_raw_damage bigint) TO "anon";
GRANT EXECUTE ON FUNCTION "public"."resolve_gvg_attack_legacy"(p_attack_id uuid, p_battle_replay_session_id uuid, p_is_victory boolean, p_raw_damage bigint) TO "service_role";
REVOKE ALL ON FUNCTION "public"."review_guild_join_request"(p_request_id uuid, p_approve boolean) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."review_guild_join_request"(p_request_id uuid, p_approve boolean) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."review_guild_join_request"(p_request_id uuid, p_approve boolean) TO "service_role";
REVOKE ALL ON FUNCTION "public"."save_gvg_defense_deck"(p_character_ids text[]) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."save_gvg_defense_deck"(p_character_ids text[]) TO "anon";
GRANT EXECUTE ON FUNCTION "public"."save_gvg_defense_deck"(p_character_ids text[]) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."save_gvg_defense_deck"(p_character_ids text[]) TO "service_role";
REVOKE ALL ON FUNCTION "public"."save_main_formation"(p_character_ids text[]) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."save_main_formation"(p_character_ids text[]) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."save_main_formation"(p_character_ids text[]) TO "service_role";
REVOKE ALL ON FUNCTION "public"."save_pvp_defense_deck"(p_character_ids text[], p_tactic text) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."save_pvp_defense_deck"(p_character_ids text[], p_tactic text) TO "anon";
GRANT EXECUTE ON FUNCTION "public"."save_pvp_defense_deck"(p_character_ids text[], p_tactic text) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."save_pvp_defense_deck"(p_character_ids text[], p_tactic text) TO "service_role";
REVOKE ALL ON FUNCTION "public"."save_recommended_main_formation"() FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."save_recommended_main_formation"() TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."save_recommended_main_formation"() TO "service_role";
REVOKE ALL ON FUNCTION "public"."search_guilds"(p_query text) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."search_guilds"(p_query text) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."search_guilds"(p_query text) TO "service_role";
