SET check_function_bodies = false;
SET search_path = public, extensions, pg_catalog;
REVOKE ALL ON FUNCTION "public"."search_user_by_name"(p_username text) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."search_user_by_name"(p_username text) TO "service_role";
GRANT EXECUTE ON FUNCTION "public"."search_user_by_name"(p_username text) TO "authenticated";
REVOKE ALL ON FUNCTION "public"."search_user_by_name_core_20260823"(p_username text) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."search_user_by_name_core_20260823"(p_username text) TO "service_role";
REVOKE ALL ON FUNCTION "public"."sell_gear_bulk"(p_user_id uuid, p_gear_ids jsonb) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."sell_gear_bulk"(p_user_id uuid, p_gear_ids jsonb) TO "service_role";
REVOKE ALL ON FUNCTION "public"."sell_owned_equipment"(p_equipment_ids uuid[]) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."sell_owned_equipment"(p_equipment_ids uuid[]) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."sell_owned_equipment"(p_equipment_ids uuid[]) TO "service_role";
REVOKE ALL ON FUNCTION "public"."send_chat_message"(p_target_type text, p_content text) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."send_chat_message"(p_target_type text, p_content text) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."send_chat_message"(p_target_type text, p_content text) TO "service_role";
REVOKE ALL ON FUNCTION "public"."send_chat_message"(p_target_type text, p_content text, p_reply_to_message_id uuid) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."send_chat_message"(p_target_type text, p_content text, p_reply_to_message_id uuid) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."send_chat_message"(p_target_type text, p_content text, p_reply_to_message_id uuid) TO "service_role";
REVOKE ALL ON FUNCTION "public"."send_direct_message"(p_recipient_id uuid, p_message text) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."send_direct_message"(p_recipient_id uuid, p_message text) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."send_direct_message"(p_recipient_id uuid, p_message text) TO "service_role";
REVOKE ALL ON FUNCTION "public"."send_friend_request"(p_receiver_id uuid) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."send_friend_request"(p_receiver_id uuid) TO "service_role";
GRANT EXECUTE ON FUNCTION "public"."send_friend_request"(p_receiver_id uuid) TO "authenticated";
REVOKE ALL ON FUNCTION "public"."send_friend_request"(p_user_id uuid, p_friend_id uuid) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."send_friend_request"(p_user_id uuid, p_friend_id uuid) TO "service_role";
REVOKE ALL ON FUNCTION "public"."send_friend_request_core_20260823"(p_receiver_id uuid) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."send_friend_request_core_20260823"(p_receiver_id uuid) TO "service_role";
REVOKE ALL ON FUNCTION "public"."set_character_equipment"(p_character_id uuid, p_equipment_id uuid, p_slot_index integer) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."set_character_equipment"(p_character_id uuid, p_equipment_id uuid, p_slot_index integer) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."set_character_equipment"(p_character_id uuid, p_equipment_id uuid, p_slot_index integer) TO "service_role";
REVOKE ALL ON FUNCTION "public"."set_character_equipment_bulk"(p_character_id uuid, p_equipment_ids uuid[], p_slot_indexes integer[]) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."set_character_equipment_bulk"(p_character_id uuid, p_equipment_ids uuid[], p_slot_indexes integer[]) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."set_character_equipment_bulk"(p_character_id uuid, p_equipment_ids uuid[], p_slot_indexes integer[]) TO "service_role";
REVOKE ALL ON FUNCTION "public"."set_current_guild_welcome_message"(p_message text) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."set_current_guild_welcome_message"(p_message text) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."set_current_guild_welcome_message"(p_message text) TO "service_role";
REVOKE ALL ON FUNCTION "public"."set_guild_member_role"(p_guild_id uuid, p_target_user_id uuid, p_new_role text) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."set_guild_member_role"(p_guild_id uuid, p_target_user_id uuid, p_new_role text) TO "service_role";
GRANT EXECUTE ON FUNCTION "public"."set_guild_member_role"(p_guild_id uuid, p_target_user_id uuid, p_new_role text) TO "authenticated";
REVOKE ALL ON FUNCTION "public"."start_raid_battle"(p_instance_id uuid, p_character_ids text[], p_tactic text) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."start_raid_battle"(p_instance_id uuid, p_character_ids text[], p_tactic text) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."start_raid_battle"(p_instance_id uuid, p_character_ids text[], p_tactic text) TO "service_role";
REVOKE ALL ON FUNCTION "public"."snapshot_gvg_match_members"(p_match_session_id uuid) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."snapshot_gvg_match_members"(p_match_session_id uuid) TO "anon";
GRANT EXECUTE ON FUNCTION "public"."snapshot_gvg_match_members"(p_match_session_id uuid) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."snapshot_gvg_match_members"(p_match_session_id uuid) TO "service_role";
REVOKE ALL ON FUNCTION "public"."soft_reset_pvp_ratings"() FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."soft_reset_pvp_ratings"() TO "service_role";
REVOKE ALL ON FUNCTION "public"."start_patrol"(p_course_id text, p_character_id text) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."start_patrol"(p_course_id text, p_character_id text) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."start_patrol"(p_course_id text, p_character_id text) TO "service_role";
REVOKE ALL ON FUNCTION "public"."start_patrol_v2"(p_user_id uuid, p_course_id text, p_character_id text, p_duration_seconds integer, p_cost_vitality integer, p_battle_chance numeric) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."start_patrol_v2"(p_user_id uuid, p_course_id text, p_character_id text, p_duration_seconds integer, p_cost_vitality integer, p_battle_chance numeric) TO "anon";
GRANT EXECUTE ON FUNCTION "public"."start_patrol_v2"(p_user_id uuid, p_course_id text, p_character_id text, p_duration_seconds integer, p_cost_vitality integer, p_battle_chance numeric) TO "service_role";
REVOKE ALL ON FUNCTION "public"."start_pvp_battle"(p_opponent_user_id uuid, p_character_ids text[], p_tactic text) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."start_pvp_battle"(p_opponent_user_id uuid, p_character_ids text[], p_tactic text) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."start_pvp_battle"(p_opponent_user_id uuid, p_character_ids text[], p_tactic text) TO "service_role";
REVOKE ALL ON FUNCTION "public"."start_tutorial_progress"() FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."start_tutorial_progress"() TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."start_tutorial_progress"() TO "service_role";
REVOKE ALL ON FUNCTION "public"."sync_and_evaluate_raid_timeout"(p_user_id uuid) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."sync_and_evaluate_raid_timeout"(p_user_id uuid) TO "service_role";
REVOKE ALL ON FUNCTION "public"."sync_and_recover_vitality_and_pvp_points"(p_user_id uuid) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."sync_and_recover_vitality_and_pvp_points"(p_user_id uuid) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."sync_and_recover_vitality_and_pvp_points"(p_user_id uuid) TO "service_role";
REVOKE ALL ON FUNCTION "public"."sync_current_missions"() FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."sync_current_missions"() TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."sync_current_missions"() TO "service_role";
REVOKE ALL ON FUNCTION "public"."sync_legacy_guild_cosmetics"(p_guild_id uuid) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."sync_legacy_guild_cosmetics"(p_guild_id uuid) TO "anon";
GRANT EXECUTE ON FUNCTION "public"."sync_legacy_guild_cosmetics"(p_guild_id uuid) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."sync_legacy_guild_cosmetics"(p_guild_id uuid) TO "service_role";
REVOKE ALL ON FUNCTION "public"."sync_legacy_user_cosmetics"() FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."sync_legacy_user_cosmetics"() TO "anon";
GRANT EXECUTE ON FUNCTION "public"."sync_legacy_user_cosmetics"() TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."sync_legacy_user_cosmetics"() TO "service_role";
REVOKE ALL ON FUNCTION "public"."transfer_guild_leader"(p_guild_id uuid, p_old_id uuid, p_new_id uuid) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."transfer_guild_leader"(p_guild_id uuid, p_old_id uuid, p_new_id uuid) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."transfer_guild_leader"(p_guild_id uuid, p_old_id uuid, p_new_id uuid) TO "service_role";
REVOKE ALL ON FUNCTION "public"."unequip_character_equipment"(p_equipment_id uuid) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."unequip_character_equipment"(p_equipment_id uuid) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."unequip_character_equipment"(p_equipment_id uuid) TO "service_role";
REVOKE ALL ON FUNCTION "public"."unequip_character_equipment_bulk"(p_character_id uuid) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."unequip_character_equipment_bulk"(p_character_id uuid) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."unequip_character_equipment_bulk"(p_character_id uuid) TO "service_role";
REVOKE ALL ON FUNCTION "public"."unequip_character_skill"(p_skill_id uuid) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."unequip_character_skill"(p_skill_id uuid) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."unequip_character_skill"(p_skill_id uuid) TO "service_role";
REVOKE ALL ON FUNCTION "public"."unequip_gear_bulk"(p_character_id text, p_user_id uuid) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."unequip_gear_bulk"(p_character_id text, p_user_id uuid) TO "service_role";
REVOKE ALL ON FUNCTION "public"."unequip_skill_bulk"(p_character_id text, p_user_id uuid) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."unequip_skill_bulk"(p_character_id text, p_user_id uuid) TO "service_role";
REVOKE ALL ON FUNCTION "public"."unlock_eligible_user_cosmetics"() FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."unlock_eligible_user_cosmetics"() TO "anon";
GRANT EXECUTE ON FUNCTION "public"."unlock_eligible_user_cosmetics"() TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."unlock_eligible_user_cosmetics"() TO "service_role";
REVOKE ALL ON FUNCTION "public"."update_favorite_character"(p_user_id uuid, p_character_id text) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."update_favorite_character"(p_user_id uuid, p_character_id text) TO "service_role";
REVOKE ALL ON FUNCTION "public"."update_guild_alignment"(p_guild_id uuid, p_main text, p_sub text) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."update_guild_alignment"(p_guild_id uuid, p_main text, p_sub text) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."update_guild_alignment"(p_guild_id uuid, p_main text, p_sub text) TO "service_role";
REVOKE ALL ON FUNCTION "public"."update_guild_recruitment"(p_guild_id uuid, p_mode text, p_description text) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."update_guild_recruitment"(p_guild_id uuid, p_mode text, p_description text) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."update_guild_recruitment"(p_guild_id uuid, p_mode text, p_description text) TO "service_role";
REVOKE ALL ON FUNCTION "public"."update_guild_settings"(p_guild_id uuid, p_desc text, p_approval boolean, p_kick_days integer) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."update_guild_settings"(p_guild_id uuid, p_desc text, p_approval boolean, p_kick_days integer) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."update_guild_settings"(p_guild_id uuid, p_desc text, p_approval boolean, p_kick_days integer) TO "service_role";
REVOKE ALL ON FUNCTION "public"."upgrade_gear"(p_user_id uuid, p_equipment_id uuid, p_exp_item_id text, p_count integer, p_cash_cost integer) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."upgrade_gear"(p_user_id uuid, p_equipment_id uuid, p_exp_item_id text, p_count integer, p_cash_cost integer) TO "service_role";
REVOKE ALL ON FUNCTION "public"."use_action_resource_ticket"(p_item_id text) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."use_action_resource_ticket"(p_item_id text) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."use_action_resource_ticket"(p_item_id text) TO "service_role";
REVOKE ALL ON FUNCTION "public"."use_energy_drink"() FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."use_energy_drink"() TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."use_energy_drink"() TO "service_role";
REVOKE ALL ON FUNCTION "public"."use_energy_drink"(p_user_id uuid) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."use_energy_drink"(p_user_id uuid) TO "service_role";
REVOKE ALL ON FUNCTION "public"."use_inventory_item"(p_user_id uuid, p_item_id text, p_quantity integer, p_vitality_gain integer) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."use_inventory_item"(p_user_id uuid, p_item_id text, p_quantity integer, p_vitality_gain integer) TO "service_role";
REVOKE ALL ON FUNCTION "public"."validate_official_battle_result"(p_result jsonb) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."validate_official_battle_result"(p_result jsonb) TO "service_role";
REVOKE ALL ON FUNCTION "public"."kpi_ensure_subject"(p_user_id uuid, p_registered_at timestamp with time zone, p_registration_type text) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."kpi_ensure_subject"(p_user_id uuid, p_registered_at timestamp with time zone, p_registration_type text) TO "service_role";
REVOKE ALL ON FUNCTION "public"."on_kpi_user_created"() FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."on_kpi_user_created"() TO "service_role";
REVOKE ALL ON FUNCTION "public"."on_kpi_user_detaching"() FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."on_kpi_user_detaching"() TO "service_role";
REVOKE ALL ON FUNCTION "public"."on_kpi_auth_method_created"() FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."on_kpi_auth_method_created"() TO "service_role";
REVOKE ALL ON FUNCTION "public"."kpi_record_daily_activity"(p_user_id uuid, p_occurred_at timestamp with time zone) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."kpi_record_daily_activity"(p_user_id uuid, p_occurred_at timestamp with time zone) TO "service_role";
REVOKE ALL ON FUNCTION "public"."on_kpi_tutorial_complete"() FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."on_kpi_tutorial_complete"() TO "service_role";
REVOKE ALL ON FUNCTION "public"."on_kpi_gacha_completed"() FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."on_kpi_gacha_completed"() TO "service_role";
REVOKE ALL ON FUNCTION "public"."kpi_v249_metadata_valid"(p_metadata jsonb) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."kpi_v249_metadata_valid"(p_metadata jsonb) TO "service_role";
REVOKE ALL ON FUNCTION "public"."issue_kpi_mypage_ready_context_v1"(p_tutorial_version text, p_idempotency_key text, p_source text) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."issue_kpi_mypage_ready_context_v1"(p_tutorial_version text, p_idempotency_key text, p_source text) TO "authenticated";
REVOKE ALL ON FUNCTION "public"."acknowledge_kpi_first_mypage_access_v1"(p_context_id uuid, p_idempotency_key text) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."acknowledge_kpi_first_mypage_access_v1"(p_context_id uuid, p_idempotency_key text) TO "authenticated";
REVOKE ALL ON FUNCTION "public"."raid_room_projection_v1"(p_room_id uuid) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."raid_room_projection_v1"(p_room_id uuid) TO "service_role";
REVOKE ALL ON FUNCTION "public"."get_raid_room_v1"(p_room_id uuid) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."get_raid_room_v1"(p_room_id uuid) TO "service_role";
GRANT EXECUTE ON FUNCTION "public"."get_raid_room_v1"(p_room_id uuid) TO "authenticated";
REVOKE ALL ON FUNCTION "public"."finalize_expired_raid_instance"(p_instance_id uuid) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."finalize_expired_raid_instance"(p_instance_id uuid) TO "service_role";
REVOKE ALL ON FUNCTION "public"."grant_canonical_raid_day_clear_reward"(p_instance_id uuid, p_user_id uuid) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."grant_canonical_raid_day_clear_reward"(p_instance_id uuid, p_user_id uuid) TO "service_role";
REVOKE ALL ON FUNCTION "public"."sync_active_users"() FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."sync_active_users"() TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."sync_active_users"() TO "service_role";
REVOKE ALL ON FUNCTION "public"."on_kpi_guild_member_joined"() FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."on_kpi_guild_member_joined"() TO "service_role";
REVOKE ALL ON FUNCTION "public"."on_kpi_guild_member_leaving"() FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."on_kpi_guild_member_leaving"() TO "service_role";
REVOKE ALL ON FUNCTION "public"."enforce_kpi_classification_no_overlap"() FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."enforce_kpi_classification_no_overlap"() TO "service_role";
REVOKE ALL ON FUNCTION "public"."kpi_jst_day_start"(p_date date) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."kpi_jst_day_start"(p_date date) TO "service_role";
REVOKE ALL ON FUNCTION "public"."kpi_is_subject_excluded"(p_subject_id uuid, p_at timestamp with time zone) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."kpi_is_subject_excluded"(p_subject_id uuid, p_at timestamp with time zone) TO "service_role";
REVOKE ALL ON FUNCTION "public"."refresh_kpi_acquisition"(p_run_id uuid, p_period_type text, p_period_start date, p_period_end date, p_watermark timestamp with time zone) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."refresh_kpi_acquisition"(p_run_id uuid, p_period_type text, p_period_start date, p_period_end date, p_watermark timestamp with time zone) TO "service_role";
REVOKE ALL ON FUNCTION "public"."refresh_kpi_active_retention"(p_run_id uuid, p_period_type text, p_period_start date, p_period_end date, p_watermark timestamp with time zone) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."refresh_kpi_active_retention"(p_run_id uuid, p_period_type text, p_period_start date, p_period_end date, p_watermark timestamp with time zone) TO "service_role";
REVOKE ALL ON FUNCTION "public"."refresh_kpi_guild"(p_run_id uuid, p_period_type text, p_period_start date, p_period_end date, p_watermark timestamp with time zone) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."refresh_kpi_guild"(p_run_id uuid, p_period_type text, p_period_start date, p_period_end date, p_watermark timestamp with time zone) TO "service_role";
REVOKE ALL ON FUNCTION "public"."refresh_kpi_content"(p_run_id uuid, p_period_type text, p_period_start date, p_period_end date, p_watermark timestamp with time zone) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."refresh_kpi_content"(p_run_id uuid, p_period_type text, p_period_start date, p_period_end date, p_watermark timestamp with time zone) TO "service_role";
REVOKE ALL ON FUNCTION "public"."refresh_kpi_revenue"(p_run_id uuid, p_period_type text, p_period_start date, p_period_end date) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."refresh_kpi_revenue"(p_run_id uuid, p_period_type text, p_period_start date, p_period_end date) TO "service_role";
REVOKE ALL ON FUNCTION "public"."get_latest_kpi_snapshots"(p_category text, p_period_type text, p_period_start date, p_period_end date) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."get_latest_kpi_snapshots"(p_category text, p_period_type text, p_period_start date, p_period_end date) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."get_latest_kpi_snapshots"(p_category text, p_period_type text, p_period_start date, p_period_end date) TO "service_role";
REVOKE ALL ON FUNCTION "public"."get_kpi_refresh_run"(p_run_id uuid) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."get_kpi_refresh_run"(p_run_id uuid) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."get_kpi_refresh_run"(p_run_id uuid) TO "service_role";
REVOKE ALL ON FUNCTION "public"."refresh_kpi_active_timeseries_v2"(p_run_id uuid, p_period_type text, p_period_start date, p_period_end date, p_watermark timestamp with time zone) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."refresh_kpi_active_timeseries_v2"(p_run_id uuid, p_period_type text, p_period_start date, p_period_end date, p_watermark timestamp with time zone) TO "service_role";
REVOKE ALL ON FUNCTION "public"."bind_kpi_acquisition_subject_v1"(p_token text, p_source text) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."bind_kpi_acquisition_subject_v1"(p_token text, p_source text) TO "authenticated";
REVOKE ALL ON FUNCTION "public"."refresh_kpi_overview_saved_results"(p_today date) FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON FUNCTION "public"."_raid_room_add_member_v1"(p_room_id uuid, p_user_id uuid) FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON FUNCTION "public"."create_raid_room_v1"(p_difficulty_id text, p_raid_variant_id text, p_request_id uuid) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."create_raid_room_v1"(p_difficulty_id text, p_raid_variant_id text, p_request_id uuid) TO "authenticated";
REVOKE ALL ON FUNCTION "public"."get_preopen_guild_power_ranking"(p_limit integer, p_offset integer) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."get_preopen_guild_power_ranking"(p_limit integer, p_offset integer) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."get_preopen_guild_power_ranking"(p_limit integer, p_offset integer) TO "service_role";
REVOKE ALL ON FUNCTION "public"."refresh_kpi_snapshots"(p_category text, p_period_type text, p_period_start date, p_period_end date, p_requested_by uuid) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."refresh_kpi_snapshots"(p_category text, p_period_type text, p_period_start date, p_period_end date, p_requested_by uuid) TO "service_role";
REVOKE ALL ON FUNCTION "public"."refresh_kpi_acquisition_v2"(p_run_id uuid, p_period_type text, p_period_start date, p_period_end date, p_watermark timestamp with time zone) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."refresh_kpi_acquisition_v2"(p_run_id uuid, p_period_type text, p_period_start date, p_period_end date, p_watermark timestamp with time zone) TO "service_role";
REVOKE ALL ON FUNCTION "public"."refresh_kpi_guild_timeseries_v2"(p_run_id uuid, p_period_type text, p_period_start date, p_period_end date, p_watermark timestamp with time zone) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."refresh_kpi_guild_timeseries_v2"(p_run_id uuid, p_period_type text, p_period_start date, p_period_end date, p_watermark timestamp with time zone) TO "service_role";
REVOKE ALL ON FUNCTION "public"."kpi_v249_current_subject"() FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON FUNCTION "public"."begin_kpi_acquisition_journey_v1"(p_token text, p_source text) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."begin_kpi_acquisition_journey_v1"(p_token text, p_source text) TO "anon";
GRANT EXECUTE ON FUNCTION "public"."begin_kpi_acquisition_journey_v1"(p_token text, p_source text) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."begin_kpi_acquisition_journey_v1"(p_token text, p_source text) TO "service_role";
REVOKE ALL ON FUNCTION "public"."record_kpi_acquisition_observation_v1"(p_token text, p_event_type text, p_idempotency_key text, p_metadata jsonb, p_source text) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."record_kpi_acquisition_observation_v1"(p_token text, p_event_type text, p_idempotency_key text, p_metadata jsonb, p_source text) TO "anon";
GRANT EXECUTE ON FUNCTION "public"."record_kpi_acquisition_observation_v1"(p_token text, p_event_type text, p_idempotency_key text, p_metadata jsonb, p_source text) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."record_kpi_acquisition_observation_v1"(p_token text, p_event_type text, p_idempotency_key text, p_metadata jsonb, p_source text) TO "service_role";
REVOKE ALL ON FUNCTION "public"."record_kpi_subject_identity_transition_v1"(p_from_subject_id uuid, p_to_subject_id uuid, p_transition_type text, p_context_id uuid, p_idempotency_key text, p_metadata jsonb, p_source text) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."record_kpi_subject_identity_transition_v1"(p_from_subject_id uuid, p_to_subject_id uuid, p_transition_type text, p_context_id uuid, p_idempotency_key text, p_metadata jsonb, p_source text) TO "service_role";
REVOKE ALL ON FUNCTION "public"."on_kpi_v249_guild_member_joined"() FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON FUNCTION "public"."on_kpi_v249_guild_chat_message"() FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON FUNCTION "public"."create_kpi_marketing_import_batch_v1"(p_source text, p_actor_identifier uuid, p_file_hash text, p_idempotency_key text, p_metadata jsonb) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."create_kpi_marketing_import_batch_v1"(p_source text, p_actor_identifier uuid, p_file_hash text, p_idempotency_key text, p_metadata jsonb) TO "service_role";
REVOKE ALL ON FUNCTION "public"."record_kpi_marketing_daily_revision_v1"(p_batch_id uuid, p_report_date_jst date, p_account_key text, p_campaign_key text, p_campaign_name text, p_line_item_key text, p_line_item_name text, p_creative_key text, p_creative_name text, p_reporting_grain text, p_spend numeric, p_currency text, p_impressions bigint, p_clicks bigint, p_external_key text, p_revision integer, p_idempotency_key text, p_metadata jsonb) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."record_kpi_marketing_daily_revision_v1"(p_batch_id uuid, p_report_date_jst date, p_account_key text, p_campaign_key text, p_campaign_name text, p_line_item_key text, p_line_item_name text, p_creative_key text, p_creative_name text, p_reporting_grain text, p_spend numeric, p_currency text, p_impressions bigint, p_clicks bigint, p_external_key text, p_revision integer, p_idempotency_key text, p_metadata jsonb) TO "service_role";
REVOKE ALL ON FUNCTION "public"."kpi_v250_landing_metadata_valid"(p_metadata jsonb) FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON FUNCTION "public"."record_kpi_acquisition_landing_v1"(p_token text, p_metadata jsonb, p_source text) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."record_kpi_acquisition_landing_v1"(p_token text, p_metadata jsonb, p_source text) TO "anon";
GRANT EXECUTE ON FUNCTION "public"."record_kpi_acquisition_landing_v1"(p_token text, p_metadata jsonb, p_source text) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."record_kpi_acquisition_landing_v1"(p_token text, p_metadata jsonb, p_source text) TO "service_role";
REVOKE ALL ON FUNCTION "public"."kpi_overview_saved_rate"(n bigint, d bigint, t numeric, r text) FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON FUNCTION "public"."kpi_guard_acquisition_first_touch"() FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON FUNCTION "public"."bind_kpi_acquisition_subject_v2"(p_tokens text[], p_source text) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."bind_kpi_acquisition_subject_v2"(p_tokens text[], p_source text) TO "authenticated";
REVOKE ALL ON FUNCTION "public"."kpi_source_rate_v1"(n bigint, d bigint, r text) FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON FUNCTION "public"."kpi_daily_engagement_v1"(p_from date, p_to date) FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON FUNCTION "public"."raid_room_can_read_v1"(p_room_id uuid) FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON FUNCTION "public"."list_raid_rooms_v1"(p_difficulty_id text, p_limit integer, p_offset integer) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."list_raid_rooms_v1"(p_difficulty_id text, p_limit integer, p_offset integer) TO "service_role";
GRANT EXECUTE ON FUNCTION "public"."list_raid_rooms_v1"(p_difficulty_id text, p_limit integer, p_offset integer) TO "authenticated";
REVOKE ALL ON FUNCTION "public"."get_raid_room_participants_v1"(p_room_id uuid, p_limit integer, p_offset integer) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."get_raid_room_participants_v1"(p_room_id uuid, p_limit integer, p_offset integer) TO "service_role";
GRANT EXECUTE ON FUNCTION "public"."get_raid_room_participants_v1"(p_room_id uuid, p_limit integer, p_offset integer) TO "authenticated";
REVOKE ALL ON FUNCTION "public"."_raid_room_power_gate_v1"(p_difficulty text, p_power bigint) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."_raid_room_power_gate_v1"(p_difficulty text, p_power bigint) TO "service_role";
REVOKE ALL ON FUNCTION "public"."_raid_room_rescue_gate_v1"(p_difficulty text, p_via_rescue boolean, p_finalized_battles bigint, p_contribution_damage bigint, p_room_cleared boolean) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."_raid_room_rescue_gate_v1"(p_difficulty text, p_via_rescue boolean, p_finalized_battles bigint, p_contribution_damage bigint, p_room_cleared boolean) TO "service_role";
REVOKE ALL ON FUNCTION "public"."_raid_room_register_v1"(p_instance_id uuid, p_owner_user_id uuid, p_difficulty_id text) FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON FUNCTION "public"."get_raid_room_briefing_v1"(p_room_id uuid) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."get_raid_room_briefing_v1"(p_room_id uuid) TO "authenticated";
REVOKE ALL ON FUNCTION "public"."register_raid_room_v1"(p_room_id uuid) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."register_raid_room_v1"(p_room_id uuid) TO "authenticated";
REVOKE ALL ON FUNCTION "public"."start_raid_room_battle_v1"(p_room_id uuid, p_character_ids text[], p_tactic text, p_request_id uuid) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."start_raid_room_battle_v1"(p_room_id uuid, p_character_ids text[], p_tactic text, p_request_id uuid) TO "authenticated";
REVOKE ALL ON FUNCTION "public"."get_raid_battle_route_v1"(p_replay_id uuid) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."get_raid_battle_route_v1"(p_replay_id uuid) TO "service_role";
REVOKE ALL ON FUNCTION "public"."finalize_expired_raid_room_v1"(p_room_id uuid) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."finalize_expired_raid_room_v1"(p_room_id uuid) TO "service_role";
REVOKE ALL ON FUNCTION "public"."finalize_raid_room_battle_v1"(p_replay_id uuid, p_result jsonb) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."finalize_raid_room_battle_v1"(p_replay_id uuid, p_result jsonb) TO "service_role";
REVOKE ALL ON FUNCTION "public"."get_raid_room_battle_result_v1"(p_replay_id uuid) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."get_raid_room_battle_result_v1"(p_replay_id uuid) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."get_raid_room_battle_result_v1"(p_replay_id uuid) TO "service_role";
REVOKE ALL ON FUNCTION "public"."get_raid_room_battle_start_receipt_v1"(p_request_id uuid) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."get_raid_room_battle_start_receipt_v1"(p_request_id uuid) TO "authenticated";
REVOKE ALL ON FUNCTION "public"."finalize_expired_raid_rooms_v1"(p_limit integer) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."finalize_expired_raid_rooms_v1"(p_limit integer) TO "service_role";
REVOKE ALL ON FUNCTION "public"."list_raid_room_battle_recoveries_v1"(p_limit integer) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."list_raid_room_battle_recoveries_v1"(p_limit integer) TO "authenticated";
REVOKE ALL ON FUNCTION "public"."acknowledge_raid_room_battle_recovery_v1"(p_request_id uuid) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."acknowledge_raid_room_battle_recovery_v1"(p_request_id uuid) TO "authenticated";
REVOKE ALL ON FUNCTION "public"."get_raid_room_rescue_v1"(p_rescue_id uuid) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."get_raid_room_rescue_v1"(p_rescue_id uuid) TO "authenticated";
REVOKE ALL ON FUNCTION "public"."get_raid_room_rescue_status_v1"(p_room_id uuid) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."get_raid_room_rescue_status_v1"(p_room_id uuid) TO "authenticated";
REVOKE ALL ON FUNCTION "public"."_raid_room_rescue_reward_progress_v1"(p_room_id uuid, p_user_id uuid) FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON FUNCTION "public"."on_raid_room_rescue_reward_finalized_v1"() FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON FUNCTION "public"."get_active_raids"() FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."get_active_raids"() TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."get_active_raids"() TO "service_role";
REVOKE ALL ON FUNCTION "public"."grant_canonical_raid_reward"(p_instance uuid, p_user uuid, p_type text, p_key text) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."grant_canonical_raid_reward"(p_instance uuid, p_user uuid, p_type text, p_key text) TO "service_role";
REVOKE ALL ON FUNCTION "public"."grant_canonical_ranking_season_reward"(p_season_id uuid, p_category text, p_recipient_user_id uuid, p_ranked_entity_id uuid, p_rank_position integer) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."grant_canonical_ranking_season_reward"(p_season_id uuid, p_category text, p_recipient_user_id uuid, p_ranked_entity_id uuid, p_rank_position integer) TO "service_role";
REVOKE ALL ON FUNCTION "public"."grant_raid_reward"(p_instance_id uuid, p_user_id uuid, p_reward_id integer, p_reason text) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."grant_raid_reward"(p_instance_id uuid, p_user_id uuid, p_reward_id integer, p_reason text) TO "service_role";
REVOKE ALL ON FUNCTION "public"."respawn_cleared_raid_slot"(p_cleared_instance_id uuid) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."respawn_cleared_raid_slot"(p_cleared_instance_id uuid) TO "service_role";
REVOKE ALL ON FUNCTION "public"."rotate_daily_raids"() FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."rotate_daily_raids"() TO "service_role";
REVOKE ALL ON FUNCTION "public"."list_raid_room_boss_choices_v1"() FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."list_raid_room_boss_choices_v1"() TO "authenticated";
REVOKE ALL ON FUNCTION "public"."cancel_raid_room_battle_request_v1"(p_request_id uuid) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."cancel_raid_room_battle_request_v1"(p_request_id uuid) TO "authenticated";
REVOKE ALL ON FUNCTION "public"."request_raid_room_rescue_v1"(p_room_id uuid, p_request_id uuid) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."request_raid_room_rescue_v1"(p_room_id uuid, p_request_id uuid) TO "authenticated";
REVOKE ALL ON FUNCTION "public"."join_raid_room_rescue_v1"(p_rescue_id uuid) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."join_raid_room_rescue_v1"(p_rescue_id uuid) TO "authenticated";
REVOKE ALL ON FUNCTION "public"."get_my_raid_contribution_v1"(p_instance_id uuid) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."get_my_raid_contribution_v1"(p_instance_id uuid) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."get_my_raid_contribution_v1"(p_instance_id uuid) TO "service_role";
REVOKE ALL ON FUNCTION "public"."on_raid_room_clear_reward_finalized_v1"() FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON FUNCTION "public"."get_raid_room_clear_reward_v1"(p_room_id uuid) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."get_raid_room_clear_reward_v1"(p_room_id uuid) TO "authenticated";
REVOKE ALL ON FUNCTION "private"."raid_daily_targets_v1"() FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON FUNCTION "private"."raid_top_snapshot_v1"() FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "private"."raid_top_snapshot_v1"() TO "authenticated";
REVOKE ALL ON FUNCTION "public"."get_raid_top_v1"() FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."get_raid_top_v1"() TO "authenticated";
REVOKE ALL ON FUNCTION "private"."raid_room_display_v1"(p_room_id uuid) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "private"."raid_room_display_v1"(p_room_id uuid) TO "authenticated";
REVOKE ALL ON FUNCTION "public"."get_raid_room_display_v1"(p_room_id uuid) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."get_raid_room_display_v1"(p_room_id uuid) TO "authenticated";
REVOKE ALL ON FUNCTION "private"."raid_page_entry_v1"(p_room_id uuid, p_rescue_id uuid) FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON FUNCTION "public"."on_post_tutorial_manual_loadout"() FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."on_post_tutorial_manual_loadout"() TO "service_role";
REVOKE ALL ON FUNCTION "private"."raid_browse_page_v1"(p_difficulty_id text, p_offset integer) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "private"."raid_browse_page_v1"(p_difficulty_id text, p_offset integer) TO "authenticated";
REVOKE ALL ON FUNCTION "private"."raid_rescue_cards_v1"(p_rescue_ids uuid[]) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "private"."raid_rescue_cards_v1"(p_rescue_ids uuid[]) TO "authenticated";
REVOKE ALL ON FUNCTION "private"."raid_enemy_info_v1"(p_variant_id text, p_difficulty_id text) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "private"."raid_enemy_info_v1"(p_variant_id text, p_difficulty_id text) TO "authenticated";
REVOKE ALL ON FUNCTION "public"."list_raid_room_cards_v1"(p_difficulty_id text, p_offset integer) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."list_raid_room_cards_v1"(p_difficulty_id text, p_offset integer) TO "authenticated";
REVOKE ALL ON FUNCTION "public"."get_raid_rescue_cards_v1"(p_rescue_ids uuid[]) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."get_raid_rescue_cards_v1"(p_rescue_ids uuid[]) TO "authenticated";
REVOKE ALL ON FUNCTION "public"."get_raid_enemy_info_v1"(p_variant_id text, p_difficulty_id text) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."get_raid_enemy_info_v1"(p_variant_id text, p_difficulty_id text) TO "authenticated";
REVOKE ALL ON FUNCTION "private"."ensure_initial_equipment_v1"() FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "private"."ensure_initial_equipment_v1"() TO "authenticated";
REVOKE ALL ON FUNCTION "public"."ensure_initial_equipment_v1"() FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."ensure_initial_equipment_v1"() TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."ensure_initial_equipment_v1"() TO "service_role";
REVOKE ALL ON FUNCTION "public"."_raid_room_launch_enemy_snapshot_v1"(p_profile jsonb, p_instance uuid, p_max_hp bigint) FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON FUNCTION "public"."request_kpi_overview_saved_refresh"(p_today date) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."request_kpi_overview_saved_refresh"(p_today date) TO "service_role";
REVOKE ALL ON FUNCTION "public"."on_raid_boss_defeated_activity"() FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."on_raid_boss_defeated_activity"() TO "service_role";
REVOKE ALL ON FUNCTION "public"."on_short_tutorial_character_setup_eligible"() FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."on_short_tutorial_character_setup_eligible"() TO "service_role";
REVOKE ALL ON FUNCTION "public"."resume_short_tutorial"() FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."resume_short_tutorial"() TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."resume_short_tutorial"() TO "service_role";
REVOKE ALL ON FUNCTION "private"."apply_recommended_main_equipment_v1"(p_user_id uuid) FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON FUNCTION "public"."get_character_setup_dialog_state"() FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."get_character_setup_dialog_state"() TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."get_character_setup_dialog_state"() TO "service_role";
REVOKE ALL ON FUNCTION "public"."complete_character_setup_dialog"(p_action text) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."complete_character_setup_dialog"(p_action text) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."complete_character_setup_dialog"(p_action text) TO "service_role";
REVOKE ALL ON FUNCTION "public"."get_beginner_mission_journey"() FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."get_beginner_mission_journey"() TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."get_beginner_mission_journey"() TO "service_role";
REVOKE ALL ON FUNCTION "public"."quest_town_key"(p_value text) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."quest_town_key"(p_value text) TO PUBLIC;
GRANT EXECUTE ON FUNCTION "public"."quest_town_key"(p_value text) TO "anon";
GRANT EXECUTE ON FUNCTION "public"."quest_town_key"(p_value text) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."quest_town_key"(p_value text) TO "service_role";
REVOKE ALL ON FUNCTION "public"."quest_hometown_snapshot"(p_user uuid, p_character text, p_course text) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."quest_hometown_snapshot"(p_user uuid, p_character text, p_course text) TO "service_role";
REVOKE ALL ON FUNCTION "public"."on_quest_hometown_snapshot"() FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."on_quest_hometown_snapshot"() TO "service_role";
REVOKE ALL ON FUNCTION "public"."advance_tutorial_progress"(p_expected_step text, p_next_step text) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."advance_tutorial_progress"(p_expected_step text, p_next_step text) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."advance_tutorial_progress"(p_expected_step text, p_next_step text) TO "service_role";
REVOKE ALL ON FUNCTION "public"."apply_tutorial_enemy_snapshot"(p_user_id uuid, p_player_snapshot jsonb, p_enemy_snapshot jsonb) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."apply_tutorial_enemy_snapshot"(p_user_id uuid, p_player_snapshot jsonb, p_enemy_snapshot jsonb) TO "service_role";
REVOKE ALL ON FUNCTION "public"."apply_tutorial_player_snapshot"(p_user_id uuid, p_snapshot jsonb) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."apply_tutorial_player_snapshot"(p_user_id uuid, p_snapshot jsonb) TO "service_role";
REVOKE ALL ON FUNCTION "public"."complete_activation_mission_handoff"() FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."complete_activation_mission_handoff"() TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."complete_activation_mission_handoff"() TO "service_role";
REVOKE ALL ON FUNCTION "public"."complete_current_tutorial_formation"() FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."complete_current_tutorial_formation"() TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."complete_current_tutorial_formation"() TO "service_role";
REVOKE ALL ON FUNCTION "public"."execute_asset_gacha_core_20260812"(p_user_id uuid, p_gacha_id text, p_pull_count integer, p_currency_type text) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."execute_asset_gacha_core_20260812"(p_user_id uuid, p_gacha_id text, p_pull_count integer, p_currency_type text) TO "service_role";
REVOKE ALL ON FUNCTION "public"."get_recent_social_activity_feed"(p_limit integer) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."get_recent_social_activity_feed"(p_limit integer) TO "authenticated";
REVOKE ALL ON FUNCTION "public"."initialize_current_player"(p_username text) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."initialize_current_player"(p_username text) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."initialize_current_player"(p_username text) TO "service_role";
REVOKE ALL ON FUNCTION "public"."set_character_skill"(p_character_id uuid, p_skill_id uuid, p_slot_index integer) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."set_character_skill"(p_character_id uuid, p_skill_id uuid, p_slot_index integer) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."set_character_skill"(p_character_id uuid, p_skill_id uuid, p_slot_index integer) TO "service_role";
REVOKE ALL ON FUNCTION "public"."set_character_skill_loadout"(p_character_id uuid, p_skill_ids uuid[], p_slot_indexes integer[]) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."set_character_skill_loadout"(p_character_id uuid, p_skill_ids uuid[], p_slot_indexes integer[]) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."set_character_skill_loadout"(p_character_id uuid, p_skill_ids uuid[], p_slot_indexes integer[]) TO "service_role";
REVOKE ALL ON FUNCTION "public"."ensure_daily_raid_rooms_v1"() FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."ensure_daily_raid_rooms_v1"() TO "service_role";
REVOKE ALL ON FUNCTION "public"."prepare_current_tutorial_formation"() FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."prepare_current_tutorial_formation"() TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."prepare_current_tutorial_formation"() TO "service_role";
REVOKE ALL ON FUNCTION "public"."set_main_formation_leader"(p_character_id text) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."set_main_formation_leader"(p_character_id text) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."set_main_formation_leader"(p_character_id text) TO "service_role";
REVOKE ALL ON FUNCTION "public"."get_daily_free_gacha_rates"() FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."get_daily_free_gacha_rates"() TO "anon";
GRANT EXECUTE ON FUNCTION "public"."get_daily_free_gacha_rates"() TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."get_daily_free_gacha_rates"() TO "service_role";
REVOKE ALL ON FUNCTION "public"."draw_daily_free_gacha_rarity"(p_gacha_id text) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."draw_daily_free_gacha_rarity"(p_gacha_id text) TO "service_role";
REVOKE ALL ON FUNCTION "public"."execute_character_gacha"(p_user_id uuid, p_gacha_id text, p_pull_count integer, p_currency_type text, p_request_id uuid, p_rate_version text) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."execute_character_gacha"(p_user_id uuid, p_gacha_id text, p_pull_count integer, p_currency_type text, p_request_id uuid, p_rate_version text) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."execute_character_gacha"(p_user_id uuid, p_gacha_id text, p_pull_count integer, p_currency_type text, p_request_id uuid, p_rate_version text) TO "service_role";
REVOKE ALL ON FUNCTION "public"."execute_asset_gacha"(p_user_id uuid, p_gacha_id text, p_pull_count integer, p_currency_type text, p_request_id uuid, p_rate_version text) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."execute_asset_gacha"(p_user_id uuid, p_gacha_id text, p_pull_count integer, p_currency_type text, p_request_id uuid, p_rate_version text) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."execute_asset_gacha"(p_user_id uuid, p_gacha_id text, p_pull_count integer, p_currency_type text, p_request_id uuid, p_rate_version text) TO "service_role";
REVOKE ALL ON FUNCTION "public"."get_ranking_self_context"(p_category text, p_daily boolean) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."get_ranking_self_context"(p_category text, p_daily boolean) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."get_ranking_self_context"(p_category text, p_daily boolean) TO "service_role";
REVOKE ALL ON FUNCTION "public"."refresh_normal_mission_owned_state"(p_user_id uuid) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."refresh_normal_mission_owned_state"(p_user_id uuid) TO "service_role";
