SET check_function_bodies = false;
SET search_path = public, extensions, pg_catalog;
CREATE TRIGGER kpi_classification_no_overlap_trigger BEFORE INSERT OR UPDATE ON kpi_account_classification_periods FOR EACH ROW EXECUTE FUNCTION enforce_kpi_classification_no_overlap();
CREATE TRIGGER character_growth_funnel_trigger AFTER UPDATE ON user_characters FOR EACH ROW EXECUTE FUNCTION on_progression_growth_funnel();
CREATE TRIGGER monthly_power_cutoff_guard BEFORE INSERT OR DELETE OR UPDATE ON user_characters FOR EACH STATEMENT EXECUTE FUNCTION guard_monthly_power_season_cutoff();
CREATE TRIGGER operations_maintenance_gate BEFORE INSERT OR DELETE OR UPDATE ON user_characters FOR EACH ROW EXECUTE FUNCTION reject_mutation_during_maintenance();
CREATE TRIGGER user_character_power_projection_trigger AFTER INSERT OR DELETE OR UPDATE OF level, awakening_level ON user_characters FOR EACH ROW EXECUTE FUNCTION power_projection_owned_row_changed();
CREATE TRIGGER user_characters_preopen_power_cutoff_guard BEFORE INSERT OR DELETE OR UPDATE ON user_characters FOR EACH STATEMENT EXECUTE FUNCTION guard_preopen_guild_power_cutoff();
CREATE TRIGGER equipment_growth_funnel_trigger AFTER UPDATE ON user_equipments FOR EACH ROW EXECUTE FUNCTION on_progression_growth_funnel();
CREATE TRIGGER monthly_power_cutoff_guard BEFORE INSERT OR DELETE OR UPDATE ON user_equipments FOR EACH STATEMENT EXECUTE FUNCTION guard_monthly_power_season_cutoff();
CREATE TRIGGER operations_maintenance_gate BEFORE INSERT OR DELETE OR UPDATE ON user_equipments FOR EACH ROW EXECUTE FUNCTION reject_mutation_during_maintenance();
CREATE TRIGGER post_tutorial_manual_equipment_loadout AFTER UPDATE OF equipped_character_id ON user_equipments FOR EACH ROW EXECUTE FUNCTION on_post_tutorial_manual_loadout();
CREATE TRIGGER user_equipment_power_projection_trigger AFTER INSERT OR DELETE OR UPDATE OF level, plus_val, equipped_character_id, equipment_id, equipment_master_id ON user_equipments FOR EACH ROW EXECUTE FUNCTION power_projection_owned_row_changed();
CREATE TRIGGER user_equipments_preopen_power_cutoff_guard BEFORE INSERT OR DELETE OR UPDATE ON user_equipments FOR EACH STATEMENT EXECUTE FUNCTION guard_preopen_guild_power_cutoff();
CREATE TRIGGER kpi_journey_first_touch_immutable BEFORE UPDATE ON kpi_acquisition_journeys FOR EACH ROW EXECUTE FUNCTION kpi_guard_acquisition_first_touch();
CREATE TRIGGER monthly_power_cutoff_guard BEFORE INSERT OR DELETE OR UPDATE ON canonical_character_growth_exponents FOR EACH STATEMENT EXECUTE FUNCTION guard_monthly_power_season_cutoff();
CREATE TRIGGER monthly_power_cutoff_guard BEFORE INSERT OR DELETE OR UPDATE ON canonical_character_growth_assignments FOR EACH STATEMENT EXECUTE FUNCTION guard_monthly_power_season_cutoff();
CREATE TRIGGER kpi_binding_first_touch_immutable BEFORE DELETE OR UPDATE ON kpi_acquisition_subject_bindings FOR EACH ROW EXECUTE FUNCTION kpi_guard_acquisition_first_touch();
CREATE TRIGGER monthly_power_snapshot_immutable BEFORE INSERT OR DELETE OR UPDATE ON monthly_power_entity_snapshots FOR EACH ROW EXECUTE FUNCTION reject_monthly_power_snapshot_mutation();
CREATE TRIGGER monthly_power_snapshot_immutable BEFORE INSERT OR DELETE OR UPDATE ON monthly_power_member_snapshots FOR EACH ROW EXECUTE FUNCTION reject_monthly_power_snapshot_mutation();
CREATE TRIGGER monthly_power_snapshot_immutable BEFORE INSERT OR DELETE OR UPDATE ON monthly_power_honor_requirements FOR EACH ROW EXECUTE FUNCTION reject_monthly_power_snapshot_mutation();
CREATE TRIGGER quest_encounter_rescue_bonus AFTER INSERT ON raid_room_rescue_rewards FOR EACH ROW EXECUTE FUNCTION issue_quest_raid_encounter_bonus_v1();
CREATE TRIGGER quest_encounter_clear_bonus AFTER INSERT ON raid_room_clear_rewards FOR EACH ROW EXECUTE FUNCTION issue_quest_raid_encounter_bonus_v1();
CREATE TRIGGER canonical_character_preopen_power_cutoff_guard BEFORE INSERT OR DELETE OR UPDATE ON canonical_character_master FOR EACH STATEMENT EXECUTE FUNCTION guard_preopen_guild_power_cutoff();
CREATE TRIGGER monthly_power_cutoff_guard BEFORE INSERT OR DELETE OR UPDATE ON canonical_character_master FOR EACH STATEMENT EXECUTE FUNCTION guard_monthly_power_season_cutoff();
CREATE TRIGGER canonical_equipment_preopen_power_cutoff_guard BEFORE INSERT OR DELETE OR UPDATE ON canonical_equipment_master FOR EACH STATEMENT EXECUTE FUNCTION guard_preopen_guild_power_cutoff();
CREATE TRIGGER monthly_power_cutoff_guard BEFORE INSERT OR DELETE OR UPDATE ON canonical_equipment_master FOR EACH STATEMENT EXECUTE FUNCTION guard_monthly_power_season_cutoff();
CREATE TRIGGER canonical_guild_chat_exp_trigger AFTER INSERT ON board_posts FOR EACH ROW EXECUTE FUNCTION on_canonical_guild_chat_exp();
CREATE TRIGGER dispatch_guild_chat_mission_trigger AFTER INSERT ON board_posts FOR EACH ROW EXECUTE FUNCTION dispatch_guild_chat_mission();
CREATE TRIGGER guild_chat_activation_funnel_trigger AFTER INSERT ON board_posts FOR EACH ROW EXECUTE FUNCTION on_guild_chat_activation();
CREATE TRIGGER m9x_first_human_response_trigger AFTER INSERT ON board_posts FOR EACH ROW EXECUTE FUNCTION on_m9x_first_human_response();
CREATE TRIGGER zz_kpi_v249_guild_chat_message AFTER INSERT ON board_posts FOR EACH ROW EXECUTE FUNCTION on_kpi_v249_guild_chat_message();
CREATE TRIGGER canonical_daily_activity_finalized AFTER UPDATE OF finalization_status ON battle_replay_sessions FOR EACH ROW EXECUTE FUNCTION on_canonical_daily_activity_finalized();
CREATE TRIGGER canonical_guild_official_battle_exp_trigger AFTER UPDATE OF finalization_status ON battle_replay_sessions FOR EACH ROW EXECUTE FUNCTION on_canonical_guild_official_battle_exp();
CREATE TRIGGER daily_ranking_participation_finalized AFTER UPDATE OF finalization_status ON battle_replay_sessions FOR EACH ROW EXECUTE FUNCTION capture_daily_ranking_participation();
CREATE TRIGGER first_official_battle_funnel_trigger AFTER UPDATE OF status ON battle_replay_sessions FOR EACH ROW EXECUTE FUNCTION on_first_official_battle_funnel();
CREATE TRIGGER official_battle_funnel_trigger AFTER UPDATE OF finalization_status ON battle_replay_sessions FOR EACH ROW EXECUTE FUNCTION on_official_battle_funnel();
CREATE TRIGGER raid_room_clear_reward_finalized_v1 AFTER UPDATE OF finalization_status ON battle_replay_sessions FOR EACH ROW EXECUTE FUNCTION on_raid_room_clear_reward_finalized_v1();
CREATE TRIGGER raid_room_rescue_reward_finalized_v1 AFTER UPDATE OF finalization_status ON battle_replay_sessions FOR EACH ROW EXECUTE FUNCTION on_raid_room_rescue_reward_finalized_v1();
CREATE TRIGGER remove_legacy_pvp_cash_before_finalize BEFORE UPDATE OF finalization_status ON battle_replay_sessions FOR EACH ROW EXECUTE FUNCTION remove_legacy_pvp_cash_before_finalize();
CREATE TRIGGER character_awakening_power_projection_trigger AFTER INSERT OR DELETE OR UPDATE ON character_awakening_master FOR EACH STATEMENT EXECUTE FUNCTION power_projection_master_changed();
CREATE TRIGGER character_awakening_preopen_power_cutoff_guard BEFORE INSERT OR DELETE OR UPDATE ON character_awakening_master FOR EACH STATEMENT EXECUTE FUNCTION guard_preopen_guild_power_cutoff();
CREATE TRIGGER monthly_power_cutoff_guard BEFORE INSERT OR DELETE OR UPDATE ON character_awakening_master FOR EACH STATEMENT EXECUTE FUNCTION guard_monthly_power_season_cutoff();
CREATE TRIGGER character_battle_power_projection_trigger AFTER INSERT OR DELETE OR UPDATE ON character_battle_master FOR EACH STATEMENT EXECUTE FUNCTION power_projection_master_changed();
CREATE TRIGGER character_battle_preopen_power_cutoff_guard BEFORE INSERT OR DELETE OR UPDATE ON character_battle_master FOR EACH STATEMENT EXECUTE FUNCTION guard_preopen_guild_power_cutoff();
CREATE TRIGGER monthly_power_cutoff_guard BEFORE INSERT OR DELETE OR UPDATE ON character_battle_master FOR EACH STATEMENT EXECUTE FUNCTION guard_monthly_power_season_cutoff();
CREATE TRIGGER character_growth_power_projection_trigger AFTER INSERT OR DELETE OR UPDATE ON character_growth_patterns FOR EACH STATEMENT EXECUTE FUNCTION power_projection_master_changed();
CREATE TRIGGER character_growth_preopen_power_cutoff_guard BEFORE INSERT OR DELETE OR UPDATE ON character_growth_patterns FOR EACH STATEMENT EXECUTE FUNCTION guard_preopen_guild_power_cutoff();
CREATE TRIGGER monthly_power_cutoff_guard BEFORE INSERT OR DELETE OR UPDATE ON character_growth_patterns FOR EACH STATEMENT EXECUTE FUNCTION guard_monthly_power_season_cutoff();
CREATE TRIGGER ranking_successful_view_special_mission_trigger AFTER INSERT ON client_funnel_events FOR EACH ROW EXECUTE FUNCTION on_ranking_successful_view_special_mission();
CREATE TRIGGER equipment_battle_power_projection_trigger AFTER INSERT OR DELETE OR UPDATE ON equipment_battle_master FOR EACH STATEMENT EXECUTE FUNCTION power_projection_master_changed();
CREATE TRIGGER equipment_battle_preopen_power_cutoff_guard BEFORE INSERT OR DELETE OR UPDATE ON equipment_battle_master FOR EACH STATEMENT EXECUTE FUNCTION guard_preopen_guild_power_cutoff();
CREATE TRIGGER monthly_power_cutoff_guard BEFORE INSERT OR DELETE OR UPDATE ON equipment_battle_master FOR EACH STATEMENT EXECUTE FUNCTION guard_monthly_power_season_cutoff();
CREATE TRIGGER feature_operating_states_audit BEFORE UPDATE ON feature_operating_states FOR EACH ROW EXECUTE FUNCTION audit_feature_operating_state_change();
CREATE TRIGGER billing_special_payment_guard BEFORE INSERT OR UPDATE OF gacha_id, payment_source ON gacha_execution_history FOR EACH ROW EXECUTE FUNCTION billing_validate_special_payment();
CREATE TRIGGER consume_tutorial_character_daily_free_gacha_trigger BEFORE INSERT ON gacha_execution_history FOR EACH ROW EXECUTE FUNCTION consume_tutorial_character_daily_free_gacha();
CREATE TRIGGER dispatch_completed_free_normal_gacha_mission_trigger AFTER UPDATE OF status ON gacha_execution_history FOR EACH ROW EXECUTE FUNCTION dispatch_completed_free_normal_gacha_mission();
CREATE TRIGGER kpi_gacha_completed_trigger AFTER INSERT OR UPDATE OF status ON gacha_execution_history FOR EACH ROW EXECUTE FUNCTION on_kpi_gacha_completed();
CREATE TRIGGER m9x_gacha_activity_trigger AFTER UPDATE OF status ON gacha_execution_history FOR EACH ROW EXECUTE FUNCTION on_m9x_gacha_activity();
CREATE TRIGGER post_tutorial_free_asset_gacha_trigger AFTER INSERT OR UPDATE OF status ON gacha_execution_history FOR EACH ROW EXECUTE FUNCTION on_post_tutorial_free_asset_gacha();
CREATE TRIGGER canonical_guild_application_level_trigger BEFORE INSERT ON guild_join_requests FOR EACH ROW EXECUTE FUNCTION enforce_canonical_guild_join_level();
CREATE TRIGGER guild_join_request_funnel_trigger AFTER INSERT ON guild_join_requests FOR EACH ROW EXECUTE FUNCTION on_guild_funnel();
CREATE TRIGGER m9x_join_approved_metric_trigger AFTER UPDATE OF status ON guild_join_requests FOR EACH ROW EXECUTE FUNCTION on_m9x_join_approved_metric();
CREATE TRIGGER operations_maintenance_gate BEFORE INSERT OR DELETE OR UPDATE ON guild_join_requests FOR EACH ROW EXECUTE FUNCTION reject_mutation_during_maintenance();
CREATE TRIGGER canonical_guild_member_level_trigger BEFORE INSERT ON guild_members FOR EACH ROW EXECUTE FUNCTION enforce_canonical_guild_join_level();
CREATE TRIGGER daily_ranking_guild_membership_snapshot AFTER INSERT OR DELETE OR UPDATE OF guild_id, user_id ON guild_members FOR EACH ROW EXECUTE FUNCTION capture_daily_ranking_guild_membership();
CREATE TRIGGER enforce_guild_member_cap_trigger BEFORE INSERT ON guild_members FOR EACH ROW EXECUTE FUNCTION enforce_guild_member_cap();
CREATE TRIGGER guard_gvg_membership_lock_trigger BEFORE INSERT OR DELETE OR UPDATE ON guild_members FOR EACH ROW EXECUTE FUNCTION guard_gvg_membership_lock();
CREATE TRIGGER guild_member_funnel_trigger AFTER INSERT ON guild_members FOR EACH ROW EXECUTE FUNCTION on_guild_funnel();
CREATE TRIGGER guild_members_preopen_power_cutoff_guard BEFORE INSERT OR DELETE OR UPDATE ON guild_members FOR EACH STATEMENT EXECUTE FUNCTION guard_preopen_guild_power_cutoff();
CREATE TRIGGER kpi_guild_member_joined_trigger AFTER INSERT ON guild_members FOR EACH ROW EXECUTE FUNCTION on_kpi_guild_member_joined();
CREATE TRIGGER kpi_guild_member_leaving_trigger BEFORE DELETE ON guild_members FOR EACH ROW EXECUTE FUNCTION on_kpi_guild_member_leaving();
CREATE TRIGGER monthly_power_cutoff_guard BEFORE INSERT OR DELETE OR UPDATE ON guild_members FOR EACH STATEMENT EXECUTE FUNCTION guard_monthly_power_season_cutoff();
CREATE TRIGGER operations_maintenance_gate BEFORE INSERT OR DELETE OR UPDATE ON guild_members FOR EACH ROW EXECUTE FUNCTION reject_mutation_during_maintenance();
CREATE TRIGGER sync_user_guild_membership_trigger AFTER INSERT OR DELETE ON guild_members FOR EACH ROW EXECUTE FUNCTION sync_user_guild_membership();
CREATE TRIGGER zz_kpi_v249_guild_member_joined AFTER INSERT ON guild_members FOR EACH ROW EXECUTE FUNCTION on_kpi_v249_guild_member_joined();
CREATE TRIGGER guild_emblem_after_insert AFTER INSERT ON guilds FOR EACH ROW EXECUTE FUNCTION initialize_guild_emblem();
CREATE TRIGGER guilds_preopen_power_cutoff_guard BEFORE INSERT OR DELETE OR UPDATE ON guilds FOR EACH STATEMENT EXECUTE FUNCTION guard_preopen_guild_power_cutoff();
CREATE TRIGGER m9x_guild_created_activity_trigger AFTER INSERT ON guilds FOR EACH ROW EXECUTE FUNCTION on_m9x_guild_created_activity();
CREATE TRIGGER monthly_power_cutoff_guard BEFORE INSERT OR DELETE OR UPDATE ON guilds FOR EACH STATEMENT EXECUTE FUNCTION guard_monthly_power_season_cutoff();
CREATE TRIGGER operations_maintenance_gate BEFORE INSERT OR DELETE OR UPDATE ON guilds FOR EACH ROW EXECUTE FUNCTION reject_mutation_during_maintenance();
CREATE TRIGGER gvg_individual_damage_projection_trigger AFTER UPDATE OF battle_result ON gvg_attack_logs FOR EACH ROW EXECUTE FUNCTION capture_gvg_individual_damage();
CREATE TRIGGER guard_gvg_defense_deck_lock_trigger BEFORE INSERT OR DELETE OR UPDATE ON gvg_defense_decks FOR EACH ROW EXECUTE FUNCTION guard_gvg_defense_deck_lock();
CREATE TRIGGER gvg_guild_result_projection_trigger AFTER UPDATE OF status ON gvg_match_sessions FOR EACH ROW EXECUTE FUNCTION capture_gvg_guild_result();
CREATE TRIGGER billing_present_claimed AFTER UPDATE OF status ON presents FOR EACH ROW EXECUTE FUNCTION billing_mark_lot_claimed();
CREATE TRIGGER pvp_daily_win_projection_trigger AFTER INSERT OR UPDATE OF daily_wins ON pvp_ranks FOR EACH ROW EXECUTE FUNCTION capture_pvp_daily_win();
CREATE TRIGGER raid_boss_defeated_activity_trigger AFTER UPDATE OF status, current_hp ON raid_bosses FOR EACH ROW WHEN (old.status IS DISTINCT FROM new.status AND new.status = 'CLEARED'::text) EXECUTE FUNCTION on_raid_boss_defeated_activity();
CREATE TRIGGER guild_exclusions_preopen_power_cutoff_guard BEFORE INSERT OR DELETE OR UPDATE ON ranking_guild_exclusions FOR EACH STATEMENT EXECUTE FUNCTION guard_preopen_guild_power_cutoff();
CREATE TRIGGER monthly_power_cutoff_guard BEFORE INSERT OR DELETE OR UPDATE ON ranking_guild_exclusions FOR EACH STATEMENT EXECUTE FUNCTION guard_monthly_power_season_cutoff();
CREATE TRIGGER ranking_guild_power_snapshot_immutable BEFORE INSERT OR DELETE OR UPDATE ON ranking_guild_power_season_snapshots FOR EACH ROW EXECUTE FUNCTION reject_guild_power_snapshot_mutation();
CREATE TRIGGER capture_lifetime_onboarding_grant_trigger AFTER UPDATE OF step_id ON tutorial_progress FOR EACH ROW EXECUTE FUNCTION capture_lifetime_onboarding_grant_after_formation();
CREATE TRIGGER kpi_tutorial_complete_trigger AFTER INSERT OR UPDATE OF step_id ON tutorial_progress FOR EACH ROW EXECUTE FUNCTION on_kpi_tutorial_complete();
CREATE TRIGGER short_tutorial_character_setup_eligible_trigger AFTER UPDATE OF step_id ON tutorial_progress FOR EACH ROW EXECUTE FUNCTION on_short_tutorial_character_setup_eligible();
CREATE TRIGGER tutorial_complete_funnel_trigger AFTER UPDATE OF step_id ON tutorial_progress FOR EACH ROW EXECUTE FUNCTION on_tutorial_complete_funnel();
CREATE TRIGGER kpi_auth_method_created_trigger AFTER INSERT OR UPDATE OF authenticated_at ON user_account_auth_methods FOR EACH ROW EXECUTE FUNCTION on_kpi_auth_method_created();
CREATE TRIGGER funnel_mission_progress_trigger AFTER INSERT OR UPDATE ON user_funnel_milestones FOR EACH ROW EXECUTE FUNCTION on_funnel_mission_progress();
CREATE TRIGGER billing_item_lots BEFORE UPDATE OF quantity ON user_items FOR EACH ROW EXECUTE FUNCTION billing_asset_balance_trigger();
CREATE TRIGGER operations_maintenance_gate BEFORE INSERT OR DELETE OR UPDATE ON user_items FOR EACH ROW EXECUTE FUNCTION reject_mutation_during_maintenance();
CREATE TRIGGER login_bonus_mission_progress AFTER INSERT OR UPDATE OF last_claimed_at ON user_login_bonuses FOR EACH ROW EXECUTE FUNCTION on_login_bonus_mission_progress();
CREATE TRIGGER main_formation_special_mission_change_trigger AFTER INSERT OR DELETE OR UPDATE ON user_main_formations FOR EACH ROW EXECUTE FUNCTION on_main_formation_special_mission_change();
CREATE TRIGGER monthly_power_cutoff_guard BEFORE INSERT OR DELETE OR UPDATE ON user_main_formations FOR EACH STATEMENT EXECUTE FUNCTION guard_monthly_power_season_cutoff();
CREATE TRIGGER user_main_formations_preopen_power_cutoff_guard BEFORE INSERT OR DELETE OR UPDATE ON user_main_formations FOR EACH STATEMENT EXECUTE FUNCTION guard_preopen_guild_power_cutoff();
CREATE TRIGGER daily_mission_authority_change_trigger AFTER UPDATE OF status ON user_missions FOR EACH ROW WHEN (old.status IS DISTINCT FROM new.status AND (new.status = ANY (ARRAY['CLEAR'::text, 'CLAIMED'::text]))) EXECUTE FUNCTION on_daily_mission_authority_change();
CREATE TRIGGER enforce_mission_claim_prerequisite_trigger BEFORE UPDATE OF status ON user_missions FOR EACH ROW EXECUTE FUNCTION enforce_mission_claim_prerequisite();
CREATE TRIGGER mission_claim_unlock_trigger AFTER UPDATE OF status ON user_missions FOR EACH ROW EXECUTE FUNCTION on_mission_claim_unlock();
CREATE TRIGGER normalize_user_mission_progress_trigger BEFORE INSERT OR UPDATE OF current_progress, progress_val, status ON user_missions FOR EACH ROW EXECUTE FUNCTION normalize_user_mission_progress();
CREATE TRIGGER operations_maintenance_gate BEFORE INSERT OR DELETE OR UPDATE ON user_missions FOR EACH ROW EXECUTE FUNCTION reject_mutation_during_maintenance();
CREATE TRIGGER special_mission_status_change_trigger AFTER UPDATE OF status ON user_missions FOR EACH ROW EXECUTE FUNCTION on_special_mission_status_change();
CREATE TRIGGER m9x_power_leader_activity_trigger AFTER INSERT OR UPDATE OF total_power ON user_power_rankings FOR EACH ROW EXECUTE FUNCTION on_m9x_power_leader_activity();
CREATE TRIGGER monthly_power_cutoff_guard BEFORE INSERT OR DELETE OR UPDATE ON user_power_rankings FOR EACH STATEMENT EXECUTE FUNCTION guard_monthly_power_season_cutoff();
CREATE TRIGGER monthly_power_cutoff_guard BEFORE INSERT OR DELETE OR UPDATE ON user_skills FOR EACH STATEMENT EXECUTE FUNCTION guard_monthly_power_season_cutoff();
CREATE TRIGGER operations_maintenance_gate BEFORE INSERT OR DELETE OR UPDATE ON user_skills FOR EACH ROW EXECUTE FUNCTION reject_mutation_during_maintenance();
CREATE TRIGGER post_tutorial_manual_skill_loadout AFTER UPDATE OF equipped_character_id ON user_skills FOR EACH ROW EXECUTE FUNCTION on_post_tutorial_manual_loadout();
CREATE TRIGGER skill_growth_funnel_trigger AFTER UPDATE ON user_skills FOR EACH ROW EXECUTE FUNCTION on_progression_growth_funnel();
CREATE TRIGGER billing_cash_lots BEFORE UPDATE OF cash ON users FOR EACH ROW EXECUTE FUNCTION billing_asset_balance_trigger();
CREATE TRIGGER billing_dia_lots BEFORE UPDATE OF neon_diamonds ON users FOR EACH ROW EXECUTE FUNCTION billing_dia_balance_trigger();
CREATE TRIGGER enforce_equipped_title_ownership BEFORE UPDATE OF title_equipped ON users FOR EACH ROW EXECUTE FUNCTION guard_equipped_title_ownership();
CREATE TRIGGER guard_daily_profile_changes_trigger BEFORE UPDATE ON users FOR EACH ROW EXECUTE FUNCTION guard_daily_profile_changes();
CREATE TRIGGER kpi_user_created_trigger AFTER INSERT ON users FOR EACH ROW EXECUTE FUNCTION on_kpi_user_created();
CREATE TRIGGER kpi_user_detaching_trigger BEFORE DELETE ON users FOR EACH ROW EXECUTE FUNCTION on_kpi_user_detaching();
CREATE TRIGGER leader_hometown_base BEFORE UPDATE OF favorite_character_id ON users FOR EACH ROW EXECUTE FUNCTION on_leader_hometown_base();
CREATE TRIGGER monthly_power_cutoff_guard BEFORE INSERT OR DELETE OR UPDATE ON users FOR EACH STATEMENT EXECUTE FUNCTION guard_monthly_power_season_cutoff();
CREATE TRIGGER operations_maintenance_gate BEFORE INSERT OR DELETE OR UPDATE ON users FOR EACH ROW EXECUTE FUNCTION reject_mutation_during_maintenance();
CREATE TRIGGER canonical_guild_quest_exp_trigger AFTER UPDATE OF status ON user_patrols FOR EACH ROW EXECUTE FUNCTION on_canonical_guild_quest_exp();
CREATE TRIGGER canonical_hard_quest_complete AFTER UPDATE OF status ON user_patrols FOR EACH ROW EXECUTE FUNCTION on_canonical_hard_quest_complete();
CREATE TRIGGER canonical_patrol_snapshot BEFORE INSERT ON user_patrols FOR EACH ROW EXECUTE FUNCTION on_canonical_patrol_snapshot();
CREATE TRIGGER capture_quest_raid_encounter_v1 AFTER UPDATE OF status ON user_patrols FOR EACH ROW EXECUTE FUNCTION capture_quest_raid_encounter_v1();
CREATE TRIGGER post_tutorial_quest_complete_trigger AFTER UPDATE OF status ON user_patrols FOR EACH ROW WHEN (old.status IS DISTINCT FROM new.status AND new.status = 'COMPLETED'::text) EXECUTE FUNCTION on_post_tutorial_quest_complete();
CREATE TRIGGER quest_base_cash_snapshot BEFORE INSERT OR UPDATE ON user_patrols FOR EACH ROW EXECUTE FUNCTION on_quest_base_cash_snapshot();
CREATE TRIGGER quest_hometown_snapshot BEFORE INSERT ON user_patrols FOR EACH ROW EXECUTE FUNCTION on_quest_hometown_snapshot();
ALTER TABLE "public"."canonical_guild_donation_master" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."canonical_guild_progression_master" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."canonical_guild_recruitment_master" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."canonical_guild_role_master" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."gacha_banner_master" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."canonical_character_master" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."canonical_equipment_master" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."canonical_gameplay_master_versions" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."canonical_equipment_lb_slot_options" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."canonical_equipment_lb_steps" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."canonical_skill_master" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."guild_decorations" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."canonical_guild_exp_source_master" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."pvp_ranking_reward_grants" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."raid_instance_user_progress" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."raid_production_reward_grants" DISABLE ROW LEVEL SECURITY;
CREATE POLICY "bbs_posts_authenticated_read" ON "public"."bbs_posts" AS PERMISSIVE FOR SELECT TO "authenticated" USING (true);
CREATE POLICY "bbs_threads_authenticated_read" ON "public"."bbs_threads" AS PERMISSIVE FOR SELECT TO "authenticated" USING (true);
CREATE POLICY "board_posts_chat_read" ON "public"."board_posts" AS PERMISSIVE FOR SELECT TO "authenticated" USING (((target_type = 'GLOBAL'::text) OR ((target_type = 'GUILD'::text) AND (EXISTS ( SELECT 1
   FROM guild_members
  WHERE ((guild_members.guild_id = board_posts.target_id) AND (guild_members.user_id = auth.uid())))))));
CREATE POLICY "direct_messages_participant_read" ON "public"."direct_messages" AS PERMISSIVE FOR SELECT TO "authenticated" USING (((auth.uid() = sender_id) OR (auth.uid() = recipient_id)));
CREATE POLICY "Allow public read on master tables" ON "public"."avatar_parts" AS PERMISSIVE FOR SELECT TO PUBLIC USING (true);
CREATE POLICY "Read own battle replay events" ON "public"."battle_replay_events" AS PERMISSIVE FOR SELECT TO "authenticated" USING ((EXISTS ( SELECT 1
   FROM battle_replay_sessions s
  WHERE ((s.id = battle_replay_events.battle_replay_session_id) AND (s.requester_user_id = auth.uid())))));
CREATE POLICY "Read own battle replay sessions" ON "public"."battle_replay_sessions" AS PERMISSIVE FOR SELECT TO "authenticated" USING ((requester_user_id = auth.uid()));
CREATE POLICY "bbs_read_states_owner_read" ON "public"."bbs_read_states" AS PERMISSIVE FOR SELECT TO "authenticated" USING ((user_id = auth.uid()));
CREATE POLICY "canonical_item_master_read" ON "public"."canonical_item_master" AS PERMISSIVE FOR SELECT TO "authenticated" USING (is_production_enabled);
CREATE POLICY "canonical_master_freeze_read" ON "public"."canonical_master_freeze_versions" AS PERMISSIVE FOR SELECT TO "authenticated" USING (is_production_enabled);
CREATE POLICY "canonical_quest_encounter_master_read" ON "public"."canonical_quest_encounter_master" AS PERMISSIVE FOR SELECT TO "authenticated" USING (is_production_enabled);
CREATE POLICY "canonical_enemy_pool_read" ON "public"."canonical_quest_enemy_pool_entries" AS PERMISSIVE FOR SELECT TO "authenticated" USING (is_production_enabled);
CREATE POLICY "canonical_quest_master_read" ON "public"."canonical_quest_master" AS PERMISSIVE FOR SELECT TO "authenticated" USING (is_production_enabled);
CREATE POLICY "canonical_quest_reward_pool_items_read" ON "public"."canonical_quest_reward_pool_items" AS PERMISSIVE FOR SELECT TO "authenticated" USING (true);
CREATE POLICY "canonical_raid_variant_read" ON "public"."canonical_raid_variants" AS PERMISSIVE FOR SELECT TO "authenticated" USING (is_production_enabled);
CREATE POLICY "canonical_reward_supply_sources_read" ON "public"."canonical_reward_supply_sources" AS PERMISSIVE FOR SELECT TO "authenticated" USING (true);
CREATE POLICY "Allow public read on master tables" ON "public"."character_awakening_master" AS PERMISSIVE FOR SELECT TO PUBLIC USING (true);
CREATE POLICY "Read own character cosmetics" ON "public"."character_cosmetics" AS PERMISSIVE FOR SELECT TO PUBLIC USING ((EXISTS ( SELECT 1
   FROM user_characters c
  WHERE ((c.id = character_cosmetics.user_character_id) AND (c.user_id = auth.uid())))));
CREATE POLICY "Allow public read on master tables" ON "public"."character_growth_patterns" AS PERMISSIVE FOR SELECT TO PUBLIC USING (true);
CREATE POLICY "character_release_master_read" ON "public"."character_release_master" AS PERMISSIVE FOR SELECT TO "anon", "authenticated" USING (is_enabled);
CREATE POLICY "chat_read_states_owner_read" ON "public"."chat_read_states" AS PERMISSIVE FOR SELECT TO "authenticated" USING ((user_id = auth.uid()));
CREATE POLICY "Read active cosmetics" ON "public"."cosmetic_master" AS PERMISSIVE FOR SELECT TO PUBLIC USING (active);
CREATE POLICY "Allow public read on master tables" ON "public"."enemies" AS PERMISSIVE FOR SELECT TO PUBLIC USING (true);
CREATE POLICY "Allow public read on master tables" ON "public"."equipment_level_up_master" AS PERMISSIVE FOR SELECT TO PUBLIC USING (true);
CREATE POLICY "Allow public read on master tables" ON "public"."equipment_limit_break_master" AS PERMISSIVE FOR SELECT TO PUBLIC USING (true);
CREATE POLICY "Read own equipped cosmetics" ON "public"."equipped_cosmetics" AS PERMISSIVE FOR SELECT TO PUBLIC USING ((auth.uid() = user_id));
CREATE POLICY "feature_operating_states_authenticated_read" ON "public"."feature_operating_states" AS PERMISSIVE FOR SELECT TO "authenticated" USING (true);
CREATE POLICY "friend_requests_participant_read" ON "public"."friend_requests" AS PERMISSIVE FOR SELECT TO "authenticated" USING (((sender_id = auth.uid()) OR (receiver_id = auth.uid())));
CREATE POLICY "gacha_execution_history_owner_read" ON "public"."gacha_execution_history" AS PERMISSIVE FOR SELECT TO "authenticated" USING ((user_id = auth.uid()));
CREATE POLICY "Allow public read on master tables" ON "public"."gacha_items_master" AS PERMISSIVE FOR SELECT TO PUBLIC USING (true);
CREATE POLICY "Allow public read on master tables" ON "public"."gacha_masters" AS PERMISSIVE FOR SELECT TO PUBLIC USING (true);
CREATE POLICY "gacha_rarity_rates_authenticated_read" ON "public"."gacha_rarity_rates" AS PERMISSIVE FOR SELECT TO "authenticated" USING (true);
CREATE POLICY "Read own gameplay reset requests" ON "public"."gameplay_reset_requests" AS PERMISSIVE FOR SELECT TO "authenticated" USING ((user_id = auth.uid()));
CREATE POLICY "guild_activity_grants_own_read" ON "public"."guild_activity_grants" AS PERMISSIVE FOR SELECT TO "authenticated" USING ((user_id = auth.uid()));
CREATE POLICY "Read guild cosmetics" ON "public"."guild_cosmetics" AS PERMISSIVE FOR SELECT TO PUBLIC USING ((EXISTS ( SELECT 1
   FROM guild_members gm
  WHERE ((gm.guild_id = guild_cosmetics.guild_id) AND (gm.user_id = auth.uid())))));
CREATE POLICY "Read equipped guild cosmetics" ON "public"."guild_equipped_cosmetics" AS PERMISSIVE FOR SELECT TO PUBLIC USING ((EXISTS ( SELECT 1
   FROM guild_members gm
  WHERE ((gm.guild_id = guild_equipped_cosmetics.guild_id) AND (gm.user_id = auth.uid())))));
CREATE POLICY "guild_exp_ledger_own_read" ON "public"."guild_exp_daily_ledger" AS PERMISSIVE FOR SELECT TO "authenticated" USING ((user_id = auth.uid()));
CREATE POLICY "guild_join_requests_read" ON "public"."guild_join_requests" AS PERMISSIVE FOR SELECT TO "authenticated" USING (((user_id = auth.uid()) OR is_current_guild_master(guild_id)));
CREATE POLICY "Allow public read on master tables" ON "public"."guild_level_master" AS PERMISSIVE FOR SELECT TO PUBLIC USING (true);
CREATE POLICY "guild_members_same_guild_read" ON "public"."guild_members" AS PERMISSIVE FOR SELECT TO "authenticated" USING (is_current_guild_member(guild_id));
CREATE POLICY "Allow public read on master tables" ON "public"."guild_xp_action_master" AS PERMISSIVE FOR SELECT TO PUBLIC USING (true);
CREATE POLICY "guilds_member_read" ON "public"."guilds" AS PERMISSIVE FOR SELECT TO "authenticated" USING (is_current_guild_member(id));
CREATE POLICY "Read own GvG attack logs" ON "public"."gvg_attack_logs" AS PERMISSIVE FOR SELECT TO "authenticated" USING ((attacker_user_id = auth.uid()));
CREATE POLICY "authenticated read gvg defense decks" ON "public"."gvg_defense_decks" AS PERMISSIVE FOR SELECT TO "authenticated" USING (true);
CREATE POLICY "Read own guild GvG matches" ON "public"."gvg_match_sessions" AS PERMISSIVE FOR SELECT TO "authenticated" USING ((EXISTS ( SELECT 1
   FROM guild_members member
  WHERE ((member.user_id = auth.uid()) AND ((member.guild_id = gvg_match_sessions.guild_a_id) OR (member.guild_id = gvg_match_sessions.guild_b_id))))));
CREATE POLICY "Allow all access to gvg_matches" ON "public"."gvg_matches" AS PERMISSIVE FOR ALL TO PUBLIC USING (true) WITH CHECK (true);
CREATE POLICY "Allow public read on master tables" ON "public"."gvg_rewards_master" AS PERMISSIVE FOR SELECT TO PUBLIC USING (true);
CREATE POLICY "Allow all access to gvg_season_status" ON "public"."gvg_season_status" AS PERMISSIVE FOR ALL TO PUBLIC USING (true) WITH CHECK (true);
CREATE POLICY "Read active home banners" ON "public"."home_banner_master" AS PERMISSIVE FOR SELECT TO PUBLIC USING ((active AND (start_at <= now()) AND ((end_at IS NULL) OR (end_at > now()))));
CREATE POLICY "Allow public read on master tables" ON "public"."login_bonus_master" AS PERMISSIVE FOR SELECT TO PUBLIC USING (true);
CREATE POLICY "mission_event_dialog_views_owner_read" ON "public"."mission_event_dialog_views" AS PERMISSIVE FOR SELECT TO "authenticated" USING ((user_id = auth.uid()));
CREATE POLICY "mission_event_telemetry_owner_read" ON "public"."mission_event_telemetry" AS PERMISSIVE FOR SELECT TO "authenticated" USING ((user_id = auth.uid()));
CREATE POLICY "mission_events_authenticated_read" ON "public"."mission_events" AS PERMISSIVE FOR SELECT TO "authenticated" USING (true);
CREATE POLICY "mission_reward_components_authenticated_read" ON "public"."mission_reward_components" AS PERMISSIVE FOR SELECT TO "authenticated" USING (true);
CREATE POLICY "mission_reward_delivery_items_owner_read" ON "public"."mission_reward_delivery_items" AS PERMISSIVE FOR SELECT TO "authenticated" USING ((EXISTS ( SELECT 1
   FROM mission_reward_delivery_ledger ledger
  WHERE ((ledger.id = mission_reward_delivery_items.delivery_ledger_id) AND (ledger.user_id = auth.uid())))));
CREATE POLICY "mission_reward_delivery_ledger_owner_read" ON "public"."mission_reward_delivery_ledger" AS PERMISSIVE FOR SELECT TO "authenticated" USING ((user_id = auth.uid()));
CREATE POLICY "missions_authenticated_read" ON "public"."missions" AS PERMISSIVE FOR SELECT TO "authenticated" USING (is_enabled);
CREATE POLICY "Allow public read on master tables" ON "public"."missions" AS PERMISSIVE FOR SELECT TO PUBLIC USING (true);
CREATE POLICY "Allow public read on master tables" ON "public"."patrol_npcs" AS PERMISSIVE FOR SELECT TO PUBLIC USING (true);
CREATE POLICY "Authenticated read patrol NPC masters" ON "public"."patrol_npcs" AS PERMISSIVE FOR SELECT TO "authenticated" USING (true);
CREATE POLICY "owner read payment transactions" ON "public"."payment_transactions" AS PERMISSIVE FOR SELECT TO "authenticated" USING ((auth.uid() = user_id));
CREATE POLICY "presents_owner_read" ON "public"."presents" AS PERMISSIVE FOR SELECT TO "authenticated" USING ((user_id = auth.uid()));
CREATE POLICY "owner access to presents" ON "public"."presents" AS PERMISSIVE FOR ALL TO PUBLIC USING ((auth.uid() = user_id)) WITH CHECK ((auth.uid() = user_id));
CREATE POLICY "authenticated read pvp defense decks" ON "public"."pvp_defense_decks" AS PERMISSIVE FOR SELECT TO "authenticated" USING (true);
CREATE POLICY "Allow all access to pvp_defense_logs" ON "public"."pvp_defense_logs" AS PERMISSIVE FOR ALL TO PUBLIC USING (true) WITH CHECK (true);
CREATE POLICY "Allow public read on master tables" ON "public"."pvp_match_rewards_master" AS PERMISSIVE FOR SELECT TO PUBLIC USING (true);
CREATE POLICY "Allow public read on master tables" ON "public"."pvp_rewards_master" AS PERMISSIVE FOR SELECT TO PUBLIC USING (true);
CREATE POLICY "Allow public read on master tables" ON "public"."quest_towns" AS PERMISSIVE FOR SELECT TO PUBLIC USING (true);
CREATE POLICY "Allow public read on master tables" ON "public"."quests" AS PERMISSIVE FOR SELECT TO PUBLIC USING (true);
CREATE POLICY "raid_attempt_cost_read" ON "public"."raid_attempt_cost_master" AS PERMISSIVE FOR SELECT TO "authenticated" USING (true);
CREATE POLICY "Allow public read on master tables" ON "public"."raid_boss_master" AS PERMISSIVE FOR SELECT TO PUBLIC USING (true);
CREATE POLICY "raid_bosses_authenticated_read" ON "public"."raid_bosses" AS PERMISSIVE FOR SELECT TO "authenticated" USING (true);
CREATE POLICY "raid_clear_claim_owner_read" ON "public"."raid_clear_reward_claims" AS PERMISSIVE FOR SELECT TO "authenticated" USING ((user_id = auth.uid()));
CREATE POLICY "Read own raid completion xp" ON "public"."raid_completion_xp_grants" AS PERMISSIVE FOR SELECT TO "authenticated" USING ((user_id = auth.uid()));
CREATE POLICY "raid_reward_grants_own_read" ON "public"."raid_reward_grants" AS PERMISSIVE FOR SELECT TO "authenticated" USING ((user_id = auth.uid()));
CREATE POLICY "Allow public read on master tables" ON "public"."raid_rewards_master" AS PERMISSIVE FOR SELECT TO PUBLIC USING (true);
CREATE POLICY "Allow public read on master tables" ON "public"."skill_limit_break_master" AS PERMISSIVE FOR SELECT TO PUBLIC USING (true);
CREATE POLICY "social_activity_feed_authenticated_read" ON "public"."social_activity_feed" AS PERMISSIVE FOR SELECT TO "authenticated" USING (true);
CREATE POLICY "Allow all access to story_sessions" ON "public"."story_sessions" AS PERMISSIVE FOR ALL TO PUBLIC USING (true) WITH CHECK (true);
CREATE POLICY "Read active title master" ON "public"."title_master" AS PERMISSIVE FOR SELECT TO "authenticated" USING ((is_active = true));
CREATE POLICY "Read own tutorial progress" ON "public"."tutorial_progress" AS PERMISSIVE FOR SELECT TO "authenticated" USING ((user_id = auth.uid()));
CREATE POLICY "Read own account auth method" ON "public"."user_account_auth_methods" AS PERMISSIVE FOR SELECT TO "authenticated" USING ((user_id = auth.uid()));
CREATE POLICY "owner access to user_avatar_parts" ON "public"."user_avatar_parts" AS PERMISSIVE FOR ALL TO PUBLIC USING ((auth.uid() = user_id)) WITH CHECK ((auth.uid() = user_id));
CREATE POLICY "owner access to user_avatars" ON "public"."user_avatars" AS PERMISSIVE FOR ALL TO PUBLIC USING ((auth.uid() = user_id)) WITH CHECK ((auth.uid() = user_id));
CREATE POLICY "Users can manage their own characters" ON "public"."user_characters" AS PERMISSIVE FOR ALL TO PUBLIC USING ((auth.uid() = user_id)) WITH CHECK ((auth.uid() = user_id));
CREATE POLICY "Read own cosmetics" ON "public"."user_cosmetics" AS PERMISSIVE FOR SELECT TO PUBLIC USING ((auth.uid() = user_id));
CREATE POLICY "owner read user_daily_gacha_claims" ON "public"."user_daily_gacha_claims" AS PERMISSIVE FOR SELECT TO "authenticated" USING ((auth.uid() = user_id));
CREATE POLICY "Users can manage their own equipments" ON "public"."user_equipments" AS PERMISSIVE FOR ALL TO PUBLIC USING ((auth.uid() = user_id)) WITH CHECK ((auth.uid() = user_id));
CREATE POLICY "user_friends_owner_read" ON "public"."user_friends" AS PERMISSIVE FOR SELECT TO "authenticated" USING ((user_id = auth.uid()));
CREATE POLICY "funnel_milestones_own_read" ON "public"."user_funnel_milestones" AS PERMISSIVE FOR SELECT TO "authenticated" USING ((user_id = auth.uid()));
CREATE POLICY "owner read user_gacha_pity_points" ON "public"."user_gacha_pity_points" AS PERMISSIVE FOR SELECT TO "authenticated" USING ((auth.uid() = user_id));
CREATE POLICY "authenticated read user gvg ranks" ON "public"."user_gvg_ranks" AS PERMISSIVE FOR SELECT TO "authenticated" USING (true);
CREATE POLICY "user_invitations_participant_read" ON "public"."user_invitations" AS PERMISSIVE FOR SELECT TO "authenticated" USING (((inviter_user_id = auth.uid()) OR (invitee_user_id = auth.uid())));
CREATE POLICY "Users can manage their own items" ON "public"."user_items" AS PERMISSIVE FOR ALL TO PUBLIC USING ((auth.uid() = user_id)) WITH CHECK ((auth.uid() = user_id));
CREATE POLICY "Allow public read on master tables" ON "public"."user_level_master" AS PERMISSIVE FOR SELECT TO PUBLIC USING (true);
CREATE POLICY "Read own lifetime onboarding grant" ON "public"."user_lifetime_onboarding_grants" AS PERMISSIVE FOR SELECT TO "authenticated" USING ((user_id = auth.uid()));
CREATE POLICY "user_login_bonuses_owner_read" ON "public"."user_login_bonuses" AS PERMISSIVE FOR SELECT TO "authenticated" USING ((user_id = auth.uid()));
CREATE POLICY "user_missions_owner_read" ON "public"."user_missions" AS PERMISSIVE FOR SELECT TO "authenticated" USING ((user_id = auth.uid()));
CREATE POLICY "owner read monthly passes" ON "public"."user_monthly_passes" AS PERMISSIVE FOR SELECT TO "authenticated" USING ((auth.uid() = user_id));
CREATE POLICY "user_patrols_owner_read" ON "public"."user_patrols" AS PERMISSIVE FOR SELECT TO "authenticated" USING ((auth.uid() = user_id));
CREATE POLICY "Users can insert their own decorations" ON "public"."user_profile_decorations" AS PERMISSIVE FOR INSERT TO "authenticated" WITH CHECK ((user_id = auth.uid()));
CREATE POLICY "Users can view all user decorations" ON "public"."user_profile_decorations" AS PERMISSIVE FOR SELECT TO "authenticated" USING (true);
CREATE POLICY "user_raid_daily_attempts_own_read" ON "public"."user_raid_daily_attempts" AS PERMISSIVE FOR SELECT TO "authenticated" USING ((user_id = auth.uid()));
CREATE POLICY "Users can view their own shop purchases" ON "public"."user_shop_purchases" AS PERMISSIVE FOR SELECT TO "authenticated" USING ((user_id = auth.uid()));
CREATE POLICY "Users can manage their own skills" ON "public"."user_skills" AS PERMISSIVE FOR ALL TO PUBLIC USING ((auth.uid() = user_id)) WITH CHECK ((auth.uid() = user_id));
CREATE POLICY "Read own titles" ON "public"."user_titles" AS PERMISSIVE FOR SELECT TO "authenticated" USING ((user_id = auth.uid()));
CREATE POLICY "users_owner_read" ON "public"."users" AS PERMISSIVE FOR SELECT TO "authenticated" USING ((auth.uid() = id));
CREATE POLICY "news_read_published" ON "public"."news" AS PERMISSIVE FOR SELECT TO "anon", "authenticated" USING ((is_published AND (start_at <= now()) AND ((end_at IS NULL) OR (end_at > now()))));
CREATE POLICY "maintenance_tester_self_read" ON "public"."operations_maintenance_testers" AS PERMISSIVE FOR SELECT TO "authenticated" USING (((user_id = ( SELECT auth.uid() AS uid)) AND (expires_at > now())));
CREATE POLICY "billing_orders_owner_read" ON "public"."billing_orders" AS PERMISSIVE FOR SELECT TO "authenticated" USING ((( SELECT auth.uid() AS uid) = user_id));
CREATE POLICY "billing_shop_owner_read" ON "public"."billing_shop_receipts" AS PERMISSIVE FOR SELECT TO "authenticated" USING ((( SELECT auth.uid() AS uid) = user_id));
CREATE POLICY "billing_asset_lots_owner" ON "public"."billing_asset_lots" AS PERMISSIVE FOR SELECT TO "authenticated" USING ((( SELECT auth.uid() AS uid) = user_id));
CREATE POLICY "special_gacha_pool_groups_read" ON "public"."special_gacha_pool_groups" AS PERMISSIVE FOR SELECT TO "authenticated" USING (true);
CREATE POLICY "special_exchange_receipts_owner" ON "public"."special_gacha_exchange_receipts" AS PERMISSIVE FOR SELECT TO "authenticated" USING ((( SELECT auth.uid() AS uid) = user_id));
CREATE POLICY "growth_exp_history_owner_read" ON "public"."growth_exp_execution_history" AS PERMISSIVE FOR SELECT TO "authenticated" USING ((user_id = auth.uid()));
CREATE POLICY "canonical_character_growth_exponents_read" ON "public"."canonical_character_growth_exponents" AS PERMISSIVE FOR SELECT TO "anon", "authenticated" USING (true);
CREATE POLICY "canonical_character_growth_assignments_read" ON "public"."canonical_character_growth_assignments" AS PERMISSIVE FOR SELECT TO "anon", "authenticated" USING (true);
REVOKE ALL ON TABLE "public"."ranking_daily_activity_snapshots" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE "public"."kpi_subjects" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE "public"."kpi_daily_user_activity" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE "public"."kpi_account_classification_periods" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE "public"."kpi_guild_membership_periods" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE "public"."kpi_tutorial_completion_facts" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE "public"."kpi_gacha_execution_facts" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON SEQUENCE "public"."kpi_account_classification_periods_id_seq" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON SEQUENCE "public"."kpi_guild_membership_periods_id_seq" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE "public"."kpi_aggregation_runs" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE "public"."kpi_metric_snapshots" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON SEQUENCE "public"."kpi_metric_snapshots_id_seq" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE "public"."quest_raid_encounter_settings" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE "public"."quest_raid_encounter_bonus_items" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE "public"."quest_raid_encounter_progress" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE "public"."special_gacha_pool_groups" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE "public"."gameplay_reward_delivery_ledger" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE "public"."user_characters" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE "public"."user_equipments" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE "public"."character_level_up_master" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE "public"."growth_exp_execution_history" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE "public"."kpi_tutorial_journey_facts" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE "public"."kpi_acquisition_journeys" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE "public"."kpi_tutorial_mypage_ready_contexts" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE "public"."kpi_subject_identity_transition_facts" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE "public"."kpi_acquisition_journey_facts" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE "public"."kpi_guild_conversion_facts" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE "public"."canonical_character_growth_exponents" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE "public"."kpi_guild_chat_message_facts" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE "public"."canonical_character_growth_assignments" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE "public"."kpi_guild_chat_activation_facts" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE "public"."kpi_marketing_import_batches" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE "public"."kpi_acquisition_subject_bindings" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE "public"."kpi_marketing_reporting_scopes" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE "public"."kpi_marketing_daily_fact_revisions" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE "public"."kpi_canonical_tutorial_completions_v1" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE "public"."kpi_guild_daily_chat_activity_v1" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE "public"."kpi_effective_active_guild_daily_v1" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE "public"."kpi_marketing_latest_revisions_v1" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE "public"."operations_maintenance_testers" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE "public"."ranking_season_reward_grants" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE "public"."monthly_power_season_runs" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE "public"."monthly_power_entity_snapshots" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE "public"."monthly_power_member_snapshots" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE "public"."monthly_power_honor_requirements" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE "public"."monthly_power_reward_master" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE "public"."billing_grants" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE "public"."billing_shop_receipts" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE "public"."billing_products" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE "public"."monthly_power_honor_bindings" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE "public"."billing_asset_lots" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE "public"."monthly_power_honor_grants" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE "public"."kpi_overview_saved_results" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE "public"."monthly_power_honor_recipients" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE "public"."billing_orders" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE "public"."raid_daily_clear_bonus_rules" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE "public"."raid_daily_clear_bonus_ledger" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE "public"."quest_raid_encounters" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE "public"."quest_raid_encounter_bonus_grants" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE "public"."pvp_match_rewards_master" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE "public"."special_gacha_exchange_receipts" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE "public"."kpi_acquisition_valid_journeys_v1" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE "public"."kpi_subject_first_touch_v1" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON SEQUENCE "public"."anonymous_onboarding_cleanup_runs_id_seq" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON SEQUENCE "public"."battle_replay_events_id_seq" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE "public"."canonical_guild_donation_master" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE "public"."canonical_guild_progression_master" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE "public"."canonical_guild_recruitment_master" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE "public"."canonical_guild_role_master" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON SEQUENCE "public"."client_funnel_events_id_seq" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE "public"."gacha_banner_master" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE "public"."raid_room_lifecycle_rules" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE "public"."raid_rooms" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE "public"."raid_room_members" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE "public"."raid_room_creation_settings" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON SEQUENCE "public"."mission_event_telemetry_id_seq" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE "public"."raid_room_creation_requests" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE "public"."raid_room_battle_settings" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE "public"."missions_master" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON SEQUENCE "public"."operations_feature_state_audit_id_seq" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE "public"."raid_room_battle_start_requests" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE "public"."raid_room_battle_request_cancellations" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON SEQUENCE "public"."pvp_rewards_master_id_seq" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE "public"."raid_room_rescue_settings" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE "public"."raid_room_rescue_requests" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE "public"."raid_room_rescue_publications" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE "public"."raid_room_rescue_members" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE "public"."raid_room_difficulty_rules" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE "public"."social_activity_feed" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON SEQUENCE "public"."raid_rewards_master_id_seq" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE "public"."raid_room_rescue_reward_rules" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE "public"."raid_room_rescue_reward_items" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE "public"."raid_room_rescue_rewards" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE "public"."raid_room_rescue_reward_grants" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE "public"."raid_room_clear_reward_items" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE "public"."raid_room_clear_rewards" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE "public"."raid_legacy_settings" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE "public"."raid_room_clear_reward_grants" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE "private"."raid_daily_targets" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE "public"."raid_room_clear_reward_rules" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE "private"."initial_equipment_receipts" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE "public"."raid_room_combat_profiles" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE "public"."raid_room_combat_snapshots" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE "public"."canonical_character_master" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE "public"."canonical_equipment_master" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE "public"."news" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON SEQUENCE "public"."news_id_seq" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE "public"."canonical_gameplay_master_versions" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE "public"."canonical_equipment_lb_slot_options" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE "public"."canonical_equipment_lb_steps" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE "public"."canonical_skill_master" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE "public"."guild_decorations" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE "public"."canonical_guild_exp_source_master" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE "public"."pvp_ranking_reward_grants" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE "public"."raid_instance_user_progress" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE "public"."raid_production_reward_grants" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE "public"."board_posts" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE "public"."anonymous_onboarding_cleanup_runs" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE "public"."avatar_parts" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE "public"."battle_replay_events" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE "public"."battle_replay_sessions" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE "public"."bbs_posts" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE "public"."bbs_read_states" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE "public"."bbs_threads" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE "public"."canonical_action_resource_master" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE "public"."canonical_daily_activity_claims" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE "public"."canonical_daily_ranking_reward_master" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE "public"."canonical_item_master" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE "public"."canonical_master_freeze_versions" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE "public"."canonical_preapply_compatibility_audit" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE "public"."canonical_pvp_production_master" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE "public"."canonical_pvp_ranking_rewards" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE "public"."canonical_quest_encounter_master" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE "public"."canonical_quest_enemy_pool_entries" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE "public"."canonical_quest_master" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE "public"."canonical_quest_resource_cost" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE "public"."canonical_quest_reward_pool_items" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE "public"."canonical_raid_boss_master" FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE "public"."canonical_raid_production_master" FROM PUBLIC, anon, authenticated, service_role;
