SET check_function_bodies = false;
SET search_path = public, extensions, pg_catalog;
GRANT MAINTAIN ON TABLE "public"."user_items" TO "authenticated";
GRANT INSERT ON TABLE "public"."user_items" TO "service_role";
GRANT SELECT ON TABLE "public"."user_items" TO "service_role";
GRANT UPDATE ON TABLE "public"."user_items" TO "service_role";
GRANT DELETE ON TABLE "public"."user_items" TO "service_role";
GRANT TRUNCATE ON TABLE "public"."user_items" TO "service_role";
GRANT REFERENCES ON TABLE "public"."user_items" TO "service_role";
GRANT TRIGGER ON TABLE "public"."user_items" TO "service_role";
GRANT MAINTAIN ON TABLE "public"."user_items" TO "service_role";
GRANT INSERT ON TABLE "public"."user_level_master" TO "anon";
GRANT SELECT ON TABLE "public"."user_level_master" TO "anon";
GRANT UPDATE ON TABLE "public"."user_level_master" TO "anon";
GRANT DELETE ON TABLE "public"."user_level_master" TO "anon";
GRANT TRUNCATE ON TABLE "public"."user_level_master" TO "anon";
GRANT REFERENCES ON TABLE "public"."user_level_master" TO "anon";
GRANT TRIGGER ON TABLE "public"."user_level_master" TO "anon";
GRANT MAINTAIN ON TABLE "public"."user_level_master" TO "anon";
GRANT INSERT ON TABLE "public"."user_level_master" TO "authenticated";
GRANT SELECT ON TABLE "public"."user_level_master" TO "authenticated";
GRANT UPDATE ON TABLE "public"."user_level_master" TO "authenticated";
GRANT DELETE ON TABLE "public"."user_level_master" TO "authenticated";
GRANT TRUNCATE ON TABLE "public"."user_level_master" TO "authenticated";
GRANT REFERENCES ON TABLE "public"."user_level_master" TO "authenticated";
GRANT TRIGGER ON TABLE "public"."user_level_master" TO "authenticated";
GRANT MAINTAIN ON TABLE "public"."user_level_master" TO "authenticated";
GRANT INSERT ON TABLE "public"."user_level_master" TO "service_role";
GRANT SELECT ON TABLE "public"."user_level_master" TO "service_role";
GRANT UPDATE ON TABLE "public"."user_level_master" TO "service_role";
GRANT DELETE ON TABLE "public"."user_level_master" TO "service_role";
GRANT TRUNCATE ON TABLE "public"."user_level_master" TO "service_role";
GRANT REFERENCES ON TABLE "public"."user_level_master" TO "service_role";
GRANT TRIGGER ON TABLE "public"."user_level_master" TO "service_role";
GRANT MAINTAIN ON TABLE "public"."user_level_master" TO "service_role";
GRANT INSERT ON TABLE "public"."user_lifetime_onboarding_grants" TO "service_role";
GRANT SELECT ON TABLE "public"."user_lifetime_onboarding_grants" TO "service_role";
GRANT UPDATE ON TABLE "public"."user_lifetime_onboarding_grants" TO "service_role";
GRANT DELETE ON TABLE "public"."user_lifetime_onboarding_grants" TO "service_role";
GRANT TRUNCATE ON TABLE "public"."user_lifetime_onboarding_grants" TO "service_role";
GRANT REFERENCES ON TABLE "public"."user_lifetime_onboarding_grants" TO "service_role";
GRANT TRIGGER ON TABLE "public"."user_lifetime_onboarding_grants" TO "service_role";
GRANT MAINTAIN ON TABLE "public"."user_lifetime_onboarding_grants" TO "service_role";
GRANT SELECT ON TABLE "public"."user_lifetime_onboarding_grants" TO "authenticated";
GRANT SELECT ON TABLE "public"."user_login_bonuses" TO "authenticated";
GRANT TRUNCATE ON TABLE "public"."user_login_bonuses" TO "authenticated";
GRANT REFERENCES ON TABLE "public"."user_login_bonuses" TO "authenticated";
GRANT TRIGGER ON TABLE "public"."user_login_bonuses" TO "authenticated";
GRANT MAINTAIN ON TABLE "public"."user_login_bonuses" TO "authenticated";
GRANT INSERT ON TABLE "public"."user_login_bonuses" TO "service_role";
GRANT SELECT ON TABLE "public"."user_login_bonuses" TO "service_role";
GRANT UPDATE ON TABLE "public"."user_login_bonuses" TO "service_role";
GRANT DELETE ON TABLE "public"."user_login_bonuses" TO "service_role";
GRANT TRUNCATE ON TABLE "public"."user_login_bonuses" TO "service_role";
GRANT REFERENCES ON TABLE "public"."user_login_bonuses" TO "service_role";
GRANT TRIGGER ON TABLE "public"."user_login_bonuses" TO "service_role";
GRANT MAINTAIN ON TABLE "public"."user_login_bonuses" TO "service_role";
GRANT INSERT ON TABLE "public"."user_main_formations" TO "service_role";
GRANT SELECT ON TABLE "public"."user_main_formations" TO "service_role";
GRANT UPDATE ON TABLE "public"."user_main_formations" TO "service_role";
GRANT DELETE ON TABLE "public"."user_main_formations" TO "service_role";
GRANT TRUNCATE ON TABLE "public"."user_main_formations" TO "service_role";
GRANT REFERENCES ON TABLE "public"."user_main_formations" TO "service_role";
GRANT TRIGGER ON TABLE "public"."user_main_formations" TO "service_role";
GRANT MAINTAIN ON TABLE "public"."user_main_formations" TO "service_role";
GRANT SELECT ON TABLE "public"."user_missions" TO "authenticated";
GRANT TRUNCATE ON TABLE "public"."user_missions" TO "authenticated";
GRANT REFERENCES ON TABLE "public"."user_missions" TO "authenticated";
GRANT TRIGGER ON TABLE "public"."user_missions" TO "authenticated";
GRANT MAINTAIN ON TABLE "public"."user_missions" TO "authenticated";
GRANT INSERT ON TABLE "public"."user_missions" TO "service_role";
GRANT SELECT ON TABLE "public"."user_missions" TO "service_role";
GRANT UPDATE ON TABLE "public"."user_missions" TO "service_role";
GRANT DELETE ON TABLE "public"."user_missions" TO "service_role";
GRANT TRUNCATE ON TABLE "public"."user_missions" TO "service_role";
GRANT REFERENCES ON TABLE "public"."user_missions" TO "service_role";
GRANT TRIGGER ON TABLE "public"."user_missions" TO "service_role";
GRANT MAINTAIN ON TABLE "public"."user_missions" TO "service_role";
GRANT SELECT ON TABLE "public"."user_monthly_passes" TO "authenticated";
GRANT MAINTAIN ON TABLE "public"."user_monthly_passes" TO "authenticated";
GRANT INSERT ON TABLE "public"."user_monthly_passes" TO "service_role";
GRANT SELECT ON TABLE "public"."user_monthly_passes" TO "service_role";
GRANT UPDATE ON TABLE "public"."user_monthly_passes" TO "service_role";
GRANT DELETE ON TABLE "public"."user_monthly_passes" TO "service_role";
GRANT TRUNCATE ON TABLE "public"."user_monthly_passes" TO "service_role";
GRANT REFERENCES ON TABLE "public"."user_monthly_passes" TO "service_role";
GRANT TRIGGER ON TABLE "public"."user_monthly_passes" TO "service_role";
GRANT MAINTAIN ON TABLE "public"."user_monthly_passes" TO "service_role";
GRANT INSERT ON TABLE "public"."user_power_rankings" TO "service_role";
GRANT SELECT ON TABLE "public"."user_power_rankings" TO "service_role";
GRANT UPDATE ON TABLE "public"."user_power_rankings" TO "service_role";
GRANT DELETE ON TABLE "public"."user_power_rankings" TO "service_role";
GRANT TRUNCATE ON TABLE "public"."user_power_rankings" TO "service_role";
GRANT REFERENCES ON TABLE "public"."user_power_rankings" TO "service_role";
GRANT TRIGGER ON TABLE "public"."user_power_rankings" TO "service_role";
GRANT MAINTAIN ON TABLE "public"."user_power_rankings" TO "service_role";
GRANT INSERT ON TABLE "public"."user_profile_decorations" TO "service_role";
GRANT SELECT ON TABLE "public"."user_profile_decorations" TO "service_role";
GRANT UPDATE ON TABLE "public"."user_profile_decorations" TO "service_role";
GRANT DELETE ON TABLE "public"."user_profile_decorations" TO "service_role";
GRANT TRUNCATE ON TABLE "public"."user_profile_decorations" TO "service_role";
GRANT REFERENCES ON TABLE "public"."user_profile_decorations" TO "service_role";
GRANT TRIGGER ON TABLE "public"."user_profile_decorations" TO "service_role";
GRANT MAINTAIN ON TABLE "public"."user_profile_decorations" TO "service_role";
GRANT INSERT ON TABLE "public"."user_profile_decorations" TO "authenticated";
GRANT SELECT ON TABLE "public"."user_profile_decorations" TO "authenticated";
GRANT INSERT ON TABLE "public"."user_quest_first_clears" TO "anon";
GRANT SELECT ON TABLE "public"."user_quest_first_clears" TO "anon";
GRANT UPDATE ON TABLE "public"."user_quest_first_clears" TO "anon";
GRANT DELETE ON TABLE "public"."user_quest_first_clears" TO "anon";
GRANT TRUNCATE ON TABLE "public"."user_quest_first_clears" TO "anon";
GRANT REFERENCES ON TABLE "public"."user_quest_first_clears" TO "anon";
GRANT TRIGGER ON TABLE "public"."user_quest_first_clears" TO "anon";
GRANT MAINTAIN ON TABLE "public"."user_quest_first_clears" TO "anon";
GRANT INSERT ON TABLE "public"."user_quest_first_clears" TO "authenticated";
GRANT SELECT ON TABLE "public"."user_quest_first_clears" TO "authenticated";
GRANT UPDATE ON TABLE "public"."user_quest_first_clears" TO "authenticated";
GRANT DELETE ON TABLE "public"."user_quest_first_clears" TO "authenticated";
GRANT TRUNCATE ON TABLE "public"."user_quest_first_clears" TO "authenticated";
GRANT REFERENCES ON TABLE "public"."user_quest_first_clears" TO "authenticated";
GRANT TRIGGER ON TABLE "public"."user_quest_first_clears" TO "authenticated";
GRANT MAINTAIN ON TABLE "public"."user_quest_first_clears" TO "authenticated";
GRANT INSERT ON TABLE "public"."user_quest_first_clears" TO "service_role";
GRANT SELECT ON TABLE "public"."user_quest_first_clears" TO "service_role";
GRANT UPDATE ON TABLE "public"."user_quest_first_clears" TO "service_role";
GRANT DELETE ON TABLE "public"."user_quest_first_clears" TO "service_role";
GRANT TRUNCATE ON TABLE "public"."user_quest_first_clears" TO "service_role";
GRANT REFERENCES ON TABLE "public"."user_quest_first_clears" TO "service_role";
GRANT TRIGGER ON TABLE "public"."user_quest_first_clears" TO "service_role";
GRANT MAINTAIN ON TABLE "public"."user_quest_first_clears" TO "service_role";
GRANT INSERT ON TABLE "public"."user_raid_daily_attempts" TO "service_role";
GRANT SELECT ON TABLE "public"."user_raid_daily_attempts" TO "service_role";
GRANT UPDATE ON TABLE "public"."user_raid_daily_attempts" TO "service_role";
GRANT DELETE ON TABLE "public"."user_raid_daily_attempts" TO "service_role";
GRANT TRUNCATE ON TABLE "public"."user_raid_daily_attempts" TO "service_role";
GRANT REFERENCES ON TABLE "public"."user_raid_daily_attempts" TO "service_role";
GRANT TRIGGER ON TABLE "public"."user_raid_daily_attempts" TO "service_role";
GRANT MAINTAIN ON TABLE "public"."user_raid_daily_attempts" TO "service_role";
GRANT SELECT ON TABLE "public"."user_raid_daily_attempts" TO "authenticated";
GRANT INSERT ON TABLE "public"."user_shop_purchases" TO "service_role";
GRANT SELECT ON TABLE "public"."user_shop_purchases" TO "service_role";
GRANT UPDATE ON TABLE "public"."user_shop_purchases" TO "service_role";
GRANT DELETE ON TABLE "public"."user_shop_purchases" TO "service_role";
GRANT TRUNCATE ON TABLE "public"."user_shop_purchases" TO "service_role";
GRANT REFERENCES ON TABLE "public"."user_shop_purchases" TO "service_role";
GRANT TRIGGER ON TABLE "public"."user_shop_purchases" TO "service_role";
GRANT MAINTAIN ON TABLE "public"."user_shop_purchases" TO "service_role";
GRANT SELECT ON TABLE "public"."user_shop_purchases" TO "authenticated";
GRANT SELECT ON TABLE "public"."user_skills" TO "anon";
GRANT TRUNCATE ON TABLE "public"."user_skills" TO "anon";
GRANT REFERENCES ON TABLE "public"."user_skills" TO "anon";
GRANT TRIGGER ON TABLE "public"."user_skills" TO "anon";
GRANT MAINTAIN ON TABLE "public"."user_skills" TO "anon";
GRANT SELECT ON TABLE "public"."user_skills" TO "authenticated";
GRANT TRUNCATE ON TABLE "public"."user_skills" TO "authenticated";
GRANT REFERENCES ON TABLE "public"."user_skills" TO "authenticated";
GRANT TRIGGER ON TABLE "public"."user_skills" TO "authenticated";
GRANT MAINTAIN ON TABLE "public"."user_skills" TO "authenticated";
GRANT INSERT ON TABLE "public"."user_skills" TO "service_role";
GRANT SELECT ON TABLE "public"."user_skills" TO "service_role";
GRANT UPDATE ON TABLE "public"."user_skills" TO "service_role";
GRANT DELETE ON TABLE "public"."user_skills" TO "service_role";
GRANT TRUNCATE ON TABLE "public"."user_skills" TO "service_role";
GRANT REFERENCES ON TABLE "public"."user_skills" TO "service_role";
GRANT TRIGGER ON TABLE "public"."user_skills" TO "service_role";
GRANT MAINTAIN ON TABLE "public"."user_skills" TO "service_role";
GRANT INSERT ON TABLE "public"."user_titles" TO "anon";
GRANT SELECT ON TABLE "public"."user_titles" TO "anon";
GRANT UPDATE ON TABLE "public"."user_titles" TO "anon";
GRANT DELETE ON TABLE "public"."user_titles" TO "anon";
GRANT TRUNCATE ON TABLE "public"."user_titles" TO "anon";
GRANT REFERENCES ON TABLE "public"."user_titles" TO "anon";
GRANT TRIGGER ON TABLE "public"."user_titles" TO "anon";
GRANT MAINTAIN ON TABLE "public"."user_titles" TO "anon";
GRANT INSERT ON TABLE "public"."user_titles" TO "authenticated";
GRANT SELECT ON TABLE "public"."user_titles" TO "authenticated";
GRANT UPDATE ON TABLE "public"."user_titles" TO "authenticated";
GRANT DELETE ON TABLE "public"."user_titles" TO "authenticated";
GRANT TRUNCATE ON TABLE "public"."user_titles" TO "authenticated";
GRANT REFERENCES ON TABLE "public"."user_titles" TO "authenticated";
GRANT TRIGGER ON TABLE "public"."user_titles" TO "authenticated";
GRANT MAINTAIN ON TABLE "public"."user_titles" TO "authenticated";
GRANT INSERT ON TABLE "public"."user_titles" TO "service_role";
GRANT SELECT ON TABLE "public"."user_titles" TO "service_role";
GRANT UPDATE ON TABLE "public"."user_titles" TO "service_role";
GRANT DELETE ON TABLE "public"."user_titles" TO "service_role";
GRANT TRUNCATE ON TABLE "public"."user_titles" TO "service_role";
GRANT REFERENCES ON TABLE "public"."user_titles" TO "service_role";
GRANT TRIGGER ON TABLE "public"."user_titles" TO "service_role";
GRANT MAINTAIN ON TABLE "public"."user_titles" TO "service_role";
GRANT SELECT ON TABLE "public"."users" TO "anon";
GRANT TRUNCATE ON TABLE "public"."users" TO "anon";
GRANT REFERENCES ON TABLE "public"."users" TO "anon";
GRANT TRIGGER ON TABLE "public"."users" TO "anon";
GRANT MAINTAIN ON TABLE "public"."users" TO "anon";
GRANT SELECT ON TABLE "public"."users" TO "authenticated";
GRANT MAINTAIN ON TABLE "public"."users" TO "authenticated";
GRANT INSERT ON TABLE "public"."users" TO "service_role";
GRANT SELECT ON TABLE "public"."users" TO "service_role";
GRANT UPDATE ON TABLE "public"."users" TO "service_role";
GRANT DELETE ON TABLE "public"."users" TO "service_role";
GRANT TRUNCATE ON TABLE "public"."users" TO "service_role";
GRANT REFERENCES ON TABLE "public"."users" TO "service_role";
GRANT TRIGGER ON TABLE "public"."users" TO "service_role";
GRANT MAINTAIN ON TABLE "public"."users" TO "service_role";
GRANT SELECT ON TABLE "public"."user_patrols" TO "anon";
GRANT TRUNCATE ON TABLE "public"."user_patrols" TO "anon";
GRANT REFERENCES ON TABLE "public"."user_patrols" TO "anon";
GRANT TRIGGER ON TABLE "public"."user_patrols" TO "anon";
GRANT MAINTAIN ON TABLE "public"."user_patrols" TO "anon";
GRANT SELECT ON TABLE "public"."user_patrols" TO "authenticated";
GRANT TRUNCATE ON TABLE "public"."user_patrols" TO "authenticated";
GRANT REFERENCES ON TABLE "public"."user_patrols" TO "authenticated";
GRANT TRIGGER ON TABLE "public"."user_patrols" TO "authenticated";
GRANT MAINTAIN ON TABLE "public"."user_patrols" TO "authenticated";
GRANT INSERT ON TABLE "public"."user_patrols" TO "service_role";
GRANT SELECT ON TABLE "public"."user_patrols" TO "service_role";
GRANT UPDATE ON TABLE "public"."user_patrols" TO "service_role";
GRANT DELETE ON TABLE "public"."user_patrols" TO "service_role";
GRANT TRUNCATE ON TABLE "public"."user_patrols" TO "service_role";
GRANT REFERENCES ON TABLE "public"."user_patrols" TO "service_role";
GRANT TRIGGER ON TABLE "public"."user_patrols" TO "service_role";
GRANT MAINTAIN ON TABLE "public"."user_patrols" TO "service_role";
REVOKE ALL ON FUNCTION "public"."admin_respawn_raid_boss"(p_boss_id text, p_max_hp integer, p_base_id text) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."admin_respawn_raid_boss"(p_boss_id text, p_max_hp integer, p_base_id text) TO "service_role";
REVOKE ALL ON FUNCTION "public"."admin_update_guild"(p_guild_id uuid, p_funds numeric, p_level integer, p_xp integer) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."admin_update_guild"(p_guild_id uuid, p_funds numeric, p_level integer, p_xp integer) TO "service_role";
REVOKE ALL ON FUNCTION "public"."admin_update_guild_finals"(p_guild_id uuid, p_funds_add numeric, p_decorations jsonb) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."admin_update_guild_finals"(p_guild_id uuid, p_funds_add numeric, p_decorations jsonb) TO "service_role";
REVOKE ALL ON FUNCTION "public"."canonical_equipment_runtime_projection_00171"(p_user_id uuid, p_user_character_id uuid) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."canonical_equipment_runtime_projection_00171"(p_user_id uuid, p_user_character_id uuid) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."canonical_equipment_runtime_projection_00171"(p_user_id uuid, p_user_character_id uuid) TO "service_role";
REVOKE ALL ON FUNCTION "public"."canonical_funnel_milestone_satisfied"(p_user_id uuid, p_trigger_type text) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."canonical_funnel_milestone_satisfied"(p_user_id uuid, p_trigger_type text) TO "service_role";
REVOKE ALL ON FUNCTION "public"."canonical_guild_member_cap"(p_guild_id uuid) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."canonical_guild_member_cap"(p_guild_id uuid) TO "service_role";
REVOKE ALL ON FUNCTION "public"."canonical_pvp_expected_score"(p_player integer, p_opponent integer) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."canonical_pvp_expected_score"(p_player integer, p_opponent integer) TO PUBLIC;
GRANT EXECUTE ON FUNCTION "public"."canonical_pvp_expected_score"(p_player integer, p_opponent integer) TO "anon";
GRANT EXECUTE ON FUNCTION "public"."canonical_pvp_expected_score"(p_player integer, p_opponent integer) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."canonical_pvp_expected_score"(p_player integer, p_opponent integer) TO "service_role";
REVOKE ALL ON FUNCTION "public"."is_operations_maintenance_tester"() FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."is_operations_maintenance_tester"() TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."is_operations_maintenance_tester"() TO "service_role";
REVOKE ALL ON FUNCTION "public"."billing_reserve_order"(p_user_id uuid, p_request_id uuid, p_product_id text) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."billing_reserve_order"(p_user_id uuid, p_request_id uuid, p_product_id text) TO "service_role";
REVOKE ALL ON FUNCTION "public"."billing_attach_session"(p_order_id uuid, p_session_id text) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."billing_attach_session"(p_order_id uuid, p_session_id text) TO "service_role";
REVOKE ALL ON FUNCTION "public"."billing_grant_order"(p_order_id uuid, p_session_id text, p_amount_jpy integer, p_currency text) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."billing_grant_order"(p_order_id uuid, p_session_id text, p_amount_jpy integer, p_currency text) TO "service_role";
REVOKE ALL ON FUNCTION "public"."billing_expire_order"(p_order_id uuid, p_session_id text) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."billing_expire_order"(p_order_id uuid, p_session_id text) TO "service_role";
REVOKE ALL ON FUNCTION "public"."billing_buy_dia_product"(p_user_id uuid, p_request_id uuid, p_product_id text) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."billing_buy_dia_product"(p_user_id uuid, p_request_id uuid, p_product_id text) TO "service_role";
REVOKE ALL ON FUNCTION "public"."billing_mark_lot_claimed"() FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."billing_mark_lot_claimed"() TO "service_role";
REVOKE ALL ON FUNCTION "public"."billing_apply_lot_delta"(p_user uuid, p_item text, p_old bigint, p_new bigint) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."billing_apply_lot_delta"(p_user uuid, p_item text, p_old bigint, p_new bigint) TO "service_role";
REVOKE ALL ON FUNCTION "public"."billing_asset_balance_trigger"() FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."billing_asset_balance_trigger"() TO "service_role";
REVOKE ALL ON FUNCTION "public"."billing_refresh_paid_assets"() FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."billing_refresh_paid_assets"() TO "service_role";
GRANT EXECUTE ON FUNCTION "public"."billing_refresh_paid_assets"() TO "authenticated";
REVOKE ALL ON FUNCTION "public"."billing_session_matches"(p_order_id uuid, p_session_id text) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."billing_session_matches"(p_order_id uuid, p_session_id text) TO "service_role";
REVOKE ALL ON FUNCTION "public"."billing_reserve_order"(p_user_id uuid, p_request_id uuid, p_product_id text, p_mode text) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."billing_reserve_order"(p_user_id uuid, p_request_id uuid, p_product_id text, p_mode text) TO "service_role";
REVOKE ALL ON FUNCTION "public"."billing_dia_balance_trigger"() FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."billing_dia_balance_trigger"() TO "service_role";
REVOKE ALL ON FUNCTION "public"."accept_friend_request"(p_request_id uuid) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."accept_friend_request"(p_request_id uuid) TO "service_role";
GRANT EXECUTE ON FUNCTION "public"."accept_friend_request"(p_request_id uuid) TO "authenticated";
REVOKE ALL ON FUNCTION "public"."accept_friend_request"(p_user_id uuid, p_friend_id uuid) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."accept_friend_request"(p_user_id uuid, p_friend_id uuid) TO "service_role";
REVOKE ALL ON FUNCTION "public"."accept_friend_request_core_20260823"(p_request_id uuid) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."accept_friend_request_core_20260823"(p_request_id uuid) TO "service_role";
REVOKE ALL ON FUNCTION "public"."acknowledge_ranking_reward_notifications"(p_notification_ids uuid[]) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."acknowledge_ranking_reward_notifications"(p_notification_ids uuid[]) TO "service_role";
GRANT EXECUTE ON FUNCTION "public"."acknowledge_ranking_reward_notifications"(p_notification_ids uuid[]) TO "authenticated";
REVOKE ALL ON FUNCTION "public"."activate_gvg_match_session"(p_match_session_id uuid) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."activate_gvg_match_session"(p_match_session_id uuid) TO "anon";
GRANT EXECUTE ON FUNCTION "public"."activate_gvg_match_session"(p_match_session_id uuid) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."activate_gvg_match_session"(p_match_session_id uuid) TO "service_role";
REVOKE ALL ON FUNCTION "public"."activate_preopen_guild_power_season"() FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."activate_preopen_guild_power_season"() TO "service_role";
REVOKE ALL ON FUNCTION "public"."add_test_cash"(p_user_id uuid, p_amount integer) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."add_test_cash"(p_user_id uuid, p_amount integer) TO "service_role";
REVOKE ALL ON FUNCTION "public"."add_test_diamonds"(p_user_id uuid) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."add_test_diamonds"(p_user_id uuid) TO "service_role";
REVOKE ALL ON FUNCTION "public"."add_test_diamonds"(p_user_id uuid, p_amount integer) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."add_test_diamonds"(p_user_id uuid, p_amount integer) TO "service_role";
REVOKE ALL ON FUNCTION "public"."add_user_vitality"(p_user_id uuid, p_amount integer) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."add_user_vitality"(p_user_id uuid, p_amount integer) TO "service_role";
REVOKE ALL ON FUNCTION "public"."add_user_xp"(p_user_id uuid, p_xp_amount integer) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."add_user_xp"(p_user_id uuid, p_xp_amount integer) TO "service_role";
GRANT EXECUTE ON FUNCTION "public"."add_user_xp"(p_user_id uuid, p_xp_amount integer) TO "authenticated";
REVOKE ALL ON FUNCTION "public"."admin_add_guild_funds"(p_guild_id uuid, p_amount numeric) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."admin_add_guild_funds"(p_guild_id uuid, p_amount numeric) TO "service_role";
REVOKE ALL ON FUNCTION "public"."admin_reset_daily_missions"(p_user_id uuid, p_mission_ids text[]) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."admin_reset_daily_missions"(p_user_id uuid, p_mission_ids text[]) TO "service_role";
REVOKE ALL ON FUNCTION "public"."advance_all_ranking_seasons"(p_at timestamp with time zone) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."advance_all_ranking_seasons"(p_at timestamp with time zone) TO "service_role";
REVOKE ALL ON FUNCTION "public"."apply_recommended_main_loadout"() FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."apply_recommended_main_loadout"() TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."apply_recommended_main_loadout"() TO "service_role";
REVOKE ALL ON FUNCTION "public"."assert_feature_mutation_allowed"(p_feature_key text) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."assert_feature_mutation_allowed"(p_feature_key text) TO PUBLIC;
GRANT EXECUTE ON FUNCTION "public"."assert_feature_mutation_allowed"(p_feature_key text) TO "anon";
GRANT EXECUTE ON FUNCTION "public"."assert_feature_mutation_allowed"(p_feature_key text) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."assert_feature_mutation_allowed"(p_feature_key text) TO "service_role";
REVOKE ALL ON FUNCTION "public"."canonical_equipment_level_cap"(p_plus_val integer) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."canonical_equipment_level_cap"(p_plus_val integer) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."canonical_equipment_level_cap"(p_plus_val integer) TO "service_role";
REVOKE ALL ON FUNCTION "public"."canonical_pvp_rating_delta"(p_player integer, p_opponent integer, p_result text) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."canonical_pvp_rating_delta"(p_player integer, p_opponent integer, p_result text) TO PUBLIC;
GRANT EXECUTE ON FUNCTION "public"."canonical_pvp_rating_delta"(p_player integer, p_opponent integer, p_result text) TO "anon";
GRANT EXECUTE ON FUNCTION "public"."canonical_pvp_rating_delta"(p_player integer, p_opponent integer, p_result text) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."canonical_pvp_rating_delta"(p_player integer, p_opponent integer, p_result text) TO "service_role";
REVOKE ALL ON FUNCTION "public"."canonical_pvp_soft_reset"(p_rating integer) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."canonical_pvp_soft_reset"(p_rating integer) TO PUBLIC;
GRANT EXECUTE ON FUNCTION "public"."canonical_pvp_soft_reset"(p_rating integer) TO "anon";
GRANT EXECUTE ON FUNCTION "public"."canonical_pvp_soft_reset"(p_rating integer) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."canonical_pvp_soft_reset"(p_rating integer) TO "service_role";
REVOKE ALL ON FUNCTION "public"."can_initialize_maintenance_google_player"() FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."can_initialize_maintenance_google_player"() TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."can_initialize_maintenance_google_player"() TO "service_role";
REVOKE ALL ON FUNCTION "public"."advance_current_tutorial_after_growth"() FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."advance_current_tutorial_after_growth"() TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."advance_current_tutorial_after_growth"() TO "service_role";
REVOKE ALL ON FUNCTION "public"."advance_ranking_season"(p_type text, p_at timestamp with time zone) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."advance_ranking_season"(p_type text, p_at timestamp with time zone) TO "service_role";
REVOKE ALL ON FUNCTION "public"."apply_canonical_guild_exp"(p_guild_id uuid, p_exp integer) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."apply_canonical_guild_exp"(p_guild_id uuid, p_exp integer) TO "service_role";
REVOKE ALL ON FUNCTION "public"."apply_character_awakening_equivalent"(p_user_id uuid, p_character_id uuid, p_equivalents integer) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."apply_character_awakening_equivalent"(p_user_id uuid, p_character_id uuid, p_equivalents integer) TO "service_role";
REVOKE ALL ON FUNCTION "public"."apply_current_player_invitation"(p_gift_code text) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."apply_current_player_invitation"(p_gift_code text) TO "service_role";
REVOKE ALL ON FUNCTION "public"."apply_user_xp"(p_user_id uuid, p_xp_amount integer) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."apply_user_xp"(p_user_id uuid, p_xp_amount integer) TO "service_role";
REVOKE ALL ON FUNCTION "public"."assert_pvp_boundary_replay_continuity"(p_season_id uuid, p_transition_at timestamp with time zone) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."assert_pvp_boundary_replay_continuity"(p_season_id uuid, p_transition_at timestamp with time zone) TO "service_role";
REVOKE ALL ON FUNCTION "public"."audit_feature_operating_state_change"() FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."audit_feature_operating_state_change"() TO PUBLIC;
GRANT EXECUTE ON FUNCTION "public"."audit_feature_operating_state_change"() TO "anon";
GRANT EXECUTE ON FUNCTION "public"."audit_feature_operating_state_change"() TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."audit_feature_operating_state_change"() TO "service_role";
REVOKE ALL ON FUNCTION "public"."awaken_character"(p_character_id uuid) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."awaken_character"(p_character_id uuid) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."awaken_character"(p_character_id uuid) TO "service_role";
REVOKE ALL ON FUNCTION "public"."begin_gvg_attack"(p_match_session_id uuid) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."begin_gvg_attack"(p_match_session_id uuid) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."begin_gvg_attack"(p_match_session_id uuid) TO "service_role";
REVOKE ALL ON FUNCTION "public"."begin_gvg_attack_core_20260817"(p_match_session_id uuid) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."begin_gvg_attack_core_20260817"(p_match_session_id uuid) TO "service_role";
REVOKE ALL ON FUNCTION "public"."build_server_battle_snapshot"(p_user_id uuid, p_character_ids text[], p_team text) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."build_server_battle_snapshot"(p_user_id uuid, p_character_ids text[], p_team text) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."build_server_battle_snapshot"(p_user_id uuid, p_character_ids text[], p_team text) TO "service_role";
REVOKE ALL ON FUNCTION "public"."build_server_battle_snapshot_00168"(p_user_id uuid, p_character_ids text[], p_team text) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."build_server_battle_snapshot_00168"(p_user_id uuid, p_character_ids text[], p_team text) TO "service_role";
REVOKE ALL ON FUNCTION "public"."buy_avatar_part"(p_user_id uuid, p_part_id text, p_currency_type text, p_price integer) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."buy_avatar_part"(p_user_id uuid, p_part_id text, p_currency_type text, p_price integer) TO "service_role";
REVOKE ALL ON FUNCTION "public"."buy_guild_decoration"(p_user_id uuid, p_guild_id uuid, p_decoration_id text, p_cost integer) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."buy_guild_decoration"(p_user_id uuid, p_guild_id uuid, p_decoration_id text, p_cost integer) TO "service_role";
REVOKE ALL ON FUNCTION "public"."buy_guild_decoration_v2"(p_guild_id uuid, p_type text, p_item_id text, p_cost bigint) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."buy_guild_decoration_v2"(p_guild_id uuid, p_type text, p_item_id text, p_cost bigint) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."buy_guild_decoration_v2"(p_guild_id uuid, p_type text, p_item_id text, p_cost bigint) TO "service_role";
REVOKE ALL ON FUNCTION "public"."buy_normal_shop_product"(p_user_id uuid, p_product_id text) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."buy_normal_shop_product"(p_user_id uuid, p_product_id text) TO "service_role";
GRANT EXECUTE ON FUNCTION "public"."buy_normal_shop_product"(p_user_id uuid, p_product_id text) TO "authenticated";
REVOKE ALL ON FUNCTION "public"."buy_normal_shop_product_core_20260823"(p_user_id uuid, p_product_id text) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."buy_normal_shop_product_core_20260823"(p_user_id uuid, p_product_id text) TO "service_role";
REVOKE ALL ON FUNCTION "public"."calculate_user_character_power"(p_user_id uuid, p_user_character_id uuid) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."calculate_user_character_power"(p_user_id uuid, p_user_character_id uuid) TO "service_role";
REVOKE ALL ON FUNCTION "public"."capture_lifetime_onboarding_grant_after_formation"() FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."capture_lifetime_onboarding_grant_after_formation"() TO PUBLIC;
GRANT EXECUTE ON FUNCTION "public"."capture_lifetime_onboarding_grant_after_formation"() TO "anon";
GRANT EXECUTE ON FUNCTION "public"."capture_lifetime_onboarding_grant_after_formation"() TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."capture_lifetime_onboarding_grant_after_formation"() TO "service_role";
REVOKE ALL ON FUNCTION "public"."calculate_user_total_power"(p_user_id uuid) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."calculate_user_total_power"(p_user_id uuid) TO "service_role";
REVOKE ALL ON FUNCTION "public"."cancel_guild_join_request"(p_request_id uuid) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."cancel_guild_join_request"(p_request_id uuid) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."cancel_guild_join_request"(p_request_id uuid) TO "service_role";
REVOKE ALL ON FUNCTION "public"."cancel_unresolved_gvg_attack"(p_attack_id uuid) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."cancel_unresolved_gvg_attack"(p_attack_id uuid) TO "anon";
GRANT EXECUTE ON FUNCTION "public"."cancel_unresolved_gvg_attack"(p_attack_id uuid) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."cancel_unresolved_gvg_attack"(p_attack_id uuid) TO "service_role";
REVOKE ALL ON FUNCTION "public"."canonical_character_awakening_required"(p_awakening_level integer) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."canonical_character_awakening_required"(p_awakening_level integer) TO PUBLIC;
GRANT EXECUTE ON FUNCTION "public"."canonical_character_awakening_required"(p_awakening_level integer) TO "anon";
GRANT EXECUTE ON FUNCTION "public"."canonical_character_awakening_required"(p_awakening_level integer) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."canonical_character_awakening_required"(p_awakening_level integer) TO "service_role";
REVOKE ALL ON FUNCTION "public"."canonical_character_stats"(p_character_id text, p_level integer, p_awakening integer) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."canonical_character_stats"(p_character_id text, p_level integer, p_awakening integer) TO PUBLIC;
GRANT EXECUTE ON FUNCTION "public"."canonical_character_stats"(p_character_id text, p_level integer, p_awakening integer) TO "anon";
GRANT EXECUTE ON FUNCTION "public"."canonical_character_stats"(p_character_id text, p_level integer, p_awakening integer) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."canonical_character_stats"(p_character_id text, p_level integer, p_awakening integer) TO "service_role";
REVOKE ALL ON FUNCTION "public"."canonical_equipment_flat_stat"(p_master_flat integer, p_level integer, p_plus_val integer) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."canonical_equipment_flat_stat"(p_master_flat integer, p_level integer, p_plus_val integer) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."canonical_equipment_flat_stat"(p_master_flat integer, p_level integer, p_plus_val integer) TO "service_role";
REVOKE ALL ON FUNCTION "public"."canonical_equipment_lb_multiplier"(p_plus_val integer) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION "public"."canonical_equipment_lb_multiplier"(p_plus_val integer) TO PUBLIC;
