'use client';
import { useMemo, useState } from 'react';
import type { RaidTopEntry, RaidTopEnemy } from '@/domain/raidTop';
import { createTopFixture } from '@/app/qa/raid-top/topFixture';
import { RaidApprovedCard, RaidApprovedChallenge, RaidApprovedContribution, RaidApprovedDetailVisual, RaidApprovedIcon, type RaidApprovedCardData, type RaidApprovedDetailData } from '../../components/raid/RaidApprovedVisual';
import './ApprovedRaidPreview.css';
import './ApprovedRaidScrollbar.css';

const fixture = createTopFixture('approved');
const entries = fixture.participating.status === 'ready' ? fixture.participating.data : [];
const attrLabel: Record<RaidTopEnemy['attribute'], string> = { EVIL: '悪', ORDER: '秩序', JUSTICE: '正義', CHAOS: '混沌', UNKNOWN: '未確認' };
const attrIcon = (value: RaidTopEnemy['attribute']) => value === 'UNKNOWN' ? undefined : `/creative/ui/element-${({ EVIL: 'fire', CHAOS: 'dark', ORDER: 'water', JUSTICE: 'wind' } as Record<string, string>)[value] ?? 'light'}.png`;
const ownerOf = (entry: RaidTopEntry) => entry.room.owner.status === 'available' ? entry.room.owner.value : null;
const enemyOf = (entry: RaidTopEntry) => entry.enemy.status === 'available' ? entry.enemy.value : null;
const remainingOf = (entry: RaidTopEntry) => entry.room.expiresAt.status === 'available' ? Math.max(0, Date.parse(entry.room.expiresAt.value) - Date.now()) : null;
const timeLabel = (value: number | null) => value === null ? '未確認' : Math.ceil(value / 60000) >= 60 ? `${Math.floor(Math.ceil(value / 60000) / 60)}時間${Math.ceil(value / 60000) % 60}分` : `${Math.ceil(value / 60000)}分`;

function cardData(entry: RaidTopEntry): RaidApprovedCardData {
  const enemy = enemyOf(entry); const owner = ownerOf(entry); const hp = entry.room.hp.status === 'available' ? entry.room.hp.value : null; const percent = hp ? Math.round(hp.current / hp.max * 100) : null;
  return { backgroundUrl: enemy?.backgroundUrl, characterUrl: enemy?.leaderImageUrl, bossName: enemy?.bossName ?? '敵情報未確認', attributeLabel: attrLabel[enemy?.attribute ?? 'UNKNOWN'], attributeIconUrl: enemy ? attrIcon(enemy.attribute) : undefined, ownerName: owner?.name ?? '未確認', ownerImageUrl: owner?.leaderIconUrl.status === 'available' ? owner.leaderIconUrl.value ?? undefined : undefined, hpPercent: percent, hpText: `HP ${percent === null ? '未確認' : `${percent}%`}`, remainingLabel: timeLabel(remainingOf(entry)), participantLabel: entry.room.participantCount.status === 'available' ? `${entry.room.participantCount.value}/20人` : '未確認', badgeLabel: entry.origin?.status === 'available' && entry.origin.value === 'territory' ? '領土侵攻' : 'エンカウント', statusLabel: '参加中' };
}

function PreviewCard({ entry }: { entry: RaidTopEntry }) { return <RaidApprovedCard data={cardData(entry)} action={<button type="button">続きへ ›</button>} />; }
function Detail({ lower = false }: { lower?: boolean }) {
  const entry = entries[1] ?? entries[0]; const enemy = enemyOf(entry); const owner = ownerOf(entry); const hp = entry.room.hp.status === 'available' ? entry.room.hp.value : null; const percent = hp ? Math.round(hp.current / hp.max * 100) : null;
  const data: RaidApprovedDetailData = { areaLabel: enemy?.areaName ?? 'エリア未確認', bossName: enemy?.bossName ?? '敵情報未確認', backgroundUrl: enemy?.backgroundUrl, characterUrl: enemy?.leaderImageUrl, ownerName: owner?.name ?? '未確認', ownerImageUrl: owner?.leaderIconUrl.status === 'available' ? owner.leaderIconUrl.value ?? undefined : undefined, guildLabel: '確認用Guild', hpPercent: percent, hpValueLabel: hp ? `${hp.current.toLocaleString()} / ${hp.max.toLocaleString()}` : 'HP未確認', remainingLabel: timeLabel(remainingOf(entry)), expiryLabel: '期限確認済み', participantLabel: entry.room.participantCount.status === 'available' ? `${entry.room.participantCount.value}人` : '未確認', faces: [] };
  const actions = !lower && <><button type="button"><RaidApprovedIcon name="swords" /><span>敵情報</span></button><button type="button"><RaidApprovedIcon name="people" /><span>参加者</span></button><button type="button"><RaidApprovedIcon name="scroll" /><span>報酬</span></button><button type="button"><RaidApprovedIcon name="handshake" /><span>救援</span></button></>;
  return <section className="raid-approved-preview-detail"><RaidApprovedDetailVisual data={data} compact={lower} actions={actions} contribution={<RaidApprovedContribution damageLabel="未挑戦" damageValue="0" battlesLabel="0戦" eligibilityLabel="討伐資格まで　あと3勝" />} challenge={<RaidApprovedChallenge><RaidApprovedIcon name="swords" /><strong>挑む</strong><span><RaidApprovedIcon name="clock" />消費行動力 5</span></RaidApprovedChallenge>} /></section>;
}

function ResourceHeader({ entry }: { entry: RaidTopEntry }) { const owner = ownerOf(entry); const portrait = owner?.leaderIconUrl.status === 'available' ? owner.leaderIconUrl.value : undefined; return <><header className="raid-approved__header"><div className="raid-approved__user">{portrait && <img src={portrait} alt="" />}<div><strong>{owner?.name ?? '開催者情報未確認'}</strong><span>Lv.1　◇ 同盟 —</span></div></div><button className="raid-approved__menu" type="button">MENU　≡</button></header><div className="raid-approved__resources"><span><img src="/ui/sengoku/13-coin.png" alt="" />30,000</span><span><img src="/ui/sengoku/16-diamond.png" alt="" />1,000</span><span><img src="/ui/sengoku/14-energy.png" alt="" />50/50</span></div></>; }
function Footer() { return <nav className="raid-approved__footer" aria-label="メインナビゲーション">{[['08-castle', 'ホーム'], ['04-fan-sakura', 'クエスト'], ['10-helmet', 'キャラ'], ['06-oni-mask', 'レイド'], ['11-ticket', 'ガチャ']].map(([asset, label]) => <button className={label === 'レイド' ? 'is-active' : ''} key={label} type="button"><img src={`/ui/sengoku/${asset}.png`} alt="" /><span>{label}</span></button>)}</nav>; }
function Listing() { const [tab, setTab] = useState('すべて'); const shown = useMemo(() => [...entries].filter(entry => tab === 'すべて' || (tab === 'エンカウント' && entry.origin?.status === 'available' && entry.origin.value === 'encounter') || (tab === '領土侵攻' && entry.origin?.status === 'available' && entry.origin.value === 'territory')).sort((a, b) => (remainingOf(a) ?? Infinity) - (remainingOf(b) ?? Infinity)), [tab]); return <section className="raid-approved__screen"><div className="raid-approved__screen-head"><h1>レイド</h1><button type="button">更新</button></div><div className="raid-approved__tabs">{['すべて', 'エンカウント', '領土侵攻'].map(value => <button key={value} className={tab === value ? 'is-active' : ''} onClick={() => setTab(value)} type="button">{value}</button>)}</div><div className="raid-approved__list">{shown.map(entry => <PreviewCard key={entry.room.roomId} entry={entry} />)}</div><button className="raid-approved__ended" type="button"><RaidApprovedIcon name="chest" />終了したレイド・未受取報酬 <b>›</b></button></section>; }
export default function ApprovedRaidPreview() { return <main className="raid-approved"><div className="raid-approved__board"><div className="raid-approved__panels">{(['listing', 'detail', 'lower'] as const).map((kind, index) => <div className="raid-approved__panel" key={kind}><h2 className="raid-approved__panel-title">{index === 0 ? '01　レイド一覧' : kind === 'detail' ? '02　レイド詳細' : '03　詳細・下部'}</h2><ResourceHeader entry={entries[0]} />{kind === 'listing' ? <Listing /> : <section className="raid-approved__screen raid-approved__detail-screen"><button className="raid-approved__back" type="button">‹ レイド一覧</button><Detail lower={kind === 'lower'} /></section>}<Footer /></div>)}</div></div></main>; }
