'use client';
import { useMemo, useState } from 'react';
import type { RaidTopEntry, RaidTopEnemy } from '@/domain/raidTop';
import { createTopFixture } from '@/app/qa/raid-top/topFixture';
import './ApprovedRaidPreview.css';
import './ApprovedRaidScrollbar.css';

type IconName = 'clock' | 'people' | 'swords' | 'scroll' | 'handshake' | 'chest' | 'armor' | 'victory' | 'medal';
const icon = (name: IconName, label = '') => <img className="raid-approved__icon" src={`/ui/raid/${name}.svg`} alt={label} />;
const attrLabel: Record<RaidTopEnemy['attribute'], string> = { EVIL: '悪', ORDER: '秩序', JUSTICE: '正義', CHAOS: '混沌', UNKNOWN: '未確認' };
const attrIcon = (value: RaidTopEnemy['attribute']) => value === 'UNKNOWN' ? null : <img className="raid-approved__icon" src={`/ui/rarity/attribute-badge-${value.toLowerCase()}.png`} alt="" />;
const fixture = createTopFixture('approved');
const entries = fixture.participating.status === 'ready' ? fixture.participating.data : [];
function owner(entry: RaidTopEntry) { return entry.room.owner.status === 'available' ? entry.room.owner.value : null; }
function ResourceHeader({ entry }: { entry: RaidTopEntry }) { const player = owner(entry); const portrait = player?.leaderIconUrl.status === 'available' ? player.leaderIconUrl.value : null; return <><header className="raid-approved__header"><div className="raid-approved__user">{portrait && <img src={portrait} alt="" />}<div><strong>{player?.name ?? '開催者情報未確認'}</strong><span>Lv.1　◇ 同盟 —</span></div></div><button className="raid-approved__menu" type="button">MENU　≡</button></header><div className="raid-approved__resources"><span><img className="raid-approved__icon" src="/ui/sengoku/13-coin.png" alt="" />30,000</span><span><img className="raid-approved__icon" src="/ui/sengoku/16-diamond.png" alt="" />1,000</span><span><img className="raid-approved__icon" src="/ui/sengoku/14-energy.png" alt="" />50/50</span></div></>; }
function Footer() { return <nav className="raid-approved__footer" aria-label="メインナビゲーション">{[['08-castle', 'ホーム'], ['04-fan-sakura', 'クエスト'], ['10-helmet', 'キャラ'], ['06-oni-mask', 'レイド'], ['11-ticket', 'ガチャ']].map(([asset, label]) => <button className={label === 'レイド' ? 'is-active' : ''} key={label} type="button"><img src={`/ui/sengoku/${asset}.png`} alt="" /><span>{label}</span></button>)}</nav>; }
function Hero({ enemy, compact = false }: { enemy: RaidTopEnemy; compact?: boolean }) { return <div className={`raid-approved__hero ${compact ? 'is-compact' : ''}`}><img className="raid-approved__hero-bg" src={enemy.backgroundUrl} alt="" /><img className="raid-approved__hero-character" src={enemy.leaderImageUrl} alt="" /><div className="raid-approved__hero-shade" /><div className="raid-approved__boss-title"><h2>{enemy.bossName} <small>Lv.1</small></h2><span>{attrIcon(enemy.attribute)}{attrLabel[enemy.attribute]}属性</span></div></div>; }
function Owner({ entry }: { entry: RaidTopEntry }) { const player = owner(entry); const portrait = player?.leaderIconUrl.status === 'available' ? player.leaderIconUrl.value : null; return <div className="raid-approved__owner">{portrait && <img src={portrait} alt="" />}<strong>開催者　{player?.name ?? '未確認'}</strong></div>; }
function Hp({ entry, detail = false }: { entry: RaidTopEntry; detail?: boolean }) { const hp = entry.room.hp.status === 'available' ? entry.room.hp.value : null; const pct = hp ? Math.max(0, Math.min(100, hp.current / hp.max * 100)) : 0; return <div className="raid-approved__hp"><div className="raid-approved__hp-bar"><span style={{ width: `${pct}%` }} /></div><div className="raid-approved__hp-text">{detail && hp ? `HP　${hp.current.toLocaleString()} / ${hp.max.toLocaleString()}　(${pct.toFixed(0)}%)` : `HP ${hp ? `${pct.toFixed(0)}%` : '未確認'}`}</div></div>; }
function Meta({ entry }: { entry: RaidTopEntry }) { const expiry = entry.room.expiresAt.status === 'available' ? new Date(entry.room.expiresAt.value).toLocaleString('ja-JP', { month: 'numeric', day: 'numeric', hour: '2-digit', minute: '2-digit' }) : '未確認'; const count = entry.room.participantCount.status === 'available' ? `${entry.room.participantCount.value}/20人` : '未確認'; return <div className="raid-approved__meta"><span>{icon('clock')}{expiry}</span><span>{icon('people')}{count}</span></div>; }
function ActionTile({ iconName, label }: { iconName: IconName; label: string }) { return <button className="raid-approved__tile" type="button">{icon(iconName)}<span>{label}</span></button>; }
function ListCard({ entry }: { entry: RaidTopEntry }) { const enemy = entry.enemy.status === 'available' ? entry.enemy.value : null; const origin = entry.origin?.status === 'available' ? entry.origin.value : null; return <article className="raid-approved__list-card"><div className="raid-approved__list-art">{enemy && <><img src={enemy.backgroundUrl} alt="" /><img src={enemy.leaderImageUrl} alt="" /></>}</div><div className="raid-approved__list-copy"><div className="raid-approved__badges"><span>{origin === 'territory' ? '領土侵攻' : 'エンカウント'}</span><span>参加中</span></div><h3>{enemy?.bossName ?? '敵情報未確認'} <small>Lv.1</small></h3>{enemy && <p className="raid-approved__attribute">{attrIcon(enemy.attribute)}{attrLabel[enemy.attribute]}属性</p>}<Owner entry={entry} /><Hp entry={entry} /></div><div className="raid-approved__card-bottom"><Meta entry={entry} /><button type="button">続きへ ›</button></div></article>; }
function Listing() { const [tab, setTab] = useState('すべて'); const shown = useMemo(() => [...entries].filter(entry => { const origin = entry.origin?.status === 'available' ? entry.origin.value : null; return tab === 'すべて' || (tab === 'エンカウント' && origin === 'encounter') || (tab === '領土侵攻' && origin === 'territory'); }).sort((a, b) => Date.parse(a.room.expiresAt.status === 'available' ? a.room.expiresAt.value : '') - Date.parse(b.room.expiresAt.status === 'available' ? b.room.expiresAt.value : '')), [tab]); return <section className="raid-approved__screen"><div className="raid-approved__screen-head"><h1>レイド</h1><button type="button">更新</button></div><div className="raid-approved__tabs">{['すべて', 'エンカウント', '領土侵攻'].map(value => <button key={value} className={tab === value ? 'is-active' : ''} onClick={() => setTab(value)} type="button">{value}</button>)}</div><div className="raid-approved__list">{shown.map(entry => <ListCard key={entry.room.roomId} entry={entry} />)}</div><button className="raid-approved__ended" type="button">{icon('chest')}終了したレイド・未受取報酬 <b>›</b></button></section>; }
function Detail({ lower = false }: { lower?: boolean }) { const entry = entries[1] ?? entries[0]; const enemy = entry.enemy.status === 'available' ? entry.enemy.value : null; return <section className="raid-approved__screen raid-approved__detail-screen"><button className="raid-approved__back" type="button">‹ レイド一覧</button>{enemy && <Hero enemy={enemy} compact={lower} />}<Owner entry={entry} /><Hp entry={entry} detail /><Meta entry={entry} />{!lower && <div className="raid-approved__tiles"><ActionTile iconName="swords" label="敵情報" /><ActionTile iconName="people" label="参加者" /><ActionTile iconName="scroll" label="報酬" /><ActionTile iconName="handshake" label="救援" /></div>}<div className="raid-approved__contribution"><h2>自分の貢献</h2><div className="raid-approved__damage">{icon('swords')}<span>累計ダメージ<strong>0</strong></span><button type="button">未挑戦</button></div><div className="raid-approved__stats"><span>{icon('armor')}挑戦　0戦</span><span>{icon('victory')}勝利　0勝</span></div><div className="raid-approved__eligibility"><span>討伐報酬資格まで<br /><b>あと3勝</b></span><div>{[1, 2, 3].map(i => <span key={i}>{icon('medal')}</span>)}</div></div><p>参加時の共通進行　Lv.1</p></div><button className="raid-approved__challenge" type="button">{icon('swords')}<strong>挑む</strong><span>{icon('clock')}消費行動力 5</span></button></section>; }
export default function ApprovedRaidPreview() { const screens = ['listing', 'detail', 'lower'] as const; return <main className="raid-approved"><div className="raid-approved__board"><div className="raid-approved__panels">{screens.map((kind, index) => <div className="raid-approved__panel" key={kind}><h2 className="raid-approved__panel-title">{index === 0 ? '01　レイド一覧' : kind === 'detail' ? '02　レイド詳細' : '03　詳細・下部'}</h2><ResourceHeader entry={entries[0]} />{kind === 'listing' ? <Listing /> : <Detail lower={kind === 'lower'} />}<Footer /></div>)}</div></div></main>; }
