'use client';
import { useMemo, useState, type ReactNode } from 'react';
import type { DeckMember, EquipmentSlot, RedesignState } from '@/domain/redesign/types';
import { CHARACTER_MASTERS, SKILL_MASTERS, EQUIPMENT_MASTERS, getCharacterStats, getEquipmentStats, getSkillSlots, buildBattleParty } from '@/domain/redesign/masters';
import { EQUIPMENT_SLOTS, SLOT_LABELS, GROWTH_PREVIEW_RULES as RULES, getCharacterLevelCap, isEquipmentAssigned, equipmentFits, autoEquipSkills, autoEquipEquipment } from '@/domain/redesign/growth';
import './growth.css';
import CentralModal from './Modal';
const ELEMENTS:Record<string,string>={fire:'火',water:'水',earth:'土',wind:'風',light:'光',dark:'闇'};
const RARITIES=['N','R','SR','SSR'];
export interface GrowthViewProps { state: RedesignState; onAction: (action:string,payload:Record<string,unknown>)=>Promise<unknown>; }
function Modal({title,onClose,children,art=false,message}:{title:string;onClose:()=>void;children:ReactNode;art?:boolean;message?:string}) { return <CentralModal title={title} onClose={onClose} className={`g4g-modal ${art?'g4g-art':''}`}>{message&&!art&&<p className="g4g-message" role="status">{message}</p>}{children}</CentralModal>; }
export default function GrowthView({state,onAction}:GrowthViewProps) {
  const [tab,setTab]=useState('デッキ'); const [filter,setFilter]=useState('');const [sort,setSort]=useState('level');const [selected,setSelected]=useState<string|null>(null);const [art,setArt]=useState(false);const [skillDetail,setSkillDetail]=useState<string|null>(null);const [equipmentDetail,setEquipmentDetail]=useState<string|null>(null);const [assign,setAssign]=useState<{kind:'skill'|'equipment';slot:number|EquipmentSlot}|null>(null);const [position,setPosition]=useState(0);const [bulk,setBulk]=useState(false);const [checked,setChecked]=useState<string[]>([]);const [confirm,setConfirm]=useState(false);const [busy,setBusy]=useState(false);const [message,setMessage]=useState('');
  const run=async(action:string,payload:Record<string,unknown>)=>{if(busy)return;setBusy(true);setMessage('');try{await onAction(action,payload);setMessage('保存しました。');return true;}catch(error){setMessage(error instanceof Error?error.message:'保存できませんでした。');return false;}finally{setBusy(false);}};
  const party=useMemo(()=>buildBattleParty(state),[state]);
  const chars=useMemo(()=>state.characters.filter(c=>c.level>0).map(owned=>({owned,master:CHARACTER_MASTERS.find(c=>c.id===owned.id)!})).filter(c=>c.master).filter(c=>!filter||c.master.element===filter||c.master.rarity===filter||c.master.role===filter).sort((a,b)=>sort==='name'?a.master.name.localeCompare(b.master.name,'ja'):sort==='rarity'?RARITIES.indexOf(b.master.rarity)-RARITIES.indexOf(a.master.rarity):sort==='element'?a.master.element.localeCompare(b.master.element):b.owned.level-a.owned.level),[state.characters,filter,sort]);
  const skills=state.skills.map(owned=>({owned,master:SKILL_MASTERS.find(s=>s.id===owned.id)!})).filter(s=>s.master).filter(s=>!filter||s.master.element===filter||s.master.rarity===filter).sort((a,b)=>sort==='name'?a.master.name.localeCompare(b.master.name,'ja'):sort==='rarity'?RARITIES.indexOf(b.master.rarity)-RARITIES.indexOf(a.master.rarity):sort==='sp'?b.master.spCost-a.master.spCost:sort==='element'?a.master.element.localeCompare(b.master.element):b.owned.level-a.owned.level);
  const equipment=state.equipment.map(owned=>({owned,master:EQUIPMENT_MASTERS.find(e=>e.id===owned.masterId)!})).filter(e=>e.master).filter(e=>!filter||e.master.rarity===filter||e.master.slot===filter).sort((a,b)=>sort==='name'?a.master.name.localeCompare(b.master.name,'ja'):sort==='rarity'?RARITIES.indexOf(b.master.rarity)-RARITIES.indexOf(a.master.rarity):sort==='lb'?b.owned.lb-a.owned.lb:sort==='slot'?a.master.slot.localeCompare(b.master.slot):b.owned.level-a.owned.level);
  const current=state.characters.find(c=>c.id===selected);const master=CHARACTER_MASTERS.find(c=>c.id===selected);const member=state.deck.find(m=>m.characterId===selected);const stats=party.find(p=>p.id===selected)?.stats??(master&&current?getCharacterStats(master,current.level,current.awakening):null);
  const detailSkill=SKILL_MASTERS.find(s=>s.id===skillDetail);const ownedSkill=state.skills.find(s=>s.id===skillDetail);const ownedEquip=state.equipment.find(e=>e.instanceId===equipmentDetail);const detailEquip=EQUIPMENT_MASTERS.find(e=>e.id===ownedEquip?.masterId);
  const saveDeck=(deck:DeckMember[])=>run('save_deck',{deck});
  const updateMember=(update:Partial<DeckMember>)=>saveDeck(state.deck.map(m=>m.characterId===selected?{...m,...update}:m));
  const changeTab=(next:string)=>{setTab(next);setFilter('');setSort('level');};
  const allEligible=equipment.filter(e=>!e.owned.locked&&!isEquipmentAssigned(state,e.owned.instanceId));
  return <section className="g4-growth"><nav className="g4g-tabs" aria-label="育成"><>{['デッキ','編成','キャラ','スキル','装備'].map(t=><button key={t} aria-pressed={tab===t} onClick={()=>changeTab(t)}>{t}</button>)}</></nav>
    {message&&<p className="g4g-message" role="status">{message}</p>}
    {(tab==='デッキ'||tab==='編成')&&<><div className="g4g-party">{state.deck.map((m,index)=>{const owned=state.characters.find(c=>c.id===m.characterId);const cm=CHARACTER_MASTERS.find(c=>c.id===m.characterId);return <button key={m.characterId} className={tab==='編成'&&index===position?'selected':''} onClick={()=>tab==='編成'?setPosition(index):setSelected(m.characterId)}><img src={cm?.image} alt={cm?.name??'武将'} /><b>{cm?.name}</b><span>{cm?.rarity} {ELEMENTS[cm?.element??'']}</span><span>Lv.{owned?.level}　+{owned?.awakening}</span><span>HP {party[index]?.stats.hp.toLocaleString()}</span><small>✦ {m.skillIds.length}　◆</small></button>;})}</div>
    <div className="g4g-totals"><span>総HP <b>{party.reduce((n,c)=>n+c.stats.hp,0).toLocaleString()}</b></span><span>合計SP <b>{party.reduce((n,c)=>n+c.stats.sp,0).toLocaleString()}</b></span></div><p className="g4g-elements">{Object.entries(ELEMENTS).map(([id,label])=>`${label} ${party.filter(p=>p.element===id).length}`).join('　')}</p>
    {tab==='デッキ'?<div className="g4g-actions">{['おまかせ編成','おまかせ装備','おまかせスキル'].map((label,index)=><button disabled={busy} key={label} onClick={()=>{if(index===1)void saveDeck(autoEquipEquipment(state));else if(index===2)void saveDeck(autoEquipSkills(state));else {const best=[...state.characters].filter(c=>c.level>0).sort((a,b)=>b.level-a.level||b.awakening-a.awakening).slice(0,5);void saveDeck(best.map(c=>state.deck.find(m=>m.characterId===c.id)??{characterId:c.id,skillIds:[],equipment:{}}));}}}>{label}</button>)}</div>:<div className="g4g-actions"><button disabled={busy||position===0} onClick={()=>{const deck=[...state.deck];[deck[position-1],deck[position]]=[deck[position],deck[position-1]];void saveDeck(deck);setPosition(position-1);}}>← 移動</button><button disabled={busy||position===4} onClick={()=>{const deck=[...state.deck];[deck[position+1],deck[position]]=[deck[position],deck[position+1]];void saveDeck(deck);setPosition(position+1);}}>移動 →</button></div>}</>}
    {tab!=='デッキ'&&<div className="g4g-filters"><label>絞り込み<select value={filter} onChange={e=>setFilter(e.target.value)}><option value="">すべて</option>{RARITIES.map(r=><option key={r}>{r}</option>)}{tab==='装備'?EQUIPMENT_SLOTS.filter(s=>s!=='accessory2').map(s=><option key={s} value={s}>{SLOT_LABELS[s]}</option>):Object.entries(ELEMENTS).map(([id,label])=><option key={id} value={id}>{label}</option>)}</select></label><label>並び替え<select value={sort} onChange={e=>setSort(e.target.value)}><option value="level">Lv</option><option value="rarity">レアリティ</option><option value="name">名前</option>{tab==='装備'?<><option value="lb">LB</option><option value="slot">部位</option></>:<option value="element">属性</option>}{tab==='スキル'&&<option value="sp">消費SP</option>}</select></label></div>}
    {(tab==='キャラ'||tab==='編成')&&<div className="g4g-grid">{chars.map(({owned,master:cm})=><button key={owned.id} disabled={busy} onClick={()=>{if(tab==='キャラ')setSelected(owned.id);else {const deck=structuredClone(state.deck);const existing=deck.findIndex(m=>m.characterId===owned.id);if(existing>=0)[deck[position],deck[existing]]=[deck[existing],deck[position]];else deck[position]={characterId:owned.id,skillIds:[],equipment:{}};void saveDeck(deck);}}}><img src={cm.image} alt={cm.name}/><b>{cm.name}</b><span>{cm.rarity}・{ELEMENTS[cm.element]}・{cm.role}</span><span>Lv.{owned.level}　覚醒+{owned.awakening}</span>{state.deck.some(m=>m.characterId===owned.id)&&<small>編成中</small>}</button>)}</div>}
    {tab==='キャラ'&&CHARACTER_MASTERS.some(c=>!state.characters.some(owned=>owned.id===c.id)&&(state.souls[c.id]??0)>0)&&<><h3>武将の魂</h3><div className="g4g-grid">{CHARACTER_MASTERS.filter(c=>!state.characters.some(owned=>owned.id===c.id)&&(state.souls[c.id]??0)>0).map(c=><button key={c.id} disabled={busy||(state.souls[c.id]??0)<RULES.unlockSouls} onClick={()=>void run('character_unlock',{characterId:c.id})}>{CHARACTER_MASTERS.find(m=>m.id===c.id)?.name}<span>{state.souls[c.id]??0} / {RULES.unlockSouls}</span>武将を迎える</button>)}</div></>}
    {tab==='スキル'&&<><p>スキルLB素材 {state.materials.skill}</p><div className="g4g-grid">{skills.map(({owned,master:sm})=><button key={owned.id} onClick={()=>setSkillDetail(owned.id)}><img src={sm.image} alt={sm.name}/><b>{sm.name}</b><span>{sm.rarity}・{ELEMENTS[sm.element]}　+{owned.level}</span><span>消費SP {sm.spCost}</span></button>)}</div></>}
    {tab==='装備'&&<><div className="g4g-actions"><button onClick={()=>{setBulk(!bulk);setChecked([]);}}>{bulk?'選択を終了':'一括分解'}</button>{bulk&&<><button onClick={()=>setChecked(allEligible.map(e=>e.owned.instanceId))}>全選択</button><button disabled={!checked.length||busy} onClick={()=>setConfirm(true)}>分解確認 {checked.length}件</button></>}</div><div className="g4g-grid">{equipment.map(({owned,master:em})=><div className="g4g-equipment" key={owned.instanceId}>{bulk&&<input aria-label={`${em.name}を分解選択`} type="checkbox" checked={checked.includes(owned.instanceId)} disabled={owned.locked||isEquipmentAssigned(state,owned.instanceId)} onChange={e=>setChecked(e.target.checked?[...checked,owned.instanceId]:checked.filter(id=>id!==owned.instanceId))}/>}<button onClick={()=>setEquipmentDetail(owned.instanceId)}><img src={em.image} alt={em.name}/><b>{em.name}</b><span>{em.rarity}・{SLOT_LABELS[em.slot]}</span><span>Lv.{owned.level}　LB+{owned.lb}</span><small>{isEquipmentAssigned(state,owned.instanceId)?'装備中':owned.locked?'保護中':''}</small></button></div>)}</div></>}
    {selected&&current&&master&&stats&&!art&&<Modal message={message} title={master.name} onClose={()=>{setSelected(null);setAssign(null);}}><div className="g4g-profile"><button onClick={()=>setArt(true)} aria-label="全身を見る"><img src={master.image} alt={master.name}/></button><div><p>{master.rarity}・{ELEMENTS[master.element]}・{master.role}</p><p>Lv.{current.level} / {getCharacterLevelCap(current.awakening)}　覚醒+{current.awakening}</p><p>武将の魂 {state.souls[current.id]??0}</p></div></div><dl className="g4g-stats">{Object.entries(stats).map(([key,value])=><div key={key}><dt>{key.toUpperCase()}</dt><dd>{value.toLocaleString()}</dd></div>)}</dl><h3>{master.passive.name} +{Math.min(10,current.awakening*2)}</h3><p>戦闘開始時・{master.passive.target==='party'?'味方全体':'自身'} {master.passive.stat.toUpperCase()} 上昇</p><div className="g4g-actions"><button disabled={busy||current.level>=getCharacterLevelCap(current.awakening)} onClick={()=>void run('character_level',{characterId:selected})}>Lv育成<br/><small>素材 {RULES.characterMaterial}・銭 {RULES.characterCash}</small></button><button disabled={busy||current.awakening>=5} onClick={()=>void run('character_awaken',{characterId:selected})}>覚醒<br/><small>魂 {RULES.awakeningSouls[current.awakening]??'—'}</small></button></div><p>育成素材 {state.materials.character}・銭 {state.cash.toLocaleString()}</p><h3>スキル</h3>{member?<>{Array.from({length:getSkillSlots(current.awakening)},(_,index)=><button className="g4g-row" key={index} onClick={()=>setAssign({kind:'skill',slot:index})}>{index+1}. {SKILL_MASTERS.find(s=>s.id===member.skillIds[index])?.name??'未装備'}　変更</button>)}<h3>装備</h3>{EQUIPMENT_SLOTS.map(slot=><button className="g4g-row" key={slot} onClick={()=>setAssign({kind:'equipment',slot})}>{SLOT_LABELS[slot]}　{EQUIPMENT_MASTERS.find(e=>e.id===state.equipment.find(e=>e.instanceId===member.equipment[slot])?.masterId)?.name??'未装備'}　変更</button>)}</>:<p>編成に加えるとスキル・装備を設定できます。</p>}</Modal>}
    {art&&master&&<Modal message={message} title="全身鑑賞" art onClose={()=>setArt(false)}><img className="g4g-fullbody" src={master.image} alt={master.name}/></Modal>}
    {assign&&member&&<Modal message={message} title={assign.kind==='skill'?'スキルを変更':'装備を変更'} onClose={()=>setAssign(null)}><button className="g4g-row" disabled={busy} onClick={async()=>{if(assign.kind==='skill') {const ids=[...member.skillIds];ids.splice(Number(assign.slot),1);await updateMember({skillIds:ids});}else {const eq={...member.equipment};delete eq[assign.slot as EquipmentSlot];await updateMember({equipment:eq});}setAssign(null);}}>外す</button>{assign.kind==='skill'?state.skills.map(s=>{const sm=SKILL_MASTERS.find(m=>m.id===s.id);return <button className="g4g-row" key={s.id} disabled={busy||member.skillIds.includes(s.id)} onClick={async()=>{const ids=[...member.skillIds];ids.splice(Math.min(Number(assign.slot),ids.length),1,s.id);await updateMember({skillIds:ids});setAssign(null);}}>{sm?.name} +{s.level}　SP {sm?.spCost}</button>;}):state.equipment.filter(e=>{const em=EQUIPMENT_MASTERS.find(m=>m.id===e.masterId);return em&&equipmentFits(assign.slot as EquipmentSlot,em.slot)&&!isEquipmentAssigned(state,e.instanceId);}).map(e=><button className="g4g-row" key={e.instanceId} disabled={busy} onClick={async()=>{await updateMember({equipment:{...member.equipment,[assign.slot]:e.instanceId}});setAssign(null);}}>{EQUIPMENT_MASTERS.find(m=>m.id===e.masterId)?.name} Lv.{e.level}</button>)}</Modal>}
    {detailSkill&&ownedSkill&&<Modal message={message} title={detailSkill.name} onClose={()=>setSkillDetail(null)}><img className="g4g-detail-icon" src={detailSkill.image} alt=""/><p>{detailSkill.rarity}・{ELEMENTS[detailSkill.element]}・+{ownedSkill.level}</p><p>{detailSkill.description}</p><p>消費SP {detailSkill.spCost}</p><p>スキルLB素材 {state.materials.skill}</p><button disabled={busy||ownedSkill.level>=RULES.skillMax} onClick={()=>void run('skill_level',{skillId:detailSkill.id})}>スキル育成（LB素材 {RULES.skillMaterial}）</button></Modal>}
    {detailEquip&&ownedEquip&&<Modal message={message} title={detailEquip.name} onClose={()=>setEquipmentDetail(null)}><img className="g4g-detail-icon" src={detailEquip.image} alt=""/><p>{detailEquip.rarity}・{SLOT_LABELS[detailEquip.slot]}・Lv.{ownedEquip.level}・LB+{ownedEquip.lb}</p><dl className="g4g-stats">{Object.entries(getEquipmentStats(detailEquip,ownedEquip.level,ownedEquip.lb)).map(([key,value])=><div key={key}><dt>{key.toUpperCase()}</dt><dd>{value}</dd></div>)}</dl><p>育成素材 {state.materials.equipment}・LB素材 {state.materials.equipmentLb}</p><div className="g4g-actions"><button disabled={busy||ownedEquip.level>=RULES.equipmentLevelCap} onClick={()=>void run('equipment_level',{instanceId:ownedEquip.instanceId})}>Lv育成<br/><small>素材 {RULES.equipmentMaterial}・銭 {RULES.equipmentCash}</small></button><button disabled={busy||ownedEquip.lb>=RULES.equipmentLbMax} onClick={()=>void run('equipment_lb',{instanceId:ownedEquip.instanceId})}>LB育成（素材 {RULES.equipmentLbMaterial}）</button></div></Modal>}
    {confirm&&<Modal message={message} title="装備を分解" onClose={()=>setConfirm(false)}><p>選択した {checked.length} 件を分解します。</p>{checked.map(id=><p key={id}>{EQUIPMENT_MASTERS.find(m=>m.id===state.equipment.find(e=>e.instanceId===id)?.masterId)?.name}</p>)}<p>獲得する銭 {checked.length*RULES.dismantleCash}</p><p>装備LB素材 {checked.length*RULES.dismantleLbMaterial}</p><button disabled={busy} onClick={async()=>{if(await run('equipment_dismantle',{instanceIds:checked})){setConfirm(false);setChecked([]);}}}>分解を確定</button></Modal>}
  </section>;
}
