'use client';
import GrowthResult, { RESULT_ACTIONS, type GrowthReceipt } from './GrowthResult';
import { withPresentation } from '../ui/presentationTasks';
import { game04UiError } from '@/app/lib/game04UiError';
import CreativeCharacter from './CreativeCharacter';
import ElementBadge from './ElementBadge';
import { characterArt } from '@/theme/creativeAssets';
import { useMemo, useRef, useState, type ReactNode } from 'react';
import type { DeckMember, EquipmentSlot, RedesignState } from '@/domain/redesign/types';
import { CHARACTER_MASTERS, SKILL_MASTERS, EQUIPMENT_MASTERS, getCharacterStats, getEquipmentStats, getSkillSlots, buildBattleParty, getCharacterPassive } from '@/domain/redesign/masters';
import { EQUIPMENT_SLOTS, SLOT_LABELS, GROWTH_PREVIEW_RULES as RULES, getCharacterLevelCap, isEquipmentAssigned, equipmentFits, autoEquipSkills, autoEquipEquipment } from '@/domain/redesign/growth';
import './growth.css';
import { LevelGrowthControls, SoulControls, GrowthInventoryView } from './GrowthControls';
import { getEquipmentLevelCap } from '@/domain/redesign/growth';
import { LB_STEPS, SKILL_LB_FACTORS, EQUIPMENT_LB_FACTORS, DISMANTLE_MATERIALS } from '@/domain/redesign/growthMaster';
import CentralModal from './Modal';
import { passiveDescription, skillDescription } from './battleLabels';
const ELEMENTS:Record<string,string>={fire:'火',water:'水',earth:'土',wind:'風',light:'光',dark:'闇'};
const RARITIES=['N','R','SR','SSR'];
export interface GrowthViewProps { state: RedesignState; onAction: (action:string,payload:Record<string,unknown>)=>Promise<unknown>; }
function Modal({title,onClose,children,art=false,message,resetKey,busy}:{title:string;onClose:()=>void;children:ReactNode;art?:boolean;message?:string;resetKey?:unknown;busy?:boolean}) { return <CentralModal trackChanges={!art} resetKey={resetKey} busy={busy} title={title} onClose={onClose} className={`g4g-modal ${art?'g4g-art':''}`}>{message&&!art&&<p className="g4g-message" role="status">{message}</p>}{children}</CentralModal>; }
export default function GrowthView({state,onAction}:GrowthViewProps) {
  const [tab,setTab]=useState('デッキ'); const [filter,setFilter]=useState('');const [sort,setSort]=useState('level');const [selected,setSelected]=useState<string|null>(null);const [art,setArt]=useState(false);const [skillDetail,setSkillDetail]=useState<string|null>(null);const [equipmentDetail,setEquipmentDetail]=useState<string|null>(null);const [assign,setAssign]=useState<{kind:'skill'|'equipment';slot:number|EquipmentSlot}|null>(null);const [position,setPosition]=useState(0);const [bulk,setBulk]=useState(false);const [checked,setChecked]=useState<string[]>([]);const [confirm,setConfirm]=useState(false);const [busy,setBusy]=useState(false);const [message,setMessage]=useState('');
  const [receipt,setReceipt]=useState<GrowthReceipt|null>(null);
  const actionLock = useRef(false);
  const [assignmentDraft, setAssignmentDraft] = useState<string | null>(null);
  const run=async(action:string,payload:Record<string,unknown>)=>{if(actionLock.current)return;actionLock.current=true;setBusy(true);setMessage('');try{const before=structuredClone(state);const response=await withPresentation(()=>onAction(action,payload));const after=response && typeof response==='object' && 'state' in response ? (response as {state:RedesignState}).state : response as RedesignState|undefined;if(RESULT_ACTIONS.includes(action)&&after&&Array.isArray(after.characters)){setReceipt({action,payload,before,after:structuredClone(after)});}setMessage('保存しました。');return true;}catch(error){setMessage(game04UiError(error));return false;}finally{actionLock.current=false;setBusy(false);}};
  const party=useMemo(()=>buildBattleParty(state),[state]);
  const chars=useMemo(()=>state.characters.filter(c=>c.level>0).map(owned=>({owned,master:CHARACTER_MASTERS.find(c=>c.id===owned.id)!})).filter(c=>c.master).filter(c=>!filter||c.master.element===filter||c.master.rarity===filter||c.master.role===filter).sort((a,b)=>sort==='name'?a.master.name.localeCompare(b.master.name,'ja'):sort==='rarity'?RARITIES.indexOf(b.master.rarity)-RARITIES.indexOf(a.master.rarity):sort==='element'?a.master.element.localeCompare(b.master.element):b.owned.level-a.owned.level),[state.characters,filter,sort]);
  const skills=state.skills.map(owned=>({owned,master:SKILL_MASTERS.find(s=>s.id===owned.id)!})).filter(s=>s.master).filter(s=>!filter||s.master.element===filter||s.master.rarity===filter).sort((a,b)=>sort==='name'?a.master.name.localeCompare(b.master.name,'ja'):sort==='rarity'?RARITIES.indexOf(b.master.rarity)-RARITIES.indexOf(a.master.rarity):sort==='sp'?b.master.spCost-a.master.spCost:sort==='element'?a.master.element.localeCompare(b.master.element):b.owned.level-a.owned.level);
  const equipment=state.equipment.map(owned=>({owned,master:EQUIPMENT_MASTERS.find(e=>e.id===owned.masterId)!})).filter(e=>e.master).filter(e=>!filter||e.master.rarity===filter||e.master.slot===filter).sort((a,b)=>sort==='name'?a.master.name.localeCompare(b.master.name,'ja'):sort==='rarity'?RARITIES.indexOf(b.master.rarity)-RARITIES.indexOf(a.master.rarity):sort==='lb'?b.owned.lb-a.owned.lb:sort==='slot'?a.master.slot.localeCompare(b.master.slot):b.owned.level-a.owned.level);
  const current=state.characters.find(c=>c.id===selected);const master=CHARACTER_MASTERS.find(c=>c.id===selected);const member=state.deck.find(m=>m.characterId===selected);const stats=party.find(p=>p.id===selected)?.stats??(master&&current?getCharacterStats(master,current.level,current.awakening):null);
  const detailSkill=SKILL_MASTERS.find(s=>s.id===skillDetail);const ownedSkill=state.skills.find(s=>s.id===skillDetail);const ownedEquip=state.equipment.find(e=>e.instanceId===equipmentDetail);const detailEquip=EQUIPMENT_MASTERS.find(e=>e.id===ownedEquip?.masterId);
  const saveDeck=(deck:DeckMember[])=>run('save_deck',{deck});
  const updateMember=(update:Partial<DeckMember>)=>saveDeck(state.deck.map(m=>m.characterId===selected?{...m,...update}:m));
  const changeTab=(next:string)=>{setTab(next);setFilter('');setSort('level');};
  const allEligible=equipment.filter(e=>!e.owned.locked&&!isEquipmentAssigned(state,e.owned.instanceId));
  if(receipt)return <GrowthResult receipt={receipt} onClose={()=>setReceipt(null)}/>;
  if(message && message!=='保存しました。')return <CentralModal kind="notice" onClose={()=>setMessage('')}><p>{message}</p></CentralModal>;
  return <section className="g4-growth"><nav className="g4g-tabs" aria-label="育成"><>{['デッキ','編成','キャラ','スキル','装備'].map(t=><button key={t} aria-pressed={tab===t} onClick={()=>changeTab(t)}>{t}</button>)}</></nav>
    {message&&<p className="g4g-message" role="status">{message}</p>}
    {(tab==='デッキ'||tab==='編成')&&<><div className="g4g-party">{state.deck.map((m,index)=>{const owned=state.characters.find(c=>c.id===m.characterId);const cm=CHARACTER_MASTERS.find(c=>c.id===m.characterId);return <button key={m.characterId} className={tab==='編成'&&index===position?'selected':''} onClick={()=>tab==='編成'?setPosition(index):setSelected(m.characterId)}>{cm && <CreativeCharacter character={cm} />}<b>{cm?.name}</b><span>{cm?.rarity} {ELEMENTS[cm?.element??'']}</span><span>Lv.{owned?.level}　+{owned?.awakening}</span><span>HP {party[index]?.stats.hp.toLocaleString()}</span><small>✦ {m.skillIds.length}　◆</small></button>;})}</div>
    <div className="g4g-totals"><span>総HP <b>{party.reduce((n,c)=>n+c.stats.hp,0).toLocaleString()}</b></span><span>共通SP上限 <b>400</b></span></div><p className="g4g-elements">{Object.entries(ELEMENTS).map(([id,label])=>`${label} ${party.filter(p=>p.element===id).length}`).join('　')}</p>
    {tab==='デッキ'?<div className="g4g-actions">{['おまかせ編成','おまかせ装備','おまかせスキル'].map((label,index)=><button disabled={busy} key={label} onClick={()=>{if(index===1)void saveDeck(autoEquipEquipment(state));else if(index===2)void saveDeck(autoEquipSkills(state));else {const best=[...state.characters].filter(c=>c.level>0).sort((a,b)=>b.level-a.level||b.awakening-a.awakening).slice(0,5);void saveDeck(best.map(c=>state.deck.find(m=>m.characterId===c.id)??{characterId:c.id,skillIds:[],equipment:{}}));}}}>{label}</button>)}</div>:<div className="g4g-actions"><button disabled={busy||position===0} onClick={()=>{const deck=[...state.deck];[deck[position-1],deck[position]]=[deck[position],deck[position-1]];void saveDeck(deck);setPosition(position-1);}}>← 移動</button><button disabled={busy||position===4} onClick={()=>{const deck=[...state.deck];[deck[position+1],deck[position]]=[deck[position],deck[position+1]];void saveDeck(deck);setPosition(position+1);}}>移動 →</button></div>}</>}
    {tab!=='デッキ'&&<div className="g4g-filters"><label>絞り込み<select value={filter} onChange={e=>setFilter(e.target.value)}><option value="">すべて</option>{RARITIES.map(r=><option key={r}>{r}</option>)}{tab==='装備'?EQUIPMENT_SLOTS.filter(s=>s!=='accessory2').map(s=><option key={s} value={s}>{SLOT_LABELS[s]}</option>):Object.entries(ELEMENTS).map(([id,label])=><option key={id} value={id}>{label}</option>)}</select></label><label>並び替え<select value={sort} onChange={e=>setSort(e.target.value)}><option value="level">Lv</option><option value="rarity">レアリティ</option><option value="name">名前</option>{tab==='装備'?<><option value="lb">LB</option><option value="slot">部位</option></>:<option value="element">属性</option>}{tab==='スキル'&&<option value="sp">消費SP</option>}</select></label></div>}
    {(tab==='キャラ'||tab==='編成')&&<div className="g4g-grid">{chars.map(({owned,master:cm})=><button key={owned.id} disabled={busy} onClick={()=>{if(tab==='キャラ')setSelected(owned.id);else {const deck=structuredClone(state.deck);const existing=deck.findIndex(m=>m.characterId===owned.id);if(existing>=0)[deck[position],deck[existing]]=[deck[existing],deck[position]];else deck[position]={characterId:owned.id,skillIds:[],equipment:{}};void saveDeck(deck);}}}><CreativeCharacter character={cm}/><b>{cm.name}</b><span>{cm.rarity}・<ElementBadge element={cm.element}/>・{cm.role}</span><span>Lv.{owned.level}　覚醒+{owned.awakening}</span>{state.deck.some(m=>m.characterId===owned.id)&&<small>編成中</small>}</button>)}</div>}
    {tab==='キャラ'&&<><GrowthInventoryView state={state}/><h3>武将の魂</h3><div className="g4g-grid">{CHARACTER_MASTERS.filter(c=>!state.characters.some(owned=>owned.id===c.id)&&(state.souls[c.id]??0)>0).map(c=><button key={c.id} onClick={()=>setSelected(c.id)}>{c.name}<span>固有魂 {state.souls[c.id]??0}</span>魂の操作</button>)}</div></>}
    {selected&&master&&!current&&<Modal resetKey={state} busy={busy} message={message} title={master.name} onClose={()=>setSelected(null)}><SoulControls key={selected} state={state} id={selected} run={run} busy={busy}/></Modal>}
    {tab==='スキル'&&<><p>スキルLB素材 {state.materials.skill}</p><p>所持スキルは旧IDの仮マスターです。新72候補は検証画面のみで接続し、ガチャには追加していません。</p><div className="g4g-grid">{skills.map(({owned,master:sm})=><button key={owned.id} onClick={()=>setSkillDetail(owned.id)}><img src={sm.image} alt={sm.name}/><b>{sm.name}</b><span>{sm.rarity}・{ELEMENTS[sm.element]}　+{owned.level}</span><span>消費SP {sm.spCost}</span></button>)}</div></>}
    {tab==='装備'&&<><div className="g4g-actions"><button onClick={()=>{setBulk(!bulk);setChecked([]);}}>{bulk?'選択を終了':'一括分解'}</button>{bulk&&<><button onClick={()=>setChecked(allEligible.map(e=>e.owned.instanceId))}>全選択</button><button disabled={!checked.length||busy} onClick={()=>setConfirm(true)}>分解確認 {checked.length}件</button></>}</div><div className="g4g-grid">{equipment.map(({owned,master:em})=><div className="g4g-equipment" key={owned.instanceId}>{bulk&&<input aria-label={`${em.name}を分解選択`} type="checkbox" checked={checked.includes(owned.instanceId)} disabled={owned.locked||isEquipmentAssigned(state,owned.instanceId)} onChange={e=>setChecked(e.target.checked?[...checked,owned.instanceId]:checked.filter(id=>id!==owned.instanceId))}/>}<button onClick={()=>setEquipmentDetail(owned.instanceId)}><img src={em.image} alt={em.name}/><b>{em.name}</b><span>{em.rarity}・{SLOT_LABELS[em.slot]}</span><span>Lv.{owned.level}　LB+{owned.lb}</span><small>{isEquipmentAssigned(state,owned.instanceId)?'装備中':owned.locked?'保護中':''}</small></button></div>)}</div></>}
    {selected&&current&&master&&stats&&!art&&!assign&&<Modal resetKey={state} busy={busy} message={message} title={master.name} onClose={()=>{setSelected(null);setAssign(null);}}><div className="g4g-profile"><button onClick={()=>setArt(true)} aria-label="全身を見る"><img src={characterArt(master, 'full')} alt={master.name}/></button><div><p>{master.rarity}・{ELEMENTS[master.element]}・{master.role}</p><p>Lv.{current.level} / {getCharacterLevelCap(current.awakening)}　覚醒+{current.awakening}</p><p>武将の魂 {state.souls[current.id]??0}</p>{master.rarity==='N'&&<p>属性・役割は検証用仮設定</p>}</div></div><dl className="g4g-stats">{Object.entries(stats).map(([key,value])=><div key={key}><dt>{key.toUpperCase()}</dt><dd>{value.toLocaleString()}</dd></div>)}</dl>{master.rarity!=='N'&&master.passive&&<><h3>{master.passive.name} Lv.{Math.min(10,current.awakening*2)}</h3><p>{passiveDescription(getCharacterPassive(master,current.awakening)??master.passive)}</p></>}<LevelGrowthControls key={`exp-${selected}`} state={state} kind="character" id={selected} run={run} busy={busy}/><SoulControls key={`soul-${selected}`} state={state} id={selected} run={run} busy={busy}/><p>銭 {state.cash.toLocaleString()}</p><h3>スキル発動優先順</h3><p>優先1 → 2 → 3の順に判定し、条件とSPを満たす最初のスキルを使います。</p>{member?<>{Array.from({length:getSkillSlots(current.awakening)},(_,index)=><button className="g4g-row" key={index} onClick={()=>{setAssignmentDraft(member.skillIds[index]??'');setAssign({kind:'skill',slot:index});}}>優先{index+1}：{SKILL_MASTERS.find(s=>s.id===member.skillIds[index])?.name??'未装備'}　変更</button>)}<h3>装備</h3>{EQUIPMENT_SLOTS.map(slot=><button className="g4g-row" key={slot} onClick={()=>{setAssignmentDraft(member.equipment[slot]??'');setAssign({kind:'equipment',slot});}}>{SLOT_LABELS[slot]}　{EQUIPMENT_MASTERS.find(e=>e.id===state.equipment.find(e=>e.instanceId===member.equipment[slot])?.masterId)?.name??'未装備'}　変更</button>)}</>:<p>編成に加えるとスキル・装備を設定できます。</p>}</Modal>}
    {art&&master&&<Modal resetKey={state} busy={busy} message={message} title="全身鑑賞" art onClose={()=>setArt(false)}><img className="g4g-fullbody" src={characterArt(master, 'full')} alt={master.name}/></Modal>}
    {assign&&member&&<CentralModal kind="edit" title={assign.kind==='skill'?'スキルを変更':'装備を変更'} busy={busy} dirty={assignmentDraft !== (assign.kind==='skill' ? member.skillIds[Number(assign.slot)]??'' : member.equipment[assign.slot as EquipmentSlot]??'')} onClose={()=>setAssign(null)} footer={cancel=><div className="g4-cta-row"><button className="rd-button" disabled={busy} onClick={cancel}>キャンセル</button><button className="rd-button rd-primary" disabled={busy} onClick={async()=>{let updated:Partial<DeckMember>;if(assign.kind==='skill'){const ids=[...member.skillIds];if(assignmentDraft)ids.splice(Math.min(Number(assign.slot),ids.length),1,assignmentDraft);else ids.splice(Number(assign.slot),1);updated={skillIds:ids};}else{const equipment={...member.equipment};if(assignmentDraft)equipment[assign.slot as EquipmentSlot]=assignmentDraft;else delete equipment[assign.slot as EquipmentSlot];updated={equipment};}if(await updateMember(updated))setAssign(null);}}>保存</button></div>}>
      <button className="g4g-row" aria-pressed={assignmentDraft===''} disabled={busy} onClick={()=>setAssignmentDraft('')}>外す</button>
      {assign.kind==='skill'?state.skills.map(skill=>{const master=SKILL_MASTERS.find(m=>m.id===skill.id);return <button className="g4g-row" key={skill.id} aria-pressed={assignmentDraft===skill.id} disabled={busy||(member.skillIds.includes(skill.id)&&member.skillIds[Number(assign.slot)]!==skill.id)} onClick={()=>setAssignmentDraft(skill.id)}>{master?.name} +{skill.level}　SP {master?.spCost}</button>;}):state.equipment.filter(e=>{const master=EQUIPMENT_MASTERS.find(m=>m.id===e.masterId);return master&&equipmentFits(assign.slot as EquipmentSlot,master.slot)&&(!isEquipmentAssigned(state,e.instanceId)||member.equipment[assign.slot as EquipmentSlot]===e.instanceId);}).map(e=><button className="g4g-row" key={e.instanceId} aria-pressed={assignmentDraft===e.instanceId} disabled={busy} onClick={()=>setAssignmentDraft(e.instanceId)}>{EQUIPMENT_MASTERS.find(m=>m.id===e.masterId)?.name} Lv.{e.level}</button>)}
      {message&&<p role="status">{message}</p>}
    </CentralModal>}
    {detailSkill&&ownedSkill&&<Modal resetKey={state} busy={busy} message={message} title={detailSkill.name} onClose={()=>setSkillDetail(null)}><img className="g4g-detail-icon" src={detailSkill.image} alt=""/><p>{detailSkill.rarity}・{ELEMENTS[detailSkill.element]}・+{ownedSkill.level}</p><p>{skillDescription(detailSkill)}</p><p>消費SP {detailSkill.spCost}</p><p>同じ所持スキルのLBは装備した全武将へ共通適用されます。</p><p>効果倍率 {(1+ownedSkill.level*0.05).toFixed(2)} → {ownedSkill.level<10?(1+(ownedSkill.level+1)*0.05).toFixed(2):"最大"}</p><p>スキルLB素材 {state.materials.skill}</p><button disabled={busy||ownedSkill.level>=RULES.skillMax} onClick={()=>void run('skill_level',{skillId:detailSkill.id})}>LBを上げる</button><p>必要素材 {LB_STEPS[ownedSkill.level]*SKILL_LB_FACTORS[detailSkill.rarity]}・必要銭 {(LB_STEPS[ownedSkill.level]*SKILL_LB_FACTORS[detailSkill.rarity]*1000).toLocaleString()}</p></Modal>}
    {detailEquip&&ownedEquip&&<Modal resetKey={state} busy={busy} message={message} title={detailEquip.name} onClose={()=>setEquipmentDetail(null)}><img className="g4g-detail-icon" src={detailEquip.image} alt=""/><p>{detailEquip.rarity}・{SLOT_LABELS[detailEquip.slot]}・Lv.{ownedEquip.level}・LB+{ownedEquip.lb}</p><dl className="g4g-stats">{Object.entries(getEquipmentStats(detailEquip,ownedEquip.level,ownedEquip.lb)).map(([key,value])=><div key={key}><dt>{key.toUpperCase()}</dt><dd>{value}</dd></div>)}</dl><p>解放Lv上限 {getEquipmentLevelCap(ownedEquip.lb)} / 最大100・装備LB素材 {state.materials.equipmentLb}</p><LevelGrowthControls key={ownedEquip.instanceId} state={state} kind="equipment" id={ownedEquip.instanceId} run={run} busy={busy}/><p>LB+{ownedEquip.lb} → {ownedEquip.lb<10?ownedEquip.lb+1:'最大'}・解放上限 {getEquipmentLevelCap(ownedEquip.lb)} → {getEquipmentLevelCap(ownedEquip.lb+1)}</p>{ownedEquip.lb<10&&<p>必要素材 {LB_STEPS[ownedEquip.lb]*EQUIPMENT_LB_FACTORS[detailEquip.rarity]}・必要銭 {(LB_STEPS[ownedEquip.lb]*EQUIPMENT_LB_FACTORS[detailEquip.rarity]*500).toLocaleString()}</p>}{ownedEquip.lb<10&&<button disabled={busy||state.materials.equipmentLb<LB_STEPS[ownedEquip.lb]*EQUIPMENT_LB_FACTORS[detailEquip.rarity]||state.cash<LB_STEPS[ownedEquip.lb]*EQUIPMENT_LB_FACTORS[detailEquip.rarity]*500} onClick={()=>void run('equipment_lb',{instanceId:ownedEquip.instanceId})}>LB育成</button>}</Modal>}
    {confirm&&<CentralModal kind="confirm" busy={busy} title="装備を分解" onClose={()=>setConfirm(false)} footer={<div className="g4-cta-row"><button className="rd-button" disabled={busy} onClick={()=>setConfirm(false)}>キャンセル</button><button className="rd-button rd-primary" disabled={busy} onClick={async()=>{if(await run('equipment_dismantle',{instanceIds:checked,confirmTrained:true})){setConfirm(false);setChecked([]);}}}>分解する</button></div>}><p>選択した {checked.length} 件を分解します。</p>{checked.map(id=><p key={id}>{EQUIPMENT_MASTERS.find(m=>m.id===state.equipment.find(e=>e.instanceId===id)?.masterId)?.name}</p>)}<p>装備LB素材 {checked.reduce((sum,id)=>sum+DISMANTLE_MATERIALS[EQUIPMENT_MASTERS.find(m=>m.id===state.equipment.find(e=>e.instanceId===id)?.masterId)!.rarity],0)}</p><p>育成済み装備も含めて分解します。投入したEXP・銭・LB素材は返還されません。</p></CentralModal>}
  </section>;
}

