'use client';
import { characterArt } from '@/theme/creativeAssets';
import PageTitleBanner from './PageTitleBanner';
import ListControls from '../ui/ListControls';
import ElementBadge from './ElementBadge';
import { AssetIcon, AssetChoice } from '../ui/AssetChoice';
import PassiveDisplay from './PassiveDisplay';
import { questDisplayName } from '@/domain/redesign/contextNames';
import { QUEST_STAGES } from '@/domain/redesign/quests';
import { useMemo, useRef, useState, type ReactNode, type CSSProperties } from 'react';
import type { DeckMember, EquipmentSlot, RedesignState } from '@/domain/redesign/types';
import { formalSkillPerformance } from '@/domain/redesign/formalOwnedSkills';
import { CHARACTER_MASTERS, OWNABLE_SKILL_MASTERS as SKILL_MASTERS, getOwnedSkillMaster, EQUIPMENT_MASTERS, getCharacterStats, getEquipmentStats, getSkillSlots, buildBattleParty, getCharacterPassive } from '@/domain/redesign/masters';
import { EQUIPMENT_SLOTS, SLOT_LABELS, GROWTH_PREVIEW_RULES as RULES, getCharacterLevelCap, isEquipmentAssigned, equipmentFits, autoEquipSkills, autoEquipEquipment, getUnlockedDeckSlots } from '@/domain/redesign/growth';
import './growth.css';
import { LevelGrowthControls, SoulControls, GrowthInventoryView } from './GrowthControls';
import { getEquipmentLevelCap } from '@/domain/redesign/growth';
import { LB_STEPS, SKILL_LB_FACTORS, EQUIPMENT_LB_FACTORS, DISMANTLE_MATERIALS } from '@/domain/redesign/growthMaster';
import CentralModal from './Modal';
import BrandedLoading from '../ui/BrandedLoading';
import { skillDescription } from './battleLabels';
import { getGrowthResult, type GrowthResult } from '@/domain/redesign/growthResult';
import { characterImageSources, useCharacterImageReadiness } from './CharacterImageReadiness';
import { CARD_OPENINGS } from './visual-bench/CharacterDisplays';
import characterArtwork from '@/theme/local-characters.json';
import characterBackgrounds from '@/theme/character-backgrounds.json';
const ELEMENTS:Record<string,string>={fire:'火',water:'水',earth:'土',wind:'風',light:'光',dark:'闇'};
const RARITIES=['N','R','SR','SSR'];
function CharacterCard({subject}:{subject:typeof CHARACTER_MASTERS[number];compact?:boolean;hideMarks?:boolean}) {
  const artwork=characterArtwork.find(row=>row.id===subject.id);
  const background=characterBackgrounds.find(row=>row.characterId===subject.id);
  const opening=CARD_OPENINGS[subject.rarity];
  const style={'--portrait-frame':`url("/creative/ui/frame-${subject.rarity}.png")`,'--portrait-top':`${opening.top}%`,'--portrait-right':`${opening.right}%`,'--portrait-bottom':`${opening.bottom}%`,'--portrait-left':`${opening.left}%`} as CSSProperties;
  return <figure className="g4g-portrait" data-rarity={subject.rarity} style={style} aria-label={`${subject.name} ${subject.rarity} ${ELEMENTS[subject.element]}`}><div className="g4g-portrait-opening"><img className="g4g-portrait-background" src={background?.background} alt=""/><img className="g4g-portrait-person" src={artwork?.portrait} alt=""/></div><img className="g4g-portrait-frame" src={`/creative/ui/frame-${subject.rarity}.png`} alt=""/>{(subject.rarity==='SR'||subject.rarity==='SSR')&&<span className="g4g-portrait-sheen" aria-hidden="true"/>}</figure>;
}
export interface GrowthViewProps { state: RedesignState; onAction: (action:string,payload:Record<string,unknown>)=>Promise<unknown>; }
function Modal({title,onClose,children,art=false,message,pending=false,resultOnly=false}:{title:string;onClose:()=>void;children:ReactNode;art?:boolean;message?:string;pending?:boolean;resultOnly?:boolean}) {
  return <CentralModal title={title} onClose={onClose} closeDisabled={pending || resultOnly} hideCloseButton={resultOnly} className={`g4g-modal ${art?'g4g-art':''}`}>
    {message&&!art&&<p className="g4g-message" role="alert">{message}</p>}
    <div inert={pending} aria-busy={pending}>{children}</div>
  </CentralModal>;
}
export default function GrowthView({state,onAction}:GrowthViewProps) {
  const [listQuery,setListQuery]=useState('');
  const [choiceQuery,setChoiceQuery]=useState(''),[choiceFilter,setChoiceFilter]=useState(''),[choiceSort,setChoiceSort]=useState('name');
  const [tab,setTab]=useState('デッキ'); const [filter,setFilter]=useState('');const [sort,setSort]=useState('level');const [selected,setSelected]=useState<string|null>(null);const [art,setArt]=useState(false);const [skillDetail,setSkillDetail]=useState<string|null>(null);const [equipmentDetail,setEquipmentDetail]=useState<string|null>(null);const [assign,setAssign]=useState<{kind:'skill'|'equipment';slot:number|EquipmentSlot}|null>(null);const [position,setPosition]=useState(0);const [bulk,setBulk]=useState(false);const [checked,setChecked]=useState<string[]>([]);const [confirm,setConfirm]=useState(false);const [saving,setBusy]=useState(false);const [message,setMessage]=useState('');const [growthMode,setGrowthMode]=useState<'level'|'soul'|'exchange'|'equipment-level'|null>(null);const actionLock=useRef(false);const [result,setResult]=useState<GrowthResult|null>(null);const [resultSubject,setResultSubject]=useState<{name:string;image?:string;character?:typeof CHARACTER_MASTERS[number]}|null>(null);
  const run=async(action:string,payload:Record<string,unknown>)=>{if(actionLock.current||!ready)return;actionLock.current=true;setBusy(true);setMessage('');try{const response=await onAction(action,payload) as {state?:RedesignState}|undefined;if(!response?.state)throw new Error('処理結果を確認できません。再読込して状態を確認してください。');const character=CHARACTER_MASTERS.find(c=>c.id===payload.characterId);const skill=SKILL_MASTERS.find(c=>c.id===payload.skillId);const equipment=EQUIPMENT_MASTERS.find(e=>e.id===state.equipment.find(e=>e.instanceId===payload.instanceId)?.masterId);setResultSubject(character?{name:character.name,character}:skill?{name:skill.name,image:skill.image}:equipment?{name:equipment.name,image:equipment.image}:null);setResult(getGrowthResult(state,response.state,action,payload));return true;}catch(error){setMessage(error instanceof Error?error.message:'保存できませんでした。');return false;}finally{actionLock.current=false;setBusy(false);}};
  const deckSlots=getUnlockedDeckSlots(state);
  const party=useMemo(()=>buildBattleParty(state),[state]);
  const chars=useMemo(()=>state.characters.filter(c=>c.level>0).map(owned=>({owned,master:CHARACTER_MASTERS.find(c=>c.id===owned.id)!})).filter(c=>c.master).filter(c=>c.master.name.includes(listQuery.trim())).filter(c=>!filter||c.master.element===filter||c.master.rarity===filter||c.master.role===filter).sort((a,b)=>sort==='name'?a.master.name.localeCompare(b.master.name,'ja'):sort==='rarity'?RARITIES.indexOf(b.master.rarity)-RARITIES.indexOf(a.master.rarity):sort==='element'?a.master.element.localeCompare(b.master.element):b.owned.level-a.owned.level),[state.characters,filter,sort,listQuery]);
  const skills=state.skills.map(owned=>({owned,master:getOwnedSkillMaster(owned.id,owned.level)!})).filter(s=>s.master).filter(s=>s.master.name.includes(listQuery.trim())).filter(s=>!filter||s.master.element===filter||s.master.rarity===filter).sort((a,b)=>sort==='name'?a.master.name.localeCompare(b.master.name,'ja'):sort==='rarity'?RARITIES.indexOf(b.master.rarity)-RARITIES.indexOf(a.master.rarity):sort==='sp'?b.master.spCost-a.master.spCost:sort==='element'?a.master.element.localeCompare(b.master.element):b.owned.level-a.owned.level);
  const equipment=state.equipment.map(owned=>({owned,master:EQUIPMENT_MASTERS.find(e=>e.id===owned.masterId)!})).filter(e=>e.master).filter(e=>e.master.name.includes(listQuery.trim())).filter(e=>!filter||e.master.rarity===filter||e.master.slot===filter).sort((a,b)=>sort==='name'?a.master.name.localeCompare(b.master.name,'ja'):sort==='rarity'?RARITIES.indexOf(b.master.rarity)-RARITIES.indexOf(a.master.rarity):sort==='lb'?b.owned.lb-a.owned.lb:sort==='slot'?a.master.slot.localeCompare(b.master.slot):b.owned.level-a.owned.level);
  const current=state.characters.find(c=>c.id===selected);const master=CHARACTER_MASTERS.find(c=>c.id===selected);const member=state.deck.find(m=>m.characterId===selected);const stats=party.find(p=>p.id===selected)?.stats??(master&&current?getCharacterStats(master,current.level,current.awakening):null);
  const ownedSkill=state.skills.find(s=>s.id===skillDetail);const detailSkill=ownedSkill?getOwnedSkillMaster(ownedSkill.id,ownedSkill.level):undefined;const ownedEquip=state.equipment.find(e=>e.instanceId===equipmentDetail);const detailEquip=EQUIPMENT_MASTERS.find(e=>e.id===ownedEquip?.masterId);
  const visibleCharacters=tab==='武将'||tab==='編成'?chars.map(c=>c.master):tab==='デッキ'?state.deck.map(m=>CHARACTER_MASTERS.find(c=>c.id===m.characterId)).filter((c):c is typeof CHARACTER_MASTERS[number]=>Boolean(c)):[];
  const sources=visibleCharacters.flatMap(characterImageSources);
  sources.push('/ui/raid/v2/panel-sakura-overlay.png');
  if(tab==='デッキ') sources.push(...['people','armor','scroll'].map(icon=>`/ui/raid/v2/${icon}.png`));
  if(master) sources.push(...characterImageSources(master));
  if(art&&master) sources.push(master.image);
  if(tab==='スキル'||assign?.kind==='skill') sources.push(...skills.map(s=>s.master.image));
  if(tab==='装備'||assign?.kind==='equipment') sources.push(...equipment.map(e=>e.master.image));
  if(detailSkill) sources.push(detailSkill.image);
  if(detailEquip) sources.push(detailEquip.image);
  if(tab==='デッキ'){sources.push(...state.deck.flatMap(m=>m.skillIds).flatMap(id=>getOwnedSkillMaster(id,state.skills.find(s=>s.id===id)?.level??0)?.image??[]));}
  if(member){sources.push(...member.skillIds.flatMap(id=>getOwnedSkillMaster(id,state.skills.find(s=>s.id===id)?.level??0)?.image??[]));sources.push(...Object.values(member.equipment).flatMap(id=>EQUIPMENT_MASTERS.find(e=>e.id===state.equipment.find(e=>e.instanceId===id)?.masterId)?.image??[]));}
  if(growthMode==='level'||growthMode==='equipment-level'){const prefix=growthMode==='level'?'char':'equip';sources.push(...['s','m','l'].map(size=>`/items/${prefix}_exp_${size}.png`));}
  const {ready,failed,retry}=useCharacterImageReadiness(sources);
  const busy=saving||!ready;
  const skillCost=ownedSkill&&detailSkill&&ownedSkill.level<RULES.skillMax?LB_STEPS[ownedSkill.level]*SKILL_LB_FACTORS[detailSkill.rarity]:0;
  const equipCost=ownedEquip&&detailEquip&&ownedEquip.lb<10?LB_STEPS[ownedEquip.lb]*EQUIPMENT_LB_FACTORS[detailEquip.rarity]:0;
  const saveDeck=(deck:DeckMember[])=>run('save_deck',{deck});
  const updateMember=(update:Partial<DeckMember>)=>saveDeck(state.deck.map(m=>m.characterId===selected?{...m,...update}:m));
  const changeTab=(next:string)=>{setTab(next);setFilter('');setSort('level');setListQuery('');};
  const selectedDeckMember=state.deck[position]??state.deck[0];
  const emptyPosition=position>=state.deck.length;
  const formationChars=tab==='編成'&&emptyPosition?chars.filter(c=>!state.deck.some(m=>m.characterId===c.owned.id)):chars;
  const unlockedStage=(index:number)=>{const id=index===3?'mikawa-1':state.earlyProgress?'mikawa-3':'mikawa-2';const stage=QUEST_STAGES.find(s=>s.id===id);return stage?questDisplayName(stage):'対象ステージ';};
  const equipmentChoices=assign?.kind==='equipment'?state.equipment.flatMap(owned=>{const master=EQUIPMENT_MASTERS.find(m=>m.id===owned.masterId);return master&&equipmentFits(assign.slot as EquipmentSlot,master.slot)?[{owned,master}]:[];}):[];
  const matchChoice=(m:{name:string;rarity:string;element?:string;slot?:string})=>m.name.normalize('NFKC').toLocaleLowerCase('ja').includes(choiceQuery.normalize('NFKC').trim().toLocaleLowerCase('ja'))&&(!choiceFilter||[m.rarity,m.element,m.slot].includes(choiceFilter));
  const choiceSkills=state.skills.map(owned=>({owned,master:getOwnedSkillMaster(owned.id,owned.level)})).filter((r):r is typeof r & {master:NonNullable<typeof r.master>}=>!!r.master).filter(r=>matchChoice(r.master)).sort((a,b)=>choiceSort==='level'?b.owned.level-a.owned.level:choiceSort==='rarity'?RARITIES.indexOf(b.master.rarity)-RARITIES.indexOf(a.master.rarity):a.master.name.localeCompare(b.master.name,'ja'));
  const filteredEquipmentChoices=equipmentChoices.filter(r=>matchChoice(r.master)).sort((a,b)=>choiceSort==='level'?b.owned.level-a.owned.level:choiceSort==='rarity'?RARITIES.indexOf(b.master.rarity)-RARITIES.indexOf(a.master.rarity):a.master.name.localeCompare(b.master.name,'ja'));
  const allEligible=equipment.filter(e=>!e.owned.locked&&!isEquipmentAssigned(state,e.owned.instanceId));
  const listKind=tab==='武将'||tab==='編成'?'武将':tab==='スキル'?'スキル':tab==='装備'?'装備':null;
  const ownedListCount=listKind==='武将'?state.characters.filter(c=>c.level>0).length:listKind==='スキル'?state.skills.length:state.equipment.length;
  const visibleListCount=listKind==='武将'?chars.length:listKind==='スキル'?skills.length:equipment.length;

  return <section className="g4-growth" aria-busy={busy} onClickCapture={event=>{if(!ready&&!(event.target as HTMLElement).closest('[data-image-retry]')){event.preventDefault();event.stopPropagation();}}}><PageTitleBanner page="character"/><nav className="g4g-tabs" aria-label="育成"><>{['デッキ','編成','武将','スキル','装備'].map(t=><button key={t} aria-pressed={tab===t} onClick={()=>changeTab(t)}>{t}</button>)}</></nav>
    {!ready&&(failed?<div className="rd-panel" role="alert"><p>画像を読み込めませんでした。通信を確認して再読み込みしてください。</p><button className="g4g-row" data-image-retry onClick={retry}>再読み込み</button></div>:<CentralModal title="読み込み中" className="g4g-image-loading" onClose={()=>{}} closeDisabled><BrandedLoading/></CentralModal>)}
    {ready&&result&&<Modal pending={saving} resultOnly title={result.title} onClose={()=>{setResult(null);setGrowthMode(null);}}><div className="g4g-result">{resultSubject&&<div className="g4g-result-subject">{resultSubject.character?<CharacterCard subject={resultSubject.character} compact hideMarks/>:resultSubject.image?<img src={resultSubject.image} alt=""/>:null}<strong>{resultSubject.name}</strong></div>}<h3>{result.changed?'更新しました':'変更はありません'}</h3>{result.rows.map((row,index)=><div className="g4g-result-row" key={`${row.label}-${index}`}><span>{{ATK:'攻撃力',DEF:'防御力',LUK:'幸運'}[row.label]??row.label}</span><span>{typeof row.before==='number'?row.before.toLocaleString():row.before}</span><strong>→ {typeof row.after==='number'?row.after.toLocaleString():row.after}</strong></div>)}</div><button className="g4g-row g4g-primary" onClick={()=>{setResult(null);setGrowthMode(null);}}>閉じる</button></Modal>}{ready&&message&&!selected&&!skillDetail&&!equipmentDetail&&!confirm&&<Modal pending={saving} title="操作を確認してください" onClose={()=>setMessage('')}><p role="alert">{message}</p><button onClick={()=>setMessage('')}>閉じる</button></Modal>}
    {(tab==='デッキ'||tab==='編成')&&<><div className="g4g-section-heading"><h3>{tab==='デッキ'?'出撃デッキ':'出撃メンバー'}</h3>{tab==='デッキ'?<button onClick={()=>changeTab('編成')}>並び替え ↕</button>:<div className="g4g-formation-order" aria-label="選択武将の行動順"><button disabled={busy||position===0||position>=state.deck.length} onClick={async()=>{const deck=[...state.deck];[deck[position-1],deck[position]]=[deck[position],deck[position-1]];if(await saveDeck(deck))setPosition(position-1);}}>← 移動</button><button disabled={busy||position>=state.deck.length-1} onClick={async()=>{const deck=[...state.deck];[deck[position+1],deck[position]]=[deck[position],deck[position+1]];if(await saveDeck(deck))setPosition(position+1);}}>移動 →</button></div>}</div><div className="g4g-party">{state.deck.map((m,index)=>{const owned=state.characters.find(c=>c.id===m.characterId);const cm=CHARACTER_MASTERS.find(c=>c.id===m.characterId);return <button key={m.characterId} className={tab==='編成'&&index===position?'selected':''} onClick={()=>{setPosition(index);if(tab==='デッキ')setSelected(m.characterId);}}><em className="g4g-order">{index+1}</em>{cm&&<CharacterCard subject={cm} compact hideMarks/>}<b>{cm?.name}</b><span>{cm?.rarity} <ElementBadge element={cm?.element??''} size="small"/></span><span>Lv.{owned?.level}　+{owned?.awakening}</span></button>;})}{Array.from({length:Math.max(0,5-state.deck.length)},(_,offset)=>{const index=state.deck.length+offset;return <button key={`empty-${index}`} className={tab==='編成'&&position===index?'selected':''} disabled={busy} onClick={()=>{if(index>=deckSlots){setMessage(unlockedStage(index)+'をクリアすると解放されます。');return;}setPosition(state.deck.length);changeTab('編成');if(index>state.deck.length)setMessage('空き枠は行動順の先頭から編成します。編成後に並び替えできます。');}}><em className="g4g-order">{index+1}</em><span className="g4g-empty-slot">{index>=deckSlots?'未解放':'＋'}</span><span>{index>=deckSlots?'':'編成する'}</span><small>{index>=deckSlots?`${unlockedStage(index)}クリア`:null}</small></button>;})}</div>
    {tab==='デッキ'&&<><div className="g4g-elements">{Object.entries(ELEMENTS).map(([id,label])=><span key={id}><i className={`g4g-element-dot g4g-element-${id}`}>{label}</i>{party.filter(p=>p.element===id).length}</span>)}</div><div className="g4g-totals g4g-sp-total"><span>共通SP上限 <b>400</b></span></div></>}
    {tab==='デッキ'?<div className="g4g-actions g4g-auto-actions">{['おまかせ編成','おまかせ装備','おまかせスキル'].map((label,index)=><button disabled={busy} key={label} onClick={()=>{if(index===1)void saveDeck(autoEquipEquipment(state));else if(index===2)void saveDeck(autoEquipSkills(state));else {const best=[...state.characters].filter(c=>c.level>0).sort((a,b)=>b.level-a.level||b.awakening-a.awakening).slice(0,deckSlots);void saveDeck(best.map(c=>state.deck.find(m=>m.characterId===c.id)??{characterId:c.id,skillIds:[],equipment:{}}));}}}><img src={`/ui/raid/v2/${['people','armor','scroll'][index]}.png`} alt=""/><span>{label}</span></button>)}</div>:null}{tab==='デッキ'&&selectedDeckMember&&<section className="g4g-selected-skills"><h3>選択中武将のスキル</h3><div className="g4g-skill-stack">{Array.from({length:3},(_,index)=>{const skill=getOwnedSkillMaster(selectedDeckMember.skillIds[index],state.skills.find(s=>s.id===selectedDeckMember.skillIds[index])?.level??0);return <button key={index} onClick={()=>setSelected(selectedDeckMember.characterId)}>{skill?<>{skill.image&&<AssetIcon src={skill.image} name=""/>}<b>{skill.name}</b><span>LB+{state.skills.find(s=>s.id===skill.id)?.level??0}</span></>:<><span className="g4g-skill-empty">{index>=getSkillSlots(state.characters.find(c=>c.id===selectedDeckMember.characterId)?.awakening??0)?'未解放':'＋'}</span><span>未装備</span></>}</button>;})}</div></section>}</>}
    {tab!=='デッキ'&&<label className="g4-list-search">名前で検索<input type="search" value={listQuery} onChange={e=>setListQuery(e.target.value)}/></label>}
    {tab!=='デッキ'&&<div className={`g4g-filters ${tab==='装備'?'g4g-equipment-filters':''}`}><label>絞り込み<select value={filter} onChange={e=>setFilter(e.target.value)}><option value="">すべて</option>{RARITIES.map(r=><option key={r}>{r}</option>)}{tab==='装備'?EQUIPMENT_SLOTS.filter(s=>s!=='accessory2').map(s=><option key={s} value={s}>{SLOT_LABELS[s]}</option>):Object.entries(ELEMENTS).map(([id,label])=><option key={id} value={id}>{label}</option>)}</select></label><label>並び替え<select value={sort} onChange={e=>setSort(e.target.value)}><option value="level">{tab==='スキル'?'LB':'Lv'}</option><option value="rarity">レアリティ</option><option value="name">名前</option>{tab==='装備'?<><option value="lb">LB</option><option value="slot">部位</option></>:<option value="element">属性</option>}{tab==='スキル'&&<option value="sp">消費SP</option>}</select></label>{tab==='装備'&&<button disabled={busy||state.equipment.length===0} onClick={()=>{setBulk(!bulk);setChecked([]);}}>{bulk?'選択を終了':'一括分解'}</button>}</div>}
    {ready&&listKind&&visibleListCount===0&&<div className="rd-panel"><p className="rd-muted" role="status">{ownedListCount===0?`所持している${listKind}はありません。`:filter?`絞り込み条件に一致する${listKind}はありません。`:`表示できる${listKind}がありません。`}</p>{filter&&ownedListCount>0&&<button className="g4g-row" onClick={()=>setFilter('')}>絞り込みを解除</button>}</div>}
    {tab==='編成'&&<div className="g4g-formation-help"><p>{emptyPosition?'空き枠へ編成する武将を選んでください。':'入れ替える武将を選んでください。編成中の武将を選ぶと行動順を交換します。'}</p>{emptyPosition&&formationChars.length===0&&<p role="status">{filter?'絞り込み条件に一致する未編成の武将がいません。':'未編成の武将がいません。武将を獲得してから編成できます。'}</p>}<button className="g4g-row" onClick={()=>changeTab('デッキ')}>デッキに戻る</button></div>}
    {(tab==='武将'||tab==='編成')&&<div className="g4g-grid">{formationChars.map(({owned,master:cm})=><button key={owned.id} disabled={busy} onClick={()=>{if(tab==='武将')setSelected(owned.id);else {const deck=structuredClone(state.deck);const existing=deck.findIndex(m=>m.characterId===owned.id);if(existing>=0){if(position>=deck.length)return;[deck[position],deck[existing]]=[deck[existing],deck[position]];}else deck[Math.min(position,deck.length)]={characterId:owned.id,skillIds:[],equipment:{}};void saveDeck(deck).then(saved=>{if(saved)changeTab('デッキ');});}}}><CharacterCard subject={cm} compact hideMarks/><b>{cm.name}</b><span>{cm.rarity}・{ELEMENTS[cm.element]}・{cm.role}</span><span>Lv.{owned.level}　覚醒+{owned.awakening}</span>{state.deck.some(m=>m.characterId===owned.id)&&<small>編成中</small>}</button>)}</div>}
    {tab==='武将'&&<><GrowthInventoryView state={state}/><h3>武将の魂</h3><div className="g4-soul-list">{CHARACTER_MASTERS.filter(c=>!state.characters.some(owned=>owned.id===c.id)&&(state.souls[c.id]??0)>0).map(c=><button className="g4-inventory-entry" key={c.id} onClick={()=>setSelected(c.id)}><CharacterCard subject={c}/><span><strong>{c.name}</strong><span><img className="g4-soul-icon" src={characterArt(c,'portrait')} alt=""/>固有魂 ×{state.souls[c.id]??0}</span></span><span>詳細 ›</span></button>)}</div></>}
    {ready&&!result&&selected&&master&&!current&&<Modal pending={saving} message={message} title="魂から解放" onClose={()=>setSelected(null)}><SoulControls key={selected} state={state} id={selected} run={run} busy={busy} portrait={<CharacterCard subject={master} compact hideMarks/>} onCancel={()=>setSelected(null)}/></Modal>}
    {tab==='スキル'&&<><div className="g4g-grid">{skills.map(({owned,master:sm})=><button key={owned.id} onClick={()=>setSkillDetail(owned.id)}>{sm.image&&<AssetIcon src={sm.image} name={sm.name}/>}<b>{sm.name}</b><span>{sm.rarity} <ElementBadge element={sm.element} size="small"/>　LB+{owned.level}</span><span>消費SP {sm.spCost}</span></button>)}</div></>}
    {tab==='装備'&&<>{bulk&&<div className="g4g-actions"><button onClick={()=>setChecked(allEligible.map(e=>e.owned.instanceId))}>全選択</button><button disabled={!checked.length||busy} onClick={()=>setConfirm(true)}>分解確認 {checked.length}件</button></div>}<div className="g4g-grid">{equipment.map(({owned,master:em})=><div className="g4g-equipment" key={owned.instanceId}>{bulk&&<input aria-label={`${em.name}を分解選択`} type="checkbox" checked={checked.includes(owned.instanceId)} disabled={owned.locked||isEquipmentAssigned(state,owned.instanceId)} onChange={e=>setChecked(e.target.checked?[...checked,owned.instanceId]:checked.filter(id=>id!==owned.instanceId))}/>}<button onClick={()=>setEquipmentDetail(owned.instanceId)}><img src={em.image} alt={em.name}/><b>{em.name}</b><span>{em.rarity}・{SLOT_LABELS[em.slot]}</span><span>Lv.{owned.level}　LB+{owned.lb}</span><small>{isEquipmentAssigned(state,owned.instanceId)?'装備中':owned.locked?'保護中':''}</small></button></div>)}</div></>}
    {ready&&!result&&selected&&current&&master&&stats&&!art&&!growthMode&&!assign&&<Modal pending={saving} message={message} title={master.name} onClose={()=>{setSelected(null);setAssign(null);}}><div className="g4g-profile"><button className="g4g-character-card" onClick={()=>setArt(true)} aria-label="全身を見る"><CharacterCard subject={master} compact hideMarks/></button><div className="g4g-character-summary"><h3>{master.name}</h3><p className="g4g-rarity-line"><b>{master.rarity}</b> <ElementBadge element={master.element}/></p><p>Lv.{current.level} / {getCharacterLevelCap(current.awakening)}　覚醒+{current.awakening}</p><p>{master.role}</p><div className="g4g-actions"><button onClick={()=>setGrowthMode('level')}>Lv育成</button><button onClick={()=>setGrowthMode('soul')}>覚醒</button></div></div></div><dl className="g4g-stats">{Object.entries(stats).filter(([key])=>['hp','atk','def','luk'].includes(key)).map(([key,value])=><div key={key}><dt>{{hp:'HP',atk:'攻撃力',def:'防御力',luk:'幸運'}[key]??key.toUpperCase()}</dt><dd>{(['hp','atk','def','luk'].includes(key)?Math.floor(value):value).toLocaleString()}</dd></div>)}</dl><PassiveDisplay passive={getCharacterPassive(master,current.awakening)} rarity={master.rarity}/>{member?<><h3>装備スキル</h3><div className="g4g-skill-stack">{Array.from({length:3},(_,index)=>{const skillId=member.skillIds[index];const skill=skillId?getOwnedSkillMaster(skillId,state.skills.find(s=>s.id===skillId)?.level??0):undefined;return <button className="g4g-row g4g-skill-row" key={index} disabled={index>=getSkillSlots(current.awakening)} onClick={()=>setAssign({kind:'skill',slot:index})}>{skill?<>{skill.image&&<AssetIcon src={skill.image} name=""/>}<span><b>{skill.name}</b><small><span className={`rq-element rq-element-${skill.element}`}>{ELEMENTS[skill.element]}</span> LB+{state.skills.find(s=>s.id===skill.id)?.level??0} / SP {skill.spCost}</small></span></>:<><span className="g4g-skill-empty">{index>=getSkillSlots(current.awakening)?'未解放':'＋'}</span><span>{index>=getSkillSlots(current.awakening)?`覚醒+${index===1?1:3}で解放`:'未装備'}</span></>}</button>;})}</div><h3>装備</h3><div className="g4g-equipment-slots">{EQUIPMENT_SLOTS.map(slot=>{const equipment=state.equipment.find(e=>e.instanceId===member.equipment[slot]);const item=EQUIPMENT_MASTERS.find(e=>e.id===equipment?.masterId);return <button key={slot} onClick={()=>setAssign({kind:'equipment',slot})}><strong>{SLOT_LABELS[slot]}</strong>{item?<><img src={item.image} alt={item.name}/><span>Lv.{equipment?.level}</span></>:<span>未装備</span>}</button>;})}</div></>:<p>編成に加えるとスキル・装備を設定できます。</p>}<div className="g4g-souls"><span>固有魂 {state.souls[selected]??0}</span><button onClick={()=>setGrowthMode('exchange')}>魂交換</button></div><div className="g4g-actions"><button onClick={()=>setGrowthMode('level')}>Lv育成</button><button onClick={()=>setGrowthMode('soul')}>覚醒</button></div><button className="g4g-row" onClick={()=>setSelected(null)}>閉じる</button></Modal>}
    {ready&&!result&&selected&&master&&current&&growthMode==='level'&&<Modal pending={saving} message={message} title="Lv育成" onClose={()=>setGrowthMode(null)}><LevelGrowthControls state={state} kind="character" id={selected} run={run} busy={busy} portrait={<CharacterCard subject={master} compact hideMarks/>} onCancel={()=>setGrowthMode(null)}/></Modal>}
    {ready&&!result&&selected&&master&&(growthMode==='soul'||growthMode==='exchange')&&<Modal pending={saving} message={message} title={growthMode==='exchange'?'魂交換':'覚醒'} onClose={()=>setGrowthMode(null)}><SoulControls state={state} id={selected} run={run} busy={busy} mode={growthMode==='exchange'?'exchange':'awaken'} portrait={<CharacterCard subject={master} compact hideMarks/>} onCancel={()=>setGrowthMode(null)}/></Modal>}
    {ready&&!result&&art&&master&&<Modal pending={saving} message={message} title="全身鑑賞" art onClose={()=>setArt(false)}><img className="g4g-fullbody" src={master.image} alt={master.name}/></Modal>}
    {ready&&!result&&assign&&member&&<Modal pending={saving} message={message} title={assign.kind==='skill'?'スキルを変更':'装備を変更'} onClose={()=>setAssign(null)}>
      <ListControls query={choiceQuery} onQuery={setChoiceQuery} filter={choiceFilter} onFilter={setChoiceFilter} filters={[...RARITIES.map(value=>({value,label:value})),...Object.entries(assign.kind==='skill'?ELEMENTS:SLOT_LABELS).map(([value,label])=>({value,label}))]} sort={choiceSort} onSort={setChoiceSort} sorts={[{value:'name',label:'名前順'},{value:'level',label:'育成値順'},{value:'rarity',label:'レアリティ順'}]} count={assign.kind==='skill'?choiceSkills.length:filteredEquipmentChoices.length}/>
      {(assign.kind==='skill'?choiceSkills.length:filteredEquipmentChoices.length)===0&&<p role="status">条件に一致する候補がありません。</p>}
      <div className="g4-asset-choices">{assign.kind==='skill'?choiceSkills.map(({owned})=>{const item=getOwnedSkillMaster(owned.id,owned.level);if(!item)return null;const equipped=member.skillIds.includes(owned.id);return <AssetChoice key={owned.id} image={item.image} name={item.name} metadata={<>{item.rarity} <ElementBadge element={item.element} size="small"/> / LB+{owned.level} / SP {item.spCost}</>} description={skillDescription(item)} status={equipped?'この武将に装備中':undefined} disabled={busy||equipped} onSelect={()=>{const ids=[...member.skillIds];ids.splice(Math.min(Number(assign.slot),ids.length),1,owned.id);void updateMember({skillIds:ids}).then(saved=>{if(saved)setAssign(null);});}}/>;}):filteredEquipmentChoices.map(({owned,master:itemMaster})=>{const item=itemMaster;const assigned=state.deck.find(m=>Object.values(m.equipment).includes(owned.instanceId));const isCurrent=member.equipment[assign.slot as EquipmentSlot]===owned.instanceId;const owner=assigned?CHARACTER_MASTERS.find(c=>c.id===assigned.characterId)?.name:undefined;const values=getEquipmentStats(item,owned.level,owned.lb);return <AssetChoice key={owned.instanceId} image={item.image} name={item.name} metadata={item.rarity+'・'+SLOT_LABELS[item.slot]+' / Lv.'+owned.level+' / LB+'+owned.lb} description={Object.entries(values).filter(([key])=>['hp','atk','def','luk'].includes(key)).map(([key,value])=>({hp:'HP',atk:'攻撃力',def:'防御力',luk:'幸運'}[key]+' '+Math.floor(value).toLocaleString())).join(' / ')} status={isCurrent?'この枠に装備中':assigned?(owner??'他の武将')+'が装備中':owned.locked?'保護中（装備できます）':undefined} disabled={busy||Boolean(assigned)} onSelect={()=>{void updateMember({equipment:{...member.equipment,[assign.slot]:owned.instanceId}}).then(saved=>{if(saved)setAssign(null);});}}/>;})}</div>
      {assign.kind==='skill'&&state.skills.length===0&&<p role="status">所持スキルがありません。スキルを獲得すると選択できます。</p>}
      {assign.kind==='equipment'&&equipmentChoices.length===0&&<p role="status">この部位に装備できる所持品がありません。</p>}
      {assign.kind==='equipment'&&equipmentChoices.length>0&&equipmentChoices.every(e=>isEquipmentAssigned(state,e.owned.instanceId))&&<p role="status">候補はすべて装備中です。他の枠から外すと選択できます。</p>}
      <div className="g4-asset-selector-actions"><button disabled={busy||!(assign.kind==='skill'?member.skillIds[Number(assign.slot)]:member.equipment[assign.slot as EquipmentSlot])} onClick={async()=>{if(assign.kind==='skill'){const ids=[...member.skillIds];ids.splice(Number(assign.slot),1);if(await updateMember({skillIds:ids}))setAssign(null);}else{const eq={...member.equipment};delete eq[assign.slot as EquipmentSlot];if(await updateMember({equipment:eq}))setAssign(null);}}}>外す</button><button disabled={busy} onClick={()=>setAssign(null)}>取消</button></div>
    </Modal>}
    {ready&&!result&&detailSkill&&ownedSkill&&<Modal pending={saving} message={message} title={detailSkill.name} onClose={()=>setSkillDetail(null)}><div className="g4g-growth-hero">{detailSkill.image&&<img className="g4g-detail-icon" src={detailSkill.image} alt=""/>}<div className="g4g-growth-summary"><h3>{detailSkill.name}</h3><p>{detailSkill.rarity} <ElementBadge element={detailSkill.element}/></p><strong className="g4g-growth-transition">LB {ownedSkill.level} → {ownedSkill.level<RULES.skillMax?ownedSkill.level+1:'最大'}</strong><p>消費SP {detailSkill.spCost}</p></div></div><p>{skillDescription(detailSkill)}</p><div className="g4g-performance"><div><span>現在の性能</span><strong>{formalSkillPerformance(detailSkill.id,ownedSkill.level)??`効果倍率 ${(1+ownedSkill.level*0.05).toFixed(2)}`}</strong></div><div><span>次の性能</span><strong>{ownedSkill.level<RULES.skillMax?(formalSkillPerformance(detailSkill.id,ownedSkill.level+1)??`効果倍率 ${(1+(ownedSkill.level+1)*0.05).toFixed(2)}`):'最大LB'}</strong></div></div><p className="g4g-skill-note">同じ所持スキルのLBは装備した全武将へ共通適用されます。</p><p className="g4g-cost">スキルLB素材 所持{state.materials.skill}{ownedSkill.level<RULES.skillMax&&<> / 必要{skillCost}・銭 {(skillCost*1000).toLocaleString()}</>}</p>{ownedSkill.level>=RULES.skillMax?<p>最大LBです。</p>:state.materials.skill<skillCost||state.cash<skillCost*1000?<p role="status">スキルLB素材または銭が不足しています。</p>:null}<button className="g4g-row g4g-primary" disabled={busy||ownedSkill.level>=RULES.skillMax||state.materials.skill<skillCost||state.cash<skillCost*1000} onClick={()=>void run('skill_level',{skillId:detailSkill.id})}>{ownedSkill.level>=RULES.skillMax?'最大LB':'LBを上げる'}</button></Modal>}
    {ready&&!result&&!confirm&&detailEquip&&ownedEquip&&growthMode!=='equipment-level'&&<Modal pending={saving} message={message} title={detailEquip.name} onClose={()=>setEquipmentDetail(null)}><img className="g4g-detail-icon" src={detailEquip.image} alt=""/><p>{detailEquip.rarity}・{SLOT_LABELS[detailEquip.slot]}・Lv.{ownedEquip.level}・LB+{ownedEquip.lb}</p><dl className="g4g-stats">{Object.entries(getEquipmentStats(detailEquip,ownedEquip.level,ownedEquip.lb)).filter(([key])=>['hp','atk','def','luk'].includes(key)).map(([key,value])=><div key={key}><dt>{{hp:'HP',atk:'攻撃力',def:'防御力',luk:'幸運'}[key]??key.toUpperCase()}</dt><dd>{['hp','atk','def','luk'].includes(key)?Math.floor(value):value}</dd></div>)}</dl><div className="g4g-actions"><button disabled={busy} onClick={()=>void run('equipment_lock',{instanceId:ownedEquip.instanceId,locked:!ownedEquip.locked})}>{ownedEquip.locked?'保護を解除':'保護する'}</button><button disabled={busy||ownedEquip.locked||isEquipmentAssigned(state,ownedEquip.instanceId)} onClick={()=>{setChecked([ownedEquip.instanceId]);setConfirm(true);}}>分解</button></div>{(ownedEquip.locked||isEquipmentAssigned(state,ownedEquip.instanceId))&&<p>装備中・保護中の装備は分解できません。</p>}<p>解放Lv上限 {getEquipmentLevelCap(ownedEquip.lb)} / 最大100・装備LB素材 {state.materials.equipmentLb}</p><button onClick={()=>setGrowthMode('equipment-level')}>Lv育成</button><p>LB+{ownedEquip.lb} → {ownedEquip.lb<10?ownedEquip.lb+1:'最大'}・解放上限 {getEquipmentLevelCap(ownedEquip.lb)} → {getEquipmentLevelCap(ownedEquip.lb+1)}</p>{ownedEquip.lb<10&&<p className="g4g-cost">必要素材 {equipCost}・必要銭 {(equipCost*500).toLocaleString()}</p>}{ownedEquip.lb<10&&(state.materials.equipmentLb<equipCost||state.cash<equipCost*500)&&<p role="status">装備LB素材または銭が不足しています。</p>}{ownedEquip.lb<10&&<button className="g4g-row g4g-primary" disabled={busy||state.materials.equipmentLb<LB_STEPS[ownedEquip.lb]*EQUIPMENT_LB_FACTORS[detailEquip.rarity]||state.cash<LB_STEPS[ownedEquip.lb]*EQUIPMENT_LB_FACTORS[detailEquip.rarity]*500} onClick={()=>void run('equipment_lb',{instanceId:ownedEquip.instanceId})}>LBで上限を解放</button>}</Modal>}
    {ready&&!result&&detailEquip&&ownedEquip&&growthMode==='equipment-level'&&<Modal pending={saving} message={message} title="装備Lv育成" onClose={()=>setGrowthMode(null)}><LevelGrowthControls state={state} kind="equipment" id={ownedEquip.instanceId} run={run} busy={busy} onCancel={()=>setGrowthMode(null)}/></Modal>}
    {ready&&!result&&confirm&&<Modal pending={saving} message={message} title="装備を分解" onClose={()=>setConfirm(false)}><p>選択した {checked.length} 件を分解します。</p>{checked.map(id=><p key={id}>{EQUIPMENT_MASTERS.find(m=>m.id===state.equipment.find(e=>e.instanceId===id)?.masterId)?.name}</p>)}<p>装備LB素材 {checked.reduce((sum,id)=>sum+DISMANTLE_MATERIALS[EQUIPMENT_MASTERS.find(m=>m.id===state.equipment.find(e=>e.instanceId===id)?.masterId)!.rarity],0)}</p><p>育成済み装備も含めて分解します。投入したEXP・銭・LB素材は返還されません。</p><button disabled={busy} onClick={async()=>{if(await run('equipment_dismantle',{instanceIds:checked,confirmTrained:true})){setConfirm(false);setChecked([]);}}}>分解を確定</button></Modal>}
  </section>;
}
