'use client';
import { characterArt } from '@/theme/creativeAssets';
import { useEffect, useRef, useState } from 'react';
import type { BattleUnit, RaidRoom, RedesignState, Reward } from '../../../domain/redesign/types';
import { buildBattleParty } from '../../../domain/redesign/masters';
import { getRoomRaidMaster, raidEnemy } from '../../../domain/redesign/raid';
import { raidElementLabels, raidRescueWindow, raidRewardLabel, raidTimeRemaining } from '../../../domain/redesign/raidPresentation';
import CanonicalDialog from '../ui/CanonicalDialog';
import PreparationModal from './PreparationModal';
import './RaidView.css';
export interface RaidViewProps { state:RedesignState;rooms:RaidRoom[];party:BattleUnit[];onAction:(action:Record<string,unknown>)=>Promise<unknown>;onOpenDeck:()=>void;initialRoomId?:string; }
function Rewards({rewards}:{rewards:Reward[]}) {return <ul>{rewards.map((r,i)=><li key={`${r.kind}-${i}`}>{raidRewardLabel(r)}</li>)}</ul>;}
export default function RaidView({state,rooms,party,onAction,onOpenDeck,initialRoomId}:RaidViewProps){
 const [selected,setSelected]=useState<string|null>(initialRoomId??null),[filter,setFilter]=useState('all'),[modal,setModal]=useState<string|null>(null),[now,setNow]=useState(()=>Date.now()),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const lock=useRef(false);
 useEffect(()=>{const timer=setInterval(()=>setNow(Date.now()),1000);return()=>clearInterval(timer);},[]);
 const room=rooms.find(r=>r.id===selected),master=room?getRoomRaidMaster(room):null,me=room?.participants.find(p=>p.userId===state.userId),enemy=master&&room?raidEnemy(master,room.level):null;
 const active=(r:RaidRoom)=>r.status==='active'&&Date.parse(r.expiresAt)>now;
 const live=rooms.filter(active).filter(r=>filter==='all'||getRoomRaidMaster(r).type===filter).sort((a,b)=>Date.parse(a.expiresAt)-Date.parse(b.expiresAt));
 async function run(action:string,extra:Record<string,unknown>={}){if(lock.current)return;lock.current=true;setBusy(true);setError('');try{await onAction({action,roomId:selected,...extra});setModal(null);}catch(e){setError(e instanceof Error?e.message:'処理に失敗しました。再度お試しください。');}finally{lock.current=false;setBusy(false);}}
 const select=(r:RaidRoom)=>{setSelected(r.id);setModal(null);setError('');};
 function Card({value}:{value:RaidRoom}){const m=getRoomRaidMaster(value),e=raidEnemy(m,value.level),p=value.participants.find(p=>p.userId===state.userId&&!p.leftAt),count=value.participants.filter(p=>!p.leftAt).length;return <button className="rd-panel rd-raid-card" onClick={()=>select(value)}>{characterArt(e, 'battle') && <img src={characterArt(e, 'battle')} alt=""/>}<div><div className="rd-raid-labels"><span>{m.type==='encounter'?'エンカウント':'領土侵攻'}</span>{p&&<span>参加中</span>}{value.rescueCount>0&&<span>救援中</span>}{Date.parse(value.expiresAt)-now<600000&&<span>残りわずか</span>}</div><strong>{m.name} Lv.{value.level}</strong><p>{raidElementLabels[e.element]}属性 · {m.type==='encounter'?'強敵':'高難度'}</p><meter min={0} max={value.maxHp} value={value.hp}/><small>残HP {Math.ceil(value.hp/value.maxHp*100)}% · {count}/{m.maxParticipants}人</small><p>{raidTimeRemaining(value.expiresAt,now)}</p><b>{p?'続きへ':value.rescueCount?'救援に向かう':'参加する'} ›</b></div></button>;}
 const window=room&&master?raidRescueWindow(master.type,room.rescueCount,room.rescueWindowStartedAt,now):null;
 const available=room&&active(room)&&!me?.leftAt;
 return <section className="rd-raid rd-stack">
 {error&&<p role="alert" className="rd-raid-error">{error}</p>}
 {!room||!master||!enemy?<><div className="rd-row"><h1>レイド</h1><button className="rd-button" disabled={busy} onClick={()=>void run('raid_refresh')}>更新</button></div><nav className="rd-tabs" aria-label="レイド種別">{[['all','すべて'],['encounter','エンカウント'],['unlock','領土侵攻']].map(([id,label])=><button key={id} className="rd-button" aria-pressed={filter===id} onClick={()=>setFilter(id)}>{label}</button>)}</nav><p className="rd-muted">開催中 · 残り時間が短い順</p>{live.length?live.map(r=><Card key={r.id} value={r}/>):<div className="rd-panel">開催中のレイドはありません。クエストをクリアすると、強敵に遭遇することがあります。</div>}{rooms.some(r=>!active(r)&&r.participants.some(p=>p.userId===state.userId))&&<details className="rd-panel"><summary>終了したレイドの結果・未受取報酬</summary>{rooms.filter(r=>!active(r)&&r.participants.some(p=>p.userId===state.userId)).map(r=><button className="rd-button" key={r.id} onClick={()=>select(r)}>{getRoomRaidMaster(r).name} · {r.status==='defeated'?'討伐成功':'終了'}{r.rewardGrants.some(g=>g.userId===state.userId&&!g.claimed)?' · 未受取あり':''}</button>)}</details>}</>:<>
 <button className="rd-button" onClick={()=>setSelected(null)}>‹ レイド一覧</button><section className="rd-panel rd-raid-detail">{characterArt(enemy, 'battle') && <img className="rd-raid-boss" src={characterArt(enemy, 'battle')} alt={master.name}/>}<div className="rd-raid-labels"><span>{master.type==='encounter'?'エンカウント':'領土侵攻'}</span><span>{raidElementLabels[enemy.element]}属性</span><span>{master.type==='encounter'?'強敵':'高難度'}</span></div><h1>{master.name} Lv.{room.level}</h1><meter min={0} max={room.maxHp} value={room.hp}/><p>共通HP {room.hp.toLocaleString()} / {room.maxHp.toLocaleString()}（{Math.ceil(room.hp/room.maxHp*100)}%）</p><p>{active(room)?raidTimeRemaining(room.expiresAt,now):room.status==='defeated'?'討伐成功':'開催終了'} · {room.participants.filter(p=>!p.leftAt).length}/{master.maxParticipants}人</p></section>
 <div className="rd-raid-tools">{[['enemy','敵情報'],['participants','参加者'],['rewards','報酬'],['rescue','救援']].map(([id,label])=><button className="rd-button" key={id} onClick={()=>setModal(id)}>{label}</button>)}</div>
 {me&&<section className="rd-panel"><h2>自分の貢献</h2><p>累計与ダメージ {me.totalDamage.toLocaleString()}</p><p>{me.attempts}戦 · {me.wins}勝 · 直近 {me.lastResult??'未挑戦'}</p><p>{me.wins>=3?'討伐報酬資格 取得済み':`討伐報酬資格まで あと${3-me.wins}勝`}</p>{master.type==='unlock'&&<p>参加時の共通進行 Lv.{me.joinedLevel}</p>}{me.leftAt&&<p>退出済み</p>}</section>}
 {available&&(me?<button className="rd-button rd-primary" disabled={busy} onClick={()=>setModal('prepare')}>挑む · 行動力 {master.energyCost}</button>:<button className="rd-button rd-primary" disabled={busy||room.participants.filter(p=>!p.leftAt).length>=master.maxParticipants} onClick={()=>void run('raid_join')}>参加する</button>)}
 {me&&!me.leftAt&&room.ownerId!==state.userId&&active(room)&&<button className="rd-button" disabled={busy} onClick={()=>setModal('leave')}>このレイドから退出</button>}
 </>}
 {room&&master&&enemy&&modal==='enemy'&&<CanonicalDialog title="敵情報" onClose={()=>setModal(null)}><p>{enemy.name} Lv.{enemy.level} · {raidElementLabels[enemy.element]}属性</p><p>個別バトルHP {enemy.stats.hp.toLocaleString()} / SP {enemy.stats.sp}</p><p>行動カウント {enemy.actionCount} · 被弾でSP回復</p><h3>主なスキル</h3>{enemy.skills.map(s=><p key={s.id}>{s.name} · 消費SP {s.spCost}<br/>{s.description}</p>)}<h3>フェーズチェンジ</h3>{enemy.phases?.map(p=><p key={p.name}>HP {Math.round(p.hpBelow*100)}%以下：{p.name} · 行動カウント {p.actionCount??enemy.actionCount}</p>)}<p>属性相性：火→風→土→水→火 / 光⇔闇</p><p>全体共通HPと、このバトルの敵HPは別です。勝利時は共通HPへの与ダメージが{master.victoryMultiplier}倍になります。</p></CanonicalDialog>}
 {room&&modal==='participants'&&<CanonicalDialog title="参加者" onClose={()=>setModal(null)}><ul className="rd-raid-participants">{room.participants.map(p=><li key={p.userId}><strong>{p.name}{p.userId===state.userId?'（自分）':''}</strong><span>{p.wins}勝 / {p.totalDamage.toLocaleString()}ダメージ{p.leftAt?' · 退出済み':''}</span></li>)}</ul></CanonicalDialog>}
 {room&&master&&modal==='rewards'&&<CanonicalDialog title="報酬" onClose={()=>setModal(null)} actions={[{label:'受け取る',semantic:'primary',disabled:busy||!room.rewardGrants.some(g=>g.userId===state.userId&&!g.claimed),onClick:()=>run('raid_claim')}]}>{error&&<p role="alert" className="rd-raid-error">{error}</p>}<h3>参加報酬</h3><Rewards rewards={master.participationRewards}/><h3>{master.type==='unlock'?'各Lv討伐報酬':'討伐報酬'}</h3><Rewards rewards={master.defeatRewards}/><p>{(me?.wins??0)>=3?'資格取得済み':`あと${3-(me?.wins??0)}勝で討伐報酬資格`}</p><p>参加報酬は初回戦闘後。討伐報酬は資格取得後に討伐されたBossが対象です。</p>{master.type==='unlock'&&<p>参加前・資格取得前に討伐済みのLv報酬は配布されません。次の出撃は現在の共有Lv.{room.level}から開始します。</p>}<p>受取待ち {room.rewardGrants.filter(g=>g.userId===state.userId&&!g.claimed).length}件</p></CanonicalDialog>}
 {room&&master&&window&&modal==='rescue'&&<CanonicalDialog title="救援依頼" onClose={()=>setModal(null)} actions={[{label:'救援を依頼',semantic:'primary',disabled:busy||!available||!me||window.remaining===0,onClick:()=>run('raid_rescue')}]}>{error&&<p role="alert" className="rd-raid-error">{error}</p>}<p>残り {window.remaining} / 3回</p><p>公開先：全体チャット・アクティビティ</p>{window.resetsAt?<p>次回回復：{raidTimeRemaining(window.resetsAt,now)}後（6時間ごと）</p>:<p>このレイドで合計3回まで依頼できます。</p>}</CanonicalDialog>}
 {modal==='leave'&&<CanonicalDialog title="レイドから退出" onClose={()=>setModal(null)} actions={[{label:'戻る',onClick:()=>setModal(null)},{label:'退出する',semantic:'danger',disabled:busy,onClick:()=>run('raid_leave')}]}>{error&&<p role="alert" className="rd-raid-error">{error}</p>}<p>退出すると、このレイドへの参加権を放棄します。再参加はできません。</p></CanonicalDialog>}
 {modal==='prepare'&&room&&master&&<PreparationModal title={`${master.name} Lv.${room.level} · ${raidElementLabels[master.enemy.element]}属性`} party={room.territorySnapshot ? buildBattleParty(state, room.territorySnapshot.battleRules) : party} commonSpMax={room.territorySnapshot && room.territorySnapshot.battleRules.version !== 'common-v2-20260920' ? null : 400} energy={state.energy} energyCost={master.energyCost} busy={busy} error={error} onBack={()=>setModal(null)} onOpenDeck={()=>{setModal(null);onOpenDeck();}} onConfirm={()=>void run('raid_battle')}/>}
 </section>;
}
