import React,{useState} from 'react';
import {createRoot} from 'react-dom/client';
import {EarlyRetentionGuide,EarlySortiePreparation} from '../../src/app/components/redesign/EarlyRetentionGuide';
import {createInitialState} from '../../src/domain/redesign/masters';
import {initializeEarlyProgress} from '../../src/domain/redesign/earlyProgress';
import {applyEarlyAction} from '../../src/domain/redesign/earlyActions';
function fixture(){let s=createInitialState('local-fixture');s.characters=['char_joe_01','char_daimon_01','char_aoi_01','char_jihoon_01','char_yuki_01'].map(id=>({id,level:1,awakening:0}));s.skills=['SKD003','SKD039','SKD035','SKD009','SKD019'].map(id=>({id,level:0}));s.deck=s.characters.slice(0,3).map((c,i)=>({characterId:c.id,skillIds:[s.skills[i].id],equipment:{}}));s=initializeEarlyProgress(s);s.clearedStages=['mikawa-1','mikawa-2','mikawa-3','mikawa-4'];s.earlyProgress!.deckSlots=5;s.earlyProgress!.clearedAdditionalStages=['mikawa-4'];return s;}
const ids=['join-maeda','equip-iwadan','join-takenaka','equip-fire','missions'] as const;
function App(){const [state,setState]=useState(()=>JSON.parse(localStorage.getItem('early-fixture')||'null')||fixture());const [fail,setFail]=useState(false),[playing,setPlaying]=useState(false),[result,setResult]=useState(false),[route,setRoute]=useState('出撃準備');function save(action:string,payload:Record<string,unknown>){return new Promise(resolve=>setTimeout(resolve,150)).then(()=>{if(fail)throw Error('保存失敗テスト：再試行してください。');const next=applyEarlyAction(state,action,payload);localStorage.setItem('early-fixture',JSON.stringify(next));setState(next);return next;});}return <><header><h1>初期導線・独立検証</h1><div>{ids.map(id=><button key={id} onClick={()=>{const s=fixture();if(id==='equip-iwadan')s.deck.push({characterId:'char_jihoon_01',skillIds:[],equipment:{}});s.earlyProgress!.guides={[id]:'pending'};setState(s);localStorage.setItem('early-fixture',JSON.stringify(s));}}>{id}</button>)}</div><label><input type="checkbox" checked={fail} onChange={e=>setFail(e.target.checked)}/>保存失敗</label><label><input type="checkbox" checked={playing} onChange={e=>setPlaying(e.target.checked)}/>戦闘中</label><label><input type="checkbox" checked={result} onChange={e=>setResult(e.target.checked)}/>リザルト中</label></header><main><h2>{route}</h2><EarlySortiePreparation state={state} save={save}/><button onClick={()=>setRoute('出撃しました')}>そのまま出撃</button><output data-testid="deck-count">編成人数 {state.deck.length}</output></main><EarlyRetentionGuide state={state} save={save} battlePlaying={playing} resultOpen={result} navigate={(route)=>setRoute(route==='missions'?'通常任務':'武将・編成')}/></>}
createRoot(document.getElementById('root')!).render(<App/>);
