const fs=require('fs'),path=require('path');const root=path.resolve(__dirname,'..'),dir=path.join(root,'docs/verification/device-debug/b13/mission-v2');fs.mkdirSync(dir,{recursive:true});
const image=p=>'data:image/png;base64,'+fs.readFileSync(path.join(root,'public',p)).toString('base64');
const icons=[image('ui/sengoku/13-coin.png'),image('items/char_exp_s.png')];
const html=`<!doctype html><html lang="ja"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>DBG-053 改訂案2・未承認</title><style>
*{box-sizing:border-box}body{margin:0;background:#100d14;color:#f4efe6;font:16px/1.5 system-ui,sans-serif}.tools{padding:16px;text-align:center}.tools h1{font-size:20px;margin:0 0 8px}.tools p{font-size:14px;margin:4px}.tools a{color:#f1d28c;margin:8px;display:inline-block}.screen{width:375px;height:664px;max-width:100%;margin:auto;display:grid;place-items:center;background:#100d14;padding:12px}.dialog{width:100%;max-height:531px;display:flex;flex-direction:column;background:#19141c;border:1px solid #a78b59;border-radius:4px;overflow:hidden}.heading{padding:6px 12px;border-bottom:1px solid #655039;display:flex;align-items:center;justify-content:center}.heading img{width:240px;max-width:100%;height:auto;display:block}.tabs{display:flex;padding:4px 12px 0;flex:none}.tabs button{flex:1;border:0;border-bottom:1px solid #655039;border-radius:0;background:transparent}.tabs .active{border-bottom:2px solid #efd28c;color:#efd28c}.body{min-height:0;overflow:auto;padding:0 12px}.mission{padding:10px 0;border-bottom:1px solid #655039}.top{display:flex;align-items:baseline;gap:8px}h3{min-width:0;flex:1;font-size:16px;font-weight:600;line-height:1.5;margin:0;overflow-wrap:anywhere}.count{white-space:nowrap;font-size:14px;font-variant-numeric:tabular-nums;color:#e1d5c3}.bottom{display:grid;grid-template-columns:minmax(0,1fr) 96px;gap:8px;align-items:center;margin-top:4px}.rewards{display:flex;flex-wrap:wrap;gap:4px 8px;margin:0;padding:0;list-style:none}.rewards li{display:flex;align-items:center;gap:3px;font-size:13px;white-space:nowrap}.rewards img{width:24px;height:24px;object-fit:contain}button{min-height:44px;padding:8px;font:600 14px/1.4 system-ui;color:#f4efe6;border:1px solid #a78b59;border-radius:4px;background:#30252c;cursor:pointer}.claim{background:#8d3024;border-color:#cd8b69}.check{display:grid;place-items:center;min-height:44px;font-size:24px;color:#bdd8ad}.footer{padding:6px 12px;display:flex;justify-content:flex-end;border-top:1px solid #655039}.footer button{width:96px}.summary{margin:8px 0 0;font-size:14px;color:#bdd8ad}.notice{margin:8px 0;font-size:12px;color:#cdbfba}button:focus-visible{outline:2px solid #fff0bc;outline-offset:2px}body.capture .tools{display:none}body.capture .screen{margin:0;width:100vw;height:100dvh}.dialog{max-height:80dvh}
</style><div class="tools"><h1>DBG-053 改訂案2・未承認</h1><p>レイアウト見本。報酬・進捗は表示用。受取・挑戦は実行しません。</p><div id="links"></div><p><a href="?width=375">375px</a><a href="?width=390">390px</a></p></div><main class="screen"><section class="dialog" role="dialog" aria-label="任務 改訂案2"><div class="heading"><img src="${image('assets/versioned/sengoku-mission-banner-v1.png')}" alt="任務"></div><nav class="tabs" aria-label="任務分類"><button>デイリー</button><button class="active" aria-pressed="true">ノーマル</button></nav><div class="body" id="rows"></div><footer class="footer"><button>閉じる</button></footer></section></main><script>
const params=new URLSearchParams(location.search),state=params.get('state')||'normal',width=params.get('width')==='390'?390:375;document.querySelector('.screen').style.width=width+'px';if(params.has('capture'))document.body.classList.add('capture');
const states={normal:'通常',claimable:'達成未受取',claimed:'全受取済',long:'長文多数'};document.getElementById('links').innerHTML=Object.entries(states).map(([key,name])=>'<a href="?state='+key+'&width='+width+'">'+name+'</a>').join('');
const icons=${JSON.stringify(icons)};function row(i){const long=state==='long',done=state==='claimed',claim=state==='claimable'&&i===0;const name=long?'長い任務名が複数行になる表示用サンプル：指定された編成で任務を達成する（'+(i+1)+'件目）':'1-'+(i+1)+'を初クリア';return '<section class="mission"><div class="top"><h3>'+name+'</h3><span class="count" aria-label="達成数 '+(done||claim?1:0)+' / '+(long?20:1)+'">'+(done||claim?1:0)+' / '+(long?20:1)+'</span></div><div class="bottom"><ul class="rewards" aria-label="報酬">'+Array.from({length:long?6:2},(_,j)=>'<li><img src="'+icons[j%2]+'" alt="'+(j%2?'武将EXP小':'銭')+'"><span>×'+(j%2?'1':'1,000')+'</span></li>').join('')+'</ul>'+(done?'<span class="check" role="img" aria-label="受取済み">✓</span>':'<button '+(claim?'class="claim"':'')+'>'+(claim?'受け取る':'挑戦する')+'</button>')+'</div></section>'}
document.getElementById('rows').innerHTML=(state==='claimed'?'<p class="summary">この分類はすべて受取済みです</p>':'')+Array.from({length:state==='long'?12:6},(_,i)=>row(i)).join('')+'<p class="notice">表示見本・操作は実行しません</p>';document.querySelectorAll('button').forEach(b=>b.onclick=()=>{});
</script></html>`;fs.writeFileSync(path.join(dir,'proposal.html'),html);
