import fs from'node:fs';import zlib from'node:zlib';import{simulateBattle}from'../src/domain/redesign/battle.ts';import{OUT,save,run,inputFor,alter}from'./rebuild_stage68_five_tier.mjs';import{hash}from'./audit_stage68.mjs';import{mechanics}from'./stage68_five_tier_mechanics.mjs';
const combine=(a,b)=>{const runs=[...a.runs,...b.runs],wins=a.wins+b.wins,n=a.n+b.n;return{n,wins,rate:wins/n,actions:[Math.min(...runs.map(r=>r.actions)),Math.max(...runs.map(r=>r.actions))],meanActions:runs.reduce((n,r)=>n+r.actions,0)/n,reasons:Object.fromEntries([...new Set(runs.map(r=>r.reason))].map(x=>[x,runs.filter(r=>r.reason===x).length])),runs};};
for(const id of (process.env.STAGE_IDS??'').split(',').filter(Boolean)){
 const d=JSON.parse(zlib.gunzipSync(fs.readFileSync(OUT+'/'+id+'-validated.json.gz')));const table=JSON.parse(fs.readFileSync(OUT+'/audit-table.json'));const name=table.find(r=>r.stage===id).primary.name;const primary=d.records.find(c=>c.name===name);d.preferredPrimary=name;const extra=run(primary.input,110001,400,true);const evidence={stage:id,primary:name,currentInput:primary.input,additional:extra,attempts:[]};console.log(id,'additional',extra.wins+'/400');save(id+'-margin-check.json.gz',evidence);
 if(extra.wins===400){primary.validation=combine(primary.validation,extra);d.additionalMarginChecked=true;d.additionalSeedRanges=[[110001,110400]];save(id+'-validated.json.gz',d);continue;}
 save(id+'-pre-margin.json.gz',d);let proposal=structuredClone(d.stageProposal),probe=extra,accepted=false;
 for(let round=0;round<4;round++){
  for(let step=0;step<7;step++){
   let changes;if(probe.wins<probe.n)changes=alter(proposal,[probe],[{...primary,party:primary.input.party}],step);else {const duration={};for(const r of probe.runs){let prev=0;for(const [w,a]of Object.entries(r.waveActions)){duration[w]=(duration[w]??0)+a-prev;prev=a;}}const wi=+Object.entries(duration).sort((a,b)=>b[1]-a[1])[0][0]-1;const e=[...proposal.waves[wi]].sort((a,b)=>b.stats.hp-a.stats.hp)[0];const before=e.stats.hp;e.stats.hp=Math.max(1,Math.round(before*.9));changes=[{enemy:e.id,field:'stats.hp',before,after:e.stats.hp,reason:'BURST乱数で上限へ接近する派に行動余裕を設ける'}];}
   d.history.push(...changes);const input=inputFor(proposal,{party:primary.input.party});probe=run(input,111001,200,true);evidence.attempts.push({round,step,changes,input,results:probe});if(probe.wins===200&&probe.actions[1]<=275)break;
  }
  const start=112001+round*1000,input=inputFor(proposal,{party:primary.input.party}),v=run(input,start,600,true);evidence.attempts.push({round,independent:true,input,results:v});console.log(id,'revised',round,v.wins+'/600',v.actions);save(id+'-margin-check.json.gz',evidence);if(v.wins!==600){probe=v;continue;}
  const records=d.records.map(c=>({...c,input:inputFor(proposal,{party:c.input.party})}));for(const c of records){c.inputHash=hash(c.input);c.validation=c.name===primary.name?v:run(c.input,start,200,true);}
  const alt=records.find(c=>c.family!==primary.family&&!c.roles.some(r=>['specific-card-substitution','order-comparison'].includes(r))&&!['raw','order-error','sp-order'].includes(c.family)&&mechanics(c,c.validation)&&c.validation.rate>=.6);if(!alt){probe=v;continue;}
  d.stageProposal=proposal;d.records=records;d.before=[primary,alt].map(c=>{const input=inputFor(d.stageOriginal,{party:c.input.party});return{name:c.name,family:c.family,input,validation:run(input,start,c.name===primary.name?600:200,true)};});const rev=structuredClone(input);rev.party.reverse();d.controls=[{name:'exact-party-order-reversed',baseName:primary.name,input:rev,validation:run(rev,start,200,true)}];d.marginRevised=true;d.validationSeeds=[start,start+599];d.priorSearchEvidence='order-search / specific-card-checks refer to pre-margin input; final records all recomputed for this proposal';save(id+'-validated.json.gz',d);save(id+'-sample-trace.json.gz',{input,seed:start,result:simulateBattle({...input,seed:start})});accepted=true;break;
 }
 if(!accepted)throw Error('margin not established '+id);
}
