import fs from'node:fs';import zlib from'node:zlib';import{buildBattleParty}from'../src/domain/redesign/masters.ts';import{loadout,hash,costs}from'./audit_stage68.mjs';import{OUT,save,run,inputFor}from'./rebuild_stage68_five_tier.mjs';import{mechanics}from'./stage68_five_tier_mechanics.mjs';
const perms=[];function perm(a,left){if(!left.length){perms.push(a);return;}for(const x of left)perm([...a,x],left.filter(v=>v!==x));}perm([],[0,1,2,3,4]);
for(const id of (process.env.STAGE_IDS??'').split(',').filter(Boolean)){
 const d=JSON.parse(zlib.gunzipSync(fs.readFileSync(OUT+'/'+id+'-validated.json.gz')));const bands=[[.5,.7,.6],[.2,.4,.3],[.000001,.1,.05],[0,0,0]],missing=bands.filter(([lo,hi])=>!d.records.some(c=>c.validation.rate>=lo&&c.validation.rate<=hi));if(!missing.length||+id.split('-')[0]<=2){save(id+'-order-search.json.gz',{stage:id,reason:'既存候補で全目標帯あり／序盤免除',candidates:[]});continue;}
 const ranked=d.records.filter(c=>!c.roles.includes('specific-card-substitution')&&!['raw','order-error','sp-order'].includes(c.family)&&mechanics(c,c.validation)).sort((a,b)=>b.validation.wins-a.validation.wins||a.validation.meanActions-b.validation.meanActions),base=ranked[0];const trials=[],seen=new Set(d.records.map(c=>hash(c.state.deck)));const selected=new Map();
 for(let n=0;n<36;n++){const order=perms[(n*37+11)%120],state=structuredClone(base.state);state.deck=order.map(i=>structuredClone(base.state.deck[i]));const key=hash(state.deck);if(seen.has(key))continue;seen.add(key);const input=inputFor(d.stageProposal,{party:buildBattleParty(state)}),selection=run(input,94001,12,true);trials.push({name:base.name+'-order-'+order.map(i=>i+1).join(''),family:base.family,state,input,inputHash:hash(input),selection});}
 for(const [lo,hi,target]of missing){const best=[...trials].sort((a,b)=>Math.abs(a.selection.rate-target)-Math.abs(b.selection.rate-target))[0];if(best&&!selected.has(best.name))selected.set(best.name,best);}
 for(const c of selected.values()){const validation=run(c.input,95001,200,true);d.records.push({...c,roles:['order-comparison'],loadout:loadout(c.state),costs:costs(c.state),validation});}
 save(id+'-order-search.json.gz',{stage:id,base:base.name,selectionSeeds:[94001,94012],validationSeeds:[95001,95200],candidates:trials});save(id+'-validated.json.gz',d);console.log(id,'orders',trials.length,'selected',selected.size);
}
