import fs from 'node:fs';
import vm from 'node:vm';
import assert from 'node:assert/strict';
import { createHash, randomUUID } from 'node:crypto';
const source = fs.readFileSync('supabase/functions/game04-redesign-api/index.ts', 'utf8');
const sourceSha256 = createHash('sha256').update(source).digest('hex');
const context = vm.createContext({ Deno: { env: { get: () => '' }, serve: () => {} }, structuredClone });
vm.runInContext(source, context);
const ownerPlaceholder = '00000000-0000-4000-8000-000000000001';
const id = randomUUID();
const room = vm.runInContext(`createRaidRoom(selectEncounterMaster(1, () => 0).id, '${ownerPlaceholder}', '${id}', Date.now())`, context);
assert.equal(room.raidSnapshot.type, 'encounter');
assert.equal(room.raidSnapshot.masterVersion, 'GAME04_RAID_FORMAL_20260923');
room.participants[0].name = '本陣QA924';
const duration = room.raidSnapshot.durationMinutes;
assert(duration > 10);
const json = JSON.stringify(room).replaceAll("'", "''");
const dir = 'docs/verification/home-20260924';
fs.mkdirSync(dir, { recursive: true });
const sql = `-- QA seed + live API/body UI verification only. Not evidence of natural encounter generation.\n-- Read-only identity lookup; DO block requires exactly one dedicated QA user.\nselect id, username from public.users where username = '本陣QA924';\n\nDO $home_fixture$\nDECLARE qa_id uuid; qa_count integer; fixture jsonb; applied_at timestamptz := clock_timestamp();\nBEGIN\n  select count(*), min(id::text)::uuid into qa_count, qa_id from public.users where username = '本陣QA924';\n  if qa_count <> 1 then raise exception 'Expected exactly one 本陣QA924 user'; end if;\n  if qa_id <> 'd7f49823-b334-4874-8667-e32e06dc836f'::uuid then raise exception 'Unexpected dedicated QA identity'; end if;\n  fixture := '${json}'::jsonb;\n  fixture := jsonb_set(fixture, '{ownerId}', to_jsonb(qa_id::text));\n  fixture := jsonb_set(fixture, '{participants,0,userId}', to_jsonb(qa_id::text));\n  -- Keep formal ${duration}-minute duration; seed the room late in its lifetime for a 10-minute observation window.\n  fixture := jsonb_set(fixture, '{createdAt}', to_jsonb(applied_at - interval '${duration - 10} minutes'));\n  fixture := jsonb_set(fixture, '{rescueWindowStartedAt}', to_jsonb(applied_at - interval '${duration - 10} minutes'));\n  fixture := jsonb_set(fixture, '{expiresAt}', to_jsonb(applied_at + interval '10 minutes'));\n  insert into public.game04_raid_rooms(id, state) values ('${id}', fixture);\nEND $home_fixture$;\n\nselect id, state->>'ownerId' as owner_id, state->>'masterId' as master_id, state->>'expiresAt' as expires_at from public.game04_raid_rooms where id = '${id}';\n`;
fs.writeFileSync(`${dir}/prepare-home-encounter.sql`, sql);
fs.writeFileSync(`${dir}/encounter-fixture.json`, JSON.stringify({ provenance: 'QA seed from live v18 createRaidRoom and selectEncounterMaster(1, random=0); real API/body UI display; not natural encounter evidence', sourceSha256, roomId: id, username: '本陣QA924', masterId: room.masterId, boss: room.raidSnapshot.name, hp: room.hp, maxHp: room.maxHp, formalDurationMinutes: duration, remainingMinutesAtInsert: 10, writes: 'one new game04_raid_rooms row only; no assets/growth/progression or existing room changes', applied: false }, null, 2) + '\n');
console.log(JSON.stringify({ roomId: id, boss: room.raidSnapshot.name, sql: `${dir}/prepare-home-encounter.sql`, applied: false }));
