import fs from'node:fs';import assert from'node:assert/strict';import{execFileSync}from'node:child_process';import{rows,stageResults,hash,metrics,brief}from'./stage68_implementation_results.mjs';import{gz,write}from'./stage68_decision_lib.mjs';
const O='docs/verification/stage68-resolution-20260927',summary=JSON.parse(fs.readFileSync(`${O}/summary.json`)),master=JSON.parse(fs.readFileSync('src/domain/redesign/data/quest65.json')),base=JSON.parse(execFileSync('git',['show',`${summary.baseline}:src/domain/redesign/data/quest65.json`],{encoding:'utf8',maxBuffer:20e6}));
const read=p=>JSON.parse(fs.readFileSync(p,'utf8').replace(/^\uFEFF/,''));const measurements=[];
for(const f of fs.readdirSync(O).filter(f=>/^playback-\d+-\d+-.*\.json$/.test(f))){const x=read(`${O}/${f}`);assert(x.success&&x.data?.text&&x.data.text!=='null',f+': incomplete measurement');const m=JSON.parse(x.data.text),fixture=`${O}/playback-fixtures/${m.case}.json.gz`;assert(m.initialSpeed==='再生速度 3倍'&&m.hiddenTransitions===0,f+': timing conditions');assert.equal(m.inputHash,gz(fixture).inputHash,f+': fixture mismatch');measurements.push({...m,seconds:m.wallMilliseconds/1000,raw:`${O}/${f}`,fixture,environment:'local Chromium / actual BattleView / development mock / 3x',interval:'intro unpaused and playback resumed through final frame',realDevice:false});}
const details=[];for(const row of rows){const p=`${O}/stages/${row.stage}.json`,s=read(p),old=stageResults(row),d=s.changedThisRound?gz(s.inputCondition):null,cs=d?.records.filter(c=>c.validation)??old.current;
if(row.stage==='5-4'){const f=gz(`${O}/band-gap/5-4-focused.json.gz`);for(const c of f.records.filter(c=>c.name===f.selected))if(!cs.some(x=>hash(x.input)===hash(c.input)))cs.push({...c,evidence:`${O}/band-gap/5-4-focused.json.gz`});}
const baseline=base.stages.find(x=>x.designId===row.stage),current=master.stages.find(x=>x.designId===row.stage);assert.deepEqual({...current,waves:null},{...baseline,waves:null},row.stage+': reward/stage metadata changed');
const roleBefore=[['主攻略',old.assessment.primary],['別攻略',old.assessment.alternative],['次点',old.assessment.tiers[1]],['低勝率',old.assessment.tiers[3]],['観測0勝',old.assessment.tiers[4]]].map(([role,c])=>{const after=c?cs.find(n=>hash(n.input.party)===hash(c.input.party)):null;return{role,before:brief(c),after:brief(after),sameParty:!!after,note:c&&!after?'旧役割の同一編成の証拠なし。新しい役割編成は本面のtiers参照。':null};});
const stalled=old.assessment.stalled, runs=stalled.flatMap(c=>c.validation.runs.filter(r=>r.reason==='action_limit')),one=runs.reduce((a,r)=>a+r.oneDamage,0),damage=runs.reduce((a,r)=>a+r.damageEvents,0),enemyEffects=[...new Set(baseline.waves.flatMap(w=>w.flatMap(e=>e.skills.flatMap(s=>s.effects.map(e=>e.type)))))];
const cause=[];if(stalled.length){if(damage&&one/damage>.3)cause.push('1ダメージ比率が高い火力不足・防御との均衡');if(enemyEffects.some(e=>['heal','hot'].includes(e)))cause.push('敵回復が存在し、低火力編成では回復との均衡が候補');if(enemyEffects.some(e=>['stun','taunt','def_up','barrier'].includes(e)))cause.push('防御・保護・行動制御の持続を含む');cause.push('波をまたぐ耐久負担と生存側の回復。原因欄はログ/技能構成からの診断で単独因果の証明ではない');}
const valid=cs.filter(c=>c.validation),allRuns=valid.flatMap(c=>c.validation.runs),max=Math.max(...allRuns.map(r=>r.actions)),measured=measurements.filter(m=>m.case.startsWith(`resolution-${row.stage}-`)),paired=`${O}/paired-replay/${row.stage}.json.gz`;
s.realPlayback=measured.map(m=>({case:m.case,seconds:m.seconds,inputHash:m.inputHash,seed:m.seed,fixture:m.fixture,reason:m.reason}));s.realPlaybackSeconds=measured.length?s.realPlayback:null;s.timeAcceptance='実機の体感受入は未判定。300行動未到達は短時間保証ではない';s.comparisonScope={validatedRecipes:valid.length,trials:allRuns.length,actionLimit:allRuns.filter(r=>r.reason==='action_limit').length,maxActions:max,sameCharacterAndEquipmentGrowth:true,arrivalAssetBasis:'adopted44A; original row.acquisition; no same-stage first clear reward'};write(p,s);
details.push({stage:row.stage,changed:s.changedThisRound,accepted:s.acceptedComparison,causes:cause,oldStallRecipes:stalled.length,oldStallTrials:runs.length,oneDamageRatio:damage?one/damage:null,enemyEffects,roleBeforeAfter:roleBefore,newRoles:{primary:s.primary,alternative:s.alternative,tiers:s.tiers},allValidated:valid.map(c=>({name:c.name,inputHash:hash(c.input),...metrics(c.validation)})),pairedReplay:fs.existsSync(paired)?paired:null,measurementCases:s.realPlayback,remainingTimeIssue:max>=250?'250行動以上の長い例あり。実機時間・体感受入は残件。':'実機時間・体感受入は残件。'});}
const retainedMeasurements=['9-6-primary','9-6-low','9-6-old-stall'].map(id=>{const root='docs/verification/stage68-implementation-20260927',fixture=`${root}/playback-fixtures/${id}.json.gz`,f=gz(fixture),raw=`${root}/playback/${id}-3x.json`,m=read(raw);return{...m,seconds:m.wallMilliseconds/1000,inputHash:hash(f.input),combatWavesHash:hash(f.input.waves),fixture,raw,initialSpeedEvidence:'previous capture and measurement protocol; previous harness recorded finished label',retained:true};});write(`${O}/role-comparisons.json`,details);write(`${O}/playback-measurements.json`,{conditions:'same 3x and interval; performance.now measured, no action-to-second conversion',retainedMeasurements,measurements,unmeasuredStages:rows.filter(r=>!measurements.some(m=>m.case.startsWith(`resolution-${r.stage}-`))).map(r=>r.stage),realDevice:false,G5:false});
const changed=details.filter(d=>d.changed);fs.writeFileSync(`${O}/STALLS.md`,['# 停滞と他攻略への影響','','旧役割の同一編成、新しい主攻略・別攻略・5帯、実発動回数は [role-comparisons.json](role-comparisons.json) と面別JSON。候補全件の試行を含む判定であり全ての未探索編成の保証ではない。','','|面|旧停滞編成数|旧300到達試行数|新検証編成数|新300到達数|新最大行動|対照再生|','|---|---:|---:|---:|---:|---:|---|',...changed.map(d=>`|${d.stage}|${d.oldStallRecipes}|${d.oldStallTrials}|${d.allValidated.length}|${d.allValidated.reduce((a,c)=>a+c.actionLimit,0)}|${Math.max(...d.allValidated.map(c=>c.max))}|${d.pairedReplay?'[同一seed]('+d.pairedReplay.split('/').slice(-2).join('/')+')':'対象外'}|`),'','250行動以上の長い例は数値上の非停滞と分離して時間残件として保持。特に低勝率編成は実機で許容される待ち時間の判断が必要。'].join('\n'));
fs.writeFileSync(`${O}/PLAYBACK.md`,['# 実再生時間','','ローカルChromiumで実際のBattleViewを再生。3倍速、導入停止解除/再開から最終フレームまでperformance.nowで測定。全記録のhiddenTransitionsは0。端末実機監査ではない。行動数から秒へ換算していない。CPU負荷・ブラウザ差を含む単回測定。','','|case|seed|行動|実秒|決着|','|---|---:|---:|---:|---|',...measurements.map(m=>`|[${m.case}](playback-fixtures/${m.case}.json.gz)|${m.seed}|${m.actions}|${m.seconds.toFixed(2)}|${m.reason}|`),'','全入力・敵hash・編成名・測定時刻は [playback-measurements.json](playback-measurements.json)。2-3 after/longは中間案、final/final-longが最終採用入力。9-6は前回から同じ敵入力を保持。従来の主51.24秒/低67.13秒/旧189.77秒も保持し、今回の別測定で上書きしない。','',`今回未測定面: ${rows.filter(r=>!measurements.some(m=>m.case.startsWith(`resolution-${r.stage}-`))).map(r=>r.stage).join('、')}`].join('\n'));
const inputs=new Set(),trials=new Set();function scan(x){if(!x||typeof x!=='object')return;if(x.input&&(x.screen||x.validation)){const h=hash(x.input);inputs.add(h);for(const v of [x.screen,x.validation])for(const r of v?.runs??[])trials.add(h+':'+r.seed);return;}for(const v of Object.values(x))scan(v);}for(const dir of fs.readdirSync(O,{withFileTypes:true}).filter(d=>d.isDirectory()&&!['playback-fixtures','paired-replay','stages'].includes(d.name)))for(const f of fs.readdirSync(`${O}/${dir.name}`).filter(f=>f.endsWith('.json.gz')))scan(gz(`${O}/${dir.name}/${f}`));
write(`${O}/verification-summary.json`,{accepted:summary.accepted,fiveBands:summary.fiveBands,remaining:summary.remaining,uniqueNewCandidateInputs:inputs.size,uniqueInputSeedTrials:trials.size,keptBaseline:summary.baseline,rewardsAndMetadataUnchangedAll68:true,changedStageCount:summary.changedStages.length,oldStallSameSeedReplayCount:details.filter(d=>d.pairedReplay).length,allObservedStallsAfter:details.reduce((a,d)=>a+d.allValidated.reduce((b,c)=>b+c.actionLimit,0),0),realMeasuredStages:[...new Set(measurements.map(m=>m.case.match(/resolution-(\d+-\d+)-/)[1]))],realDevice:false,G5:false});
console.log(JSON.stringify({accepted:summary.accepted,candidates:inputs.size,uniqueTrials:trials.size,measurements:measurements.length}));
