import fs from'node:fs';import zlib from'node:zlib';import assert from'node:assert/strict';import{FORMAL_QUEST_STAGES as STAGES}from'../src/domain/redesign/questMaster.ts';import{FORMAL_NORMAL_MISSIONS as MISSIONS}from'../src/domain/redesign/formalMissions.ts';import{CHARACTER_MASTERS as CM}from'../src/domain/redesign/masters.ts';import{EXP_VALUES}from'../src/domain/redesign/growthMaster.ts';import{costs}from'./audit_stage68.mjs';import{OUT,save}from'./rebuild_stage68_five_tier.mjs';import{mechanics}from'./stage68_five_tier_mechanics.mjs';
const skillSources=Object.fromEntries(['SKD003','SKD035','SKD039'].map(id=>[id,{source:'チュートリアル確定',stage:null}])),gearSources={};
const state={characters:[],skills:[],equipment:[],deck:[]};const fixedSkills=new Set(['SKD003','SKD035','SKD039']),fixedChars=new Set(['char_joe_01','char_daimon_01','char_aoi_01']);const earned={cash:0,charExp:0,eqExp:0,skillMaterials:0,genericR:0},added={...earned},gearOwned={},soulSpent={},rows=[],proposals=[],claimed=new Set();
const sums=rs=>{const b={cash:0,charExp:0,eqExp:0,skillMaterials:0,genericR:0};for(const r of rs){if(r.kind==='cash')b.cash+=r.amount;if(r.kind==='character_exp_item')b.charExp+=EXP_VALUES[r.id]*r.amount;if(r.kind==='equipment_exp_item')b.eqExp+=EXP_VALUES[r.id]*r.amount;if(r.kind==='skill_material')b.skillMaterials+=r.amount;if(r.kind==='generic_soul'&&r.id==='R')b.genericR+=r.amount;}return b;};
const reward=(key,n)=>{if(key==='cash')return [{kind:'cash',amount:n}];if(key==='skillMaterials')return [{kind:'skill_material',amount:n}];if(key==='genericR')return [{kind:'generic_soul',id:'R',amount:n}];let remaining=Math.ceil(n/100)*100,rs=[];for(const id of ['xlarge','large','medium','small']){const amount=Math.floor(remaining/EXP_VALUES[id]);if(amount)rs.push({kind:key==='charExp'?'character_exp_item':'equipment_exp_item',id,amount});remaining-=amount*EXP_VALUES[id];}return rs;};
const mergeState=s=>{for(const c of s.characters){let p=state.characters.find(x=>x.id===c.id);if(!p)state.characters.push(structuredClone(c));else if(c.level>p.level)Object.assign(p,c);}for(const c of s.skills){let p=state.skills.find(x=>x.id===c.id);if(!p)state.skills.push(structuredClone(c));else p.level=Math.max(p.level,c.level);}const counts={};for(const e of s.equipment){let k=e.masterId+':'+(counts[e.masterId]=(counts[e.masterId]??0)+1);let p=state.equipment.find(x=>x.instanceId===k);if(!p)state.equipment.push({...e,instanceId:k});else if(e.level>p.level)Object.assign(p,{...e,instanceId:k});}};
for(let i=0;i<STAGES.length;i++){
 const s=STAGES[i],path=OUT+'/'+s.designId+'-validated.json.gz';if(!fs.existsSync(path))throw Error('validation missing '+s.designId);const d=JSON.parse(zlib.gunzipSync(fs.readFileSync(path)));let ranked=[...d.records].sort((a,b)=>b.validation.wins-a.validation.wins||a.validation.meanActions-b.validation.meanActions);const best=ranked.find(c=>c.name===d.preferredPrimary)??ranked.find(c=>!c.roles.some(r=>['specific-card-substitution','order-comparison'].includes(r))&&!['raw','order-error','sp-order'].includes(c.family)&&mechanics(c,c.validation))??ranked[0];const alt=ranked.find(c=>!c.roles.some(r=>['specific-card-substitution','order-comparison'].includes(r))&&c.family!==best.family&&!['raw','order-error','sp-order'].includes(c.family)&&mechanics(c,c.validation)&&c.validation.rate>=.6);const funded=[best,...(alt?[alt]:[])];
 const common=i>=10&&alt?best.state.skills.filter(a=>alt.state.skills.some(b=>a.id===b.id)):[];for(const sk of common){const c=ranked.find(c=>c.validation.rate>=.3&&!c.state.skills.some(a=>a.id===sk.id));if(c&&!funded.includes(c))funded.push(c);}
 const previousCost=costs(state);funded.forEach(c=>mergeState(c.state));const need=costs(state);const soulNeed=Object.values(need.awakeningSouls).reduce((n,x)=>n+x,0);const resources={cash:need.cash,charExp:need.charExp,eqExp:need.eqExp,skillMaterials:need.skillMaterials,genericR:soulNeed};const currentGap=Object.fromEntries(Object.entries(resources).map(([k,v])=>[k,Math.max(0,v-earned[k])]));
 const additions=[];for(const c of state.characters)assert(fixedChars.has(c.id),'non-guaranteed character '+c.id);for(const sk of state.skills)if(!fixedSkills.has(sk.id)){additions.push({kind:'skill',id:sk.id,amount:1});fixedSkills.add(sk.id);skillSources[sk.id]={source:'追加提案・前面初回確定',stage:STAGES[i-1]?.designId};}
 const gearCounts={};for(const e of state.equipment)gearCounts[e.masterId]=(gearCounts[e.masterId]??0)+1;for(const [id,n]of Object.entries(gearCounts)){const extra=n-(gearOwned[id]??0);if(extra>0){additions.push({kind:'equipment',id,amount:extra});gearOwned[id]=n;gearSources[id]??={source:'追加提案・前面初回確定',stage:STAGES[i-1]?.designId};}}
 for(const [k,n]of Object.entries(resources)){const short=Math.max(0,n-earned[k]-added[k]);if(short){const rs=reward(k,short);additions.push(...rs);added[k]+=sums(rs)[k];}}
 if(additions.length){assert(i>0,'no earlier reward at stage1');proposals.push({beforeStage:s.designId,grantOn:STAGES[i-1].designId,stageId:STAGES[i-1].id,path:'firstRewards append',status:'UNAPPROVED',rewards:additions,reason:'同育成で主経路と別戦法を切替可能にする確定供給。既存報酬は全て保持'});}
 const prev=STAGES[i-1],yield_=prev?sums(prev.rewards):null;const farmWins=prev?Math.max(...['cash','charExp','eqExp'].map(k=>currentGap[k]?yield_[k]?Math.ceil(currentGap[k]/yield_[k]):Infinity:0)):0;
 rows.push({stage:s.designId,availableGuaranteedSkills:[...fixedSkills],skillSources:structuredClone(skillSources),gearSources:structuredClone(gearSources),availableGuaranteedEquipmentCounts:{...gearOwned},trainedSkills:structuredClone(state.skills),trainedEquipment:structuredClone(state.equipment),trainedCharacters:structuredClone(state.characters),fundedRecipes:funded.map(c=>({name:c.name,wins:c.validation.wins,n:c.validation.n})),cumulativeTrainingCost:need,incrementalTrainingCost:Object.fromEntries(['cash','charExp','eqExp','skillMaterials'].map(k=>[k,need[k]-previousCost[k]])),existingEnumeratedSupply:{...earned},proposedAddedSupply:{...added},gapWithoutNewResourceRewards:currentGap,newBeforeStageRewards:additions,preStageSoulsSource:soulNeed?'追加提案の汎用R魂（現行確定経路なし）':'不要',farmWithoutProposal:prev?{stage:prev.designId,successfulClears: farmWins,energy: farmWins*prev.energyCost,recipeSource:prev.designId+'-validated.json.gz',note:'前面の検証済み編成を使う。現在面向け育成を先取りしない。魂・新スキル・装備・技素材はこの周回では保証しない。累積収入を既クリア1回のみとした独立比較であり、各行の回数を加算しない。'}:null,proposedMandatoryFarmWins:0,sourceNotes:'既クリア各面1回＋ステージ/エリア任務のみ。日次・ログボ・育成任務・ガチャ・所持資産は計上しない。資源追加はこの保守的経路を保証する案で、実ユーザーの不足額ではない。'});
 const rewards=[...s.rewards,...s.firstRewards];for(const m of MISSIONS){const c=m.condition;const done=c.type==='stage_clear'?c.stageId===s.id:c.type==='area_clear'?STAGES.filter(t=>t.areaId===c.areaId).every(t=>STAGES.indexOf(t)<=i):false;if(done&&!claimed.has(m.id)){rewards.push(...m.rewards);claimed.add(m.id);}}
 const got=sums(rewards);for(const k of Object.keys(earned))earned[k]+=got[k];for(const r of rewards){if(r.kind==='skill'){fixedSkills.add(r.id);skillSources[r.id]??={source:'現行初回/任務確定',stage:s.designId};}if(r.kind==='character')fixedChars.add(r.id);if(r.kind==='equipment')gearOwned[r.id]=(gearOwned[r.id]??0)+r.amount;}
}
assert.equal(rows.length,68);assert(MISSIONS.filter(m=>m.condition.type==='area_clear').every(m=>m.rewards.some(r=>r.kind==='free_diamonds'&&r.amount===300)));save('economy-proposal.json',{status:'UNAPPROVED_ISOLATED_PROPOSAL',policy:'素材待ちを攻略の中心にしないため、検証した複数経路の切替費を前面初回報酬で保証する案。既存報酬減額なし。',additionalTotals:added,guaranteedSkillIds:[...fixedSkills],gearInstances:gearOwned,rows,rewardAdditions:proposals});console.log('economy',rows.length,added,'reward sites',proposals.length);
