import fs from 'node:fs';
import {SOURCE,OUT as DECISION,rows,candidatesFor,brief,assetCheck,gz,write,inBand} from './stage68_decision_lib.mjs';
import {hash} from './audit_stage68.mjs';
export {SOURCE,DECISION,rows,candidatesFor,brief,assetCheck,gz,write,inBand,hash};
export const OUT='docs/verification/stage68-adoption-20260927';
export const read=p=>JSON.parse(fs.readFileSync(p));
export const previous=stage=>read(`${DECISION}/stages/${stage}.json`);
export const stalls=read(`${DECISION}/stall-diagnosis.json`).map(x=>x.stage);
export function metrics(v){const a=v.runs.map(r=>r.actions).sort((a,b)=>a-b);return {wins:v.wins,n:v.n,rate:v.wins/v.n,actionLimit:v.runs.filter(r=>r.reason==='action_limit').length,min:a[0],median:a[Math.ceil(a.length*.5)-1],p90:a[Math.ceil(a.length*.9)-1],max:a.at(-1),mean:a.reduce((a,b)=>a+b,0)/a.length,reasons:v.reasons??Object.fromEntries([...new Set(v.runs.map(r=>r.reason))].map(k=>[k,v.runs.filter(r=>r.reason===k).length])),measuredPlaybackSeconds:null};}
export function select(r){const {d,cs}=candidatesFor(r),p=previous(r.stage);const primary=cs.find(c=>c.name===p.primary.name),alt=cs.find(c=>c.name===p.alternative?.name);const next=cs.filter(c=>c.asset.covered&&inBand(c.validation.rate,1)).sort((a,b)=>Math.abs(a.validation.rate-.6)-Math.abs(b.validation.rate-.6))[0];const low=cs.filter(c=>c.asset.covered&&c.validation.rate<=.1&&c.validation.runs.some(x=>x.reason==='action_limit')).sort((a,b)=>metrics(b.validation).actionLimit/b.validation.n-metrics(a.validation).actionLimit/a.validation.n)[0]??d.records.filter(c=>c.validation.rate<=.1).sort((a,b)=>metrics(b.validation).actionLimit/b.validation.n-metrics(a.validation).actionLimit/a.validation.n)[0];return {d,cs,primary,alt,next,low};}
export function timeWave(c){const sums={},counts={};for(const r of c.validation.runs.filter(r=>r.reason==='action_limit')){let prev=0;for(const [wave,n]of Object.entries(r.waveActions??{})){sums[wave]=(sums[wave]??0)+n-prev;counts[wave]=(counts[wave]??0)+1;prev=n;}}return Object.entries(sums).map(([wave,actions])=>({wave:+wave,totalActions:actions,samples:counts[wave],meanActions:actions/counts[wave]})).sort((a,b)=>b.totalActions-a.totalActions);}
export function plans(r){const selected=select(r),{d,low}=selected,waves=timeWave(low),wi=(waves[0]?.wave??1)-1,wave=d.stageProposal.waves[wi];const enemy=[...wave].sort((a,b)=>b.stats.hp-a.stats.hp)[0],ei=wave.indexOf(enemy);const variant=(name,changes)=>{const stage=structuredClone(d.stageProposal);for(const c of changes)stage.waves[wi][ei].stats[c.field]=c.after;return {name,stage,target:{wave:wi+1,position:ei+1,id:enemy.id,name:enemy.name},changes:changes.map(c=>({...c,path:`waves[${wi}][${ei}].stats.${c.field}`,before:enemy.stats[c.field]})),status:'UNAPPROVED',waveEvidence:waves};};return {...selected,variants:[variant('local-hp-60',[{field:'hp',after:Math.max(1,Math.round(enemy.stats.hp*.6))}]),variant('local-defense-85-attack-125',[{field:'def',after:Math.round(enemy.stats.def*.85)},{field:'atk',after:Math.max(1,Math.round(enemy.stats.atk*1.25))}])]};}
export function active(c,v){if(c.family==='sp-feed')return v.runs.filter(r=>(r.casts?.basic??0)>0&&r.bursts>0).length>=v.n/2;const core={boost:['SKD035'],weaken:['SKD038'],dot:['SKD029'],area:['SKD019','SKD020','SKD021','SKD022','SKD023','SKD024'],backline:['SKD026','SKD027'],counter:['SKD049','SKD048'],sustain:['SKD036','SKD037','SKD043','SKD045'],control:['SKD032'],'purge-buff':['SKD051'],'purge-protection':['SKD052'],cleanse:['SKD053','SKD054','SKD055'],basic:['SKD003']};return (core[c.family]??[]).some(id=>v.runs.filter(r=>(r.casts?.[id]??0)>0).length>=v.n/2);}
