import fs from 'node:fs';import assert from 'node:assert/strict';import {execFileSync} from 'node:child_process';
import {rows,stageResults,assess,brief,hash,metrics} from './stage68_implementation_results.mjs';
import {gz,write,assetCheck} from './stage68_decision_lib.mjs';
import {inputFor} from './rebuild_stage68_five_tier.mjs';
const OUT='docs/verification/stage68-resolution-20260927',base='16d45e1abbecfa258f9996e6f297780a1fce5800',path='src/domain/redesign/data/quest65.json';
const master=JSON.parse(execFileSync('git',['show',`${base}:${path}`],{encoding:'utf8',maxBuffer:20e6})),original=structuredClone(master),index=[],patch=[],combat=x=>hash(JSON.parse(JSON.stringify({party:x.party,waves:x.waves,rules:x.rules,earlyQuestAssist:x.earlyQuestAssist},(k,v)=>['image','name','description'].includes(k)?undefined:v)));
for(const row of rows){let selected;for(const folder of ['fill-pressure-aoe','fill-pressure-combined','fill-pressure-refined','first-validation']){const p=`${OUT}/${folder}/${row.stage}.json.gz`;if(fs.existsSync(p)){const d=gz(p);if(d.complete&&d.passed)selected={...d,evidence:p};}}
 const old=stageResults(row);let cs=old.current;if(selected){cs=selected.records.filter(c=>c.validation).map(c=>({...c,evidence:selected.evidence}));const stage=master.stages.find(s=>s.designId===row.stage);
  for(const [wi,w]of stage.waves.entries())for(const [ei,e]of w.entries()){const n=selected.stageProposal.waves[wi][ei];assert.equal(e.id,n.id);for(const field of ['stats','skills','phases'])if(JSON.stringify(e[field])!==JSON.stringify(n[field])){patch.push({stage:row.stage,wave:wi+1,position:ei+1,enemy:e.id,field,before:e[field]??null,after:n[field]??null});if(n[field]===undefined)delete e[field];else e[field]=structuredClone(n[field]);}}
 }
 if(row.stage==='5-4'){const p=`${OUT}/band-gap/5-4-focused.json.gz`;if(fs.existsSync(p)){const d=gz(p);if(d.selected)cs=[...cs,...d.records.filter(c=>c.name===d.selected).map(c=>({...c,evidence:p}))];}}
 const a=assess(cs),stage=master.stages.find(s=>s.designId===row.stage);
 for(const c of cs){assert(assetCheck(c,row).covered,`${row.stage}: unfunded ${c.name}`);assert.equal(combat(c.input),combat(inputFor(stage,{party:c.input.party})),`${row.stage}: stale input ${c.name}`);}
 const growth=c=>hash({characters:c.state.characters,equipment:c.state.equipment});assert(new Set(a.tiers.filter(Boolean).map(growth)).size<=1,`${row.stage}: growth gradient`);
 const unmet=[];if(a.missing.length)unmet.push({kind:row.stage==='1-1'?'DESIGN_CONFLICT':'CANDIDATE_OR_EVIDENCE',missingBands:a.missing});if(a.stalled.length)unmet.push({kind:'DESIGN_STALL',recipes:a.stalled.map(c=>({name:c.name,...metrics(c.validation)}))});if(!a.alternative&&row.stage!=='1-1')unmet.push({kind:'TACTIC_EVIDENCE'});const dep=a.dependency.filter(d=>!d.without);if(dep.length)unmet.push({kind:'SKILL_DEPENDENCY_EVIDENCE',ids:dep.map(d=>d.id)});
 const r={stage:row.stage,name:stage.name,inputCondition:selected?selected.evidence:'16d45e1 baseline',changedThisRound:!!selected,acceptedComparison:!unmet.length,primary:brief(a.primary),alternative:brief(a.alternative),tiers:a.tiers.map(brief),skillWithout:a.dependency.map(d=>({id:d.id,without:brief(d.without)})),unmet,enemyHash:hash(stage.waves),realPlaybackSeconds:null,realDevice:false,G5:false};write(`${OUT}/stages/${row.stage}.json`,r);index.push(r);
}
const current=JSON.parse(fs.readFileSync(path)),previous=fs.existsSync(`${OUT}/summary.json`)?JSON.parse(fs.readFileSync(`${OUT}/summary.json`)):null;assert(hash(current)===hash(original)||hash(current)===previous?.masterHash,'Concurrent master edit; do not overwrite');
if(process.argv.includes('--apply'))fs.writeFileSync(path,JSON.stringify(master,null,2)+'\n');
const summary={baseline:base,previousAccepted:38,accepted:index.filter(r=>r.acceptedComparison).length,fiveBands:index.filter(r=>!r.unmet.some(u=>u.missingBands)).length,resolved:index.filter(r=>r.acceptedComparison&&(r.changedThisRound||r.stage==='5-4')).map(r=>r.stage),remaining:index.filter(r=>!r.acceptedComparison).map(r=>r.stage),changedStages:index.filter(r=>r.changedThisRound).map(r=>r.stage),masterHash:hash(master),applied:process.argv.includes('--apply'),realDevice:false,G5:false};write(`${OUT}/summary.json`,summary);write(`${OUT}/enemy-patch.json`,patch);
fs.writeFileSync(`${OUT}/STAGES68.md`,['# 全68面の今回判定','','前回の保存証拠を保持。変更した面は新入力の独立試行だけを採用。全勝/0勝は実測であり理論値ではない。','','|面|敵変更|5帯の勝数/試行数|判定|','|---|---|---|---|',...index.map(r=>`|[${r.stage}](stages/${r.stage}.json)|${r.changedThisRound?'今回変更':'基準保持'}|${r.tiers.map(t=>t?`${t.metrics.wins}/${t.metrics.n}`:'不足').join(' / ')}|${r.acceptedComparison?'保存比較条件充足':'未達: '+r.unmet.map(u=>u.kind).join(',')}|`)].join('\n'));
console.log(JSON.stringify(summary));
