import fs from 'node:fs';
import assert from 'node:assert/strict';
import {SOURCE,OUT,rows,labels,targets,inBand,gz,write,candidatesFor,brief,propose,assetCheck} from './stage68_decision_lib.mjs';
import {FORMAL_QUEST_STAGES as stages} from '../src/domain/redesign/questMaster.ts';
import {FORMAL_NORMAL_MISSIONS as missions} from '../src/domain/redesign/formalMissions.ts';
import {CHARACTER_MASTERS as chars,EQUIPMENT_MASTERS as equipment} from '../src/domain/redesign/masters.ts';
import {getFormalOwnedSkill} from '../src/domain/redesign/formalOwnedSkills.ts';
import {EXP_VALUES} from '../src/domain/redesign/growthMaster.ts';
import {hash} from './audit_stage68.mjs';
const economy=JSON.parse(fs.readFileSync(`${SOURCE}/economy-proposal.json`));
const diagnostics=JSON.parse(fs.readFileSync(`${SOURCE}/difficulty-diagnostics.json`));
const skillName=id=>{try{return getFormalOwnedSkill(id,0).name;}catch{return id;}};
const nm=id=>chars.find(x=>x.id===id)?.name??equipment.find(x=>x.id===id)?.name??id;
const rewardText=r=>`${r.kind}:${r.id??''}${r.kind==='skill'?'('+skillName(r.id)+')':r.kind==='equipment'?'('+nm(r.id)+')':''}×${r.amount}`;
const rate=c=>c?`${c.name} ${c.wins}/${c.n} (${c.percent.toFixed(1)}%)`:'該当なし';
const order=c=>c.order.map((p,i)=>`${i+1}.${nm(p.id)}[${p.skills.join('/')||'通常攻撃'}]`).join(' → ');
const activations=c=>Object.entries(c.coreCasts).map(([id,n])=>`${id} ${n}/${c.n}`).join('、');
const bandPick=(cs,i)=>[...cs].filter(c=>inBand(c.validation.rate,i)).sort((a,b)=>Math.abs(a.validation.rate-targets[i])-Math.abs(b.validation.rate-targets[i]))[0];
const currentSkills=new Map(['SKD003','SKD035','SKD039'].map(id=>[id,'チュートリアル完了時']));
const currentChars=new Map(['char_joe_01','char_daimon_01','char_aoi_01'].map(id=>[id,'チュートリアル完了時']));
const currentGear=new Map(),claimed=new Set();
const farmIncome={cash:0,charExp:0,eqExp:0};let farmTotal=0,energyTotal=0;
const reducedSchedule=economy.rewardAdditions.map(p=>({...p,rewards:p.rewards.filter(r=>!['cash','character_exp_item','equipment_exp_item'].includes(r.kind))})).filter(p=>p.rewards.length);
const all=[],early=[],stallRows=[],proposalInputs=[],newTests=[];
const earlyPairs={'1-1':['cheap-attacks','starter-buff-first'],'1-2':['basic-focus','starter-rush'],'1-3':['basic-focus','attack-up'],'1-4':['basic-focus','all-cheap'],'1-5':['attack-up','starter-area-sp-feed'],'2-1':['cheap-attacks','starter-area-sp-feed'],'2-2':['cheap-attacks','starter-area-sp-feed'],'2-3':['attack-up','starter-area-sp-feed'],'2-4':['attack-up','starter-area-sp-feed'],'2-5':['attack-up','starter-area-sp-feed']};
const earlyCore={'1-1':['SKD003','SKD035'],'1-2':['SKD035','SKD003'],'1-3':['SKD035','SKD009'],'1-4':['SKD035','SKD003'],'1-5':['SKD035','SKD019'],'2-1':['SKD035','SKD019'],'2-2':['SKD039','SKD019'],'2-3':['SKD039','SKD019'],'2-4':['SKD039','SKD019'],'2-5':['SKD039','SKD019']};
const earlyMeaning={'1-1':['低SP攻撃で速攻','攻撃強化を先行する案（中核未達）'],'1-2':['攻撃強化後に低SP技','強化にSPを使わず低SP技で速攻'],'1-3':['攻撃強化＋低SP攻撃','岩断2役へSPを割り当てる属性単体攻撃'],'1-4':['先行強化＋低SP攻撃','全員低SP技で攻撃し、支援SPを不要にする'],'1-5':['強化＋岩断の単体集中','通常攻撃でSPを供給して全体攻撃'],'2-1':['強化＋低SP技を多数回','通常攻撃でSPを供給して全体攻撃'],'2-2':['単体回復しながら低SP技','通常攻撃でSPを供給して全体攻撃'],'2-3':['回復継戦＋単体岩断','通常攻撃でSPを供給して全体攻撃'],'2-4':['回復継戦＋単体岩断','通常攻撃でSPを供給して全体攻撃'],'2-5':['回復継戦＋単体岩断','通常攻撃でSPを供給して全体攻撃']};
const amounts=rs=>{const out={cash:0,charExp:0,eqExp:0};for(const r of rs){if(r.kind==='cash')out.cash+=r.amount;if(r.kind==='character_exp_item')out.charExp+=EXP_VALUES[r.id]*r.amount;if(r.kind==='equipment_exp_item')out.eqExp+=EXP_VALUES[r.id]*r.amount;}return out;};
for(let idx=0;idx<rows.length;idx++){
 const r=rows[idx],s=stages[idx],{d,cs}=candidatesFor(r);assert.equal(s.designId,r.stage);
 const primaryName=r.stage==='8-5'?'barrier':r.primary.name,altName=r.stage==='8-5'?'burst-focus':r.alternative?.name;
 const primary=cs.find(c=>c.name===primaryName),alt=cs.find(c=>c.name===altName);assert(primary);assert(primary.asset.covered);
 const funded=cs.filter(c=>c.asset.covered),proposals=propose(r,cs);
 proposalInputs.push({stage:r.stage,proposals});
 const tierRows=labels.map((label,i)=>{const target=targets[i],near=[...cs].sort((a,b)=>Math.abs(a.validation.rate-target)-Math.abs(b.validation.rate-target)).slice(0,3);return {label,original:r.tiers[i],allSaved:brief(bandPick(cs,i)),withinBudget:brief(bandPick(funded,i)),nearest:near.map(brief),proposal:proposals.find(p=>p.band===i)?{...proposals.find(p=>p.band===i),state:undefined,input:undefined}:null};});
 const originalMissing=tierRows.filter(t=>!t.original).map(t=>t.label),missing=tierRows.filter(t=>!t.withinBudget).map(t=>t.label);
 const rates=[...new Set(funded.map(c=>c.validation.rate))].sort((a,b)=>a-b);
 const dataCause=rates.length===1&&rates[0]===1?'保存済みの到達前資産内編成が全勝に集中。弱編成を作るための育成低下や敵強化は未採用。':rates.every(x=>x===0||x===1)?'保存済み候補が全勝/0勝に分かれる。SP消費順・回復/強化の発動可否による閾値挙動が候補だが、連続的な難度曲線は未証明。':'限られた編成/攻撃順の標本で、該当帯を挟む中間入力が未検証。区分境界への丸めや未所持技の流用では補わない。';
 const actualRequired=[...new Set([primary,...(alt?[alt]:[])].flatMap(c=>c.state.skills.map(s=>s.id)))];
 const necessary=row=>({characters:row.trainedCharacters.map(c=>({...c,name:nm(c.id),source:currentChars.get(c.id)??'現行確定取得未確認'})),skills:row.trainedSkills.map(k=>({...k,name:skillName(k.id),source:currentSkills.has(k.id)?{status:'CURRENT',where:currentSkills.get(k.id)}:{status:'PROPOSED',...row.skillSources[k.id]}})),equipment:row.trainedEquipment,awakeningSouls:row.cumulativeTrainingCost.awakeningSouls,cumulativeTrainingCost:row.cumulativeTrainingCost});
 const existing={skills:[...currentSkills].map(([id,where])=>({id,name:skillName(id),where})),characters:[...currentChars].map(([id,where])=>({id,name:nm(id),where})),gear:[...currentGear].map(([id,count])=>({id,count})),resources:r.acquisition.existingEnumeratedSupply};
 const missingCurrentSkills=actualRequired.filter(id=>!currentSkills.has(id));
 const gap={...r.acquisition.gapWithoutNewResourceRewards};
 const prev=stages[idx-1],yield_=prev?amounts(prev.rewards):{cash:0,charExp:0,eqExp:0};
 const shortage=Object.fromEntries(Object.keys(farmIncome).map(k=>[k,Math.max(0,r.acquisition.cumulativeTrainingCost[k]-r.acquisition.existingEnumeratedSupply[k]-farmIncome[k])]));
 const neededRuns=Math.max(0,...Object.keys(shortage).map(k=>shortage[k]?(yield_[k]?Math.ceil(shortage[k]/yield_[k]):Infinity):0));
 const finite=Number.isFinite(neededRuns);if(finite){for(const k of Object.keys(farmIncome))farmIncome[k]+=neededRuns*yield_[k];farmTotal+=neededRuns;energyTotal+=neededRuns*(prev?.energyCost??0);}
 const optionB={status:'UNAPPROVED_CONDITIONAL_ON_ITEM_SUPPLY',keepKinds:['skill','equipment','skill_material','generic_soul'],priorStage:prev?.designId??null,repeatRewards:prev?.rewards??[],successfulClears:finite?neededRuns:null,energy:finite?neededRuns*(prev?.energyCost??0):null,cumulativeSuccessfulClears:farmTotal,cumulativeEnergy:energyTotal,farmIncome:{...farmIncome},shortageBeforeFarming:shortage,note:'累積周回収入を繰越す逐次案。前面の既検証育成だけで周回する。回数は成功回数で、失敗・行動力回復待ち・実時間は含まない。現在面初回報酬は未計上。'};
 const noAddPath=`${OUT}/no-add/${r.stage}.json.gz`,noAdd=fs.existsSync(noAddPath)?gz(noAddPath):null;
 const route={requiredAssets:necessary(r.acquisition),currentBeforeStage:existing,additionsHere:economy.rewardAdditions.filter(x=>x.beforeStage===r.stage),allPreStageAdditions:economy.rewardAdditions.filter(x=>rows.findIndex(y=>y.stage===x.beforeStage)<=idx),optionA:{status:idx<10?'CURRENT':'UNAPPROVED_SUPPLY_REQUIRED',cumulativeAdded:r.acquisition.proposedAddedSupply,mandatoryFarmSuccesses:0},optionB,optionC:{status:idx<10?'CURRENT_EARLY_ONLY':'NOT_GUARANTEED',missingCurrentSkills,missingCurrentEquipment:primary.state.equipment.filter(x=>(currentGear.get(x.masterId)??0)===0).map(x=>x.masterId).filter((x,i,a)=>a.indexOf(x)===i),resourceGap:gap,recommendation:'追加しないなら、現行確定スキルだけ・未配布装備なし・初期R覚醒0へ編成を再設計し、その条件で敵を再評価する。現候補の勝率を流用しない。ガチャ/ランダム魂を確定入手としない。',sameLevelPossible:primary.state.characters.every(c=>c.level<=50)||gap.genericR===0,exactCandidateEvidence:noAdd?noAddPath:null,exactCandidates:noAdd?.records.map(c=>({name:c.name,status:c.status,loadout:c.loadout,costs:c.costs,inputHash:c.inputHash,wins:c.validation?.wins,n:c.validation?.n})),note:noAdd?.note}};
 let earlyData=null;
 if(idx<10){const pair=earlyPairs[r.stage].map(name=>cs.find(c=>c.name===name));assert(pair.every(Boolean));const cores=earlyCore[r.stage];const coreRuns=pair.map((c,i)=>c.validation.runs.filter(x=>(x.casts[cores[i]]??0)>0).length);const pass=pair.every((c,i)=>c.asset.covered&&c.validation.rate>=.6&&coreRuns[i]>=c.validation.n/2);earlyData={stage:r.stage,status:pass?'二戦法の勝利/中核発動確認':'別戦法未達',pair:pair.map((c,i)=>({...brief(c),meaning:earlyMeaning[r.stage][i],core:cores[i],coreName:skillName(cores[i]),coreRuns:coreRuns[i]})),requiredChange:pass?'敵/配布/育成は変更不要。編成ガイドと勝因説明を修正。':'1-1は短い戦闘で強化SPを確保する前に終了。強化型200/200勝でも発動41/200。初戦は操作習得として複数戦法/5段階の適用開始を1-2以降にする例外案を推奨（未承認）。例外不可なら1-1の敵HP/開始SPを別案として再設計・再検証する必要がある。共通SP式は変更しない。',sourceAtArrival:existing};early.push(earlyData);}
 const diag=diagnostics[idx],stalled=diag.flags.includes('不適合編成で上限待ちが残る');let stall=null;
 if(stalled){
  const low=d.records.filter(c=>c.validation.rate<=.1&&c.validation.runs.filter(x=>x.reason==='action_limit').length>c.validation.n/2);
  const details=low.map(c=>{const runs=c.validation.runs.filter(x=>x.reason==='action_limit'),waves={};let one=0,events=0;for(const x of runs){one+=x.oneDamage;events+=x.damageEvents;for(const [w,v]of Object.entries(x.waveDamage??{})){waves[w]??={one:0,count:0,totalDamage:0};waves[w].one+=v.one;waves[w].count+=v.count;waves[w].totalDamage+=v.total;}}
   const reached={};for(const x of runs)reached[x.waves+1]=(reached[x.waves+1]??0)+1;
   return {name:c.name,wins:c.validation.wins,n:c.validation.n,actionLimit:runs.length,oneDamageRatio:one/Math.max(1,events),reachedWave:reached,waveDamage:waves,reason:'action_limit',exampleSeed:runs[0].seed,skills:c.input.party.map(p=>({id:p.id,skills:p.skills.map(s=>s.id)})),explanation:one/Math.max(1,events)>.5?'失敗試行の直接攻撃の過半数が1ダメージ。防御/属性/支援の組合せ不足が疑われる。':'攻撃は通るが300行動内に全Waveを処理できない。回復・保護・SP消費順・HP負担の個別因果は保存集計だけでは断定しない。'};
  });
  const worst=[...details].sort((a,b)=>b.actionLimit-a.actionLimit)[0];
  stall={limit:'味方300行動でaction_limit敗北。計算ジョブのタイムアウトではない',details,primary:brief(primary),alternative:brief(alt),continueValidationCloses:false,recommendation:`敵の追加弱体は現時点で推奨しない。${worst.name}から${primary.name}または${alt?.name??'別候補'}へ、保存済み配置・技へ変更する。HP/DEFを下げて不適合編成まで勝たせると攻略差を消す。`,uxProposal:'未承認：敗北結果にaction_limit専用の説明と同育成の2編成例を表示。既存戦闘ログの最終到達Wave・1ダメージ比率・中核技発動を根拠にする。戦闘中は60行動以降、直近30味方行動の敵合計HP最小値が低下しない場合に1回だけ停滞案内。自動敗北/自動撤退/返金はしない。早期離脱は既存の離脱契約を確認して別途統合担当へ。',closure:'原因区分と代替攻略の証拠整理は完了。実際の待ち時間短縮はUXの承認・実装・実機確認が必要。追加試行だけでは閉じない。'};stallRows.push({stage:r.stage,...stall});
 }
 const matchedBefore=d.before.find(c=>hash(c.input.party)===hash(primary.input.party));
 const tags={originalFiveTierGap:!!originalMissing.length,supplyProposal:idx>=10,early:idx<10,actionLimitWait:stalled};
 const orderContrasts=d.controls.map(control=>{const match=d.records.find(c=>hash([...c.input.party].sort((a,b)=>a.id.localeCompare(b.id)))===hash([...control.input.party].sort((a,b)=>a.id.localeCompare(b.id))));return match?{base:brief(match),changed:brief({...control,inputHash:hash(control.input)}),sameSeedSet:JSON.stringify(match.validation.runs.map(x=>x.seed))===JSON.stringify(control.validation.runs.map(x=>x.seed)),interpretation:'party順だけの対照。勝率差がない場合は勝敗への寄与確認とはしない。'}:null;}).filter(Boolean);
 const stageDoc={stage:r.stage,id:r.id,name:r.name,status:idx<10?'現行敵/到達前供給で検証':'未承認の敵/供給案での検証',tags,profile:r.profile,primary:{...brief(primary),loadout:primary.loadout??null},alternative:brief(alt),early:earlyData,enemyChanges:r.changes,enemyPolicy:'回収済み43面273項目の案を継承。今回新たな敵数値変更なし。beforeが最新値と違う箇所は統合時に停止。',beforeSameParty:matchedBefore?brief({...matchedBefore,inputHash:hash(matchedBefore.input),evidence:`${SOURCE}/${r.stage}-validated.json.gz`}):null,orderContrasts,originalMissing,missingWithinBudget:missing,tierRows,observedRates:rates.map(x=>100*x),cause:dataCause,exactProposals:proposals.map(({state,input,...p})=>p),supply:route,stall,remaining:[...(missing.length?[`5段階未達：${missing.join('、')}`]:[]),...(idx>=10?['追加供給案の承認前。現行仕様の成立とはしない']:[]),...(earlyData&&!earlyData.status.startsWith('二戦法')?['初戦の例外承認または再設計']:[]),...(stall?['300行動待ちのUX対応未承認/未実装']:[]),'実機受入・G5未通過']};
 write(`${OUT}/stages/${r.stage}.json`,stageDoc);all.push(stageDoc);
 for(const c of cs.filter(c=>c.origin.startsWith('new-')))newTests.push({stage:r.stage,name:c.name,inputHash:c.inputHash,newTrials:c.newTrials??0,wins:c.validation.wins,n:c.validation.n,path:c.evidence});
 if(noAdd)for(const c of noAdd.records)if(c.validation)newTests.push({stage:r.stage,name:c.name,inputHash:c.inputHash,newTrials:c.newTrials,wins:c.validation.wins,n:c.validation.n,path:noAddPath,scope:'no-add-feasibility-not-five-tier'});
 const take=[...s.rewards,...s.firstRewards];for(const m of missions){const co=m.condition,done=co.type==='stage_clear'?co.stageId===s.id:co.type==='area_clear'?stages.filter(x=>x.areaId===co.areaId).every(x=>stages.indexOf(x)<=idx):false;if(done&&!claimed.has(m.id)){take.push(...m.rewards);claimed.add(m.id);}}
 for(const x of take){if(x.kind==='skill'&&!currentSkills.has(x.id))currentSkills.set(x.id,`${r.stage}クリア報酬/任務受領後`);if(x.kind==='character'&&!currentChars.has(x.id))currentChars.set(x.id,`${r.stage}初回クリア後`);if(x.kind==='equipment')currentGear.set(x.id,(currentGear.get(x.id)??0)+x.amount);}
}
write(`${OUT}/candidate-inputs.json.gz`,proposalInputs);write(`${OUT}/supply-options.json`,{optionA:economy.rewardAdditions,optionB:reducedSchedule,optionBTotalSuccessfulClears:farmTotal,optionBTotalEnergy:energyTotal,note:'Bは新規資源追加を減らすが、無追加案ではない。全案未承認。',rows:all.map(r=>({stage:r.stage,supply:r.supply}))});
write(`${OUT}/early-strategies.json`,early);write(`${OUT}/stall-diagnosis.json`,stallRows);
const summary={basis:'c13003991a59f0bb9c2cb4a273b4b62de6fde1e2',stages:68,overlappingTags:Object.fromEntries(Object.keys(all[0].tags).map(k=>[k,all.filter(r=>r.tags[k]).length])),originalTierCoverage:labels.map((label,i)=>({label,count:rows.filter(r=>r.tiers[i]).length})),currentTierCoverage:labels.map((label,i)=>({label,allEvidence:all.filter(r=>r.tierRows[i].allSaved).length,assetCovered:all.filter(r=>r.tierRows[i].withinBudget).length})),allTiersAssetCovered:all.filter(r=>!r.missingWithinBudget.length).length,earlyTwoStrategies:early.filter(r=>r.status.startsWith('二戦法')).length,newTests,newTrials:newTests.reduce((n,c)=>n+c.newTrials,0),newEnemyChanges:0,supplyDeltaBeyondRecovered:0,optionBFarmTotal:farmTotal,optionBEnergyTotal:energyTotal};
write(`${OUT}/summary.json`,summary);
const table=['# 全68面：対応一覧','', 'タグは重複する。未達56・追加供給58・序盤10・上限待ち14を合算しない。8-5はPR #40の修正を優先。約60%は50～70%、約30%は20～40%を探索帯として継承したが、最終許容幅の承認とはしない。','', '|面|敵変更項目|供給|序盤別戦法|300行動待ち|到達前資産内で未達の帯|','|---|---:|---|---|---|---|',...all.map(r=>`|[${r.stage}](stages/${r.stage}.json)|${r.enemyChanges.length}|${r.tags.supplyProposal?'追加案依存':'現行'}|${r.early?.status??'対象外'}|${r.stall?'残る':'旧14面の対象外'}|${r.missingWithinBudget.join('・')||'なし'}|`)];
for(const r of all){table.push('',`## ${r.stage} ${r.name}`,`敵：${r.enemyChanges.length?`${r.enemyChanges.length}項目の既存案を継承。`:'数値維持。'} ${r.enemyChanges.map(c=>`${c.enemy} ${c.field} ${c.before}→${c.after}（${c.reasons.join('、')}）`).join('；')}`,`育成：Lv${r.profile.level}、${r.profile.eq??'装備なし'}${r.profile.eq?r.profile.eqLevel:''}、技LB${r.profile.lb}。主：${rate(r.primary)}。${order(r.primary)}。`,`別戦法：${r.early?r.early.pair.map(c=>`${c.meaning}：${rate(c)}、中核${c.core}発動${c.coreRuns}/${c.n}`).join(' ／ '):r.alternative?`${rate(r.alternative)}。${order(r.alternative)}。実発動：${activations(r.alternative)}`:'未達'}`,`主の実発動：${activations(r.primary)}。発動0の技を勝因にしない。`, '|帯|保存比較（参考含む）|到達前資産内の比較|','|---|---|---|',...r.tierRows.map(t=>`|${t.label}|${rate(t.allSaved)}|${rate(t.withinBudget)}|`),`原因整理：${r.cause}`, ...r.tierRows.filter(t=>!t.withinBudget).map(t=>`- ${t.label}未達。近傍実測：${t.nearest.map(rate).join(' ／ ')}。${t.proposal?`変更候補：${t.proposal.explanation} 新順=${order({order:t.proposal.base.order.map((_,i)=>{const [a,b]=t.proposal.swapPositions.map(x=>x-1);return t.proposal.base.order[i===a?b:i===b?a:i];})})}。未検証入力=${t.proposal.inputHash}。`:'同資産の未実行交換候補なし。既存範囲で未達。'}`),`入手：必要資産・数量と全前面配布は[面別JSON](stages/${r.stage}.json)。直前追加：${r.supply.additionsHere.map(p=>`${p.grantOn}初回クリア後→${p.beforeStage}前：${p.rewards.map(rewardText).join('、')}`).join('；')||'この面前の新規追加なし（以前の追加依存は別）'}`,`追加削減案B：前面${r.supply.optionB.priorStage??'なし'}を追加${r.supply.optionB.successfulClears??'確定計算不能'}回成功、行動力${r.supply.optionB.energy??'未定'}。技・装備・技素材・魂の確定追加は保持。完全無追加案C：不足技${r.supply.optionC.missingCurrentSkills.join(',')||'なし'}、資源不足${JSON.stringify(r.supply.optionC.resourceGap)}。${r.tags.supplyProposal?'現行だけで同条件成立は未証明。':'現行序盤条件の範囲。'}`,r.stall?`上限待ち：${r.stall.details.map(x=>`${x.name} ${x.actionLimit}/${x.n}で300行動敗北、1ダメージ比${(x.oneDamageRatio*100).toFixed(1)}%、到達Wave${JSON.stringify(x.reachedWave)}`).join('；')}。${r.stall.recommendation}`:'旧14面の上限待ち対象外。全編成で停滞しないことの証明ではない。',`残件：${r.remaining.join('／')}`);}
fs.writeFileSync(`${OUT}/STAGES.md`,table.join('\n')+'\n');
const supply=['# 配布案・追加削減・完全無追加の比較','', 'Aは回収済みの確定供給案。現在面初回報酬を前提にしない。BはAから銭/武将EXP/装備EXPの追加を外し、前面の通常報酬を累積周回して補う。技・装備・技素材・汎用R魂の追加は残る。Cは完全無追加で、58面の同条件攻略は保証できない。ガチャ当選や現行クエストにない初期武将魂の周回を保証扱いしない。','', `Bの逐次計算：追加成功${farmTotal}回、行動力${energyTotal}。プレイヤーごとの既存資産/日次/育成任務/ログボは未計上。唯一の最小周回数ではなく、保存された主/別戦法/代替切替予算を維持する1案。`, '', '|受領面（初回クリア後）|必要になる面（攻略前）|追加内容A|','|---|---|---|',...economy.rewardAdditions.map(p=>`|${p.grantOn}|${p.beforeStage}|${p.rewards.map(rewardText).join('、')}|`),'', '武将の追加配布は0体。初期確定3名＋1-1/1-3の確定加入で5名を用いる。汎用R魂は覚醒用で武将新規配布ではない。名称・ID・必要Lv/覚醒・魂数は各面JSONに記載。', '', '|面|B前面|追加成功数|行動力|累積成功数|','|---|---|---:|---:|---:|',...all.map(r=>`|${r.stage}|${r.supply.optionB.priorStage??'—'}|${r.supply.optionB.successfulClears??'未定'}|${r.supply.optionB.energy??'未定'}|${r.supply.optionB.cumulativeSuccessfulClears}|`)];
fs.writeFileSync(`${OUT}/SUPPLY.md`,supply.join('\n')+'\n');
fs.writeFileSync(`${OUT}/EARLY.md`,['# 序盤10面の別戦法','',...early.flatMap(r=>[`## ${r.stage}`,`判定：${r.status}。${r.requiredChange}`,...r.pair.map(c=>`- ${c.meaning}：${rate(c)}。${order(c)}。中核${c.coreName}(${c.core}) ${c.coreRuns}/${c.n}試行で発動。`),''])].join('\n'));
fs.writeFileSync(`${OUT}/STALL.md`,['# 14面の300行動待ち','', 'これは戦闘仕様上の敗北であり、未完了の計算ジョブではない。主/別戦法は保存済みだが不適合編成の体験が未解消。各面の失敗結果は既に完了しているため、同じ試行を続けても閉じない。','',...stallRows.flatMap(r=>[`## ${r.stage}`,...r.details.map(x=>`- ${x.name}: ${x.wins}/${x.n}勝、上限敗北${x.actionLimit}/${x.n}、直接1ダメージ比${(100*x.oneDamageRatio).toFixed(1)}%。${x.explanation}`),`主${rate(r.primary)}／別${rate(r.alternative)}。${r.recommendation}`,r.uxProposal,r.closure,''])].join('\n'));
console.log(JSON.stringify({...summary,newTests:undefined}));
