import fs from 'node:fs';
import assert from 'node:assert/strict';
import {OUT,SOURCE,DECISION,rows,read,write,previous,candidatesFor,brief,stalls,select,timeWave,metrics,inBand,hash} from './stage68_adoption_lib.mjs';
import {FORMAL_QUEST_STAGES as stages} from '../src/domain/redesign/questMaster.ts';
import {CHARACTER_MASTERS as chars} from '../src/domain/redesign/masters.ts';
import {getFormalOwnedSkill} from '../src/domain/redesign/formalOwnedSkills.ts';
import {costs} from './audit_stage68.mjs';
const economy=read(`${SOURCE}/economy-proposal.json`),enemyRows=[],dependency=[],remaining=[],stallTable=[],supplyRows=[];
const recipe=c=>c?{...brief(c),metrics:metrics(c.validation)}:null;
const rate=c=>c?`${c.name} ${c.wins}/${c.n} (${(100*c.wins/c.n).toFixed(1)}%)`:'該当する検証なし';
const order=c=>c.order.map((p,i)=>`${i+1}:${chars.find(x=>x.id===p.id)?.name??p.id}[${p.skills.join('/')||'通常'}]`).join('→');
function additionalAssets(c,r){
 if(!c.state)return null;const a=r.acquisition,base={characters:a.trainedCharacters,skills:a.trainedSkills,equipment:a.trainedEquipment},after=structuredClone(base),items=[];
 for(const s of c.state.skills){const old=after.skills.find(t=>t.id===s.id);if(old)old.level=Math.max(old.level,s.level);else{after.skills.push(s);if(!a.availableGuaranteedSkills.includes(s.id))items.push({kind:'skill',id:s.id,amount:1});}}
 const oldCost=costs(base),newCost=costs(after),delta=Object.fromEntries(['cash','charExp','eqExp','skillMaterials'].map(k=>[k,newCost[k]-oldCost[k]]));
 return {items,trainingDelta:delta,scope:'技能追加/追加LBのみ。他の不足資産はcandidate.assets.missingを確認',grantOn:stages[rows.findIndex(x=>x.stage===r.stage)-1]?.designId??null};
}
for(let idx=0;idx<rows.length;idx++){
 const r=rows[idx],old=previous(r.stage),{d,cs}=candidatesFor(r),primary=cs.find(c=>c.name===old.primary.name),alt=cs.find(c=>c.name===old.alternative?.name),funded=cs.filter(c=>c.asset.covered);
 const used=[...new Set([primary,alt].filter(Boolean).flatMap(c=>c.state.skills.map(s=>s.id)))];
 const perSkill=used.map(id=>{const without=cs.filter(c=>c.state&&!c.state.skills.some(s=>s.id===id)).sort((a,b)=>b.validation.rate-a.validation.rate);const fundedWithout=without.filter(c=>c.asset.covered);const viable=fundedWithout.find(c=>c.validation.rate>=.3),strong=fundedWithout.find(c=>c.validation.rate>=.6),unfunded=without.find(c=>!c.asset.covered&&c.validation.rate>=.3);return {id,name:getFormalOwnedSkill(id,0).name,usedBy:[primary,alt].filter(c=>c?.state.skills.some(s=>s.id===id)).map(c=>c.name),status:strong?'到達前資産内で60%以上の技能なし候補あり':viable?'30%以上60%未満の回避例のみ':unfunded?'回避例は資産外。供給案Aだけでは依存を除外できない':'保存候補では資産内の回避経路未確認',withoutSkill:recipe(viable),strongWithoutSkill:recipe(strong),bestWithinAssets:recipe(fundedWithout[0]),outsideAssets:recipe(unfunded),mitigation:viable?{kind:strong?'guide-alternative':'strengthen-alternative-review',detail:strong?'保存済み代替の配置/技をガイドへ併記。必要技として固定しない。':'主攻略からこの技を外すと60%以上の代替がない。30%台のみを実用同等と扱わない。別候補/敵個別調整を次の限定対象とする。'}:unfunded?{kind:'additional-skill-option',candidate:unfunded.name,...additionalAssets(unfunded,r),detail:'この追加は44箇所のAに含まれない別の未承認案。既存値に黙って加算しない。'}:{kind:'enemy-local-option',detail:'当該技なしで最も高い保存勝率の候補を基点に、失敗Waveの高DEF/回復/保護源へ局所調整を検討。現時点で成功を保証する変更値は未確定。全体式や必須技能指定で埋めない。'}};});
 const dep={stage:r.stage,scope:'回収済み敵提案/供給A。新しい停滞実験には流用不可',primary:recipe(primary),alternative:recipe(alt),skills:perSkill,unresolved:perSkill.filter(s=>!s.withoutSkill).map(s=>s.id),onlyMarginal:perSkill.filter(s=>s.withoutSkill&&!s.strongWithoutSkill).map(s=>s.id)};dependency.push(dep);
 if(r.changes.length){
  const changesByEnemy=new Map();for(const c of r.changes){const k=c.wave+'/'+c.position;const group=changesByEnemy.get(k)??[];group.push(c);changesByEnemy.set(k,group);}
  const enemies=[...changesByEnemy].map(([key,changes])=>{const [w,p]=key.split('/').map(Number),before=d.stageOriginal.waves[w-1][p-1],after=d.stageProposal.waves[w-1][p-1];return {wave:w,position:p,id:after.id,name:after.name,changes,statsBefore:before.stats,statsAfter:after.stats,behaviorBefore:{element:before.element,initialCount:before.initialCount,actionCount:before.actionCount,initialSp:before.initialSp,hitSpGain:before.hitSpGain,skills:before.skills,passives:before.passives,phases:before.phases??[]},behaviorAfter:{element:after.element,initialCount:after.initialCount,actionCount:after.actionCount,initialSp:after.initialSp,hitSpGain:after.hitSpGain,skills:after.skills,passives:after.passives,phases:after.phases??[]}};});
  for(const e of enemies)assert.deepEqual(e.behaviorBefore,e.behaviorAfter);
  const distinct=funded.filter(c=>c.validation.rate<primary.validation.rate).sort((a,b)=>a.validation.rate-b.validation.rate)[0];
  const namedEffects=c=>c.input.party.flatMap((p,i)=>p.skills.map(s=>({actor:p.id,slot:i+1,id:s.id,element:s.element,target:s.target,condition:s.condition,effects:s.effects,casts:c.validation.runs.filter(x=>(x.casts[s.id]??0)>0).length,n:c.validation.n})));
  enemyRows.push({stage:r.stage,name:r.name,id:r.id,status:'UNAPPROVED',enemies,problems:[...new Set(r.changes.flatMap(c=>c.reasons))],profile:r.profile,primary:recipe(primary),alternative:recipe(alt),primaryMechanics:namedEffects(primary),alternateMechanics:alt?namedEffects(alt):[],primaryBurstRuns:primary.validation.runs.filter(x=>x.bursts>0).length,alternateBurstRuns:alt?.validation.runs.filter(x=>x.bursts>0).length??null,beforeSameParty:old.beforeSameParty,orderContrasts:old.orderContrasts,lowerSameBudget:recipe(distinct),tacticalEvidence:distinct?'同育成/到達前資産内で低勝率の比較あり。技/順序差と実発動を併記。':'主/別の勝利と発動は確認済みだが、この保存集合では同予算の勝敗差は未確認。',dependency:dep});
 }
 if(old.missingWithinBudget.length){
  const untested=old.exactProposals?.length??0,hasBlockedEvidence=old.tierRows.some(t=>!t.withinBudget&&t.allSaved),tag={adoptionDependent:r.profile.area>=3,compositionOrTacticMissing:old.missingWithinBudget.some(b=>!old.tierRows.find(t=>t.label===b).allSaved),stallResolution:stalls.includes(r.stage),evidenceOnly:untested>0};
  // Evidence-only is a strict primary classification only when same-budget inputs already exist and no other gameplay/supply issue blocks them.
  const principal=tag.stallResolution?'停滞解消が必要':r.stage==='1-1'||!untested?'編成候補・戦法が不足':hasBlockedEvidence?'敵・配布案の採否が前提':tag.adoptionDependent?'敵・配布案の採否が前提':'試行証拠の補完が次の作業';
  remaining.push({stage:r.stage,missing:old.missingWithinBudget,principal,tags:tag,untestedBandPlans:untested,assetBlockedSavedBands:old.tierRows.filter(t=>!t.withinBudget&&t.allSaved).map(t=>t.label),next:tag.stallResolution?'停滞実験の可否を先に判断。採用する敵入力を固定後、未達帯の編成を限定評価。':hasBlockedEvidence?'資産外の保存候補をAに追加するか、同資産の未検証候補で代替するかを判断。':untested?'既存candidate-inputsの具体入力を対象面のみ検証。採否待ちだけで5帯が揃った扱いにしない。':'新しい戦法候補または1-1限定例外の判断。',note:'4タグは重複可。evidenceOnlyは未検証入力があるという補助タグで、他の残件がないことを意味しない。主因は1つ。'});
 }
 if(stalls.includes(r.stage)){
  const p=select(r),tests=`${OUT}/stall-tests/${r.stage}.json.gz`;
  const stalled=p.cs.filter(c=>c.validation.runs.some(x=>x.reason==='action_limit'));
  const details=stalled.map(c=>({recipe:recipe(c),stageOfRate:inBand(c.validation.rate,0)?'全勝':inBand(c.validation.rate,1)?'約60%':inBand(c.validation.rate,2)?'約30%':inBand(c.validation.rate,3)?'0%超～10%':inBand(c.validation.rate,4)?'観測0%':'区分間',timedWaves:timeWave(c)}));
  const waves=timeWave(p.low),w=(waves[0]?.wave??1)-1,enemies=d.stageProposal.waves[w];
  const effects=enemies.flatMap(e=>[...e.skills,...(e.phases??[]).flatMap(p=>p.skills??[])].flatMap(s=>s.effects.map(ef=>({enemy:e.id,skill:s.id,target:s.target,condition:s.condition,type:ef.type}))));
  const runs=p.low.validation.runs.filter(x=>x.reason==='action_limit'),oneRatio=runs.reduce((n,x)=>n+x.oneDamage,0)/Math.max(1,runs.reduce((n,x)=>n+x.damageEvents,0));
  stallTable.push({stage:r.stage,primary:recipe(p.primary),alternative:recipe(p.alt),near60:recipe(p.next),representativeLow:recipe(p.low),details,causes:{directOneDamageRatio:oneRatio,stalledWave:w+1,enemyMechanisms:effects,observed:oneRatio>.5?'直接攻撃の過半数が1ダメージ。防御閾値で削りが止まる。':'攻撃は通るが全Wave処理が300行動内に終わらない。',hypotheses:[...(effects.some(e=>['heal','hot','revive'].includes(e.type))?['敵回復/復活との均衡が候補（定義あり、集計だけで実発動因果は未確定）']:[]),...(effects.some(e=>['atk_down','def_up','barrier','protect','stun'].includes(e.type))?['弱体/防御/保護/行動制御の影響が候補']:[]),'先頭集中と後列の残存、SP消費順は保存編成と順序対照で確認。個別効果の因果寄与は未網羅'],scope:'保存集計と敵定義に基づく。仮説と観測を分離。'},tests:fs.existsSync(tests)?{path:tests,...(()=>{const x=readGz(tests);return {recommendation:x.recommendation,selected:x.selected,acceptance:x.acceptance};})()}:null,playback:{measured:false,seconds:null,reason:'実クライアントの再生/倍速/SKIPを測っていない。行動数から秒へ換算しない。'},UI:'補助案のみ。戦闘側の改善合格には数えない。'});
 }
}
function readGz(p){return JSON.parse((awaitlessGunzip(fs.readFileSync(p))).toString());}
import {gunzipSync as awaitlessGunzip} from 'node:zlib';
for(const p of economy.rewardAdditions){const si=stages.findIndex(s=>s.designId===p.grantOn),ni=stages.findIndex(s=>s.designId===p.beforeStage);assert(si<ni);const s=stages[si],needed=previous(p.beforeStage),dep=dependency.find(d=>d.stage===p.beforeStage);supplyRows.push({grantOn:p.grantOn,stageId:s.id,receivedAt:'この面の初回クリア報酬受領時',requiredBefore:p.beforeStage,currentFirstRewards:s.firstRewards,additions:p.rewards,proposedFirstRewards:[...s.firstRewards,...p.rewards],currentRepeatRewardsUnchanged:s.rewards,status:'UNAPPROVED',purpose:'次の必要面より前に主/別戦法を選択できる資産を確定供給。特定技の装備必須化ではない。',strategies:{primary:dep.primary,alternative:dep.alternative},dependencyAtNextStage:{unresolved:dep.unresolved,onlyMarginal:dep.onlyMarginal},budget:needed.supply.requiredAssets.cumulativeTrainingCost});}
for(const r of remaining){const dep=dependency.find(d=>d.stage===r.stage);r.tags.skillRemovalEvidenceMissing=dep.unresolved.length>0;if(r.principal==='試行証拠の補完が次の作業'&&dep.unresolved.length){r.principal='編成候補・戦法が不足';r.tags.compositionOrTacticMissing=true;r.next=`5帯向け具体入力はあるが、${dep.unresolved.join('/')}を外した到達前資産内候補が未確認。資産内の代替戦法を先に作るか、別承認の早期供給を判断。`;}}
assert.equal(enemyRows.length,43);assert.equal(supplyRows.length,44);assert.equal(stallTable.length,14);assert.equal(remaining.length,59);
write(`${OUT}/enemy43.json`,enemyRows);write(`${OUT}/supply44.json`,supplyRows);write(`${OUT}/skill-dependency.json`,dependency);write(`${OUT}/stall14.json`,stallTable);write(`${OUT}/remaining59.json`,remaining);
const enemyText=['# 敵43面：変更内容・攻略根拠','', '全て未承認。元の正式値→回収済み提案値を表示。停滞追加実験の値はこの表へ混ぜない。敵行動・条件・SP・技能・形態は43面案では不変。技能効果/条件全量はenemy43.json。数値変更自体は弱体化だが、同育成の攻略差を併記し、弱体化だけを攻略性の証明にしない。',''];
for(const r of enemyRows){enemyText.push(`## ${r.stage} ${r.name}`,`問題：${r.problems.join('／')}`,'|敵ID・Wave/位置|数値変更|初期→再行動count（前後不変）|技能・条件（前後不変）|','|---|---|---|---|',...r.enemies.map(e=>`|${e.id} W${e.wave}/${e.position} ${e.name}|${e.changes.map(c=>`${c.field} ${c.before}→${c.after}`).join('、')}|${e.behaviorBefore.initialCount}→${e.behaviorBefore.actionCount}|${e.behaviorBefore.skills.map(s=>`${s.id}:${s.target}:${JSON.stringify(s.condition)}`).join('、')||'通常攻撃'}|`),`主：${rate(r.primary)}。${order(r.primary)}。BURST発生${r.primaryBurstRuns}/${r.primary.n}試行。`,`別：${rate(r.alternative)}。${r.alternative?order(r.alternative):''}。BURST発生${r.alternateBurstRuns}/${r.alternative?.n??0}試行。`,`別の中核候補実発動：${r.alternateMechanics.map(s=>`${s.id}(${s.element}/${s.target}) ${s.casts}/${s.n}`).join('、')}。0発動の技は勝因にしない。`,`同資産の低勝率比較：${rate(r.lowerSameBudget)}。${r.tacticalEvidence}`,`順序対照：${r.orderContrasts.map(c=>`${rate(c.base)}→${rate(c.changed)}、同seed=${c.sameSeedSet}`).join('／')||'対応比較なし'}`,`技能なし30%以上の回避未確認：${r.dependency.unresolved.join(',')||'なし'}。30～60%未満だけ：${r.dependency.onlyMarginal.join(',')||'なし'}。`,'');}
fs.writeFileSync(`${OUT}/ENEMY43.md`,enemyText.join('\n'));
fs.writeFileSync(`${OUT}/SUPPLY44.md`,['# 前面44箇所：現行報酬と追加差分','', 'Aは未承認。既存報酬の削除/減額0、追加武将0。反復報酬は変更しない。currentFirstRewards/additions/proposedFirstRewardsをJSONに分離。Bの2,711成功周回案は非推奨の履歴で追加検証なし。','',...supplyRows.flatMap(r=>[`## ${r.grantOn}初回クリア後 → ${r.requiredBefore}攻略前`,`既存初回報酬：${JSON.stringify(r.currentFirstRewards)}`,`追加差分：${JSON.stringify(r.additions)}`,`成立候補：主${rate(r.strategies.primary)}／別${rate(r.strategies.alternative)}。前面供給Aの条件付き。`,`次面の技能依存：回避未確認${r.dependencyAtNextStage.unresolved.join(',')||'なし'}／30～60%未満だけ${r.dependencyAtNextStage.onlyMarginal.join(',')||'なし'}。全後続面の依存はskill-dependency.jsonを参照。`,''])].join('\n'));
fs.writeFileSync(`${OUT}/DEPENDENCY.md`,['# 特定技能への依存（同じ敵提案・到達前資産A）','', '主/別で使う技能を1種類ずつ外した保存候補を照合。単独除去の証拠であり、全技能同時除去や全編成の網羅ではない。30%以上の回避例だけなら必須性の完全否定ではなく、実用代替の強化余地として残す。','', '|面|30%以上の回避未確認|30～60%未満の回避だけ|','|---|---|---|',...dependency.map(r=>`|${r.stage}|${r.unresolved.join(',')||'なし'}|${r.onlyMarginal.join(',')||'なし'}|`),'',...dependency.filter(r=>r.unresolved.length||r.onlyMarginal.length).flatMap(r=>[`## ${r.stage}`,...r.skills.filter(s=>!s.strongWithoutSkill).map(s=>`- ${s.id} ${s.name}：${s.status}。資産内${rate(s.bestWithinAssets)}。資産外${rate(s.outsideAssets)}。対案 ${JSON.stringify(s.mitigation)}`),''])].join('\n'));
fs.writeFileSync(`${OUT}/REMAINING59.md`,['# 残59面の区分','', '到達前資産の条件付き5帯充足9面/残59面の管理数を維持。分類は重複タグ、主因は1つ。採否が決まっただけでは未達帯の試行は完了しない。「試行証拠あり」のタグも成功保証ではない。','', '|面|主因|採否前提|候補/戦法不足|停滞解消|具体入力の未評価あり|未達帯|','|---|---|---|---|---|---|---|',...remaining.map(r=>`|${r.stage}|${r.principal}|${r.tags.adoptionDependent?'あり':'—'}|${r.tags.compositionOrTacticMissing?'あり':'—'}|${r.tags.stallResolution?'あり':'—'}|${r.tags.evidenceOnly?'あり':'—'}|${r.missing.join('、')}|`)].join('\n'));
const summary={enemyStages:enemyRows.length,enemyFields:enemyRows.reduce((n,r)=>n+r.enemies.reduce((n,e)=>n+e.changes.length,0),0),supplySites:supplyRows.length,stalls:14,remaining:59,skillDependencyUnresolvedStages:dependency.filter(r=>+r.stage.split('-')[0]>=3&&r.unresolved.length).map(r=>r.stage),marginalOnlyStages:dependency.filter(r=>+r.stage.split('-')[0]>=3&&r.onlyMarginal.length).map(r=>r.stage),classification:Object.fromEntries([...new Set(remaining.map(r=>r.principal))].map(k=>[k,remaining.filter(r=>r.principal===k).length]))};write(`${OUT}/table-summary.json`,summary);console.log(JSON.stringify(summary));
