import fs from'node:fs';import{gz,write}from'./stage68_decision_lib.mjs';import{assess,hash,metrics}from'./stage68_implementation_results.mjs';import{inputFor,run}from'./rebuild_stage68_five_tier.mjs';
const OUT='docs/verification/stage68-resolution-20260927';
for(const id of ['2-3','10-1','10-9']){if(process.argv.length>2&&!process.argv.slice(2).includes(id))continue;const folder=id==='2-3'?'fill-pressure-aoe':'fill-pressure-refined2',source=gz(`${OUT}/${folder}/${id}.json.gz`),path=`${OUT}/pressure-targeted/${id}.json.gz`,d=fs.existsSync(path)?gz(path):{stage:id,variants:[],complete:false};if(d.complete)continue;
 const cs=source.records.filter(c=>c.validation),hpMax=Math.max(...cs.flatMap(c=>c.input.party.map(p=>p.stats.hp))),defMax=Math.max(...cs.flatMap(c=>c.input.party.map(p=>p.stats.def)));
 for(const [hp,n]of (id==='10-9'?[[1,24]]:id==='10-1'?[[1.6,16],[2,16],[2.4,16]]:[[.75,10],[.6,10],[.6,8]])){const name=`hp${hp}-period${n}`;if(d.variants.some(v=>v.name===name))continue;const stage=structuredClone(source.stageProposal);
  for(const [wi,wave]of stage.waves.entries())for(const e of wave){e.stats.hp=Math.round(e.stats.hp*hp);const existing=e.skills.find(s=>s.id.includes('/pressure-'));if(existing){if(id!=='10-9'){existing.condition.value=n;existing.id=existing.id.replace(/pressure-.+/,`pressure-${n}-targeted`);existing.description=`自身の${n}行動ごとに全体へ強打。共通計算式を使用。`;}}else if(id==='10-1'||id==='10-9'&&wi===2){const skill={id:`${e.id}/pressure-${n}-targeted`,name:'長期戦の強打',image:'',rarity:'N',element:e.element,spCost:1,condition:{type:'every_n_actions',value:n},target:'all_enemies',effects:[{type:'damage',power:Math.ceil((defMax*2+hpMax*.65)/e.stats.atk*250)}],description:`自身の${n}行動ごとに全体へ強打。共通計算式を使用。`};e.skills.unshift(skill);}}
  const records=cs.map(c=>{const input=inputFor(stage,{party:c.input.party});return{name:c.name,state:c.state,input,inputHash:hash(input),screen:run(input,590001,16,true)};});const a=assess(records.map(c=>({...c,validation:c.screen}))),v={name,stage,records,gate:!!a.primary&&!!a.alternative&&!a.stalled.length};d.variants.push(v);write(path,d);console.log(JSON.stringify({stage:id,name,gate:v.gate}));
 }
 for(const v of d.variants.filter(v=>v.gate)){for(const c of v.records)if(!c.validation){c.validation=run(c.input,591001,200,true);write(path,d);}const a=assess(v.records),max=Math.max(...v.records.map(c=>metrics(c.validation).max));if(a.primary&&a.alternative&&!a.stalled.length&&(id!=='2-3'||max<=200)){d.selected=v.name;d.result={missing:a.missing,stalled:[],max,dependencyMissing:a.dependency.filter(d=>!d.without).map(d=>d.id)};break;}}
 d.complete=true;write(path,d);console.log(JSON.stringify({stage:id,selected:d.selected,result:d.result}));
}
