import fs from 'node:fs';import {rows,assess,metrics,hash}from'./stage68_implementation_results.mjs';import{gz,write}from'./stage68_decision_lib.mjs';import{inputFor,run}from'./rebuild_stage68_five_tier.mjs';
const OUT='docs/verification/stage68-resolution-20260927';
for(const id of process.argv.slice(2)){const src=`${OUT}/pressure-refined/${id}.json.gz`;if(!fs.existsSync(src))continue;const prior=gz(src),path=`${OUT}/pressure-refined2/${id}.json.gz`,d=fs.existsSync(path)?gz(path):{stage:id,variants:[],complete:false};if(d.complete)continue;
 const combined=gz(`${OUT}/pressure-combined/${id}.json.gz`),base=combined.variants.find(v=>v.name===combined.selected)??combined.variants.at(-1),cs=[...base.records];
 for(const folder of ['fill-pressure-combined','fill-pressure-refined']){const p=`${OUT}/${folder}/${id}.json.gz`;if(fs.existsSync(p))for(const c of gz(p).records.filter(c=>c.validation&&metrics(c.validation).actionLimit))if(!cs.some(x=>hash(x.input.party)===hash(c.input.party)))cs.push(c);}
 const configurations=[...prior.variants.filter(v=>v.gate&&v.name!==prior.selected).map(v=>({name:'retained-'+v.name,reuse:v})),...[[1,2,24],[.6,2.5,24],[.4,1.6,20]].map(([hp,power,n])=>({name:`hp${hp}-power${power}-period${n}`,hp,power,n}))];
 for(const config of configurations){if(d.variants.some(v=>v.name===config.name))continue;let v;if(config.reuse){v={...structuredClone(config.reuse),name:config.name,screenReused:true};for(const c of cs)if(!v.records.some(x=>hash(x.input.party)===hash(c.input.party))){const input=inputFor(v.stage,{party:c.input.party});v.records.push({name:c.name,state:c.state,input,inputHash:hash(input),screen:run(input,580001,16,true)});}}else{const stage=structuredClone(base.stage);for(const w of stage.waves)for(const e of w){e.stats.hp=Math.round(e.stats.hp*config.hp);for(const s of [...e.skills,...(e.phases??[]).flatMap(p=>p.skills??[])])if(s.id.includes('/pressure-')){s.condition.value=config.n;s.effects[0].power=Math.round(s.effects[0].power*config.power);s.id=s.id.replace(/pressure-.+/,`pressure-${config.n}-p${config.power}`);s.description=`自身の${config.n}行動ごとに全体へ強打。共通計算式を使用。`;}}v={name:config.name,stage,config,records:cs.map(c=>{const input=inputFor(stage,{party:c.input.party});return {name:c.name,state:c.state,input,inputHash:hash(input),screen:run(input,580001,16,true)};})};}
  const a=assess(v.records.map(c=>({...c,validation:c.screen})));v.gate=!!a.primary&&!!a.alternative&&!a.stalled.length;d.variants.push(v);write(path,d);console.log(JSON.stringify({stage:id,name:v.name,gate:v.gate}));
 }
 for(const v of d.variants.filter(v=>v.gate)){for(const c of v.records)if(!c.validation){c.validation=run(c.input,581001,200,true);write(path,d);}const a=assess(v.records);if(a.primary&&a.alternative&&!a.stalled.length){d.selected=v.name;d.result={missing:a.missing,stalled:[],dependencyMissing:a.dependency.filter(x=>!x.without).map(x=>x.id)};break;}}
 d.complete=true;write(path,d);console.log(JSON.stringify({stage:id,selected:d.selected,result:d.result}));
}
