import fs from'node:fs';import zlib from'node:zlib';import{buildBattleParty}from'../src/domain/redesign/masters.ts';import{getFormalOwnedSkill}from'../src/domain/redesign/formalOwnedSkills.ts';import{costs,loadout,hash}from'./audit_stage68.mjs';import{OUT,save,run,inputFor}from'./rebuild_stage68_five_tier.mjs';
const replacements={SKD003:['SKD001','SKD004'],SKD009:['SKD010','SKD007','SKD008'],SKD010:['SKD009','SKD007'],SKD007:['SKD008','SKD009'],SKD008:['SKD009','SKD010'],SKD011:['SKD012','SKD009'],SKD012:['SKD011','SKD009'],SKD026:['SKD027'],SKD027:['SKD026'],SKD035:['SKD038','SKD037'],SKD038:['SKD035','SKD037'],SKD039:['SKD040','SKD043','SKD041'],SKD040:['SKD039','SKD043'],SKD043:['SKD039','SKD040'],SKD049:['SKD045','SKD048'],SKD045:['SKD049','SKD046'],SKD051:['SKD052','SKD038'],SKD052:['SKD051','SKD038'],SKD053:['SKD054','SKD035'],SKD054:['SKD053','SKD035'],SKD055:['SKD053','SKD035'],SKD032:['SKD026','SKD027']};
for(const id of (process.env.STAGE_IDS??'').split(',').filter(Boolean)){
 const d=JSON.parse(zlib.gunzipSync(fs.readFileSync(OUT+'/'+id+'-validated.json.gz')));const initial=[...d.records],best=[...initial].sort((a,b)=>b.validation.wins-a.validation.wins||a.validation.meanActions-b.validation.meanActions)[0],checks=[];
 for(const s of best.state.skills){if(d.records.some(c=>!c.state.skills.some(t=>t.id===s.id)&&c.validation.rate>=.6))continue;const candidates=[];
  for(const r of replacements[s.id]??[]){const state=structuredClone(best.state);state.deck.forEach(m=>m.skillIds=[...new Set(m.skillIds.map(id=>id===s.id?r:id))]);state.skills=state.skills.filter(sk=>sk.id!==s.id);if(!state.skills.some(sk=>sk.id===r))state.skills.push({id:r,level:s.level});const party=buildBattleParty(state),input=inputFor(d.stageProposal,{party}),selection=run(input,92001,30,true);candidates.push({replacement:r,state,party,input,selection});}
  candidates.sort((a,b)=>b.selection.wins-a.selection.wins||a.selection.meanActions-b.selection.meanActions);const top=candidates[0];let tested=null;
  if(top){const validation=run(top.input,93001,200,true);tested={name:best.name+'-replace-'+s.id+'-'+top.replacement,family:best.family,roles:['specific-card-substitution', 'without-'+s.id],state:top.state,loadout:loadout(top.state),costs:costs(top.state),input:top.input,inputHash:hash(top.input),selection:top.selection,validation};d.records.push(tested);}
  checks.push({omitted:s.id,base:best.name,candidates:candidates.map(({party,input,...c})=>c),independent:tested?{name:tested.name,wins:tested.validation.wins,n:200}:null});
 }
 save(id+'-specific-card-checks.json.gz',{stage:id,checks});d.specificCardChecks=checks.map(c=>({omitted:c.omitted,base:c.base,independent:c.independent}));save(id+'-validated.json.gz',d);console.log(id,'substitutions',checks.map(c=>c.omitted+':'+c.independent?.wins).join(','));
}
