// Synthetic QA only: persistent browser created this turn through ordinary New Game UI. Never reads or injects any pre-existing user session.
const fs=require('node:fs'),assert=require('node:assert/strict'),ts=require('typescript');
const {chromium}=require('@playwright/test');
require.extensions['.ts']=(mod,file)=>mod._compile(ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,esModuleInterop:true}}).outputText,file);
const {CHARACTER_MASTERS,SKILL_MASTERS,EQUIPMENT_MASTERS}=require('../src/domain/redesign/masters.ts');
const output='docs/verification/character-20260923',base='https://game04-btsnlophl-kiyoshi-kitamura.vercel.app',supabase='https://lrgyllgzcdcphlbmkknc.supabase.co';
const qa=JSON.parse(fs.readFileSync('/tmp/game04-fresh-qa-meta.json','utf8')).userId;assert.equal(qa,'83d6fd82-bd7d-4d17-add0-bb583114367e');
(async()=>{
 const config=require('../config/game04-preview-public.json');
 assert.equal(config.supabaseUrl,supabase);assert.equal(JSON.parse(Buffer.from(config.supabaseAnonKey.split('.')[1],'base64url').toString()).ref,'lrgyllgzcdcphlbmkknc');
 const report={kind:'fresh-synthetic-qa-mainbody-live-api',root:base,qaUserId:qa,at:new Date().toISOString(),authorization:'Materially safer alternative: this turn ordinary New Game UI created a fresh synthetic QA guest. Only its persistent browser profile is used. No pre-existing session file, token injection, or private user state is read. Explicitly authorized operations/save/reload remain limited to fixed GAME04 Preview and verified dev origin.',screens:[],api:[],actions:[],errors:[],failures:[],blockedOrigins:[]};let browser,page,state;
 const persist=()=>fs.writeFileSync(`${output}/fresh-mainbody-browser.json`,JSON.stringify(report,null,2));
 const fields=s=>Object.fromEntries(['cash','characters','skills','equipment','deck','souls','growthInventory','materials'].map(k=>[k,s[k]]));
 try{
  browser=await chromium.launchPersistentContext('/tmp/game04-fresh-qa-profile',{viewport:{width:390,height:844},ignoreHTTPSErrors:true,reducedMotion:'reduce',headless:true,executablePath:'/tmp/game04-browser/chrome-headless-shell-linux64/chrome-headless-shell',args:['--no-sandbox'],...(process.env.HTTPS_PROXY?{proxy:{server:process.env.HTTPS_PROXY}}:{})});
  page=browser.pages()[0]||await browser.newPage();
  await browser.route('**/*',route=>{const origin=new URL(route.request().url()).origin;if(origin===base||origin===supabase)return route.continue();if(!report.blockedOrigins.includes(origin))report.blockedOrigins.push(origin);return route.abort('blockedbyclient');});
  page.on('pageerror',e=>report.errors.push(e.message));
  page.on('response',r=>{const u=new URL(r.url());if(u.origin===supabase)console.log('QA network',r.status(),u.pathname);});
  page.on('response',async r=>{if(r.url()===supabase+'/functions/v1/game04-redesign-api'){try{const body=await r.json();if(body.state){assert.equal(body.state.userId,qa);if(!state||body.state.version>=state.version)state=body.state;}report.api.push({status:r.status(),action:r.request().postDataJSON()?.action,version:body.state?.version,error:body.error});}catch{}}});
  const enter=async()=>{await Promise.race([page.locator('.rd-footer').waitFor({timeout:90000}),page.getByRole('button',{name:'TAP TO START',exact:true}).waitFor({timeout:90000})]);if(await page.getByRole('button',{name:'TAP TO START',exact:true}).isVisible()){await page.waitForFunction(()=>{const b=[...document.querySelectorAll('button')].find(e=>e.textContent==='TAP TO START');return b&&Object.keys(b).some(k=>k.startsWith('__reactProps'));});await page.waitForTimeout(1500);await page.getByRole('button',{name:'TAP TO START',exact:true}).click();if(await page.getByText('セッション確認中',{exact:true}).isVisible()){console.log('Waiting for fresh QA authentication bootstrap');await page.getByText('セッション確認中',{exact:true}).waitFor({state:'hidden',timeout:60000});}console.log('Entry buttons',await page.locator('button:visible').allTextContents());await page.getByRole('button',{name:/^(続きから|チュートリアルを続ける)$/}).click({timeout:15000});}await page.locator('.rd-footer').waitFor({timeout:120000});};
  const ready=async()=>{await page.getByRole('dialog',{name:'画像を準備中'}).waitFor({state:'hidden',timeout:60000});await page.locator('img').evaluateAll(imgs=>Promise.all(imgs.map(i=>i.decode().catch(()=>{}))));};
  const capture=async(name,ends=false)=>{await ready();for(const height of [844,600]){await page.setViewportSize({width:390,height});if(ends)await page.locator('.rd-modal-body').evaluate(e=>{e.scrollTop=e.scrollHeight;});const check=await page.evaluate(()=>({horizontalOverflow:document.documentElement.scrollWidth>innerWidth,images:[...document.images].filter(i=>i.getBoundingClientRect().width&&(!i.complete||!i.naturalWidth)).map(i=>i.getAttribute('src')),dialogs:[...document.querySelectorAll('[role=dialog]')].map(d=>{const r=d.getBoundingClientRect();return {title:d.querySelector('h2')?.textContent||d.getAttribute('aria-label'),x:r.x,y:r.y,height:r.height,width:r.width};}),inert:[...document.querySelectorAll('.rd-shell')].every(s=>s.inert)}));assert.equal(check.horizontalOverflow,false);assert.deepEqual(check.images,[]);for(const d of check.dialogs){assert.ok(d.height<=height*.8+2);assert.ok(Math.abs(d.y+d.height/2-height/2)<3);}if(check.dialogs.length){assert.equal(check.dialogs.length,1);assert.equal(check.inert,true);}await page.screenshot({path:`${output}/mainbody-${name}-390x${height}.png`});report.screens.push({name,height,...check,text:(await page.locator('body').innerText()).slice(-14000)});}await page.setViewportSize({width:390,height:844});if(ends)await page.locator('.rd-modal-body').evaluate(e=>{e.scrollTop=0;});persist();};
  const close=async()=>{await page.getByRole('dialog').getByRole('button',{name:'閉じる',exact:true}).last().click();};
  const tab=async(name)=>{await page.locator('.g4g-tabs').getByRole('button',{name,exact:true}).click();await ready();};
  const perform=async(action,label,resultName)=>{const before=structuredClone(state),receipt=page.waitForResponse(r=>r.url()===supabase+'/functions/v1/game04-redesign-api'&&r.request().postDataJSON()?.action===action,{timeout:120000});await page.getByRole('button',{name:label,exact:true}).click();const response=await receipt,body=await response.json();assert.equal(response.status(),200,body.error);assert.equal(body.state.userId,qa);state=body.state;assert.notDeepEqual(fields(state),fields(before));await page.getByRole('dialog',{name:resultName,exact:true}).waitFor({timeout:30000});report.actions.push({action,status:response.status(),beforeVersion:before.version,afterVersion:state.version,beforeCash:before.cash,afterCash:state.cash,resultDialog:resultName,changed:true});persist();console.log('PASS live UI action',action);};
  const entry=await page.goto(base,{waitUntil:'domcontentloaded',timeout:120000});report.entryStatus=entry.status();persist();console.log('Preview entry HTTP',entry.status());assert.equal(entry.status(),200);await enter();await page.locator('.rd-footer').getByRole('button',{name:/キャラ/}).click();await page.locator('.g4-growth').waitFor();await ready();assert.ok(state);assert.equal(state.userId,qa);console.log('PASS authenticated mainbody entry');
  await capture('deck');await tab('編成');await capture('formation');await perform('save_deck','移動 →','編成保存結果');await capture('formation-result');await close();await capture('formation-reflected');await tab('キャラ');await capture('character-list');
  const character=state.characters.find(c=>c.level<50&&c.awakening<5),cm=CHARACTER_MASTERS.find(m=>m.id===character.id);assert.ok(character);
  await page.locator('.g4g-grid button').filter({has:page.locator('b',{hasText:cm.name})}).first().click();await capture('character-detail');await capture('character-detail-end',true);
  const member=state.deck.find(m=>m.characterId===character.id),equippedId=member?.equipment.accessory1;assert.ok(equippedId,'QA selected character must have accessory1');const equipped=state.equipment.find(e=>e.instanceId===equippedId),equippedMaster=EQUIPMENT_MASTERS.find(m=>m.id===equipped.masterId);await page.locator('.g4g-equipment-slots button').filter({has:page.locator('strong',{hasText:'アクセ1'})}).click();await perform('save_deck','外す','編成保存結果');await capture('equipment-remove-result');await close();assert.equal(state.deck.find(m=>m.characterId===character.id).equipment.accessory1,undefined);await page.locator('.g4g-equipment-slots button').filter({has:page.locator('strong',{hasText:'アクセ1'})}).click();await perform('save_deck',`${equippedMaster.name} Lv.${equipped.level}`,'編成保存結果');await capture('equipment-assign-result');await close();assert.equal(state.deck.find(m=>m.characterId===character.id).equipment.accessory1,equippedId);await capture('equipment-assignment-reflected');
  await page.getByRole('dialog').getByRole('button',{name:'Lv育成',exact:true}).first().click();await capture('character-growth');await page.getByRole('spinbutton',{name:'武将EXP小投入数'}).fill('1');await perform('character_level','育成する','武将育成結果');await capture('character-result');await capture('character-result-end',true);await close();await capture('character-level-reflected');
  await page.getByRole('dialog').getByRole('button',{name:'覚醒',exact:true}).first().click();await capture('character-awaken');await perform('character_awaken','覚醒する','覚醒結果');await capture('character-awaken-result');await close();await capture('character-awaken-reflected');await close();
  const unlock=CHARACTER_MASTERS.find(m=>!state.characters.some(c=>c.id===m.id)&&(state.souls[m.id]||0)>=100);assert.ok(unlock,'No unlockable QA character');await page.getByRole('button',{name:new RegExp(unlock.name+'.*魂の操作')}).click();await capture('character-unlock');await perform('character_unlock','解放する','魂解放結果');await capture('character-unlock-result');await close();await capture('character-unlock-reflected');if(await page.getByRole('dialog').count())await close();
  await tab('スキル');await capture('skill-list');const skill=state.skills.find(s=>s.level<10),sm=SKILL_MASTERS.find(m=>m.id===skill.id);await page.locator('.g4g-grid button').filter({has:page.locator('b',{hasText:sm.name})}).first().click();await capture('skill-detail');await perform('skill_level','LBを上げる','スキルLB結果');await capture('skill-result');await close();await capture('skill-reflected');await close();
  await tab('装備');await capture('equipment-list');const eq=state.equipment.find(e=>e.level<50&&e.lb<10),em=EQUIPMENT_MASTERS.find(m=>m.id===eq.masterId);await page.locator('.g4g-grid button').filter({has:page.locator('b',{hasText:em.name})}).filter({has:page.getByText(`Lv.${eq.level}　LB+${eq.lb}`,{exact:true})}).first().click();await capture('equipment-detail');await page.getByRole('button',{name:'Lv育成',exact:true}).click();await capture('equipment-growth');await page.getByRole('spinbutton',{name:'装備EXP小投入数'}).fill('1');await perform('equipment_level','育成する','装備育成結果');await capture('equipment-result');await close();await capture('equipment-level-reflected');await perform('equipment_lb','LBで上限を解放','装備LB結果');await capture('equipment-lb-result');await close();await capture('equipment-lb-reflected');await close();
  const expected=fields(state);const reloadReceipt=page.waitForResponse(r=>r.url()===supabase+'/functions/v1/game04-redesign-api'&&r.request().postDataJSON()?.action==='get_state',{timeout:120000});await page.reload({waitUntil:'domcontentloaded'});await enter();const restored=(await (await reloadReceipt).json()).state;assert.deepEqual(fields(restored),expected);report.reload={pass:true,version:restored.version,verifiedActions:report.actions.map(a=>a.action)};await page.locator('.rd-footer').getByRole('button',{name:/キャラ/}).click();await page.locator('.g4-growth').waitFor();await capture('reload-deck');assert.deepEqual(report.errors,[]);report.complete=true;
 }catch(e){report.failures.push(e.message);if(page){report.failureText=(await page.locator('body').innerText()).slice(0,5000);await page.screenshot({path:`${output}/fresh-mainbody-blocked.png`}).catch(()=>{});}process.exitCode=1;}finally{if(browser)await browser.close();persist();}
 console.log(JSON.stringify({kind:report.kind,screens:report.screens.length,actions:report.actions,complete:report.complete,errors:report.errors,failures:report.failures}));
})();
