import assert from 'node:assert/strict';
import { BATTLE_EFFECT_FAMILIES, classifyBattleDamageEffect, resolveBattleFrameEffects } from '../src/app/components/redesign/battleEffectPresentation.ts';
const unit = statuses => ({id:'target',statuses});
const base = {wave:1,party:[],enemies:[unit([])],targetIds:['target']};
const status = {type:'atk_up',sourceId:'actor',sourceSkillId:'skill',appliedAction:1,power:10};
const applied = {...base,event:'effect_applied',enemies:[unit([status])]};
assert.equal(BATTLE_EFFECT_FAMILIES.length,16);
assert.deepEqual(resolveBattleFrameEffects(applied,base),[{targetId:'target',family:'atk_up'}]);
assert.deepEqual(resolveBattleFrameEffects({...applied,event:'effect_miss'},base),[]);
assert.deepEqual(resolveBattleFrameEffects(applied,applied),[]);
assert.deepEqual(resolveBattleFrameEffects(applied,undefined),[]);
assert.deepEqual(resolveBattleFrameEffects({...applied,wave:2},base),[]);
assert.deepEqual(resolveBattleFrameEffects({...base,event:'action_start'},base),[]);
assert.equal(classifyBattleDamageEffect({name:'大槌',target:'all_enemies',effects:[]}),'impact_all');
assert.equal(classifyBattleDamageEffect({name:'一文字斬り',target:'first',effects:[]}),'slash');
assert.equal(classifyBattleDamageEffect({name:'毒針',target:'first',effects:[]}),'projectile');
assert.deepEqual(resolveBattleFrameEffects({...base,event:'heal'},base,{target:'all_allies',effects:[]}),[{targetId:'target',family:'heal_all'}]);
assert.deepEqual(resolveBattleFrameEffects({...base,event:'dot'},base),[{targetId:'target',family:'poison'}]);
console.log('PASS: 16 families, success-only status delta, miss/phase/start exclusion, range and damage classification');
