const fs=require('fs'),ts=require('typescript'),assert=require('assert/strict');
require.extensions['.ts']=(m,f)=>m._compile(ts.transpileModule(fs.readFileSync(f,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,esModuleInterop:true}}).outputText,f);
const {simulateBattle}=require('../src/domain/redesign/battle.ts'),{createInitialState,buildBattleParty,EQUIPMENT_MASTERS}=require('../src/domain/redesign/masters.ts'),{FORMAL_QUEST_STAGES,createQuestBattleInput}=require('../src/domain/redesign/questMaster.ts'),{getFormalOwnedSkill}=require('../src/domain/redesign/formalOwnedSkills.ts');
const saved=require('../docs/verification/device-debug/b10/047-input.json'),stage=FORMAL_QUEST_STAGES.find(s=>s.id==='mino-1');
const stable=x=>x===null||typeof x!=='object'?JSON.stringify(x):Array.isArray(x)?'['+x.map(stable).join(',')+']':'{'+Object.keys(x).sort().map(k=>JSON.stringify(k)+':'+stable(x[k])).join(',')+'}';
const digest=x=>{let h=2166136261;for(const c of stable(x))h=Math.imul(h^c.charCodeAt(0),16777619)>>>0;return h;};
const replay=simulateBattle(saved.input);assert.equal(digest(JSON.parse(JSON.stringify(replay))),saved.expected.fnv1aStable,'entire saved result must reproduce');assert.deepEqual(stage,saved.input.questSnapshot,'formal enemy and stage master match saved input');
const hits=replay.frames.filter(f=>f.event==='damage'&&saved.input.party.some(p=>p.id===f.actorId)).flatMap(f=>f.hits??[]);
const ids=['SKD034','SKD038','SKD010','SKD009','SKD039'],rows=[];
const seeds=[saved.input.seed,...Array.from({length:19},(_,i)=>Math.imul(i+1,2654435761)>>>0)];
function trial(label,party,conditions){const runs=seeds.map(seed=>{const r=simulateBattle({...saved.input,seed,party});return {seed,outcome:r.outcome,actions:r.playerActions,waves:r.wavesCleared,damage:r.totalDamage};});rows.push({label,conditions,party,runs,wins:runs.filter(r=>r.outcome==='win').length});}
trial('saved-input',saved.input.party,{source:'saved battle'});
trial('saved-stats-guide-skills',saved.input.party.map((p,i)=>({...p,skills:[getFormalOwnedSkill(ids[i],0)]})),{stats:'unchanged saved stats',skills:ids,lb:0});
for(const level of [20,25,30,35,40])for(const gearLevel of [0,20]){const state=createInitialState('offline');state.characters=saved.input.party.map(p=>({id:p.id,level,awakening:0,exp:0}));state.skills=ids.map(id=>({id,level:0}));state.equipment=[];state.deck=state.characters.map((c,i)=>({characterId:c.id,skillIds:[ids[i]],equipment:{}}));if(gearLevel){for(let i=0;i<5;i++)for(const [slot,id] of Object.entries({weapon:'WEAPON_001',head:'HEAD_001',body:'BODY_001',legs:'LEGS_001',accessory1:'ACCESSORY_001',accessory2:'ACCESSORY_001'})){assert(EQUIPMENT_MASTERS.some(e=>e.id===id));const instanceId=`qa-${i}-${slot}`;state.equipment.push({instanceId,masterId:id,level:gearLevel,lb:0});state.deck[i].equipment[slot]=instanceId;}}
trial(`Lv${level}-gear${gearLevel}`,buildBattleParty(state,saved.input.rules),{level,awakening:0,skillIds:ids,skillLb:0,equipment:state.equipment,order:state.deck.map(d=>d.characterId)});}
fs.writeFileSync('docs/verification/device-debug/b10/047-report.json',JSON.stringify({savedReproduced:true,masterIdentical:true,hitCount:hits.length,allHitsOne:hits.every(h=>h===1),burstStarts:replay.frames.filter(f=>f.event==='burst_start').length,seeds,rows},null,2));console.log(JSON.stringify({reproduced:true,hits:hits.length,allOne:hits.every(h=>h===1),rows:rows.map(r=>({label:r.label,wins:r.wins,minActions:Math.min(...r.runs.map(x=>x.actions)),maxActions:Math.max(...r.runs.map(x=>x.actions))}))},null,2));

