const fs=require('fs'),assert=require('assert/strict'),{chromium}=require('playwright');const base=process.env.BASE_URL||'http://localhost:3013',out=process.env.QA_OUT||'../../outputs/additional29';fs.mkdirSync(out,{recursive:true});
(async()=>{const b=await chromium.launch();const report=[];try{for(const width of [375,390]){const p=await b.newPage({viewport:{width,height:600},reducedMotion:'reduce'});p.setDefaultTimeout(60000);const errors=[];p.on('pageerror',e=>errors.push(e.message));
for(const kind of ['starter','daily-free']){await p.goto(base+'/qa/additional29?kind='+kind);await p.getByRole('dialog').waitFor();await p.getByRole('dialog').locator('img').evaluateAll(imgs=>Promise.all(imgs.map(i=>i.decode())));assert.equal(await p.getByRole('dialog').evaluate(e=>{const r=e.getBoundingClientRect();return r.left>=0&&r.right<=innerWidth&&r.bottom<=innerHeight}),true);await p.screenshot({path:`${out}/${kind}-${width}.png`});await p.getByRole('button',{name:kind==='starter'?'パックを見る':'召喚する',exact:true}).click();await p.getByRole('status').filter({hasText:kind==='starter'?'shop:beginner_pack_01':'gacha'}).waitFor();assert.equal(await p.getByRole('dialog').count(),0);}
assert(await p.getByText('所持品に入りました。',{exact:true}).isVisible());assert(await p.getByText('プレゼントBOXへ',{exact:true}).isVisible());await p.screenshot({path:`${out}/receipts-${width}.png`});
if(!process.env.SKIP_ALL_ASSET_FIXTURE){await p.goto(base+'/qa/common-ui-audit?view=character');await p.getByRole('button',{name:'スキル',exact:true}).click();await ready(p);assert(await p.locator('.g4-asset-list').count());await p.screenshot({path:`${out}/skills-${width}.png`});
await p.getByRole('button',{name:'装備',exact:true}).first().click();await ready(p);await p.screenshot({path:`${out}/equipment-${width}.png`});assert(await p.locator('.g4-asset-list').count());
await p.getByRole('button',{name:'編成',exact:true}).click();await ready(p);await p.screenshot({path:`${out}/formation-${width}.png`});await p.locator('.g4g-formation-help').scrollIntoViewIfNeeded();await p.locator('.g4g-grid').scrollIntoViewIfNeeded();await p.waitForTimeout(200);assert.equal(await p.locator('.g4-candidate-hint').count(),0);
}
await p.goto(base+'/qa/shop-ui');await p.locator('.g4-product-row').first().waitFor();assert.equal(await p.locator('.g4-product-row h3').first().innerText(),'VIPパス');await p.screenshot({path:`${out}/shop-${width}.png`});assert(!await p.locator('body').innerText().then(t=>t.includes('無償0個')));
await p.goto(base+'/qa/formal-names?mode=inventory');await p.getByRole('region',{name:'所持品',exact:true}).waitFor();await p.screenshot({path:`${out}/inventory-${width}.png`});
assert.deepEqual(errors,[]);report.push({width,height:600,errors,promotions:true,directRoute:true,mixedReceipt:true,compactLists:!process.env.SKIP_ALL_ASSET_FIXTURE,vipFirst:true,formationHintStops:!process.env.SKIP_ALL_ASSET_FIXTURE});await p.close();}fs.writeFileSync(out+'/browser.json',JSON.stringify(report,null,2));console.log(report);}finally{await b.close();}})().catch(e=>{console.error(e);process.exitCode=1});

async function ready(p){for(let i=0;i<3;i++){await p.waitForFunction(()=>document.querySelector('.g4-growth')?.getAttribute('aria-busy')==='false'||document.querySelector('.g4-growth [role=alert]'));if(await p.locator('.g4-growth').getAttribute('aria-busy')==='false')return;await p.getByRole('button',{name:'再読み込み',exact:true}).click();await p.waitForTimeout(13000);}await p.waitForFunction(()=>document.querySelector('.g4-growth')?.getAttribute('aria-busy')==='false');}