const fs=require('fs'),ts=require('typescript'),Module=require('module'),path=require('path'),assert=require('assert/strict');
const compile=s=>ts.transpileModule(s,{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,esModuleInterop:true}}).outputText;
require.extensions['.ts']=(m,f)=>m._compile(compile(fs.readFileSync(f,'utf8')),f);
const {simulateBattle}=require('../src/domain/redesign/battle.ts'),{projectRecordedBattleFrame:project}=require('../src/domain/presentation/recordedBattlePresentation.ts'),{recordedBattleSounds:sounds}=require('../src/audio/recordedBattleSound.ts');
const engine=path.resolve('src/domain/redesign/battleBalanceV2.ts'),source=fs.readFileSync(engine,'utf8'),out='docs/verification/device-debug/dbg035';fs.mkdirSync(out,{recursive:true});
function atBoundary(input,sp=0){const m=new Module(engine,module);m.filename=engine;m.paths=module.paths;const injected=source.replace('let partySp = 0, gauge = 0,','let partySp = '+sp+', gauge = 200,');assert.notEqual(injected,source);m._compile(compile(injected),engine);return m.exports.simulateBalanceBattle(input);}
const original=JSON.parse(fs.readFileSync('docs/verification/device-debug/b05/usable.json')).input;
function input(){const x=structuredClone(original);x.seed=7;x.rules.burstPolicy='attack-free-v1-20260926';return x;}
const attack=(id,cost=1000,condition={type:'always'})=>({...original.party[0].skills[0],id,name:id,spCost:cost,condition});
function episodes(r){const list=[];let e;for(const f of r.frames){if(f.event==='burst_start'){e={start:f.index,actor:f.actorId,sp:f.partySp,actions:[],events:[]};list.push(e);}if(e){e.events.push(f.event);assert.equal(f.partySp,e.sp);assert.equal(f.burstGauge,0);if(f.event==='action_start'&&f.actorId===e.actor){assert.notEqual(f.skillId,'basic');e.actions.push(f.skillId);assert.equal(f.skillStates[e.actor].find(s=>s.skillId===f.skillId).cost,0);}if(f.event==='burst_end'){assert(e.actions.length<=5);e.end=f.index;e=null;}}assert.equal(project(r,f.index).cutIn==='burst',f.event==='burst_start');assert.equal(sounds(r,f.index).includes('BATTLE_BURST'),f.event==='burst_start');}return list;}
const report=[];function run(name,setup,check,sp=0){const x=input();setup(x);const r=atBoundary(x,sp),es=episodes(r);assert.equal(es[0].start,1,'boundary fixture must start immediately');assert.equal(es[0].sp,sp);check(r,es);report.push({name,episodes:es});if(name==='zero-sp')fs.writeFileSync(out+'/new-battle.json',JSON.stringify({...r,frames:r.frames.slice(0,es[0].end+3)}));return r;}
run('zero-sp',x=>x.party[0].skills=[attack('expensive')],(r,e)=>assert.deepEqual(e[0].actions,Array(5).fill('expensive')));
run('insufficient-sp',x=>x.party[0].skills=[attack('expensive')],(r,e)=>assert.equal(e[0].actions.length,5),1);
run('slot-condition',x=>x.party[0].skills=[attack('alternating',1000,{type:'every_n_actions',value:2}),attack('fallback')],(r,e)=>assert.deepEqual(e[0].actions,['fallback','alternating','fallback','alternating','fallback']));
run('condition-disappears',x=>{x.party[0].skills=[attack('once',1000,{type:'enemy_count',value:2})];const other=structuredClone(x.waves[0][0]);other.id='second';x.waves[0][0].stats.hp=1;x.waves[0].push(other);},(r,e)=>{assert.equal(e[0].actions.length,1);assert(e[0].events.includes('burst_interrupted'));});
run('attached-buff',x=>{x.party[0].skills=[attack('hybrid')];x.party[0].skills[0].effects.push({type:'atk_up',power:10,duration:3,target:'self'});},(r,e)=>{assert.equal(e[0].actions.length,5);assert(r.frames.slice(e[0].start,e[0].end).some(f=>f.event==='effect_applied'));});
run('target-reevaluation',x=>{x.party[0].skills=[attack('hit')];const other=structuredClone(x.waves[0][0]);other.id='second';x.waves[0][0].stats.hp=1;x.waves[0].push(other);},(r,e)=>{const targets=r.frames.slice(e[0].start,e[0].end).filter(f=>f.event==='damage').map(f=>f.targetIds[0]);assert.deepEqual(targets,['qa-enemy','second','second','second','second']);});
run('wave-end',x=>{x.party[0].skills=[attack('hit')];x.waves[0][0].stats.hp=1;x.waves.push(structuredClone(x.waves[0]));},(r,e)=>{assert.equal(e[0].actions.length,1);assert(r.frames[e[0].end+1].event==='wave');});
run('enemy-defeated-boundary',x=>{x.party[0].skills=[attack('hit')];x.waves[0][0].stats.hp=1;},(r,e)=>{assert.equal(e[0].actions.length,1);assert.equal(r.outcome,'win');});
run('death-boundary',x=>{x.party[0].skills=[attack('hit')];x.waves[0][0].initialCount=1;x.waves[0][0].stats.atk=100000;},(r,e)=>{assert.equal(e[0].actions.length,1);assert.equal(r.outcome,'lose');});
run('stun-boundary',x=>{x.party[0].skills=[attack('hit')];const enemy=x.waves[0][0];enemy.initialCount=1;enemy.initialSp=100;enemy.skills=[{...attack('stun',100),effects:[{type:'stun',power:0,chance:1}]}];},(r,e)=>{assert.equal(e[0].actions.length,1);assert(e[0].events.includes('stun_skip'));});
for(const name of ['area1-assist']){const x=JSON.parse(fs.readFileSync(`docs/verification/device-debug/b05/${name}.json`)).input;x.rules.burstPolicy='attack-free-v1-20260926';const r=simulateBattle(x);report.push({name,episodes:episodes(r)});}
// Old snapshots keep their original calculations exactly, including half-SP/basic fallback.
for(const name of ['usable','sp-shortage','mixed','actor-death','enemy-defeated','stunned']){const f=JSON.parse(fs.readFileSync(`docs/verification/device-debug/b05/${name}.json`)),r=simulateBattle(f.input);const acts=[];let e;for(const fr of r.frames){if(fr.event==='burst_start'){e=[];acts.push(e);}if(e&&fr.event==='action_start'&&fr.actorId==='qa-actor')e.push(fr.skillId);if(fr.event==='burst_end')e=null;}assert.deepEqual(acts,f.result.episodes.map(e=>e.actions.map(a=>a.skill)));}
const {BATTLE_RULES,createInitialState}=require('../src/domain/redesign/masters.ts'),{createQuestBattleInput}=require('../src/domain/redesign/questMaster.ts'),{getQuestStage}=require('../src/domain/redesign/quests.ts');
for(let n=1;n<=5;n++){const saved=JSON.parse(fs.readFileSync('docs/verification/device-debug/b05/saved-qa-stage'+n+'.json'));const rules={...BATTLE_RULES};delete rules.burstPolicy;const x=createQuestBattleInput(saved.seed,saved.party,getQuestStage('mikawa-'+n),rules);assert.deepEqual(JSON.parse(JSON.stringify(simulateBattle(x).frames)),saved.frames);}
const {createTutorialBattle}=require('../src/domain/redesign/tutorial/battle.ts');const tutorial=createTutorialBattle(createInitialState('dbg035-test'));const starts=tutorial.frames.filter(f=>f.event==='burst_start');assert.equal(starts.length,1);const tb=tutorial.frames.filter(f=>f.burst);assert(tb.every(f=>f.partySp===starts[0].partySp&&f.burstGauge===0));
report.push({name:'old-saved-five-battles-and-tutorial',exactOldFrames:true,tutorialFreeSp:true,episodes:[]});
fs.writeFileSync(out+'/regression.json',JSON.stringify(report,null,2));console.log('PASS DBG-035',report.map(r=>({name:r.name,bursts:r.episodes.length,first:r.episodes[0]?.actions})));

