// Offline UI verification: production TerritoryView and shell, formal master projection; no API/DB writes.
const assert=require('node:assert/strict');const fs=require('node:fs');const {spawn}=require('node:child_process');const {chromium}=require('playwright');
const out='docs/verification/invasion-20260924';
const ts=require('typescript');require.extensions['.ts']=(m,f)=>m._compile(ts.transpileModule(fs.readFileSync(f,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,esModuleInterop:true}}).outputText,f);
const {createFormalInvasionMaster}=require('../src/domain/redesign/raidInvasionMaster.ts');const {getTerritoryPreviewStages,territoryEnemyArt}=require('../src/domain/redesign/territoryPresentation.ts');const oracle=getTerritoryPreviewStages(createFormalInvasionMaster('TI01',()=>0));
(async()=>{fs.mkdirSync(out,{recursive:true});let server;let browser;const base=process.env.INVASION_PREVIEW_URL||'http://127.0.0.1:3106';const results=[];
try{if(!process.env.INVASION_PREVIEW_URL){server=spawn(process.execPath,['node_modules/next/dist/bin/next','dev','--webpack','--hostname','127.0.0.1','--port','3106'],{env:{...process.env,VERCEL_ENV:'preview',NEXT_PUBLIC_APP_ENV:'development',NEXT_PUBLIC_ENABLE_QA_TOOLS:'true'},stdio:['ignore','pipe','pipe']});await new Promise((resolve,reject)=>{const timer=setTimeout(()=>reject(Error('server timeout')),60000);server.stdout.on('data',d=>{if(String(d).includes('Ready')){clearTimeout(timer);resolve();}});server.stderr.on('data',d=>process.stderr.write(d));server.on('exit',c=>{clearTimeout(timer);reject(Error('server exited '+c));});});}
browser=await chromium.launch({executablePath:process.env.INVASION_BROWSER_EXECUTABLE||'/tmp/game04-browser/chrome-headless-shell-linux64/chrome-headless-shell',args:['--no-sandbox']});const page=await browser.newPage({viewport:{width:390,height:844}});const errors=[];page.on('pageerror',e=>errors.push(e.message));
async function images(){await page.locator('.rd-shell img,[role=dialog] img').evaluateAll(async imgs=>{await Promise.all(imgs.map(img=>img.decode().catch(()=>{})));});const broken=await page.locator('.rd-shell img,[role=dialog] img').evaluateAll(imgs=>imgs.filter(i=>!i.complete||!i.naturalWidth).map(i=>i.getAttribute('src')));assert.deepEqual(broken,[]);await page.waitForTimeout(240);}
async function open(scenario='ready'){await page.goto(base+'/qa/invasion-approved?scenario='+scenario,{waitUntil:'networkidle',timeout:120000});await page.getByRole('heading',{name:'領土侵攻',exact:true}).waitFor();await images();}
async function geometry(){return page.locator('.rd-shell').evaluate(e=>({width:e.clientWidth,scrollWidth:e.scrollWidth,headerTop:e.querySelector('.rd-header').getBoundingClientRect().top,footerBottom:e.querySelector('.rd-footer').getBoundingClientRect().bottom,viewport:innerHeight}));}
await open();assert.deepEqual(await page.locator('.rd-footer button').allTextContents(),['本陣','出陣','武将','共闘','召喚']);results.push({check:'initial',geometry:await geometry()});await page.screenshot({path:out+'/list-390.png'});
// Remaining selectors are kept semantic so the test follows the real user controls.
await page.getByRole('button',{name:/詳細/}).first().click();await images();await page.screenshot({path:out+'/detail-390.png'});
const stages=page.getByRole('button',{name:/^(開始|中間|最終)/});assert.equal(await stages.count(),3);
for(let i=0;i<3;i++){await stages.nth(i).click();await images();const expected=oracle[i];assert.equal(await stages.nth(i).getAttribute('aria-pressed'),'true');assert.deepEqual(await page.locator('.inv-stats dd').allTextContents(),['hp','atk','def'].map(key=>expected.enemy.stats[key].toLocaleString()));assert.match(await page.locator('.inv-enemy-info h3').innerText(),new RegExp(expected.enemy.name));assert.match(await page.locator('.inv-enemy-info h3').innerText(),new RegExp('敵Lv\\.'+expected.enemy.level));assert.equal(await page.locator('.inv-enemy-info > .inv-art > img').getAttribute('src'),territoryEnemyArt(expected.enemy,'portrait'));results.push({check:'stage '+i,level:expected.enemy.level,stats:expected.enemy.stats,pass:true});}
await stages.first().click();await page.getByRole('button',{name:'侵攻する',exact:true}).click();const dialog=page.getByRole('dialog',{name:'侵攻確認'});await dialog.waitFor();assert.equal(await page.locator('.rd-shell').evaluate(e=>e.inert),true);await images();await page.screenshot({path:out+'/confirm-390.png'});await dialog.getByRole('button',{name:'キャンセル',exact:true}).click();assert.equal(await page.getByTestId('fixture-state').getAttribute('data-calls'),'0');assert.equal(await page.locator('.rd-shell').evaluate(e=>e.inert),false);
await page.setViewportSize({width:390,height:568});await page.locator('.rd-shell').evaluate(e=>e.scrollTop=0);await images();await page.screenshot({path:out+'/detail-low-390.png'});await page.getByRole('button',{name:'侵攻する',exact:true}).click();await dialog.waitFor();const bounds=await dialog.boundingBox();assert.ok(bounds.y>=0&&bounds.y+bounds.height<=568);await page.screenshot({path:out+'/confirm-low-390.png'});await dialog.getByRole('button',{name:'キャンセル',exact:true}).click();
await open();await page.screenshot({path:out+'/list-low-390.png'});await open('insufficient');await page.getByRole('button',{name:/詳細/}).first().click();assert.equal(await page.getByRole('button',{name:'侵攻する',exact:true}).isDisabled(),true);results.push({check:'zero item still enters detail',pass:true});
await open('low-level');await page.getByRole('button',{name:/詳細/}).nth(1).click();assert.equal(await page.getByRole('button',{name:'侵攻する',exact:true}).isDisabled(),true);results.push({check:'low level still enters detail; hosting disabled',pass:true});await open('failure');await page.getByRole('button',{name:/詳細/}).first().click();await page.getByRole('button',{name:'侵攻する',exact:true}).click();await dialog.getByRole('button',{name:'侵攻する',exact:true}).click();await page.getByRole('alert').waitFor();assert.equal(await page.getByTestId('fixture-state').getAttribute('data-owned'),'3');results.push({check:'failed fixture request does not consume',pass:true});
await open();await page.getByRole('button',{name:/詳細/}).first().click();await page.getByRole('button',{name:'侵攻する',exact:true}).click();await dialog.getByRole('button',{name:'侵攻する',exact:true}).evaluate(b=>{b.click();b.click();});await page.waitForFunction(()=>document.querySelector('[data-testid="fixture-state"]').dataset.room==='fixture-hosted');assert.equal(await page.getByTestId('fixture-state').getAttribute('data-calls'),'1');assert.equal(await page.getByTestId('fixture-state').getAttribute('data-owned'),'2');results.push({check:'double click runs once and opens existing RaidView',pass:true});
await open('multiple');const resume=page.getByRole('button',{name:/攻略を再開/});assert.equal(await resume.count(),2);await resume.nth(1).click();assert.equal(await page.getByTestId('fixture-state').getAttribute('data-room'),'fixture-room-1');results.push({check:'multiple room resumes correct ID',pass:true});
await open('ended');assert.equal(await page.getByRole('button',{name:/攻略を再開/}).count(),0);assert.match(await page.locator('.inv-progress').innerText(),/0 \/ 1/);await page.getByText('終了した侵攻',{exact:false}).click();await page.getByRole('button',{name:/結果・報酬を確認/}).first().click();assert.equal(await page.getByTestId('fixture-state').getAttribute('data-room'),'fixture-room-0');results.push({check:'ended room frees slot and opens existing result path',pass:true});assert.deepEqual(errors,[]);fs.writeFileSync(out+'/browser-results.json',JSON.stringify({scope:'Offline fixture of production components, not real API or persistence acceptance',url:base,results,errors},null,2));console.log('PASS',results.map(x=>x.check));
}finally{await browser?.close();server?.kill();}})().catch(e=>{console.error(e);process.exit(1)});
