// Saved start context must stay distinct from a later room stage/current HP.
const assert = require('node:assert/strict');
const fs = require('node:fs');
const ts = require('typescript');
const path = require('node:path');
const Module = require('node:module');
const resolve = Module._resolveFilename;
Module._resolveFilename = function(name, parent, ...rest) { return resolve.call(this, name.startsWith('@/') ? path.resolve(__dirname, '../src', name.slice(2)) : name, parent, ...rest); };
require.extensions['.ts'] = (module, filename) => module._compile(ts.transpileModule(fs.readFileSync(filename, 'utf8'), { compilerOptions: { module: ts.ModuleKind.CommonJS, target: ts.ScriptTarget.ES2022, esModuleInterop: true } }).outputText, filename);
const {projectRaidBattleHp} = require('../src/domain/presentation/raidBattleHpPresentation.ts');
const start = {roomId:'own-room',level:2,hp:22287,maxHp:54000};
const saved = JSON.parse(JSON.stringify(start));
const after = {current:90000,max:90000,level:3};
assert.deepEqual(projectRaidBattleHp(saved,after),{current:22287,max:54000,label:'開始時の共通HP（Lv.2）'});
assert.deepEqual(projectRaidBattleHp(saved,undefined),projectRaidBattleHp(saved,after));
after.current = 80000;
assert.equal(projectRaidBattleHp(saved,after).current,22287);
assert.equal(projectRaidBattleHp(undefined,after).label,'現在の共通HP（Lv.3）');
assert.equal(projectRaidBattleHp(undefined,after).current,80000);
assert.equal(projectRaidBattleHp(undefined,undefined),undefined);
assert.deepEqual(start,saved);
const {simulateBattle} = require('../src/domain/redesign/battle.ts');
const {commonBattleFixture} = require('../src/app/qa/battle-common/fixture.ts');
const input = commonBattleFixture('six-waves');
const original = simulateBattle(input);
const withContext = simulateBattle({...input, raidStartSnapshot:saved});
assert.deepEqual(withContext,original,'display context must not change frames, damage, SP, waves or outcomes');
assert.equal(original.raidStartSnapshot,undefined,'engine does not fabricate start metadata on old inputs');
console.log('PASS: persisted start survives reload, stage advancement and current-room refresh; old snapshot/current fallback and quest absence retained.');
