import fs from'node:fs';import zlib from'node:zlib';import assert from'node:assert/strict';import{FORMAL_QUEST_STAGES as STAGES}from'../src/domain/redesign/questMaster.ts';import{buildBattleParty}from'../src/domain/redesign/masters.ts';import{validateDeck}from'../src/domain/redesign/growth.ts';import{hash,costs}from'./audit_stage68.mjs';import{OUT,save,inputFor}from'./rebuild_stage68_five_tier.mjs';import{mechanics}from'./stage68_five_tier_mechanics.mjs';
const rows=JSON.parse(fs.readFileSync(OUT+'/audit-table.json')),econ=JSON.parse(fs.readFileSync(OUT+'/economy-proposal.json'));assert.equal(rows.length,68);let recipeCount=0,trials=0,fields=0;const checks=[];
for(let i=0;i<68;i++){const s=STAGES[i],row=rows[i],d=JSON.parse(zlib.gunzipSync(fs.readFileSync(OUT+'/'+s.designId+'-validated.json.gz')));assert.equal(row.stage,s.designId);assert.equal(d.stageOriginal.id,s.id);assert.deepEqual(d.stageOriginal,s);const restored=structuredClone(d.stageProposal);for(let wi=0;wi<s.waves.length;wi++)for(let ei=0;ei<s.waves[wi].length;ei++)for(const k of ['hp','atk','def']){if(restored.waves[wi][ei].stats[k]!==s.waves[wi][ei].stats[k])fields++;restored.waves[wi][ei].stats[k]=s.waves[wi][ei].stats[k];}assert.deepEqual(restored,s,'non-approved-field modification '+s.designId);
 for(const c of d.records){validateDeck(c.state,c.state.deck);assert.deepEqual(c.input.party,buildBattleParty(c.state));assert.equal(c.inputHash,hash(c.input));assert.deepEqual(c.input,inputFor(d.stageProposal,{party:c.input.party}));assert.deepEqual(c.costs,costs(c.state));const v=c.validation;assert.equal(v.n,v.runs.length);assert.equal(new Set(v.runs.map(r=>r.seed)).size,v.n);assert.equal(v.wins,v.runs.filter(r=>r.outcome==='win').length);assert.equal(v.rate,v.wins/v.n);assert(v.n>=200);recipeCount++;trials+=v.n;}
 const primary=d.records.find(c=>c.name===row.primary.name);assert.equal(primary.validation.wins,primary.validation.n);assert(mechanics(primary,primary.validation));if(i>=10){assert(row.alternative);const alt=d.records.find(c=>c.name===row.alternative.name);assert(alt.validation.rate>=.6);assert.notEqual(alt.family,primary.family);assert(mechanics(alt,alt.validation));for(const card of row.dependency)assert(card.alternatives.some(a=>a.wins/a.n>=.3),'card fallback '+row.stage+'/'+card.skill);}
 for(const name of [row.primary.name,row.alternative?.name].filter(Boolean)){const c=d.records.find(c=>c.name===name),e=econ.rows[i];for(const sk of c.state.skills)assert(e.trainedSkills.some(t=>t.id===sk.id&&t.level>=sk.level),'unfunded skill '+row.stage+'/'+sk.id);const needed={};for(const item of c.state.equipment)needed[item.masterId]=(needed[item.masterId]??0)+1;for(const [id,n]of Object.entries(needed))assert(e.trainedEquipment.filter(t=>t.masterId===id&&t.level>=c.state.equipment.find(x=>x.masterId===id).level).length>=n);}
 checks.push({stage:s.designId,recipeCount:d.records.length,primaryWins:primary.validation.wins,n:primary.validation.n,differentMechanism:i<10?'early exemption':true,originalMasterMatch:true,onlyEnemyHpAtkDefChanged:true,primaryAndAlternateFunded:true});}
for(const r of econ.rewardAdditions){const at=STAGES.findIndex(s=>s.designId===r.beforeStage);assert(at>0);assert.equal(r.stageId,STAGES[at-1].id);assert(r.rewards.every(r=>r.amount>0&&r.kind!=='free_diamonds'));}
const table=fs.readFileSync(OUT+'/AUDIT_TABLE.md','utf8').split('\n').filter(l=>l.startsWith('|'));assert.equal(table.length,70);const width=table[0].split('|').length;assert(table.every(l=>l.split('|').length===width),'markdown columns');save('artifact-checks.json',{stages:68,recipes:recipeCount,finalSelectedTrials:trials,changedEnemyFields:fields,checks});console.log('artifact checks',68,recipeCount,trials,fields);
