import assert from 'node:assert/strict';
import { createInitialState, CHARACTER_MASTERS, SKILL_MASTERS, EQUIPMENT_MASTERS, grantReward } from '../src/domain/redesign/masters';
import { applyAcquisitionEvents, PREVIEW_ACQUISITION_MASTER, type AcquisitionEvent, type AcquisitionState } from '../src/domain/redesign/acquisitions';
const initial=createInitialState('qa');
const character=initial.characters[0].id,skill=initial.skills[0].id,equipment=EQUIPMENT_MASTERS[0].id;
const events:AcquisitionEvent[]=[{id:'draw:1',kind:'character',masterId:character},{id:'draw:2',kind:'character',masterId:character},{id:'draw:3',kind:'skill',masterId:skill},{id:'equip:1',kind:'equipment',masterId:equipment,instanceId:'e1'},{id:'equip:2',kind:'equipment',masterId:equipment,instanceId:'e2'}];
const granted=applyAcquisitionEvents(initial,events,PREVIEW_ACQUISITION_MASTER);
assert.equal(granted.souls[character],20);assert.equal(granted.materials.skill,initial.materials.skill+2);assert.equal(granted.equipment.length,2);assert.deepEqual(applyAcquisitionEvents(granted,events,PREVIEW_ACQUISITION_MASTER),granted);assert.equal(initial.souls[character],undefined);
const cap=structuredClone(initial);cap.characters[0].awakening=5;cap.skills[0].level=10;
const pending=applyAcquisitionEvents(cap,events.slice(0,3),PREVIEW_ACQUISITION_MASTER);assert.equal(pending.pendingAcquisitions?.length,3);assert.equal(pending.appliedAcquisitionIds?.length,0);
const resumed=applyAcquisitionEvents(pending,[],{...PREVIEW_ACQUISITION_MASTER,characterAtCap:'convert',skillAtCap:'convert'});assert.equal(resumed.pendingAcquisitions?.length,0);assert.equal(resumed.souls[character],20);assert.equal(resumed.materials.skill,initial.materials.skill+2);
const freshCharacter=CHARACTER_MASTERS.find(c=>!initial.characters.some(o=>o.id===c.id))!;
const freshSkill=SKILL_MASTERS.find(c=>!initial.skills.some(o=>o.id===c.id))!;
let rewards=grantReward(initial,{kind:'character',id:freshCharacter.id,amount:2},'quest:character');
rewards=grantReward(rewards,{kind:'skill',id:freshSkill.id,amount:2},'quest:skill');
assert.equal(rewards.characters.find(c=>c.id===freshCharacter.id)?.awakening,0);assert.equal(rewards.souls[freshCharacter.id],10);assert.equal(rewards.skills.find(s=>s.id===freshSkill.id)?.level,0);
assert.deepEqual(grantReward(rewards,{kind:'character',id:freshCharacter.id,amount:2},'quest:character'),rewards);
const absent=applyAcquisitionEvents(initial,[{id:'exclusive:1',kind:'skill',masterId:'unknown_exclusive'}],PREVIEW_ACQUISITION_MASTER);assert.equal(absent.pendingAcquisitions?.[0].reason,'master_missing');
const directPending=grantReward(cap,{kind:'character',id:character,amount:1},'mission:cap') as AcquisitionState;assert.equal(directPending.pendingAcquisitions?.length,1);
assert.equal(applyAcquisitionEvents(directPending,[],{...PREVIEW_ACQUISITION_MASTER,characterAtCap:'convert'}).souls[character],10);
console.log('PASS: distinct asset semantics, replay, immutable input, cap pending/replay, unknown master pending, direct reward IDs, circular module initialization');

const overlap=structuredClone(initial);overlap.legacyImportedIds=['character:legacy-c'];
const overlapDone=applyAcquisitionEvents(overlap,[{id:'asset:character:legacy-c',kind:'character',masterId:character,legacyId:'legacy-c'}],PREVIEW_ACQUISITION_MASTER);
assert.equal(overlapDone.souls[character],undefined);assert.ok(overlapDone.appliedAcquisitionIds?.includes('asset:character:legacy-c'));
const eq=grantReward(initial,{kind:'equipment',id:equipment,amount:2},'reward:e');assert.deepEqual(eq.equipment.map(e=>e.instanceId),['reward:e:0','reward:e:1']);
assert.deepEqual(grantReward(eq,{kind:'equipment',id:equipment,amount:2},'reward:e'),eq);
assert.equal((grantReward(initial,{kind:'equipment',id:'missing',amount:1},'missing:e') as AcquisitionState).pendingAcquisitions?.length,1);
assert.throws(()=>grantReward(initial,{kind:'cash',amount:NaN}));assert.throws(()=>grantReward(initial,{kind:'cash',amount:-1}));
console.log('PASS: deployment overlap import/event dedupe, equipment instance compatibility, missing Master preservation, invalid quantities rejected');
