const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),Module=require('node:module'),ts=require('typescript');
const resolve=Module._resolveFilename;Module._resolveFilename=function(n,p,...r){return resolve.call(this,n.startsWith('@/')?path.resolve(__dirname,'../src',n.slice(2)):n,p,...r)};
require.extensions['.ts']=(m,f)=>m._compile(ts.transpileModule(fs.readFileSync(f,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,esModuleInterop:true}}).outputText,f);
const {createInitialState,buildBattleParty,BATTLE_RULES}=require('../src/domain/redesign/masters.ts');
const {recordMissionEvent}=require('../src/domain/redesign/missionProgress.ts');
const {FORMAL_MISSION_CONFIG}=require('../src/domain/redesign/formalMissions.ts');
const {evaluateMissions,getClaimableMission}=require('../src/domain/redesign/missions.ts');
const {createFormalInvasionMaster}=require('../src/domain/redesign/raidInvasionMaster.ts');
const {applyRaidAction}=require('../src/domain/redesign/raid.ts');
const {simulateBattle}=require('../src/domain/redesign/battle.ts');
const {createFormalBattleInput}=require('../src/domain/redesign/formalBattleInput.ts');
const before=Date.parse('2026-09-25T14:59:59.999Z'),after=before+1;
let s=createInitialState('rules-qa');
// Saved current-day progress stays valid; previous-day unclaimed rewards expire.
s=recordMissionEvent(s,{id:'old',counters:['quest_clear','battle'],at:before});
assert.equal(evaluateMissions(s,FORMAL_MISSION_CONFIG,before).find(x=>x.id==='DM004:2026-09-25').status,'claimable');
for(let n=0;n<3;n++)s=recordMissionEvent(s,{id:`win-${n}`,counters:['quest_clear','battle'],at:before});
const row=getClaimableMission(s,FORMAL_MISSION_CONFIG,'DM005:2026-09-25',before);assert.equal(row.rewards.find(r=>r.kind==='unlock_item').amount,1);
assert(!getClaimableMission(s,FORMAL_MISSION_CONFIG,'DM004:2026-09-25',before).rewards.some(r=>r.kind==='unlock_item'));
const snapshot=structuredClone(s);assert.throws(()=>getClaimableMission(s,FORMAL_MISSION_CONFIG,'DM005:2026-09-25',after));assert.deepEqual(s,snapshot);
s.claimedMissionIds=['DM005:2026-09-25'];assert.throws(()=>getClaimableMission(s,FORMAL_MISSION_CONFIG,'DM005:2026-09-25',before));
s=recordMissionEvent(s,{id:'cross-midnight-result',counters:['quest_clear','battle'],at:after});assert.equal(s.missionProgress.daily['2026-09-26'].quest_clear,1);
assert.deepEqual(recordMissionEvent(s,{id:'cross-midnight-result',counters:['quest_clear','battle'],at:after+86400000}),s);
assert.equal(evaluateMissions(s,FORMAL_MISSION_CONFIG,after).find(x=>x.id==='DM005:2026-09-26').status,'progress');
// Completion bonuses count only the eight basic objectives (not each other).
for(let n=0;n<5;n++)s=recordMissionEvent(s,{id:`all-${n}`,counters:['battle','quest_clear','growth','normal_gacha'],at:after});
assert.equal(evaluateMissions(s,FORMAL_MISSION_CONFIG,after).find(x=>x.id==='DM010:2026-09-26').status,'claimable');
const master=createFormalInvasionMaster('TI01',()=>0);assert.equal(master.damagePolicy,'actual-hp-v1-20260925');
const unit=buildBattleParty(s)[0];unit.skills=[];unit.stats.atk=10000000;unit.stats.hp=100000;const enemy=structuredClone(master.enemy);enemy.stats.hp=100;enemy.stats.def=0;enemy.passives=[];enemy.skills=[];
const input=createFormalBattleInput(42,[unit],[[enemy]],BATTLE_RULES),old=simulateBattle(input),actual=simulateBattle({...input,raidDamagePolicy:master.damagePolicy});
assert.equal(actual.actualHpDamage,100);assert(actual.totalDamage>100);const without={...actual};delete without.actualHpDamage;assert.deepEqual(without,old,'display damage, frames and battle result retained exactly');
const room={raidSnapshot:master,id:'qa-room',masterId:'TI01',ownerId:s.userId,level:1,hp:120,maxHp:120,expiresAt:new Date(after+600000).toISOString(),createdAt:new Date(after).toISOString(),status:'active',rescueCount:0,rescueWindowStartedAt:new Date(after).toISOString(),participants:[{userId:s.userId,name:'qa',wins:2,attempts:2,totalDamage:10,joinedLevel:1}],settledBattleIds:[],rewardGrants:[]};
const payload={battleId:'settle-3',battleLevel:1,energyAlreadyPaid:true,result:actual};
const settled=applyRaidAction(room,s,'raid_battle',payload,after);assert.equal(settled.room.participants[0].totalDamage,130);assert.equal(settled.room.rewardGrants.length,1);assert.equal(settled.room.participants[0].wins,3);assert.equal(settled.room.level,2);
assert.deepEqual(applyRaidAction(settled.room,settled.state,'raid_battle',payload,after),{...settled,rewards:[]});
const late=applyRaidAction(settled.room,settled.state,'raid_battle',{...payload,battleId:'late-old-level'},after);assert.equal(late.room.hp,settled.room.hp);assert.equal(late.room.participants[0].totalDamage,130);
const oldRoom=structuredClone(room);delete oldRoom.raidSnapshot.damagePolicy;const oldSettled=applyRaidAction(oldRoom,s,'raid_battle',{...payload,result:old},after);assert.equal(oldSettled.room.participants[0].totalDamage,10+Math.floor(old.totalDamage*1.5));
assert.throws(()=>applyRaidAction(room,s,'raid_battle',{...payload,result:old},after),'missing accounting fails before mutation');
console.log(JSON.stringify({status:'PASS',scope:'local domain tests; API/DB acceptance separate',daily:['JST boundary/expiry','DM005 only order','saved current-day history retained; prior-day no backpay','settled-day event','duplicate event/claim rejection','eight basic completion objectives'],invasion:['per-hit actual HP excludes overkill','display/replay unchanged','multiplier preserved','shared HP cap/contribution','three wins eligibility','late old-level contribution zero','old snapshot unchanged','same battle replay unchanged'],combat:{displayDamage:actual.totalDamage,actualHpDamage:actual.actualHpDamage,sharedHpReduction:120,contribution:120}},null,2));
