const fs=require('fs'),assert=require('assert/strict'),{chromium}=require('playwright');
const base=process.env.BASE_URL||'http://localhost:3104',out='../../outputs/common-ui-continuation/growth-states';fs.mkdirSync(out,{recursive:true});
(async()=>{const b=await chromium.launch(),report=[];try{for(const width of [375,390]){const p=await b.newPage({viewport:{width,height:480}}),errors=[];p.on('pageerror',e=>errors.push(e.message));
const open=async(mode='')=>{await p.goto(base+'/qa/common-ui-audit?view=character&state='+mode);await p.locator('.g4-growth[aria-busy="false"]').waitFor({timeout:90000});};
const shot=async state=>{await p.waitForTimeout(400);assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await p.screenshot({path:`${out}/${state}-${width}.png`});report.push({width,height:480,state,errors:[...errors]});fs.writeFileSync(out+'/report.json',JSON.stringify(report,null,2));};
await open();await p.locator('.g4g-party button').first().click();await p.getByRole('button',{name:'全身を見る',exact:true}).click();await shot('character-art');await p.getByRole('dialog').getByRole('button',{name:'閉じる',exact:true}).first().click();
for(const name of ['覚醒','魂交換']){await p.getByRole('button',{name,exact:true}).first().click();await shot(name);await p.getByRole('dialog').getByRole('button',{name:'閉じる',exact:true}).first().click();}
await open();await p.locator('.g4g-tabs').getByRole('button',{name:'スキル',exact:true}).click();await p.locator('.g4g-grid button').first().click();await shot('skill-detail');await p.getByRole('button',{name:'LBを上げる',exact:true}).click();await p.getByRole('heading',{name:'更新しました',exact:true}).waitFor();await shot('skill-result');
await open('failure');await p.locator('.g4g-tabs').getByRole('button',{name:'スキル',exact:true}).click();await p.locator('.g4g-grid button').first().click();await p.getByRole('button',{name:'LBを上げる',exact:true}).click();await p.getByText('検証用の保存失敗',{exact:true}).waitFor();await shot('skill-failure');
await open();await p.locator('.g4g-tabs').getByRole('button',{name:'装備',exact:true}).click();await p.locator('.g4g-grid button').first().click();await shot('equipment-detail');await p.getByRole('button',{name:'Lv育成',exact:true}).click();await shot('equipment-exp');await p.getByRole('button',{name:'育成する',exact:true}).scrollIntoViewIfNeeded();await shot('equipment-exp-actions');await p.getByRole('dialog').getByRole('button',{name:'閉じる',exact:true}).first().click();await p.getByRole('button',{name:'分解',exact:true}).click();await shot('equipment-dismantle-confirm');await p.getByRole('button',{name:'分解を確定',exact:true}).click();await p.getByRole('heading',{name:'更新しました',exact:true}).waitFor();await shot('equipment-dismantle-result');
assert.deepEqual(errors,[]);await p.close();}console.log('PASS growth consumer states');}finally{await b.close();}})().catch(e=>{console.error(e);process.exitCode=1});
