// 正式ドメイン検証。API・ブラウザ結果とは区別する。
require('./verify_game04_growth_resume.cjs');
const assert = require('node:assert/strict');
const g = require('../src/domain/redesign/growth.ts');
const m = require('../src/domain/redesign/growthMaster.ts');
const masters = require('../src/domain/redesign/masters.ts');
const s = masters.createInitialState('character-domain-only');
s.growthInventory = m.emptyGrowthInventory();
s.cash = 10000000;
const owned = s.characters[0], character = masters.CHARACTER_MASTERS.find(c=>c.id===owned.id);
const unseen = masters.CHARACTER_MASTERS.find(c=>!s.characters.some(o=>o.id===c.id));
function rejectsWithoutMutation(state, action, payload) {
  const before=structuredClone(state);
  assert.throws(()=>g.applyGrowthAction(state,action,payload));
  assert.deepEqual(state,before);
}
s.souls[unseen.id]=11;
rejectsWithoutMutation(s,'soul_exchange',{characterId:unseen.id,amount:8});
rejectsWithoutMutation(s,'soul_exchange',{characterId:unseen.id,amount:11});
const exchanged=g.applyGrowthAction(s,'soul_exchange',{characterId:unseen.id,amount:10});
assert.equal(exchanged.souls[unseen.id],1);
assert.equal(exchanged.growthInventory.genericSouls[unseen.rarity],5);
assert.equal(exchanged.cash,s.cash);
s.growthInventory.genericSouls[unseen.rarity]=1000;
rejectsWithoutMutation(s,'character_unlock',{characterId:unseen.id});
s.souls[unseen.id]=m.SOUL_UNLOCK[unseen.rarity];
const unlocked=g.applyGrowthAction(s,'character_unlock',{characterId:unseen.id});
assert.equal(unlocked.cash,s.cash);
assert.equal(unlocked.growthInventory.genericSouls[unseen.rarity],1000);
assert.deepEqual(unlocked.characters.find(c=>c.id===unseen.id),{id:unseen.id,level:1,awakening:0,exp:0,growthVersion:m.GROWTH_VERSION});
rejectsWithoutMutation(unlocked,'character_unlock',{characterId:unseen.id});
owned.awakening=5;
rejectsWithoutMutation(s,'character_awaken',{characterId:owned.id});
s.growthInventory.soulSelectors[character.rarity]=1;
rejectsWithoutMutation(s,'soul_select',{characterId:owned.id});
const skill=s.skills[0];
s.materials.skill=0;
rejectsWithoutMutation(s,'skill_level',{skillId:skill.id});
skill.level=10;s.materials.skill=1000;
rejectsWithoutMutation(s,'skill_level',{skillId:skill.id});
const equipmentMaster=masters.EQUIPMENT_MASTERS.find(e=>e.slot==='weapon');
s.equipment=[{instanceId:'boundary-weapon',masterId:equipmentMaster.id,level:1,lb:0,exp:0,growthVersion:m.GROWTH_VERSION}];
s.deck=[{characterId:owned.id,skillIds:[],equipment:{weapon:'boundary-weapon'}}];
rejectsWithoutMutation(s,'equipment_dismantle',{instanceIds:['boundary-weapon']});
rejectsWithoutMutation(s,'save_deck',{deck:[s.deck[0],s.deck[0]]});
const second=s.characters.find(c=>c.id!==owned.id);
if(second) rejectsWithoutMutation(s,'save_deck',{deck:[s.deck[0],{...s.deck[0],characterId:second.id}]});
const saved=g.applyGrowthAction(s,'save_deck',{deck:s.deck});
assert.deepEqual(JSON.parse(JSON.stringify(saved)).deck,s.deck);
s.deck=[];s.equipment[0].lb=10;
rejectsWithoutMutation(s,'equipment_lb',{instanceId:'boundary-weapon'});
console.log('PASS: 魂交換最小10/奇数/未所持/端数・初回汎用不可/再解放拒否・最大覚醒/選択不可・スキル不足/上限・装備中分解/重複個体禁止・保存JSON整合');
const resultHelper=require('../src/domain/redesign/growthResult.ts');
const resultState=masters.createInitialState('character-result-only');
resultState.cash=10000000; resultState.growthInventory=m.emptyGrowthInventory();
const resultCharacter=resultState.characters[0];
resultState.souls[resultCharacter.id]=1000;
const awakened=g.applyGrowthAction(resultState,'character_awaken',{characterId:resultCharacter.id});
const awakeningResult=resultHelper.getGrowthResult(resultState,awakened,'character_awaken',{characterId:resultCharacter.id});
assert.equal(awakeningResult.changed,true);
assert.ok(awakeningResult.rows.some(row=>row.label==='Lv'&&row.before===row.after));
assert.equal(resultHelper.getGrowthResult(awakened,awakened,'character_awaken',{characterId:resultCharacter.id}).changed,false);
resultState.equipment=[{instanceId:'result-equipment',masterId:equipmentMaster.id,level:1,lb:0,exp:0,growthVersion:m.GROWTH_VERSION}];
resultState.materials.equipmentLb=1000;
const limitBroken=g.applyGrowthAction(resultState,'equipment_lb',{instanceId:'result-equipment'});
const lbResult=resultHelper.getGrowthResult(resultState,limitBroken,'equipment_lb',{instanceId:'result-equipment'});
assert.equal(lbResult.changed,true);
assert.ok(lbResult.rows.some(row=>row.label==='Lv'&&row.before===row.after));
assert.equal(resultHelper.getGrowthResult(limitBroken,limitBroken,'equipment_lb',{instanceId:'result-equipment'}).changed,false);
console.log('PASS: 覚醒/装備LB結果で現在Lv不変を明示・再送同状態で成功差分を捏造しない');
