import fs from'node:fs';import assert from'node:assert/strict';import{execFileSync}from'node:child_process';import{hash}from'./stage68_implementation_results.mjs';import{write}from'./stage68_decision_lib.mjs';
const O='docs/verification/stage68-resolution-20260927',base='16d45e1abbecfa258f9996e6f297780a1fce5800',p='src/domain/redesign/data/quest65.json',read=p=>JSON.parse(fs.readFileSync(p)),old=JSON.parse(execFileSync('git',['show',`${base}:${p}`],{encoding:'utf8',maxBuffer:20e6})),current=read(p),expected=structuredClone(old),patch=read(`${O}/enemy-patch.json`),summary=read(`${O}/summary.json`);
for(const c of patch){const e=expected.stages.find(s=>s.designId===c.stage).waves[c.wave-1][c.position-1];assert.equal(e.id,c.enemy);assert.deepEqual(e[c.field]??null,c.before);if(c.after===null)delete e[c.field];else e[c.field]=c.after;}assert.deepEqual(current,expected);assert.equal(hash(current),summary.masterHash);
const supply=read('docs/verification/stage68-adoption-20260927/supply44.json');assert.equal(supply.length,44);for(const g of supply){assert(current.stages.findIndex(s=>s.designId===g.grantOn)<current.stages.findIndex(s=>s.designId===g.requiredBefore));assert.deepEqual(current.stages.find(s=>s.designId===g.grantOn).firstRewards,[...g.currentFirstRewards,...g.additions]);}
const paths=['src/domain/redesign/battle.ts','src/domain/redesign/battleBalanceV2.ts','src/domain/redesign/masters.ts','src/domain/redesign/formalBattleInput.ts','src/app/components/redesign/BattleView.tsx',...['recovery-20260927','decision-20260927','adoption-20260927','implementation-20260927','five-tier-20260926'].map(s=>'docs/verification/stage68-'+s)];for(const p of paths)assert.equal(execFileSync('git',['diff','--name-only',base,'--',p],{encoding:'utf8'}).trim(),'','Preserved path changed: '+p);
const roles=read(`${O}/role-comparisons.json`);assert.equal(roles.length,68);assert.equal(summary.accepted,68);assert.equal(summary.fiveBands,68);assert(roles.every(s=>s.allValidated.every(c=>c.actionLimit===0)));const missingOldRoles=roles.filter(s=>s.changed).flatMap(s=>s.roleBeforeAfter.filter(r=>r.before&&!r.after).map(r=>({stage:s.stage,role:r.role,name:r.before.name})));assert.deepEqual(missingOldRoles,[],'Old main/alternative/next/low must be rechecked');
const checks={pass:true,baseline:base,currentMasterHash:hash(current),enemyOnlyPatchReconstructsCurrent:true,enemyStages:summary.changedStages.length,enemyObjects:[...new Set(patch.map(c=>c.enemy))].length,patchFields:patch.length,rewardSites:44,allGrantsBeforeUse:true,all68StageMetadataAndRewardsKept:true,oldPrimaryAlternativeNextLowAllRechecked:true,commonFormulaBurst300AndUIUnchanged:true,allOldEvidenceKept:true,applicationTypecheck:'PASS tsc -p scripts/stage68-app-tsconfig.json --noEmit',fullRepositoryTypecheck:'Previous known archived deployed-api-v8.ts errors; not re-run or modified',apiBundle:'PASS verify_game04_redesign_api_bundle.mjs; no deploy',realDevice:false,G5:false};write(`${O}/checks.json`,checks);console.log(JSON.stringify(checks));
const formatSkill=s=>`${s.id}: ${s.condition.type}${s.condition.value??''}; ${s.target}; ${s.effects.map(e=>e.type+':'+e.power).join(',')}`;
const lines=['# 今回の敵変更差分','','16d45e1からの差分。採用43面・追加12面・配布44箇所を土台に、停滞28面と1-1を変更。既存敵技能を保持し、敵固有の長期戦攻撃を追加。プレイヤー能力に合わせた動的補正はなく、保存した固定数値。共通式・300行動・BURST・周回報酬は変更なし。','','|面|敵（wave/位置）|項目|前|後|','|---|---|---|---|---|'];for(const c of patch){const e=current.stages.find(s=>s.designId===c.stage).waves[c.wave-1][c.position-1];if(c.field==='stats')for(const key of Object.keys(c.after).filter(k=>c.before[k]!==c.after[k]))lines.push(`|${c.stage}|${e.name} ${c.enemy}|${key}|${c.before[key]}|${c.after[key]}|`);else lines.push(`|${c.stage}|${e.name} ${c.enemy}|${c.field}|${c.field==='skills'?c.before.map(formatSkill).join('<br>'):JSON.stringify(c.before)}|${c.field==='skills'?c.after.map(formatSkill).join('<br>'):JSON.stringify(c.after)}|`);}fs.writeFileSync(`${O}/IMPLEMENTATION.md`,lines.join('\n'));
