const {chromium}=require('@playwright/test'),fs=require('fs'),assert=require('assert/strict');
const base=process.env.QA_URL||'http://localhost:3040',out=process.env.QA_OUTPUT||'docs/verification/all-battle-effects-20260928/browser';fs.mkdirSync(out,{recursive:true});
(async()=>{const browser=await chromium.launch(),page=await browser.newPage({viewport:{width:390,height:720},isMobile:true,hasTouch:true});const errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('response',r=>{if(r.status()>=400)errors.push(`${r.status()} ${r.url()}`)});
await page.addInitScript(()=>{window.events=[];let last='';const seen=new WeakSet();new MutationObserver(()=>{const b=document.querySelector('[data-playback-frame]');if(b){const key=[b.dataset.playbackFrame,b.dataset.presentationPhase].join(':');if(key!==last){last=key;events.push({kind:'frame',frame:+b.dataset.playbackFrame,phase:b.dataset.presentationPhase,event:b.dataset.frameEvent,time:performance.now()})}}document.querySelectorAll('[data-tutorial-cutin],[data-tutorial-combo]').forEach(n=>{if(!seen.has(n)){seen.add(n);events.push({kind:n.dataset.tutorialCutin?'skill':'combo',frame:+n.dataset.effectFrame,value:n.dataset.tutorialCombo,time:performance.now()})}})}).observe(document,{subtree:true,childList:true,attributes:true,attributeFilter:['data-playback-frame','data-presentation-phase']})});
await page.goto(base+'/qa/battle-device-five?mode=burst&count=1&skillCharacter=char_ageha_01');await page.locator('[data-tutorial-cutin]').waitFor();await page.getByRole('button',{name:'一時停止',exact:true}).click();const f=await page.locator('[data-playback-frame]').getAttribute('data-playback-frame');await page.waitForTimeout(600);assert.equal(await page.locator('[data-playback-frame]').getAttribute('data-playback-frame'),f);await page.screenshot({path:out+'/skill-paused.png'});await page.getByRole('button',{name:'バトルを続ける',exact:true}).click();await page.getByRole('region',{name:'戦闘リザルト',exact:true}).waitFor({timeout:60000});const events=await page.evaluate(()=>events);const combos=events.filter(e=>e.kind==='combo');assert.deepEqual(combos.map(e=>+e.value),[1,2,3,4,5]);assert.equal(events.filter(e=>e.kind==='skill').length,5);for(const c of combos){assert(events.find(e=>e.kind==='skill'&&e.frame===c.frame).time<c.time);assert(events.find(e=>e.kind==='frame'&&e.frame===c.frame+1&&e.event==='damage').time>c.time)}assert.equal(await page.locator('[data-completed]').getAttribute('data-completed'),'1');assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
await page.goto(base+'/qa/battle-device-five?mode=wave');await page.locator('header strong').filter({hasText:'派'}).waitFor();await page.getByRole('button',{name:'SKIP',exact:true}).click();await page.locator('[data-completed="1"]').waitFor();assert.equal(await page.locator('[data-tutorial-cutin],[data-tutorial-combo]').count(),0);
await page.goto(base+'/qa/battle-device-five?mode=burst&count=1');await page.locator('[data-presentation-phase="combo"]').waitFor({timeout:15000});assert.equal(await page.locator('[data-tutorial-cutin]').count(),0);await page.getByRole('button',{name:'一時停止',exact:true}).click();await page.getByRole('button',{name:'リタイア',exact:true}).click();await page.getByRole('button',{name:'リタイア',exact:true}).click();await page.getByRole('status').filter({hasText:'出撃元へ戻りました'}).waitFor();assert.equal(await page.locator('[data-tutorial-combo]').count(),0);
assert.deepEqual(errors,[]);fs.writeFileSync(out+'/report.json',JSON.stringify({base,checks:['shared default SSR: five actions once each','skill -> combos 1..5 -> damage','pause/resume','completion callback once','wave retained','VIP skip clears effects and completes','nonSSR fallback and retire clears effects','mobile no overflow'],errors,events},null,2));await browser.close();console.log('PASS shared battle effects');})().catch(e=>{console.error(e);process.exit(1)});

