// Creates a development-only harness temporarily, then removes only its own files.
const {chromium}=require('playwright'),fs=require('fs'),assert=require('assert/strict');
const dir='src/app/qa/b05-investigation';
assert(!fs.existsSync(dir),'Refuse to overwrite an existing QA route');fs.mkdirSync(dir);
fs.writeFileSync(dir+'/page.tsx',`import {notFound} from 'next/navigation';import Harness from './Harness';export default function Page(){if(process.env.NODE_ENV!=='development')notFound();return <Harness/>;}`);
fs.writeFileSync(dir+'/Harness.tsx',`'use client';import {AudioProvider} from '@/audio/AudioProvider';import BattleView from '@/app/components/redesign/BattleView';import type {BattleResult} from '@/domain/redesign/battle';import saved from '../../../../docs/verification/device-debug/b05/saved-qa-battle.json';import '@/app/components/redesign/redesign.css';export default function Harness(){return <AudioProvider><BattleView result={saved as unknown as BattleResult} initialFrame={32} vipActive={false} onComplete={()=>{}} backgroundSrc="/bg/approved-20260925/quest-mikawa.webp"/></AudioProvider>;}`);
(async()=>{const b=await chromium.launch({channel:'chrome',headless:true});try{const page=await b.newPage({viewport:{width:390,height:740}});await page.goto('http://localhost:3002/qa/b05-investigation');await page.waitForFunction(()=>document.querySelector('[data-playback-frame]')&&!document.querySelector('dialog[aria-label="戦闘画面の読み込み"]')?.open);const events=await page.evaluate(async()=>{
 const rows=[];let last=-1;const start=performance.now();while(performance.now()-start<45000){const root=document.querySelector('[data-playback-frame]'),n=Number(root?.getAttribute('data-playback-frame'));if(n!==last){const cuts=[...document.querySelectorAll('[aria-label$=" BURST"]')];rows.push({frame:n,elapsedMs:Math.round(performance.now()-start),burstCutIn:cuts.map(e=>e.getAttribute('aria-label')),sp:document.querySelector('[role="meter"][aria-label="共通SP"]')?.getAttribute('aria-valuenow'),gauge:document.querySelector('[role="meter"][aria-label="バーストゲージ"]')?.getAttribute('aria-valuenow')});last=n;}if(n>=65)break;await new Promise(r=>setTimeout(r,10));}return rows;
 });const starts=events.filter(e=>e.burstCutIn.length);assert.equal(starts.length,1);assert(events.at(-1).frame>=65);assert(events.every((e,i)=>i===0||e.frame>events[i-1].frame));fs.writeFileSync('docs/verification/device-debug/b05/fix/browser-playback.json',JSON.stringify({source:'actual BattleView playback of previously saved QA battle; local development, DBG-032 renderer',events},null,2));console.log('PASS monotonic playback; one BURST cut-in for one saved BURST',starts.map(e=>e.frame));}finally{await b.close();}})().catch(e=>{console.error(e);process.exitCode=1}).finally(()=>{fs.unlinkSync(dir+'/page.tsx');fs.unlinkSync(dir+'/Harness.tsx');fs.rmdirSync(dir);});

