const assert = require('node:assert/strict');
const fs = require('node:fs');
const ts = require('typescript');
const React = require('react');
const source = fs.readFileSync('src/app/components/ui/CanonicalDialog.tsx', 'utf8');
const compiled = ts.transpile(source, { jsx:ts.JsxEmit.ReactJSX, target:ts.ScriptTarget.ES2020, module:ts.ModuleKind.CommonJS, esModuleInterop:true });
const state = []; let cursor = 0;
const mockReact = {...React, useLayoutEffect:()=>{}, useRef:value=>{ const i=cursor++; return state[i] ??= {current:value}; }, useState:value=>{ const i=cursor++; if (!(i in state)) state[i]=value; return [state[i], next=>{state[i]=next;}]; }};
const exportsObject={};
new Function('require','exports',compiled)(name=>name==='react'?mockReact:name==='react-dom'?{flushSync:fn=>fn()}:name.includes('dialogPresence')?{registerPresentedDialog:()=>{}}:name.includes('OutlawButton')?{default:'button'}:name.endsWith('.css')?{}:require(name),exportsObject);
const render = props => {cursor=0; return exportsObject.default(props);};
const find = (node, test) => { if (!node || typeof node !== 'object') return; if(test(node))return node; for(const child of React.Children.toArray(node.props?.children)){const found=find(child,test);if(found)return found;} };
(async()=>{
 let calls=0, closeCalls=0, reject;
 const promise=new Promise((_,r)=>{reject=r;});
 const props={title:'交換',children:React.createElement('input',{defaultValue:'10'}),onClose:()=>closeCalls++,actions:[{label:'交換する',onClick:()=>{calls++;return promise;}}]};
 let tree=render(props);
 const action=find(tree,n=>n.props.children==='交換する');
 action.props.onClick(); action.props.onClick();
 assert.equal(calls,1,'immediate duplicate submissions blocked');
 tree=render(props);
 assert.equal(find(tree,n=>n.props.role==='dialog').props['aria-busy'],true);
 assert.equal(find(tree,n=>String(n.props.className).startsWith('canonical-dialog-body')).props.inert,true,'body inputs blocked while request pending');
 assert.equal(find(tree,n=>n.props['aria-label']==='閉じる').props.disabled,true);
 tree.props.onMouseDown({target:1,currentTarget:1}); assert.equal(closeCalls,0);
 reject(new Error('network')); await Promise.resolve(); await Promise.resolve();
 tree=render(props);
 assert.equal(find(tree,n=>String(n.props.className).startsWith('canonical-dialog-body')).props.inert,false,'failure releases body for retry');
 assert.equal(find(tree,n=>n.props['aria-label']==='閉じる').props.disabled,false);
 assert.equal(find(tree,n=>n.props.role==='dialog').props['aria-busy'],false);
 tree.props.onMouseDown({target:1,currentTarget:1}); assert.equal(closeCalls,1);
 console.log('PASS shared dialog pending: duplicate call, body inert, close lock, rejection recovery');
})().catch(error=>{console.error(error);process.exitCode=1;});
