// Candidate-policy guard evidence. No API/DB, and no adoption of proposed rules.
const assert = require('node:assert/strict');
const fs = require('node:fs');
const ts = require('typescript');
require.extensions['.ts'] = (m,f) => m._compile(ts.transpileModule(fs.readFileSync(f,'utf8'), {compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,esModuleInterop:true}}).outputText,f);
const {createInitialState} = require('../src/domain/redesign/masters.ts');
const {FORMAL_MISSION_CONFIG,FORMAL_DAILY_MISSIONS} = require('../src/domain/redesign/formalMissions.ts');
const {evaluateMissions,getClaimableMission} = require('../src/domain/redesign/missions.ts');
const {recordMissionEvent} = require('../src/domain/redesign/missionProgress.ts');
const {createFormalInvasionMaster} = require('../src/domain/redesign/raidInvasionMaster.ts');
const {createRaidRoom,applyRaidAction} = require('../src/domain/redesign/raid.ts');
const beforeMidnight=Date.parse('2026-09-24T14:59:59Z'), afterMidnight=beforeMidnight+1000;
let state=createInitialState('g2-policy-guard');
for(let i=0;i<5;i++) state=recordMissionEvent(state,{id:`fixture:${i}`,counters:['battle','quest_clear','growth','normal_gacha'],at:beforeMidnight});
assert.equal(FORMAL_DAILY_MISSIONS.length,10);
assert(FORMAL_DAILY_MISSIONS.every(m=>!m.enabled));
for(const at of [beforeMidnight,afterMidnight]) assert(!evaluateMissions(state,FORMAL_MISSION_CONFIG,at).some(m=>m.id.startsWith('DM')));
const snapshot=structuredClone(state);
for(const m of FORMAL_DAILY_MISSIONS) for(const id of [m.id,`${m.id}:2026-09-24`,`${m.id}:2026-09-25`]) assert.throws(()=>getClaimableMission(state,FORMAL_MISSION_CONFIG,id));
assert.deepEqual(state,snapshot);
const cross=recordMissionEvent(state,{id:'fixture:cross',counters:['battle'],at:afterMidnight});
assert.equal(cross.missionProgress.daily['2026-09-24'].battle,5);
assert.equal(cross.missionProgress.daily['2026-09-25'].battle,1);
assert.deepEqual(recordMissionEvent(cross,{id:'fixture:cross',counters:['battle'],at:afterMidnight+5000}),cross);
const master=createFormalInvasionMaster('TI01',()=>0.5);
const first=master.stages.find(s=>s.level===1);
const enemyHp=first.enemies.reduce((sum,e)=>sum+e.stats.hp,0);
assert.equal(enemyHp,23040);assert.equal(first.sharedHp,70000);assert.equal(master.victoryMultiplier,1.5);
let room=createRaidRoom('encounter_flame',state.userId,'policy-fixture',beforeMidnight);
room.masterId=master.id;room.raidSnapshot=master;room.hp=first.sharedHp;room.maxHp=first.sharedHp;
state.energy=100;
const settle=(id,outcome,totalDamage)=>{const result=applyRaidAction(room,state,'raid_battle',{battleId:id,battleLevel:room.level,energyAlreadyPaid:true,result:{outcome,totalDamage}},beforeMidnight);room=result.room;state=result.state;};
settle('loss','lose',8);settle('win1','win',23992);
assert.equal(room.hp,34004);assert.equal(room.participants[0].totalDamage,35996);
const frozen=structuredClone({room,state});
const replay=applyRaidAction(room,state,'raid_battle',{battleId:'win1',battleLevel:1,energyAlreadyPaid:true,result:{outcome:'win',totalDamage:23992}},beforeMidnight);
assert.deepEqual(replay.room,frozen.room);assert.deepEqual(replay.state,frozen.state);
settle('win2','win',24063);
assert.equal(room.level,2);assert.equal(room.participants[0].wins,2);
assert.equal(room.rewardGrants.filter(g=>g.level===1).length,0);
const proposedContribution=Math.floor(enemyHp*master.victoryMultiplier);
assert.equal(proposedContribution,34560);
assert.equal(first.sharedHp-8-2*proposedContribution,872);
console.log(JSON.stringify({status:'PASS',scope:'local domain / pending policy guard; not live acceptance',checks:['all 10 daily rows hidden even with complete counters','30 raw/dated claim attempts rejected with state unchanged','recorded event timestamp follows JST and event replay is idempotent','TI01 formal Lv1 enemy HP / shared HP / multiplier verified','current full damage causes Lv2 after 2 wins; no retroactive Lv1 grant','same battle replay leaves state unchanged'],comparison:{source:first.source,enemyNames:first.enemies.map(e=>e.name),enemyHp,sharedHp:first.sharedHp,displayDamage:23992,overkill:23992-enemyHp,currentContribution:35988,proposedContribution,proposedRemainingAfterLossAndTwoWins:872}},null,2));
