const {chromium}=require('playwright'),fs=require('fs'),path=require('path'),assert=require('node:assert/strict');
const dir=process.env.B13_MISSION_OUT||'docs/verification/device-debug/b13/mission-implemented',base=process.env.B13_BASE_URL||'http://localhost:3013';fs.mkdirSync(dir,{recursive:true});
(async()=>{const b=await chromium.launch({headless:true}),report=[];try{for(const width of [375,390]){const p=await b.newPage({viewport:{width,height:664}}),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto(base+'/qa/b13-missions');const nav=p.locator('nav[aria-label=任務検証操作]');await p.locator('.g4-mission-row').first().waitFor();const reset=async mode=>{await p.getByLabel('任務検証状態').selectOption(mode==='zero'?'progress':'zero');await p.getByLabel('任務検証状態').selectOption(mode);await p.locator('.g4-mission-modal').waitFor()};const screenshot=async name=>{await nav.evaluate(e=>e.style.visibility='hidden');await p.screenshot({path:path.join(dir,`${name}-${width}.png`)});await nav.evaluate(e=>e.style.visibility='visible')};
for(const mode of ['zero','progress','achieved','claimed','bulk']){await reset(mode);const layout=await p.evaluate(()=>{const s=document.querySelector('.g4-mission-scroll'),rect=s.getBoundingClientRect(),rows=[...s.querySelectorAll(':scope>.g4-mission-row')];return {heights:rows.map(r=>r.getBoundingClientRect().height),visible:rows.filter(r=>r.getBoundingClientRect().bottom<=rect.bottom+.1).length,overflow:s.scrollWidth>s.clientWidth,taps:[...document.querySelectorAll('.g4-mission-modal button')].map(e=>e.getBoundingClientRect().height)}});assert(!layout.overflow);assert(layout.taps.every(h=>h>=44));if(mode!=='claimed'){assert(layout.visible>=3);assert(layout.heights.every(h=>h>=100&&h<=112));}else{assert.equal(await p.locator('.g4-mission-check').count(),0);await p.getByRole('button',{name:'▸ 受取済み（6件）'}).click();assert.equal(await p.locator('.g4-mission-check').count(),6)}await screenshot(mode);report.push({width,mode,...layout});}
await p.locator('[data-mission-id^="DM005:"]').getByRole('button',{name:'全3件の報酬を確認'}).click();assert.equal(await p.locator('.g4-reward-list>li').count(),3);await screenshot('reward-detail');await p.getByRole('button',{name:'戻る',exact:true}).click();
await p.locator('.g4-mission-bulk').evaluate(e=>{e.click();e.click()});await p.keyboard.press('Escape');assert(await p.locator('.g4-mission-modal').isVisible());await p.getByRole('status').filter({hasText:'3件を受け取りました'}).waitFor();assert.equal(await nav.getAttribute('data-cash'),'5000');assert.equal(await nav.getAttribute('data-calls'),'3');assert(await p.locator('.g4-mission-bulk').isDisabled());await screenshot('bulk-after');await p.getByRole('button',{name:'ノーマル (1)',exact:true}).click();assert.equal(await p.locator('.g4-mission-bulk').innerText(),'一括受取（1件）');await p.locator('[data-mission-id="NM159"]').getByRole('button',{name:'条件の詳細'}).click();assert((await p.getByRole('dialog').last().innerText()).includes('第2枠にスキルを装備した武将を含め'));await p.getByRole('button',{name:'戻る',exact:true}).click();await screenshot('normal-conditions');
await reset('bulk');await p.getByRole('button',{name:'2件目失敗',exact:true}).click();await p.locator('.g4-mission-bulk').click();await p.getByRole('alert').filter({hasText:'受取確認済み1件'}).waitFor();assert.equal(await nav.getAttribute('data-cash'),'2000');assert.equal(await nav.getAttribute('data-refreshes'),'1');await screenshot('partial-failure');await p.locator('.g4-mission-bulk').click();await p.getByRole('status').filter({hasText:'2件を受け取りました'}).waitFor();assert.equal(await nav.getAttribute('data-cash'),'5000');assert.equal(await nav.getAttribute('data-calls'),'4');
await reset('bulk');await p.getByRole('button',{name:'応答切断',exact:true}).click();await p.locator('.g4-mission-bulk').click();await p.getByRole('alert').filter({hasText:'保存済み・応答切断'}).waitFor();await p.waitForFunction(()=>document.querySelector('nav[data-cash]')?.dataset.cash==='2000');assert.equal(await p.locator('.g4-mission-bulk').innerText(),'一括受取（2件）');await p.locator('.g4-mission-bulk').click();await p.getByRole('status').filter({hasText:'2件を受け取りました'}).waitFor();assert.equal(await nav.getAttribute('data-cash'),'5000');
await reset('bulk');await p.getByRole('button',{name:'日付境界',exact:true}).click();await p.locator('.g4-mission-bulk').click();await p.getByRole('alert').filter({hasText:'この任務の報酬は受け取れません'}).waitFor();assert.equal(await nav.getAttribute('data-cash'),'0');
await reset('bulk');await p.locator('[data-mission-id^="DM005:"]').getByRole('button',{name:'受取',exact:true}).click();await p.getByRole('status').filter({hasText:'1件を受け取りました'}).waitFor();assert.equal(await nav.getAttribute('data-cash'),'2000');await reset('zero');await p.locator('[data-mission-id^="DM002:"]').getByRole('button',{name:'挑戦',exact:true}).click();await p.locator('.g4-mission-modal').waitFor({state:'detached'});assert.equal(await nav.getAttribute('data-tab'),'quest');assert.deepEqual(errors,[]);report.push({width,batchAndSingle:true,lockAndEscape:true,partialFailureRetry:true,uncertainResponseRetry:true,dayBoundaryRejected:true,otherTabPreserved:true,navigation:true,errors});await p.close();}fs.writeFileSync(path.join(dir,'verification.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report));}finally{await b.close()}})().catch(e=>{console.error(e);process.exit(1)});


