const fs=require('fs'),assert=require('assert/strict'),{chromium}=require('playwright');const base=process.env.BASE_URL||'http://localhost:3013',out=process.env.QA_OUT||'../../outputs/area1-guide';fs.mkdirSync(out,{recursive:true});
(async()=>{const browser=await chromium.launch();try{const page=await browser.newPage({viewport:{width:375,height:650}}),trace=[],errors=[];page.setDefaultTimeout(60000);page.on('pageerror',e=>errors.push(e.message));let fail=true;
 await page.addInitScript(s=>{if(window===window.top)localStorage.setItem('sb-soiksqgtmcnspfedmanr-auth-token',JSON.stringify(s))},JSON.parse(fs.readFileSync('scratch/prod-guide-session.json')));
 await page.route('**/functions/v1/game04-redesign-api*',async route=>{const req=route.request();let b;try{b=req.postDataJSON()}catch{}if(fail&&b?.action==='early_guide'){fail=false;trace.push({action:b.action,requestId:b.requestId,injectedFailure:true});await route.fulfill({status:503,contentType:'application/json',body:JSON.stringify({error:'Unexpected token <, <!DOCTYPE html> is not valid JSON'})});}else await route.continue()});
 page.on('response',async r=>{if(!r.url().includes('/functions/v1/game04-redesign-api'))return;try{const b=r.request().postDataJSON();if(!b)return;trace.push({action:b.action,requestId:b.requestId,url:r.url(),status:r.status(),contentType:r.headers()['content-type'],redirectTo:r.headers().location||null});}catch{}});
 await page.goto(base);await page.getByRole('button',{name:'TAP TO START',exact:true}).click();await page.getByRole('button',{name:'続きから',exact:true}).click();
 const cfg=JSON.parse(fs.readFileSync('scratch/prod-public-config.json')),session=JSON.parse(fs.readFileSync('scratch/prod-guide-session.json'));async function assets(){const r=await fetch(cfg.url+'/functions/v1/game04-redesign-api',{method:'POST',headers:{apikey:cfg.key,Authorization:'Bearer '+session.access_token,'Content-Type':'application/json'},body:JSON.stringify({action:'get_state',payload:{},requestId:crypto.randomUUID()})});assert(r.ok);const {state}=await r.json();return Object.fromEntries(['cash','diamonds','materials','souls','characters','skills','equipment','questTicketGrants','questClearCounts','clearedStages'].map(k=>[k,state[k]]));}
 const guide=page.getByRole('dialog',{name:'三河を制した',exact:true});
 for(let i=0;i<8;i++){if(await guide.count())break;await page.waitForTimeout(700);const close=page.getByRole('dialog').getByRole('button',{name:'閉じる',exact:true});if(await close.count())await close.last().click();const later=page.getByRole('dialog').getByRole('button',{name:'あとで',exact:true});if(await later.count())await later.last().click();}
 await guide.waitFor();await page.waitForTimeout(500);const before=await assets();await page.screenshot({path:out+'/guide-375.png'});await guide.getByRole('button',{name:'任務へ',exact:true}).click();await guide.locator('.screen-state-error').waitFor();await page.waitForTimeout(500);assert(!(await page.locator('body').innerText()).includes('DOCTYPE'));await page.screenshot({path:out+'/error-375.png'});await guide.getByRole('button',{name:'再試行',exact:true}).click();
 const missions=page.getByRole('dialog',{name:'任務',exact:true});await missions.waitFor();await page.waitForTimeout(500);await missions.getByRole('button',{name:/^ノーマル/}).waitFor();assert.equal(await missions.getByRole('button',{name:/^ノーマル/}).getAttribute('aria-pressed'),'true');await page.screenshot({path:out+'/normal-375.png'});await page.setViewportSize({width:390,height:650});await page.screenshot({path:out+'/normal-390.png'});await page.waitForTimeout(1000);assert.deepEqual(errors,[]);const requests=trace.filter(t=>t.action==='early_guide');assert.equal(new Set(requests.map(t=>t.requestId)).size,1,'retry retains operation ID');assert(trace.some(t=>t.action==='early_guide'&&t.status===200));assert(trace.some(t=>t.action==='early_missions_opened'&&t.status===200));const after=await assets();assert.deepEqual(after,before,'guide retry does not grant rewards or clear again');fs.writeFileSync(out+'/browser.json',JSON.stringify({base,trace,normalTab:true,safeError:true,retrySameId:true,rewardsAndClearsUnchanged:true},null,2));console.log('PASS area1 guide -> safe common failure -> same-ID retry -> normal missions; actual API commits');
}finally{await browser.close()}})().catch(e=>{console.error(e);process.exitCode=1});
