const {chromium}=require('playwright'),fs=require('fs'),assert=require('node:assert/strict');
const out='docs/verification/device-debug/b13';
(async()=>{const browser=await chromium.launch({headless:true}),report=[];try{for(const width of [375,390]){
 const p=await browser.newPage({viewport:{width,height:664}});await p.goto('http://localhost:3013/qa/b13-local');const nav=p.locator('nav[aria-label="B13検証操作"]');
 const ready=()=>p.waitForFunction(()=>document.querySelector('.g4-growth')?.getAttribute('aria-busy')==='false');const hide=()=>nav.evaluate(e=>e.style.visibility='hidden');const show=()=>nav.evaluate(e=>e.style.visibility='visible');await ready();await hide();
 await p.locator('.g4g-party>button').nth(4).click();await ready();await p.getByRole('button',{name:'デッキに戻る'}).click();assert.equal(await nav.getAttribute('data-deck'),'4');
 await show();await p.getByRole('button',{name:'次回保存失敗'}).click();await hide();await p.locator('.g4g-party>button').nth(4).click();await ready();await p.locator('.g4g-grid>button').first().click();await p.getByRole('alert').filter({hasText:'保存に失敗'}).waitFor();assert.equal(await nav.getAttribute('data-deck'),'4');await p.screenshot({path:`${out}/save-error-${width}.png`});await p.getByRole('button',{name:'閉じる',exact:true}).last().click();await p.locator('.g4g-grid>button').first().click();await p.waitForFunction(()=>document.querySelector('[data-deck]')?.getAttribute('data-deck')==='5');
 await show();await p.getByRole('button',{name:'4人初期化'}).click();await ready();await hide();await p.locator('.g4g-party>button').first().click();await p.locator('.g4g-modal .g4g-skill-row').first().click();const candidate=p.locator('.g4-asset-choice:not(:disabled)').first();await candidate.waitFor();const name=await candidate.locator('strong').innerText();await candidate.click();await ready();await p.locator('.g4g-result').waitFor();await p.getByRole('button',{name:'閉じる',exact:true}).last().click();await p.locator('.g4g-modal .g4g-skill-row').first().waitFor();assert.match(await p.locator('.g4g-modal .g4g-skill-row').first().innerText(),new RegExp(name));await p.locator('.g4g-modal .g4g-skill-row').first().click();await p.getByRole('button',{name:'外す',exact:true}).click();await ready();assert.equal(await nav.getAttribute('data-saves'),'2');
 for(const [button,count] of [['未解放',3],['5人初期化',5]]){await show();await p.getByRole('button',{name:button,exact:true}).click();await ready();await nav.getByLabel('検証状態').selectOption('prepare');await hide();await p.locator('.rq-party-card').first().waitFor();assert.equal(await p.locator('.rq-party-card').count(),count);await p.screenshot({path:`${out}/prepare-${count}-${width}.png`});const masks=await p.locator('[class*="cardOpening"]').evaluateAll(es=>es.map(e=>({clip:getComputedStyle(e).overflow,backgroundInside:!!e.querySelector('img')})));assert(masks.every(m=>m.clip==='hidden'&&m.backgroundInside));}
 await show();await nav.getByLabel('検証状態').selectOption('characters');await hide();await p.locator('.tutorial-character-card [class*="cardOpening"] img').first().waitFor();await p.screenshot({path:`${out}/characters-${width}.png`});
 report.push({width,cancelPreservesDeck:true,saveFailurePreservesDeck:true,retrySaves:true,skillSelectAndRemove:true,preparationCounts:[3,5],sharedMask:true});await p.close();
}fs.writeFileSync(out+'/edge-verification.json',JSON.stringify(report,null,2));console.log(JSON.stringify(report));}finally{await browser.close();}})().catch(e=>{console.error(e);process.exit(1)});
