const fs=require('fs'),assert=require('assert/strict'),{chromium}=require('playwright');
const base=process.env.BASE_URL||'http://localhost:3013',out=process.env.QA_OUT||'../../outputs/community-layout';fs.mkdirSync(out,{recursive:true});
(async()=>{const browser=await chromium.launch();try{const p=await browser.newPage({viewport:{width:375,height:600}});p.setDefaultTimeout(60000);const errors=[];p.on('pageerror',e=>errors.push(e.message));
await p.addInitScript(s=>{if(window===window.top)localStorage.setItem('sb-znakrkaazliexzwihxge-auth-token',JSON.stringify(s))},JSON.parse(fs.readFileSync('scratch/additional29-session.json')));
await p.goto(base);await p.getByRole('button',{name:'TAP TO START',exact:true}).click();await p.getByRole('button',{name:'続きから',exact:true}).click();await p.getByRole('button',{name:'メニュー',exact:true}).waitFor();for(let i=0;i<5;i++){await p.waitForTimeout(1000);const close=p.getByRole('dialog').getByRole('button',{name:'閉じる',exact:true});if(await close.count())await close.last().click();}await p.waitForFunction(()=>document.querySelector('.g4-home')?.getAttribute('aria-busy')==='false');
const metrics=[];
async function check(scope,label,width){await p.waitForTimeout(450);const root=p.locator(scope);await root.locator('.g4-community-name').first().waitFor();
// Text-only stress variants on the real rendered components; no user data writes.
await root.locator('.g4-community-name').evaluateAll(els=>els.forEach((el,i)=>{el.textContent=['追加29検証','墨朱送信検証','とても長い名前の追加検証ユーザー二十九文字確認'][i%3];if(!el.parentElement.querySelector('.rd-auth-badge')){const badge=document.createElement('span');badge.className='rd-auth-badge';badge.setAttribute('aria-label','認証済み');badge.textContent='✓';el.parentElement.append(badge)}}));
const result=await root.locator('.g4-community-message').evaluateAll(els=>els.map(el=>{const n=el.querySelector('.g4-community-name'),body=el.querySelector('.g4-community-body');if(!n||!body)return null;const ns=getComputedStyle(n),bs=getComputedStyle(body),r=n.getBoundingClientRect(),br=body.getBoundingClientRect();return {name:n.textContent,nameSize:ns.fontSize,weight:ns.fontWeight,whiteSpace:ns.whiteSpace,nameHeight:r.height,bodySize:bs.fontSize,bodyWhiteSpace:bs.whiteSpace,nameRight:r.right,bodyRight:br.right,badgeRight:el.querySelector('.rd-auth-badge')?.getBoundingClientRect().right,viewport:innerWidth}}).filter(Boolean));
for(const r of result){assert.equal(r.nameSize,'12px');assert.equal(r.whiteSpace,'nowrap');assert(r.nameHeight<28);assert.equal(r.bodySize,label.startsWith('home')?'12px':'13px');assert(r.bodyRight<=width+1);assert(!r.badgeRight||r.badgeRight<=width+1);}
metrics.push({width,label,result});await p.screenshot({path:`${out}/${label}-${width}.png`});}
for(const width of [375,390]){await p.setViewportSize({width,height:600});await p.locator('.g4-home-community .rd-tabs').getByRole('button',{name:/全体/}).click();await p.locator('.g4-home-community').scrollIntoViewIfNeeded();await check('.g4-home-community','home-global',width);
for(const [i,name] of ['追加29検証','墨朱送信検証','とても長い名前の追加検証ユーザー二十九文字確認'].entries()) {await p.locator('.g4-home-community .g4-community-name').first().evaluate((el,name)=>el.textContent=name,name);await p.locator('.g4-home-community .g4-community-body').first().evaluate(el=>el.textContent='長い本文も本陣では一行の末尾を省略し、交流では全文を読めるようにします。');const detail=await p.locator('.g4-home-community .g4-community-body').first().evaluate(el=>({whiteSpace:getComputedStyle(el).whiteSpace,overflow:getComputedStyle(el).textOverflow,width:el.clientWidth,content:el.scrollWidth}));assert.equal(detail.whiteSpace,'nowrap');assert.equal(detail.overflow,'ellipsis');assert(detail.content>detail.width);await p.screenshot({path:`${out}/home-name-${i+1}-${width}.png`});}

await p.locator('.g4-home-shortcuts').getByRole('button',{name:/交流/}).click();const modal=p.getByRole('dialog',{name:'コミュニティ',exact:true});await modal.waitFor();await check('.g4-community-dialog','global',width);
await modal.getByRole('button',{name:/活動/}).click();await check('.g4-community-dialog','activity',width);
await modal.getByRole('button',{name:/^DM/}).click();if(await modal.getByRole('button',{name:'会話一覧へ',exact:true}).count())await modal.getByRole('button',{name:'会話一覧へ',exact:true}).click();await check('.g4-community-dialog','dm-list',width);await modal.locator('.rd-conversation').first().click();await check('.g4-community-dialog','dm',width);await modal.getByRole('button',{name:'閉じる',exact:true}).click();}
assert(await p.locator('.g4-home-territory').isEnabled());assert.equal(await p.locator('.g4-home-territory .g4-home-unlock-overlay').count(),0);
await p.goto(base+'/qa/home-state');await p.waitForFunction(()=>document.querySelector('.g4-home')?.getAttribute('aria-busy')==='false');
for(const width of [375,390]){await p.setViewportSize({width,height:600});for(const cls of ['.g4-home-alliance','.g4-home-territory']){const el=p.locator(cls);assert(await el.isDisabled());await el.scrollIntoViewIfNeeded();const geometry=await el.evaluate(el=>{const b=el.getBoundingClientRect(),o=el.querySelector('.g4-home-unlock-overlay'),r=o.getBoundingClientRect(),cs=getComputedStyle(o);o.style.display='none';const after=el.getBoundingClientRect();o.style.display='';return {width:b.width,height:b.height,afterWidth:after.width,afterHeight:after.height,dx:(r.x+r.width/2)-(b.x+b.width/2),dy:(r.y+r.height/2)-(b.y+b.height/2),color:cs.color,background:cs.backgroundColor}});assert.equal(geometry.width,geometry.afterWidth);assert.equal(geometry.height,geometry.afterHeight);assert(Math.abs(geometry.dx)<1&&Math.abs(geometry.dy)<1);metrics.push({width,cls,geometry});await p.screenshot({path:`${out}/${cls.slice(1)}-${width}.png`});}}
assert.deepEqual(errors,[]);fs.writeFileSync(out+'/results.json',JSON.stringify({base,metrics,errors,note:'Name stress variants change DOM text only; real rendered activity/global/DM components; unlocked live QA state and locked offline QA state.'},null,2));console.log('PASS community typography, wrapping, overlay centering, unchanged dimensions, unlocked CTA');}finally{await browser.close()}})().catch(e=>{console.error(e);process.exitCode=1});
