const fs=require('node:fs'),assert=require('node:assert/strict'),ts=require('typescript');
require.extensions['.ts']=(module,name)=>module._compile(ts.transpileModule(fs.readFileSync(name,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,name);
const {gameplayMeasurementReceipt}=require('../src/domain/redesign/gameplayMeasurement.ts');
const before={version:8,cash:100,energy:99,userId:'qa',email:'private',bio:'private'};
const after={...before,cash:40,energy:149};
const r=gameplayMeasurementReceipt('use_energy_drink',before,after);
assert.deepEqual(r,{gameplayMeasurement:{contractVersion:'game04-gameplay-v1',action:'use_energy_drink',stateVersionBefore:8,stateVersionAfter:9,cashDelta:-60,energyDelta:50}});
for(const unsupported of ['purchase','get_state','quest_battle','normal_gacha','unknown']) assert.deepEqual(gameplayMeasurementReceipt(unsupported,before,after),{});
assert(!JSON.stringify(r).includes('private'));assert.equal(before.cash,100);
console.log('PASS: explicit validated action receipt, state versions/resource deltas, no PII, unknown/purchase/battle actions excluded. DB transaction dedup requires integration test.');
global.AsyncLocalStorage=require('node:async_hooks').AsyncLocalStorage;
const {unstable_doesMiddlewareMatch}=require('next/experimental/testing/server');
const {NextRequest}=require('next/server');
const {proxy,config}=require('../src/proxy.ts');
assert.equal(unstable_doesMiddlewareMatch({config,nextConfig:{},url:'https://example.test/api/admin/kpi/v2/gameplay?from=2026-09-24'}),true);
const oldUser=process.env.KPI_BASIC_AUTH_USER,oldPassword=process.env.KPI_BASIC_AUTH_PASSWORD;
delete process.env.KPI_BASIC_AUTH_USER;delete process.env.KPI_BASIC_AUTH_PASSWORD;
assert.equal(proxy(new NextRequest('https://example.test/api/admin/kpi/v2/gameplay')).status,503);
process.env.KPI_BASIC_AUTH_USER='test-only';process.env.KPI_BASIC_AUTH_PASSWORD='not-a-real-password';
assert.equal(proxy(new NextRequest('https://example.test/api/admin/kpi/v2/gameplay')).status,401);
assert.equal(proxy(new NextRequest('https://example.test/api/admin/kpi/v2/gameplay',{headers:{authorization:'Basic '+Buffer.from('test-only:wrong').toString('base64')}})).status,401);
const pass=proxy(new NextRequest('https://example.test/api/admin/kpi/v2/gameplay',{headers:{authorization:'Basic '+Buffer.from('test-only:not-a-real-password').toString('base64')}}));
assert.equal(pass.headers.get('x-middleware-next'),'1');
if(oldUser===undefined)delete process.env.KPI_BASIC_AUTH_USER;else process.env.KPI_BASIC_AUTH_USER=oldUser;
if(oldPassword===undefined)delete process.env.KPI_BASIC_AUTH_PASSWORD;else process.env.KPI_BASIC_AUTH_PASSWORD=oldPassword;
console.log('PASS: Next matcher selects gameplay route; unconfigured 503, missing/wrong credentials 401, valid test credentials continue.');
