// Targeted G2 regressions; synthetic account state, no network/DB writes.
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const Module = require('node:module');
const ts = require('typescript');
const resolve = Module._resolveFilename;
Module._resolveFilename = function(name, parent, ...rest) { return resolve.call(this, name.startsWith('@/') ? path.resolve(__dirname, '../src', name.slice(2)) : name, parent, ...rest); };
require.extensions['.ts'] = (module, filename) => module._compile(ts.transpileModule(fs.readFileSync(filename, 'utf8'), {compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,esModuleInterop:true}}).outputText, filename);
const {simulateBattle}=require('../src/domain/redesign/battle.ts');
const {commonBattleFixture}=require('../src/app/qa/battle-common/fixture.ts');
const {getFormalRaidSkill}=require('../src/domain/redesign/raidFormalSkills.ts');
const {createInitialState}=require('../src/domain/redesign/masters.ts');
const {createRaidRoom,applyRaidAction}=require('../src/domain/redesign/raid.ts');
const checks=[];
const six=simulateBattle(commonBattleFixture('six-waves'));
assert.equal(six.wavesCleared,6);assert.equal(six.outcome,'win');
for(let wave=1;wave<=6;wave++) {const frame=six.frames.find(f=>f.wave===wave);assert.equal(frame.enemies[0].sp,(wave-1)*5);assert.equal(frame.enemies[0].maxSp,80);}
checks.push('6 Wave and distinct enemy initial/cap SP retained');
const healing=commonBattleFixture('limit');
healing.party=healing.party.slice(0,1);healing.party[0].skills=[getFormalRaidSkill('SKD068',0)];
const healthy=simulateBattle(healing);
assert(!healthy.frames.some(f=>f.event==='action_start'&&f.skillId==='SKD068'),'healthy party must not cast heal+shield');
assert(healthy.frames.some(f=>f.partySp>=120),'test must have enough SP to expose invalid use');
checks.push('SKD068 does not spend SP on healthy ally through shield eligibility');
const now=Date.UTC(2026,8,24),state=createInitialState('qa-g2-c');state.energy=100;
const room=createRaidRoom('encounter_flame',state.userId,'qa-c-room',now);
const payload={battleId:'qa-c-battle',battleLevel:1,result:{outcome:'win',totalDamage:100}};
const settled=applyRaidAction(room,state,'raid_battle',payload,now);
assert.equal(settled.state.energy,80);assert.equal(settled.room.participants[0].attempts,1);
const replay=applyRaidAction(settled.room,settled.state,'raid_battle',payload,now);
assert.deepEqual(replay.room,settled.room);assert.deepEqual(replay.state,settled.state);
const claimed=applyRaidAction(settled.room,settled.state,'raid_claim',{},now);
const twice=applyRaidAction(claimed.room,claimed.state,'raid_claim',{},now);
assert.deepEqual(twice.state,claimed.state);
checks.push('same battle settlement and reward claim replay do not charge/grant twice');
(async()=>{
 let created=0,fail=false;
 global.Image=class {constructor(){created++;}set src(value){queueMicrotask(()=>fail?this.onerror?.():this.onload?.());}decode(){return Promise.resolve();}};
 const {preloadBattleImage,isBattleImageReady}=require('../src/app/components/battle/battleAssetPreload.ts');
 assert.equal(isBattleImageReady('/qa-c-image'),false);
 await Promise.all([preloadBattleImage('/qa-c-image'),preloadBattleImage('/qa-c-image')]);
 assert.equal(created,1);assert.equal(isBattleImageReady('/qa-c-image'),true);
 await preloadBattleImage('/qa-c-image');assert.equal(created,1);
 fail=true;await assert.rejects(preloadBattleImage('/qa-c-retry'));assert.equal(isBattleImageReady('/qa-c-retry'),false);
 fail=false;await preloadBattleImage('/qa-c-retry');assert.equal(isBattleImageReady('/qa-c-retry'),true);
 checks.push('decoded image cache deduplicates loads and failed loads remain retryable');
 console.log(JSON.stringify({status:'PASS',scope:'synthetic domain/cache regression, not live acceptance',checks},null,2));
})().catch(error=>{console.error(error);process.exitCode=1;});
