// Parent runs after dedicated QA fixture. Does not alter masters or configure fixture.
const fs=require('node:fs'),assert=require('node:assert/strict');
const config=JSON.parse(fs.readFileSync('config/game04-preview-public.json'));assert.equal(new URL(config.supabaseUrl).hostname,'lrgyllgzcdcphlbmkknc.supabase.co');
const session=JSON.parse(fs.readFileSync(process.argv[2])),out=process.argv[3],expectedEnergy=Number(process.argv[4]);assert([100,149].includes(expectedEnergy));
const report={checkedAt:new Date().toISOString(),userId:session.user.id,stageId:'izumo-1',requests:[],checks:[],scope:'Authenticated HTTP / reload, QA stage unlock and strong party; not natural G4 progression'};
async function call(action,payload={},requestId=crypto.randomUUID()){const r=await fetch(config.supabaseUrl+'/functions/v1/game04-redesign-api',{method:'POST',headers:{apikey:config.supabaseAnonKey,Authorization:'Bearer '+session.access_token,'Content-Type':'application/json'},body:JSON.stringify({action,payload,requestId}),signal:AbortSignal.timeout(60000)});const data=await r.json();report.requests.push({action,requestId,status:r.status,version:data.state?.version,error:data.error});assert.equal(r.status,200,data.error);return data;}
(async()=>{const before=(await call('get_state')).state;assert.equal(before.playerProgress.level,1);assert.equal(before.playerProgress.exp,99);assert.equal(before.playerProgress.status,'active');assert(!before.clearedStages.includes('izumo-1'));assert.equal(before.questAttempts?.['izumo-1']??0,0);report.before={playerProgress:before.playerProgress,energy:before.energy,version:before.version};
 const id=crypto.randomUUID(),result=await call('quest_battle',{stageId:'izumo-1'},id);assert.equal(result.battle.outcome,'win');assert.equal(result.state.playerProgress.level,3);assert.equal(result.state.playerProgress.exp,243);assert.equal(result.state.energy,expectedEnergy);assert.equal(result.playerGrowth.energy,expectedEnergy);assert.equal(result.playerGrowth.gainedExp,144);report.receipt=result.playerGrowth;
 const after=(await call('get_state')).state;assert.deepEqual(after.playerProgress,result.state.playerProgress);assert.equal(after.energy,expectedEnergy);const replay=await call('quest_battle',{stageId:'izumo-1'},id);assert.equal(replay.state.version,after.version);assert.deepEqual(replay.state.playerProgress,after.playerProgress);assert.equal(replay.state.energy,expectedEnergy);report.after={version:after.version,playerProgress:after.playerProgress,energy:after.energy};report.checks.push({name:expectedEnergy===149?'multi-level overcap retained':'multi-level refill once to 100',pass:true},{name:'same battle request replay no EXP/recovery duplication',pass:true});report.pass=true;
})().catch(e=>{report.pass=false;report.error=e.message;process.exitCode=1;}).finally(()=>{fs.writeFileSync(out,JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify(report));});
