const assert=require('node:assert/strict'),fs=require('node:fs'),ts=require('typescript');
require.extensions['.ts']=(m,f)=>m._compile(ts.transpileModule(fs.readFileSync(f,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,esModuleInterop:true}}).outputText,f);
const {createInitialState}=require('../src/domain/redesign/masters.ts');
const {createRaidRoom,applyRaidAction}=require('../src/domain/redesign/raid.ts');
const {createFormalInvasionMaster}=require('../src/domain/redesign/raidInvasionMaster.ts');
const {raidBattleMissionEvent,raidRescueMissionEvent,raidQualificationMissionEvents,reconcileRaidMissionProgress}=require('../src/domain/redesign/missionRaidProgress.ts');
const now=Date.UTC(2026,8,24),state=createInitialState('qa-c-mission');state.energy=100;
let room=createRaidRoom('encounter_flame','other-host','qa-mission-room',now);
room.participants.push({userId:state.userId,name:'QA',wins:2,attempts:2,totalDamage:0,joinedLevel:1});room.hp=1;
let done=applyRaidAction(room,state,'raid_battle',{battleId:'b1',battleLevel:1,result:{outcome:'win',totalDamage:10}},now);
assert.deepEqual(raidBattleMissionEvent(room,done.room,state.userId,'b1','win',now).counters,['battle','encounter_battle','encounter_win','encounter_other_win']);
assert.equal(raidBattleMissionEvent(done.room,done.room,state.userId,'b1','win',now),null);
assert.equal(raidRescueMissionEvent({...room,rescueCount:1},state.userId,'r1',now),null);
assert.deepEqual(raidRescueMissionEvent({...room,ownerId:state.userId,rescueCount:1},state.userId,'r1',now).counters,['encounter_rescue']);
assert.equal(raidQualificationMissionEvents(done.room,state.userId,now).length,1);
let recorded=reconcileRaidMissionProgress(done.state,[done.room],now);
assert.equal(recorded.missionProgress.counters.encounter_qualified_defeat,1);
assert.deepEqual(reconcileRaidMissionProgress(recorded,[done.room],now),recorded);
const late=structuredClone(done.room);late.rewardGrants=[];late.participants.find(p=>p.userId===state.userId).wins=100;
assert.deepEqual(raidQualificationMissionEvents(late,state.userId,now),[]);
const invasion={...structuredClone(room),ownerId:state.userId,level:7,raidSnapshot:createFormalInvasionMaster('TI01',()=>0),rewardGrants:[{id:`defeat:6:${state.userId}`,userId:state.userId,level:6,rewards:[],claimed:true}]};
assert.deepEqual(raidQualificationMissionEvents(invasion,state.userId,now)[0].counters,['invasion_okazaki_gate']);
invasion.level=12;invasion.status='defeated';invasion.rewardGrants=[{id:`defeat:12:${state.userId}`,userId:state.userId,level:12,rewards:[],claimed:false}];
assert.deepEqual(raidQualificationMissionEvents(invasion,state.userId,now)[0].counters,['invasion_okazaki_lord','invasion_host_qualified_clear']);
const after=reconcileRaidMissionProgress(state,[invasion],now);
assert.equal(after.missionProgress.counters.invasion_host,1);
assert.deepEqual(reconcileRaidMissionProgress(after,[invasion],now),after);
console.log(JSON.stringify({status:'PASS',checks:['settlement only participation/win/other-host','same battle replay ignored','NM164 own host only','qualified defeat proof and dedupe','no retroactive grant from current wins','castle gate/final host proof','claimed grants and repeated room synchronization']},null,2));
