const assert=require('node:assert/strict'),fs=require('fs'),cp=require('child_process'),ts=require('typescript');
require.extensions['.ts']=(m,f)=>m._compile(ts.transpileModule(fs.readFileSync(f,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,esModuleInterop:true}}).outputText,f);
const {createInitialState,grantReward,buildBattleParty,BATTLE_RULES,EQUIPMENT_MASTERS}=require('../src/domain/redesign/masters.ts');
const {getQuestStage,QUEST_STAGES,isQuestStageUnlocked,nextQuestStage}=require('../src/domain/redesign/quests.ts');
const {createQuestBattleInput,questVictoryRewards,questEnergyCost}=require('../src/domain/redesign/questMaster.ts');
const {initializeEarlyProgress,recordEarlyQuestClear,nextEarlyGuide}=require('../src/domain/redesign/earlyProgress.ts');
const {applyEarlyAction}=require('../src/domain/redesign/earlyActions.ts');
const {earlyLoadoutPlan}=require('../src/domain/redesign/earlyLoadout.ts');
const {getUnlockedDeckSlots,validateDeck}=require('../src/domain/redesign/growth.ts');
const {FORMAL_MISSION_CONFIG}=require('../src/domain/redesign/formalMissions.ts');
const {evaluateMissions}=require('../src/domain/redesign/missions.ts');
const {simulateBattle}=require('../src/domain/redesign/battle.ts');
const {createFormalBattleInput}=require('../src/domain/redesign/formalBattleInput.ts');
const base=JSON.parse(cp.execFileSync('git',['show','4e34bd8:src/domain/redesign/data/quest65.json'],{encoding:'utf8',maxBuffer:4e6}));
const starters=['char_joe_01','char_daimon_01','char_aoi_01'];
function initial(){let s=createInitialState('early-test');s.characters=starters.map(id=>({id,level:1,awakening:0}));s.skills=['SKD003','SKD039','SKD035'].map(id=>({id,level:0}));s.deck=starters.map((characterId,i)=>({characterId,skillIds:[s.skills[i].id],equipment:{}}));s.clearedStages=[];return initializeEarlyProgress(s);}
function clear(s,id){let n=structuredClone(s);const r=questVictoryRewards(getQuestStage(id),s,buildBattleParty(s),1);for(let i=0;i<r.rewards.length;i++)n=grantReward(n,r.rewards[i],`${id}:${i}`);if(r.firstClear)n.clearedStages.push(id);n.questClearCounts={...n.questClearCounts,[id]:r.count};return recordEarlyQuestClear(s,n,id);}
assert.equal(QUEST_STAGES.length,68);
for(const s of base.stages.filter(s=>!['mikawa','owari'].includes(s.areaId))){const actual=structuredClone(getQuestStage(s.id));actual.waves.flat().forEach(e=>e.image='');assert.deepEqual(actual,s);}
for(const id of ['mikawa-2','mikawa-3','mikawa-4','mikawa-5','owari-5'])for(const e of getQuestStage(id).waves.flat()){assert.equal(e.skills.length,0);assert.equal(e.passives.length,0);assert.equal(e.initialSp,0);assert.equal(e.stats.sp,100);assert.equal(e.stats.luk,0);assert.equal(e.hitSpGain,10);assert(e.image);}
let s=initial();assert.equal(getUnlockedDeckSlots(s),3);assert.equal(isQuestStageUnlocked('owari-1',s.clearedStages,s.earlyProgress),false);
s=clear(s,'mikawa-1');assert.equal(nextEarlyGuide(s,{battlePlaying:true,resultOpen:false}),null);assert.equal(nextEarlyGuide(s,{battlePlaying:false,resultOpen:true}),null);s=applyEarlyAction(s,'early_guide',{guide:'join-maeda',choice:'save'});assert.equal(s.deck.length,4);
s=clear(s,'mikawa-2');assert.equal(getUnlockedDeckSlots(s),4);s=applyEarlyAction(s,'early_guide',{guide:'equip-iwadan',choice:'save'});assert.deepEqual(s.deck[3].skillIds,['SKD009']);
s=clear(s,'mikawa-3');assert.equal(getUnlockedDeckSlots(s),5);s=applyEarlyAction(s,'early_guide',{guide:'join-takenaka',choice:'later'});s=JSON.parse(JSON.stringify(s));assert.equal(s.earlyProgress.guides['join-takenaka'],'deferred');assert.equal(isQuestStageUnlocked('owari-1',s.clearedStages,s.earlyProgress),false);
s=clear(s,'mikawa-4');s=applyEarlyAction(s,'early_guide',{guide:'equip-fire',choice:'later'});assert.equal(nextEarlyGuide(JSON.parse(JSON.stringify(s)),{battlePlaying:false,resultOpen:false}),null);
const before=structuredClone(s);s=applyEarlyAction(s,'early_auto_loadout',{});assert.equal(s.deck.length,5);assert.deepEqual(s.deck.map(m=>m.skillIds[0]),['SKD003','SKD019','SKD039','SKD009','SKD035']);for(const key of ['characters','skills','equipment','materials','cash'])assert.deepEqual(s[key],before[key]);validateDeck(s,s.deck);
const geared=structuredClone(s);geared.equipment=EQUIPMENT_MASTERS.slice(0,12).map((e,i)=>({instanceId:'gear-'+i,masterId:e.id,level:1,lb:0}));const gearPlan=earlyLoadoutPlan(geared);validateDeck(geared,gearPlan);const usedGear=gearPlan.flatMap(m=>Object.values(m.equipment));assert(usedGear.length>0);assert.equal(new Set(usedGear).size,usedGear.length);assert(usedGear.every(id=>geared.equipment.some(e=>e.instanceId===id)));
const trained=structuredClone(s);trained.characters.push({id:'char_reiji_01',level:20,awakening:0});assert(earlyLoadoutPlan(trained).some(m=>m.characterId==='char_reiji_01'));
s=clear(s,'mikawa-5');assert.equal(nextEarlyGuide(s,{battlePlaying:false,resultOpen:false}),'missions');s=applyEarlyAction(s,'early_guide',{guide:'missions',choice:'missions'});assert.equal(nextEarlyGuide(JSON.parse(JSON.stringify(s)),{battlePlaying:false,resultOpen:false}),'missions');s=applyEarlyAction(s,'early_missions_opened',{});assert.equal(nextEarlyGuide(s,{battlePlaying:false,resultOpen:false}),null);assert(isQuestStageUnlocked('owari-1',s.clearedStages,s.earlyProgress));
const legacy=initial();delete legacy.earlyProgress;legacy.clearedStages=['mikawa-1','mikawa-2','mikawa-3','owari-1','owari-2','owari-3','owari-4'];legacy.characters.push({id:'char_yuki_01',level:3,awakening:0});const migrated=initializeEarlyProgress(legacy);assert.equal(getUnlockedDeckSlots(migrated),5);assert(isQuestStageUnlocked('mino-1',migrated.clearedStages,migrated.earlyProgress));assert(isQuestStageUnlocked('mikawa-4',migrated.clearedStages,migrated.earlyProgress));assert.equal(migrated.earlyProgress.guides.missions,'completed');assert.deepEqual(migrated.characters,legacy.characters);assert.deepEqual(migrated.clearedStages,legacy.clearedStages);assert.equal(evaluateMissions(migrated,FORMAL_MISSION_CONFIG).find(m=>m.id==='NM066').status,'claimable');
const oldHanbei={...migrated,clearedStages:['mikawa-1','mikawa-2']};assert(!questVictoryRewards(getQuestStage('mikawa-3'),oldHanbei,buildBattleParty(oldHanbei),1).rewards.some(r=>r.kind==='character'&&r.id==='char_yuki_01'));
assert(!questVictoryRewards(getQuestStage('mikawa-1'),s,buildBattleParty(s),1).firstClear);assert.equal(questEnergyCost(getQuestStage('owari-5'),initial()),0);assert.equal(questEnergyCost(getQuestStage('owari-5'),{...initial(),earlyProgress:{...initial().earlyProgress,additionalStageAttempts:{'owari-5':1}}}),1);
assert.equal(FORMAL_MISSION_CONFIG.missions.filter(m=>m.rewards.some(r=>r.kind==='free_diamonds')).length,10);assert.equal(new Set(FORMAL_MISSION_CONFIG.missions.map(m=>m.id)).size,FORMAL_MISSION_CONFIG.missions.length);assert.equal(FORMAL_MISSION_CONFIG.missions.find(m=>m.id==='NM004').condition.stageId,'owari-1');
const collision=initializeEarlyProgress({...legacy,clearedStages:[...legacy.clearedStages,'mikawa-4','mikawa-5','owari-5']});
assert(questVictoryRewards(getQuestStage('mikawa-4'),collision,buildBattleParty(collision),1).firstClear);assert.equal(evaluateMissions(collision,FORMAL_MISSION_CONFIG).find(m=>m.id==='NM184').status,'progress');assert(collision.clearedStages.includes('mikawa-4'));
const oldPending=initial();oldPending.clearedStages=['mikawa-1'];const oldSettled={...oldPending,clearedStages:['mikawa-1','mikawa-2']};const recovered=recordEarlyQuestClear(oldPending,oldSettled,'mikawa-2',true);assert.equal(recovered.earlyProgress.deckSlots,5);assert.equal(recovered.earlyProgress.guides['equip-iwadan'],'completed');const recoveredArea=recordEarlyQuestClear(recovered,{...recovered,clearedStages:[...recovered.clearedStages,'mikawa-3']},'mikawa-3',true);assert(isQuestStageUnlocked('owari-1',recoveredArea.clearedStages,recoveredArea.earlyProgress));assert.equal(recoveredArea.earlyProgress.guides.missions,'completed');
const report={checks:['68 stages; area3+ exact equality','formal enemy assets and normal-only attacks','guide save/defer/reload/result gating','mandatory mission navigation acknowledgement','no auto growth/material use; preserve trained outsiders','legacy progression and five slots; no duplicate Hanbei','mission IDs stable; 10x300 gems; first-clear and energy rules'],simulations:[]};
let partyState=initial();for(const id of ['mikawa-1','mikawa-2','mikawa-3','mikawa-4','mikawa-5','owari-1','owari-2']){
 if(id==='mikawa-2')partyState=applyEarlyAction(partyState,'early_guide',{guide:'join-maeda',choice:'save'});
 if(id==='mikawa-3')partyState=applyEarlyAction(partyState,'early_guide',{guide:'equip-iwadan',choice:'save'});
 if(id==='mikawa-4'||id==='mikawa-5')partyState.deck=earlyLoadoutPlan(partyState);
 for(const level of (id==='owari-1'?[1,3]:id==='owari-2'?[3,5,10]:[1])){
  const st=structuredClone(partyState);st.characters.forEach(c=>c.level=level);let win=0,burst=0,finish=0;
  for(let seed=1;seed<=50;seed++){const input=createQuestBattleInput(seed,buildBattleParty(st),getQuestStage(id),BATTLE_RULES);assert.equal(!!input.earlyQuestAssist,id.startsWith('mikawa'));const r=simulateBattle(input);if(r.outcome==='win')win++;if(r.frames.some(f=>f.burst))burst++;const last=r.frames.filter(f=>f.event==='action_end').at(-1);if(r.outcome==='win'&&last?.burst)finish++;}
  report.simulations.push({stage:id,level,party:st.deck.length,seeds:50,win,burst,burstFinish:finish});
 }
 partyState=clear(partyState,id);
}
for(const id of ['owari-1','mino-1']){const input=createQuestBattleInput(7,buildBattleParty(s),getQuestStage(id),BATTLE_RULES);assert(!input.earlyQuestAssist);const plain=createFormalBattleInput(7,input.party,input.waves,BATTLE_RULES);assert.deepEqual(simulateBattle(input),simulateBattle(plain));}
// A saved pre-rollout quest input remains identical when replayed: no implicit area inference.
const oldInput=createFormalBattleInput(7,buildBattleParty(s),base.stages[0].waves,BATTLE_RULES);assert(!oldInput.earlyQuestAssist);assert.deepEqual(simulateBattle(oldInput),simulateBattle(JSON.parse(JSON.stringify(oldInput))));
let skipped=initial();for(const id of ['mikawa-1','mikawa-2','mikawa-3']){skipped=clear(skipped,id);if(id==='mikawa-1')skipped=applyEarlyAction(skipped,'early_guide',{guide:'join-maeda',choice:'save'});if(id==='mikawa-2')skipped=applyEarlyAction(skipped,'early_guide',{guide:'equip-iwadan',choice:'save'});}for(const id of ['mikawa-4','mikawa-5']){let win=0;for(let seed=1;seed<=50;seed++)if(simulateBattle(createQuestBattleInput(seed,buildBattleParty(skipped),getQuestStage(id),BATTLE_RULES)).outcome==='win')win++;assert.equal(win,50);report.simulations.push({stage:id,level:1,party:4,seeds:50,win,optionalGuidesSkipped:true});skipped=clear(skipped,id);}
fs.writeFileSync('docs/verification/early-retention-20260926/domain-results.json',JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify(report,null,2));
