import assert from 'node:assert/strict';
import { applyRaidAction, createRaidRoom, getRaidMaster, raidEnemy } from '../src/domain/redesign/raid.ts';
import { BATTLE_RULES, buildBattleParty, createInitialState } from '../src/domain/redesign/masters.ts';
import { simulateBattle } from '../src/domain/redesign/battle.ts';
const now = Date.parse('2026-09-19T12:00:00Z');
const master = getRaidMaster('unlock_shadow');
let state = createInitialState('late');
let room = {...createRaidRoom(master.id, 'owner', 'room', now), level:14, hp:1000000, maxHp:1000000};
({room,state} = applyRaidAction(room,state,'raid_join',{},now));
assert.equal(room.participants[1].joinedLevel,14);
assert.equal('checkpoint' in room.participants[1],false);
const enemy14 = raidEnemy(master, room.level);
assert.equal(enemy14.level,14);
assert.notEqual(enemy14.stats.hp,room.maxHp,'individual HP is separate');
const party = buildBattleParty(state);
const win = simulateBattle({seed:41,party:party.map(p=>({...p,stats:{...p.stats,hp:1000000,atk:1000000}})),waves:[[enemy14]],rules:BATTLE_RULES});
const lose = simulateBattle({seed:42,party:party.map(p=>({...p,stats:{...p.stats,hp:1,atk:1,def:0}})),waves:[[enemy14]],rules:BATTLE_RULES});
assert.equal(win.outcome,'win'); assert.equal(lose.outcome,'lose');
function settle(id,outcome,damage,level=room.level) {
 ({room,state}=applyRaidAction(room,state,'raid_battle',{battleId:id,battleLevel:level,energyAlreadyPaid:true,result:{outcome,totalDamage:damage}},now));
}
// Old saved participant data is harmless; it must never restore the removed lock.
room.participants[1].checkpoint=10;
settle('loss','lose',100);
assert.equal(room.participants[1].wins,0);
assert.equal(room.rewardGrants.length,1,'first battle participation reward even after loss');
settle('w1','win',100);
assert.equal(room.hp,1000000-100-100*master.victoryMultiplier);
room.hp=1;settle('w2','win',100);
assert.equal(room.level,15);
assert.equal(room.rewardGrants.some(g=>g.id==='defeat:14:late'),false,'two wins never qualify');
const hp15=room.hp;
settle('late-w3','win',100,14);
assert.equal(room.hp,hp15,'in-flight old Lv cannot damage new shared boss');
assert.equal(room.participants[1].wins,3,'old battle still counts as personal win');
assert.equal(room.rewardGrants.some(g=>g.id==='defeat:14:late'),false,'no retroactive reward at qualification');
const settled=structuredClone({room,state});
settle('late-w3','win',100,14);
assert.deepEqual({room,state},settled,'retry has no duplicate wins/damage/grants');
const enemy15=raidEnemy(master,room.level);
assert.ok(enemy15.stats.hp>enemy14.stats.hp);assert.ok(enemy15.stats.atk>enemy14.stats.atk);
room.hp=1;settle('w4','win',100);
assert.equal(room.level,16);
assert.equal(room.rewardGrants.filter(g=>g.id==='defeat:15:late').length,1);
assert.equal(room.rewardGrants.some(g=>g.level<14&&g.userId==='late'),false);
({room,state}=applyRaidAction(room,state,'raid_claim',{},now));
const claimed=structuredClone({room,state});
({room,state}=applyRaidAction(room,state,'raid_claim',{},now));
assert.deepEqual({room,state},claimed,'repeat claim cannot grant twice');
assert.notEqual(raidEnemy(master,1).image,raidEnemy(master,10).image);
assert.notEqual(raidEnemy(master,10).image,raidEnemy(master,20).image);
console.log('PASS: Lv14 join, WIN/LOSE, legacy save compatibility, 3-win qualification, no retroactive reward, old-Lv settlement, next-Lv scaling, battle/claim replay, appearance stages');
