const fs=require('fs'),assert=require('assert/strict'),{chromium}=require('playwright');
const base='http://localhost:3104',out='../../outputs/common-ui-continuation/remaining';fs.mkdirSync(out,{recursive:true});
(async()=>{const b=await chromium.launch(),report=[];try{for(const width of [375,390]){const p=await b.newPage({viewport:{width,height:480}}),errors=[];p.on('pageerror',e=>errors.push(e.message));const shot=async name=>{await p.waitForTimeout(400);await p.screenshot({path:`${out}/${name}-${width}.png`});assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),name);report.push({width,height:480,state:name,errors:[...errors]});fs.writeFileSync(out+'/report.json',JSON.stringify(report,null,2));};
await p.goto(base+'/qa/redesign?view=quest');await p.locator('.raid-area-card:not(:disabled)').first().waitFor({timeout:90000});await shot('quest-areas');await p.locator('.raid-area-card:not(:disabled)').first().click();await p.locator('.rq-stage:not(:disabled)').first().waitFor();await shot('quest-stages');await p.locator('.rq-stage:not(:disabled)').first().click();await p.getByRole('dialog').waitFor();await shot('quest-detail');fs.writeFileSync(out+'/quest-controls.json',JSON.stringify(await p.getByRole('dialog').getByRole('button').allTextContents()));
for(const name of ['攻略のヒント','報酬を確認']){const button=p.getByRole('dialog').getByRole('button',{name,exact:true});if(await button.count()){await button.click();await shot('quest-'+name);await p.getByRole('dialog').last().getByRole('button',{name:'閉じる',exact:true}).first().click();}}
await p.goto(base+'/qa/raid-integrated');await p.locator('.raid-approved-card').first().waitFor({timeout:90000});await shot('raid-list');await p.getByRole('button',{name:/の詳細$/}).first().click();await p.getByRole('button',{name:'敵情報',exact:true}).waitFor();await shot('raid-room');for(const name of ['敵情報','参加者','報酬','救援']){await p.getByRole('button',{name,exact:true}).click();await p.getByRole('dialog').waitFor();await shot('raid-'+name);await p.getByRole('dialog').last().getByRole('button',{name:'閉じる',exact:true}).first().click();}
await p.goto(base+'/qa/shop-ui');await p.getByRole('button',{name:'購入履歴',exact:true}).waitFor();for(const name of ['購入履歴','購入分の有効期限']){await p.getByRole('button',{name,exact:true}).click();await p.getByRole('dialog').waitFor();await shot('shop-'+name);await p.getByRole('dialog').last().getByRole('button',{name:'閉じる',exact:true}).last().click();}await p.getByRole('button',{name:'お知らせ',exact:true}).first().click();await p.locator('.inbox-news-item').first().waitFor();await shot('news-list');await p.locator('.inbox-news-item').first().click();await shot('news-detail');
for(const route of ['legal/age-rating','legal/commercial','legal/contact','legal/cookies','legal/payments','legal/privacy','legal/rights','legal/terms','legal/tokusho','auth/game04/callback','auth/callback','billing/return','open']){await p.goto(base+'/'+route,{waitUntil:'domcontentloaded',timeout:60000});await p.waitForTimeout(300);await shot(route.replaceAll('/','-'));}
assert.deepEqual(errors,[]);await p.close();}console.log('PASS remaining consumer views');}finally{await b.close();}})().catch(e=>{console.error(e);process.exitCode=1});
