const fs=require('fs'),ts=require('typescript'),Module=require('module'),path=require('path'),assert=require('assert/strict');const compile=s=>ts.transpileModule(s,{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,esModuleInterop:true}}).outputText;require.extensions['.ts']=(m,f)=>m._compile(compile(fs.readFileSync(f,'utf8')),f);
const {simulateBattle}=require('../src/domain/redesign/battle.ts'),engine=path.resolve('src/domain/redesign/battleBalanceV2.ts'),source=fs.readFileSync(engine,'utf8'),base=JSON.parse(fs.readFileSync('docs/verification/device-debug/b05/usable.json')).input,out='docs/verification/burst-enemy-pause';fs.mkdirSync(out,{recursive:true});
const policy='attack-free-enemy-pause-v2-20260927';
function run(setup=()=>{},counter=false){const x=structuredClone(base);x.seed=7;x.rules.burstPolicy=policy;x.party[0].skills[0].spCost=1000;x.party[0].skills[0].condition={type:'always'};x.waves[0][0].initialCount=2;setup(x);const m=new Module(engine,module);m.filename=engine;m.paths=module.paths;let s=source.replace('let partySp = 0, gauge = 0,','let partySp = 0, gauge = 200,');if(counter)s=s.replace('    let cursor = 0;',"    for(const e of enemies)e.statuses.push({type:'counter',power:100,remaining:999,carry:true,sourceId:e.id,sourceEnemy:true,sourceSkillId:'qa-counter',appliedAction:-1});\n    let cursor = 0;");m._compile(compile(s),engine);const r=m.exports.simulateBalanceBattle(x);return {x,r};}
const report=[];
function check(name,r){let start;let total=0;for(const f of r.frames){if(f.event==='burst_start'){start=f;total++;}if(start&&f.burst){assert(!['counts','interrupt_start','interrupt_end','counter'].includes(f.event));assert(!(f.event==='action_start'&&f.enemies.some(e=>e.id===f.actorId)));for(const e of f.enemies){const original=start.enemies.find(o=>o.id===e.id);if(e.hp>0&&original?.hp>0)assert.equal(e.count,original.count);}assert.equal(f.partySp,start.partySp);}if(f.event==='burst_end'){const es=r.frames.slice(start.index,f.index);assert(es.filter(e=>e.event==='action_start').length<=5);start=null;}}report.push({name,bursts:total});}
const normal=run();check('five-continuous-count-held',normal.r);const start=normal.r.frames.find(f=>f.event==='burst_start'),end=normal.r.frames.find(f=>f.event==='burst_end');assert.equal(normal.r.frames.slice(start.index,end.index).filter(f=>f.event==='action_start').length,5);assert.equal(normal.r.frames[end.index].enemies[0].count,2);const tick=normal.r.frames.slice(end.index+1).find(f=>f.event==='counts');assert.equal(tick.enemies[0].count,1);assert(normal.r.frames.slice(end.index+1,tick.index).some(f=>f.event==='action_start'&&!f.burst));
const c=run(()=>{},true);check('counter-suppressed-not-deferred',c.r);assert(c.r.frames.slice(c.r.frames.find(f=>f.event==='burst_end').index+1).some(f=>f.event==='counter'));
for(const mode of ['kill','wave','death-trigger','phase','stun-due']){const {r}=run(x=>{if(['kill','wave','death-trigger'].includes(mode))x.waves[0][0].stats.hp=1;if(mode==='wave')x.waves.push(structuredClone(x.waves[0]));if(mode==='death-trigger')x.waves[0][0].deathEffects=[{type:'damage',power:99999,target:'all_enemies'}];if(mode==='phase')x.waves[0][0].phases=[{name:'phase2',hpBelow:1,actionCount:1}];if(mode==='stun-due'){x.waves[0][0].initialCount=1;x.waves[0][0].initialSp=100;x.waves[0][0].skills=[{...x.party[0].skills[0],spCost:1,effects:[{type:'stun',power:0,chance:1}]}]}});check(mode,r);if(mode==='death-trigger')assert(!r.frames.some(f=>f.skillId?.startsWith('death:')));if(mode==='wave')assert(r.frames.some(f=>f.event==='wave'));if(mode==='kill')fs.writeFileSync(out+'/early.json',JSON.stringify(r));}
// Old v1 input and saved records retain their exact original behavior (including enemy interruptions).
const old=structuredClone(base);old.rules.burstPolicy='attack-free-v1-20260926';const before=new Module(engine,module);before.filename=engine;before.paths=module.paths;before._compile(compile(require('child_process').execFileSync('git',['show','1297da0:src/domain/redesign/battleBalanceV2.ts'],{encoding:'utf8'})),engine);assert.deepEqual(simulateBattle(old),before.exports.simulateBalanceBattle(old));report.push({name:'old-v1-exact-compatibility',pass:true});
const arts=JSON.parse(fs.readFileSync('src/theme/local-characters.json')),roster=JSON.parse(fs.readFileSync('src/theme/sengoku-characters.json'));const byRarity=r=>arts.find(a=>roster.find(c=>c.characterId===a.id)?.runtimeRarity===r);
for(const mode of ['1','2','3','center-normal','fallen']){const count=Number(mode)||3;const {r}=run(x=>{x.waves[0]=Array.from({length:count},(_,i)=>{const rarity=mode==='center-normal'&&i===1?'N':i===1||count===1?'SSR':i===2?'SR':'N';const a=rarity==='SR'?arts.find(a=>JSON.parse(fs.readFileSync('src/theme/enemy-art-bounds.json'))[a.battle]?.rarity==='SR'):byRarity(rarity);return {...structuredClone(x.waves[0][0]),id:'enemy-'+i,name:a.name,image:a.battle,order:i,initialCount:2+i,stats:{...x.waves[0][0].stats,hp:mode==='fallen'&&i===0?1:x.waves[0][0].stats.hp}}})});const e=r.frames.find(f=>f.event==='burst_end');fs.writeFileSync(out+`/layout-${mode}.json`,JSON.stringify({...r,frames:r.frames.slice(0,e.index+8)}));}
fs.writeFileSync(out+'/logic.json',JSON.stringify(report,null,2));console.log('PASS',report);
