const fs=require('fs'),path=require('path'),ts=require('typescript'),assert=require('node:assert/strict'),Module=require('module');const original=Module._resolveFilename;Module._resolveFilename=function(request,parent,...rest){return original.call(this,request.startsWith('@/')?path.resolve('src',request.slice(2)):request,parent,...rest)};require.extensions['.ts']=(m,f)=>m._compile(ts.transpileModule(fs.readFileSync(f,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,esModuleInterop:true}}).outputText,f);
const {recordedBattleMvp}=require('../src/domain/presentation/recordedBattleMvp.ts');const {createInitialState,buildBattleParty,BATTLE_RULES}=require('../src/domain/redesign/masters.ts');const {FORMAL_QUEST_STAGES,createQuestBattleInput}=require('../src/domain/redesign/questMaster.ts');const {simulateBattle}=require('../src/domain/redesign/battle.ts');const state=createInitialState('local-mvp-verification');const result=simulateBattle(createQuestBattleInput(917,buildBattleParty(state),FORMAL_QUEST_STAGES[0],BATTLE_RULES));const before=JSON.stringify(result),actual=recordedBattleMvp(result);assert(actual.mvp);assert.equal(JSON.stringify(result),before);assert(actual.mvp.score.total<=100);for(const c of actual.candidates){const a=result.analysis.find(a=>a.id===c.participant.id);assert.equal(c.raw.damage,a.damage);assert.equal(c.raw.heal,a.healing)}
const clone=structuredClone(result),last=clone.frames.at(-1);const first=clone.party[0].id;last.party.find(p=>p.id===first).hp=1;assert.equal(recordedBattleMvp(clone).candidates.find(c=>c.participant.id===first).raw.survived,true);last.party.find(p=>p.id===first).hp=0;assert.equal(recordedBattleMvp(clone).candidates.find(c=>c.participant.id===first).score.survival,0);
const old=structuredClone(result);delete old.frames[0].event;assert.equal(recordedBattleMvp(old).mvp,null);
fs.mkdirSync('docs/verification/device-debug/b03/v5',{recursive:true});fs.writeFileSync('docs/verification/device-debug/b03/v5/formal-result.json',JSON.stringify({stage:FORMAL_QUEST_STAGES[0].id,seed:917,outcome:result.outcome,frames:result.frames.length,analysis:actual,scope:'Formal GAME04 masters, local engine-produced BattleResult. No user battle or DB write.'},null,2));console.log('PASS formal recorded result, immutable projection, final survival, old-record fallback',actual.mvp.participant.name,actual.mvp.score.total);

// A changed recorded contribution must change the winner, never pin party[0].
const other=structuredClone(result);other.analysis.forEach(a=>{a.damage=0;a.healing=0});other.analysis[1].damage=10000;other.analysis[1].healing=100;assert.equal(recordedBattleMvp(other).mvp.participant.id,other.analysis[1].id);
// Shield attachment is counted once, not again when the amount is consumed.
const tiny=structuredClone(result);tiny.frames=[structuredClone(result.frames[0])];tiny.frames[0].event='start';const actor=tiny.party[1].id,target=tiny.party[0].id;
let next=structuredClone(tiny.frames[0]);next.index=1;next.event='effect_applied';next.actorId=actor;next.targetIds=[target];next.party.find(p=>p.id===target).statuses.push({type:'shield',sourceId:actor,sourceSkillId:'test',sequence:1,appliedAction:1,amount:80,remaining:3,power:100,carry:true});tiny.frames.push(next);next=structuredClone(next);next.index=2;next.event='shield_absorbed';next.party.find(p=>p.id===target).statuses[0].amount=30;tiny.frames.push(next);assert.equal(recordedBattleMvp(tiny).candidates.find(c=>c.participant.id===actor).raw.shield,80);
const ambiguous=structuredClone(result);const deathIndex=ambiguous.frames.findIndex((f,i)=>i>0&&f.event==='damage'&&(f.targetIds??[]).some(id=>ambiguous.frames[i-1].enemies.find(e=>e.id===id)?.hp>0&&f.enemies.find(e=>e.id===id)?.hp===0));assert(deathIndex>0);const death=ambiguous.frames[deathIndex],oldEnemy=ambiguous.frames[deathIndex-1].enemies.find(e=>e.id===death.targetIds[0]);death.event='dot';oldEnemy.statuses=[{type:'dot',sourceId:ambiguous.party[0].id},{type:'dot',sourceId:ambiguous.party[1].id}];assert.equal(recordedBattleMvp(ambiguous).mvp,null);
console.log('PASS winner follows contribution, shield not double-counted, ambiguous DOT withheld');
