const assert = require('node:assert/strict');
const fs = require('node:fs');
const ts = require('typescript');
const source = fs.readFileSync('src/app/components/redesign/HomeView.tsx', 'utf8');
const start = source.indexOf('  useEffect(() => {\n    if (previewOnly) return;\n    let cancelled = false;');
const end = source.indexOf('  const profileUserIds =', start);
assert.ok(start > 0 && end > start, 'activity effect exists');
const effectCode = ts.transpile(source.slice(start, end), { target: ts.ScriptTarget.ES2020 });
const flush = () => new Promise(resolve => setImmediate(resolve));
const deferred = () => { let resolve, reject; const promise = new Promise((a,b) => {resolve=a;reject=b;}); return {promise, resolve, reject}; };
function mount(request, initial = []) {
  const result = { activities: initial, loading: false, error: '', calls: [], signal: null, timer: null };
  const fakeWindow = { setTimeout: (fn, duration) => {assert.equal(duration,12000);result.timer=fn;return 1;}, clearTimeout: () => {result.timer=null;} };
  let cleanup;
  const run = new Function('useEffect','previewOnly','state','activityAttempt','supabase','setActivityLoading','setActivityError','setActivities','window','HOME_ACTIVITY_READ_TIMEOUT_MS', effectCode);
  run(fn => {cleanup = fn();}, false, {userId:'qa-home'}, 0, {rpc: (...args) => {result.calls.push(args);return {abortSignal: signal => {result.signal=signal;return request.promise;}};}}, value => result.loading=value, value => result.error=value, value => result.activities=value, fakeWindow, 12000);
  return {result, cleanup};
}
(async () => {
  const request = deferred();
  const current = mount(request);
  assert.equal(current.result.loading, true);
  request.resolve({data:[{id:'public',activity_type:'QUEST_CLEAR'}, {id:'old',activity_type:'PVP_WIN'}],error:null});
  await flush();
  assert.deepEqual(current.result.activities.map(a=>a.id), ['public']);
  assert.equal(current.result.loading, false);
  assert.deepEqual(current.result.calls.map(a=>a[0]), ['get_recent_social_activity_feed'], 'public profiles do not delay the feed');
  const old = [{id:'retained'}];
  const failure = deferred(); const failed = mount(failure, old);
  failure.resolve({data:null,error:{message:'offline'}}); await flush();
  assert.equal(failed.result.activities, old, 'failed refresh keeps confirmed feed');
  assert.ok(failed.result.error); assert.equal(failed.result.loading,false);
  const rejected = deferred(); const thrown = mount(rejected, old);
  rejected.reject(new Error('transport')); await flush();
  assert.equal(thrown.result.activities, old); assert.ok(thrown.result.error);
  const stale = deferred(); const cancelled = mount(stale, old); cancelled.cleanup();
  stale.resolve({data:[{id:'late'}],error:null}); await flush();
  assert.equal(cancelled.result.activities, old, 'late owner/unmount response cannot project');
  const stalled = deferred(); const timeout = mount(stalled, old);
  timeout.result.timer();
  assert.equal(timeout.result.loading,false, 'unsettled read reaches retry UI');
  assert.equal(timeout.result.signal.aborted,true);
  assert.ok(timeout.result.error);
  stalled.resolve({data:[{id:'too-late'}],error:null}); await flush();
  assert.equal(timeout.result.activities,old, 'response after timeout is ignored');
  const retryRequest=deferred(); const retry=mount(retryRequest,old);
  retryRequest.resolve({data:[{id:'retried'}],error:null}); await flush();
  assert.deepEqual(retry.result.activities.map(a=>a.id),['retried']);
  assert.equal(retry.result.error,''); assert.equal(retry.result.timer,null);
  assert.equal(cancelled.result.signal.aborted,true, 'cleanup aborts read');
  assert.equal(cancelled.result.timer,null, 'cleanup clears timer');
  console.log('PASS G2 home activity: first success/filter, optional profile independence, error retention, thrown transport, cancelled response, stalled timeout, late response, retry recovery');
})();
